### ISSUE TITLE
Group Profile Screen is missing Profile Data

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#101]
Profile data on the Group Profile screen is not appearing. Information regarding name, description, membership, etc. should appear.

**Comment by petervojtek** [comment]
This is how group profile detail looks now:

<img width="710" alt="screen shot 2016-07-13 at 15 58 19" src="https://cloud.githubusercontent.com/assets/225506/16805952/d29bbe12-4912-11e6-9e6b-c25563baa0ef.png">

I am not sure what else should be displayed for user group, here is the data provided by backend:

```
{"id":295,"group_type":0,"avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","manager_phone":"+1123","official_title":"Save the Planet Now","official_description":"Save everything worth saving..","acronym":"STP","joined":1,"total_members":0,"membership_control":"public","fill_fields_required":false,"required_permissions":[]}
```

Actually, the old code also displays number of total_members, however with the v2 api `total_members` is always `0` even when the actual number of users is e.g. 2. 
@jterps08 , please confirm we want to display the `total_members` count, and if yes, I will have to ask Igor to adjust the backend..

**Comment by jterps08** [comment]
Two things here:
1) We actually want to display the total members count. 
2) The old code should (somewhere) show that a user could tap on the total members count to open a listing of all members. On that membership list page, each user's avatar and name are listed along with a follow button for each user. There is also a Follow-All users button at the top of that membership list page. 

This is low-priority for now.

**Comment by jterps08** [comment]
Also, to see what it should look like, skip to the 20second mark in this video:

https://drive.google.com/open?id=0B2Loy21ehREyMlpuVHluZGVrRnc

**Comment by petervojtek** [comment]
Jesse, thanks for video, noted.

I assign this issue to @igaponov due to following bug:

in GET group detail, `total_members` is always zero even when users have joined the group.

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/295
Request Method:GET
Status Code:200 OK

{"id":295,"group_type":0,"avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","manager_phone":"+1123","official_title":"Save the Planet Now","official_description":"Save everything worth saving..","acronym":"STP","joined":1,"total_members":0,"membership_control":"public","fill_fields_required":false,"required_permissions":[]}
```

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/192

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#192 has been deployed

**Comment by petervojtek** [comment]
than you @igaponov .

now I moved forward and I face following issue:

When I try to follow all users from a group, I face following backend behaviour:

```
Request URL:https://api-dev.powerli.ne/api/v2/user/group-followers/295
Request Method:PUT
Status Code:500 Internal Server Error

{"code":500,"message":"An exception occurred while executing '\n                INSERT INTO users_follow(user_id, follower_id, date_create, status) \n                SELECT ug.user_id, :user, current_timestamp, :status FROM users_groups ug \n                LEFT JOIN users_follow uf ON uf.user_id = ug.user_id\n                WHERE ug.group_id = :group AND uf.id IS NULL':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':user, current_timestamp, :status FROM users_groups ug \n                LEFT JOI' at line 2","errors":null}
```

**Comment by jterps08** [comment]
For background information: The original purpose of the Follow All Group Members button was to send, in one action, follow requests to all group members. In the future, I think we will want to give users a "list" that allows them to "uncheck a box" of certain members before the follow requests go out. 

This concept is _separate_ from a "Subscribe to Group Notifications" concept which the user, without following any of the individual group members, would be alerted every time a new post was made inside the group by anyone. The difference between Following All Group Members and Subscribe to Group Notifications is to account for two very different needs / use cases: 1) Wanting to know about all group activity (SGN), and 2) Wanting to be able to follow group members activity both inside _and_ _outside_ the group (particularly useful for helping people support each other's posts in the public town/state/country groups)

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/pull/200 was deployed

**Comment by petervojtek** [comment]
thanks all. 

done.
