### ISSUE TITLE
Unjoining a Group

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#102]
When user is on Group Profile screen and clicks "Unjoin", the app stays on the Group Profile page, and it does not appear that the user has left the group. The app should unjoin the user and display the previous screen.

**Comment by petervojtek** [comment]
now the behaviour is, that unjoin works thanks to #133, but after successfull Unjoin, user stays at the group page.

**Comment by jterps08** [comment]
Okay - I'm going to change this to enhancement, since it's really a UI issue not a bug anymore.

**Comment by petervojtek** [comment]
ok, current behaviour is that after successful unjoin user is redirected to 'my groups page'
