### ISSUE TITLE
UI: User Profile

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#104]
Increase size and contrast of displayed user profile information for readability. 
User's tagline and bio fields should be displayed.for followed users.

**Comment by petervojtek** [comment]
@jterps08 , on which screen should be the "Increased size and contrast  of displayed user profile" ?

And on which screen is supposed to be displayed "User's tagline and bio fields for followed users"?

**Comment by jterps08** [comment]
Both should be the User Profile screen... (When you tap on a user's name in the newsfeed or on their @mention in a comment or when you open up their user profile page from the My Influences Following/Followed list - they all link to the screen below)>>>

I will try to find a screenshot and put it here...

**Comment by petervojtek** [comment]
@jterps08 , I found it.
<img width="718" alt="screen shot 2016-07-13 at 07 13 33" src="https://cloud.githubusercontent.com/assets/225506/16792528/80e85cea-48c9-11e6-8527-084a51d62acc.png">

Will fix following issues:
- add bio and tagline
- increase readability of name - DONE
- tapping username in newsfeed activity title is doing nothing,  will change to goto user profile (tapping on user avatar works properly) - DONE
- tapping on a @username mention in comment leads to no action, will change to goto user profile - DONE

Questions:
- tapping on a @username mention in User post description text opens browser and is trying to open twitter page for that user -- is this intentional? (it makes some sense, however from UX point of view it is confusing that the same looking @mention in comment will lead to different action)..  
- the font of mentioned username is intentionally serif? It looks to me like a bug (i find it ugly, I would expect there sans-serif)

<img width="712" alt="screen shot 2016-07-13 at 07 18 35" src="https://cloud.githubusercontent.com/assets/225506/16792605/2e6e57ac-48ca-11e6-9321-bf5af619969d.png">

**Comment by petervojtek** [comment]
I am unable to display tagline (`slogan`) and `bio` in user profile because backend is currently not providing this details.  @igaponov can you please add them to `GET api/profile/info` ? 

This is present behaviour:

```
Request URL:https://api-dev.powerli.ne/api/profile/info/75
Request Method:GET
Status Code:200 OK

{"id":75,"type":"user","username":"Peter12","first_name":"Peter12","last_name":"Peter12","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577df93a7df44.jpeg","birth":"01\/01\/1977","city":"San Diego","state":"CA","country":"US"}
```

**Comment by jterps08** [comment]
**tapping on a @username mention in User post description text opens browser and is trying to open twitter page for that user -- is this intentional? (it makes some sense, however from UX point of view it is confusing that the same looking @mention in comment will lead to different action)..**

This is a good question. I don't know why it points to the Twitter page. It makes more sense that it would point to the user's profile page. @mentioning someone in a post will not lead to a notification alert (but it will in a comment -- we may change this behavior later, but not now). I think we should change the @mention in a post to point to the user profile page. It might be cool in the future that a double @@mention might link out to Twitter or something. 

**the font of mentioned username is intentionally serif? It looks to me like a bug (i find it ugly, I would expect there sans-serif)**

It is not intentional. Please change it. Thanks!

Igor will need to update the profile call, but he should prioritize bug-blocking defects first.

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/185

**Comment by austinpapp** [comment]
definitely san-serif. and yes we should not link to a twitter profile / page but rather the user's profile in app. i'm wondering if there is an external process that was trying to pick up @ mentions with twitter.

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#185 was deployed

**Comment by petervojtek** [comment]
@igaponov , @austinpapp , the `bio` and `slogan` still does not seem to be present in GET profile (if I understand properly powerline-server#185  should have added them).

```
Request URL:https://api-dev.powerli.ne/api/profile/info/73
Request Method:GET
Status Code:200 OK

{"full_name":"Peter10 Peter10","id":73,"username":"Peter10","first_name":"Peter10","last_name":"Peter10","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg","birth":"01\/01\/1977","country":"US"}
```

**Comment by austinpapp** [comment]
its there. i assume you updated the bio and slogan fields?

**Comment by igaponov** [comment]
@petervojtek first, `/api/profile/info/` returns follower profile (short info). Second, `/api/profile` (that returns logged in user's profile) is deprecated now, use `GET /api/v2/user`.

**Comment by petervojtek** [comment]
@austinpapp , yes user `Peter10` has both bio ans slogan values set.

@igaponov , I understand you last comment, however @jterps08 's request (first comment in this issue) is: "User's tagline and bio fields should be displayed.for followed users." -- which I guess means that `bio` and `slogan` should be provided via the  short info request `/api/profile/info/`

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/193

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#193 was deployed

**Comment by petervojtek** [comment]
thanks for the bio and slogan, it works now.
