### ISSUE TITLE
App crashes when Saving Profile Photo

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#105]
User tries to provide new profile photo via My Profile screen. App crashes and restarts automatically. Newsfeed is empty upon restarting app.

**Comment by jterps08** [comment]
It does not appear that the "stay logged in" feature works correctly if the user is crashed out of the app.  The user is brought back into the app (and My Profile shows that it's the same correct logged in user), but the newsfeed is only restored if the user manually logs out and logs back in.

**Comment by petervojtek** [comment]
Cannot reproduce (on Android 6, update profile photo works well.)
@jterps08 , can you tell me which android version you use?

**Comment by jterps08** [comment]
I'm using Android 5.0.1 on a Galaxy S4...

**Comment by petervojtek** [comment]
@jterps08 , I am unable to reproduce the bug -  I used emulator with android 5.0.1, but the app did not crashed and photo in profile was updated successfully. 

Let's see with the next apk if you will still face this problem with your smartphone..
