### ISSUE TITLE
Error on Saving Profile Changes 

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#106]
When user makes any adjustment to Profile (except photo), an error is thrown regarding the "duplicate value already used" in the e-mail address field (even if e-mail address was not changed). All other changes to the My Profile screen cannot be tested as a result of this recurring problem.

**Comment by petervojtek** [comment]
@igaponov, we face two issues related to user profile update:

### Problem 1: unable to change users email in profile

Editing profile works well except when I try to change user's email. In such case it fails in following manner:

```
Request URL:https://api-dev.powerli.ne/api/profile/update?step=0
Request Method:POST
Status Code:500 Internal Server Error

{"full_name":"Peter No 11","id":74,"username":"Peter11","first_name":"Peter","last_name":"No 11","email":"peter11@test2.com","zip":"111","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cac73df67a.jpeg","birth":"01/01/1977","address1":"San Diego","address2":"111","city":"San Diego","state":"CA","country":"US","phone":"+1111","bio":"there","slogan":"hello","interests":[],"do_not_disturb":false,"is_notif_questions":true,"is_notif_discussions":true,"is_notif_messages":true,"is_notif_micro_following":true,"is_notif_micro_group":true,"is_notif_scheduled":false,"is_notif_own_post_changed":true,"is_registration_complete":true,"avatar_src_prefix":null}
Name


response:
{"code":500,"message":"Unable to connect."}
```

### Problem2 : unable to edit profile for old users due to email:This value is already used.

Then there seems to be a bug which is present only for old users (e.g. `Jesse55`) - when I try to edit e.g. zip code for `Jesse55`, it fails in following manner:

```
Request URL:https://api-dev.powerli.ne/api/profile/update?step=0
Request Method:POST
Status Code:400 Bad Request

{"full_name":"Jtest55 Jtest55","id":27,"username":"jtest55","first_name":"Jtest55","last_name":"Jtest55","email":"jterps08+56@gmail.com","zip":"1002","avatar_file_name":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png","birth":"05/28/1986","address1":"276 W 71st St","city":"New York","state":"NY","country":"US","phone":"+19084335678","interests":[],"do_not_disturb":false,"is_notif_questions":true,"is_notif_discussions":true,"is_notif_messages":true,"is_notif_micro_following":true,"is_notif_micro_group":true,"is_notif_scheduled":false,"is_notif_own_post_changed":true,"is_registration_complete":true}


response:
{"errors":[{"property":"email","message":"This value is already used."}]}
```

This bug affects only old users. E.g. user `Peter10` is not affected by this problem no 2.

**Comment by jterps08** [comment]
@petervojtek  Just for reference: The intended behavior is as follows --
1)  We never allowed user to change e-mail previously. We do not need to accommodate this change from a backend standpoint yet (maybe in the future - we'll just need corresponding UI to confirm the new e-mail address along with a confirmation e-mail link to confirm real e-mail address). 
2) _I believe_ that we did allow the user to change _everything else_ in the profile including maybe username too. We _definitely_ allowed the user to change his physical address. When that change is submitted, it's important that the backend update the user's linked elected leaders and groups. If there's a way to initiate a refresh of that information from the frontend upon a profile save that specificaly involves the user's address, that would be ideal, but we can treat that separately as an enhancement. 

Otherwise, user must be able to save profile successfully without this value is already used error.

**Comment by igaponov** [comment]
@jterps08 accordig to the code:
1. We [did](https://github.com/PowerlineApp/powerline-server/blob/develop/backend/src/Civix/ApiBundle/Controller/ProfileController.php#L232) allow user to change his email. And this 500 error is because the server can't connect to payment gateway to change customer's email.
2. I see many duplicated emails in dev db. Maybe before there was no unique validator and there is no unique index in db for an `email` field.

**Comment by jterps08** [comment]
As long as we can save the profile photo we can close this bug. We can open a separate issue for changing customer's e-mail in Stripe.

**Comment by petervojtek** [comment]
@jterps08 , unless @igaponov won't fix this: `I see many duplicated emails in dev db` , some some users (`e.g. Jesse1`) won't be able to change their profile photo, because the email validation seems to be fired in that use case as well thus preventing the profile photo from being changed.

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/240 was deployed

**Comment by petervojtek** [comment]
@igaponov ,  when I try to change photo for user `JTest1` and save the profile, I experience following error:

```
Request URL:https://api-dev.powerli.ne/api/profile/update?step=0
Request Method:POST
Status Code:400 Bad Request

response:
{"errors":[{"property":"email","message":"This value is already used."}]}

```

**Comment by igaponov** [comment]
@jterps08 please try to use command to delete users after deploy.

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/258 was deployed

**Comment by petervojtek** [comment]
@austinpapp , I am not sure who is responsible for the backend side on this issue, but the bug still persists, i.e. when I try to update photo for user `JTest1`, I experience:

```
Request URL:https://api-dev.powerli.ne/api/profile/update?step=0
Request Method:POST
Status Code:400 Bad Request

{"errors":[{"property":"email","message":"This value is already used."}]}
```

**Comment by austinpapp** [comment]
if its backend code, it's @igaponov

**Comment by austinpapp** [comment]
@igaponov it's also worth pointing out that while you are handling this error, please build out a v1 test suite for profile. i realize avatar uploads maybe slightly more challenging but as long as we can some what prove out updates to profiles for the major things are working, we are in a much better place.

**Comment by igaponov** [comment]
This error occurs because of duplicated user's emails, we need @jterps08 to delete all duplicated users with console command.

**Comment by jterps08** [comment]
@austinpapp I'll need your help to complete this effort. It's pretty much my address that's causing the problem because of all the test accounts I made with it. Will discuss via Slack

**Comment by jterps08** [comment]
ping.

**Comment by austinpapp** [comment]
still have issues with sql and constraints. https://github.com/PowerlineApp/powerline-server/issues/280

**Comment by igaponov** [comment]
@jterps08  PowerlineApp/powerline-server#280 is fixed, try again please.

**Comment by jterps08** [comment]
@austinpapp is running the console. I'll talk to him via Slack. Thanks @igaponov

**Comment by jterps08** [comment]
What is our status with this?

**Comment by igaponov** [comment]
@jterps08 you should try to delete duplicated users on dev with console command

**Comment by austinpapp** [comment]
@igaponov run the command. delete them. its dev...

**Comment by igaponov** [comment]
All duplicates were deleted

**Comment by petervojtek** [comment]
@igaponov , I still experience the error when trying to update profile as `JTest1`:

```
Request URL:https://api-dev.powerli.ne/api/profile/update?step=0
Request Method:POST
Status Code:400 Bad Request

{"errors":[{"property":"email","message":"This value is already used."}]}
```

**Comment by austinpapp** [comment]
What is jtest1 email? Let's just take a look in the back end. Igor you can show me the output via slack

**Comment by petervojtek** [comment]
ok, finally it works for JTest1

**Comment by jterps08** [comment]
Hallelujah.
