### ISSUE TITLE
Both Group Selectors Missing Local Group

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#109]
The Group Selector on the Newsfeed and the Group Selector on New Post/Petition screen are both missing the Local Group (e.g. Bucklin). State and Country are appearing correctly.

**Comment by petervojtek** [comment]
I cannot reproduce this bug with user `Peter10` , I see all his groups properly.  It seems to affects only older users while newly created users are [fine due to this Igor's comment](https://github.com/PowerlineApp/powerline-mobile/issues/93#issuecomment-229321702).

I confirm that when I log in as `Jesse1`, I cannot see `Bucklin` group in the newsfeed filter nor in the new post/petition screen. 

@jterps08 , Not sure how important it is to have this bug fixed for old users, if yes, we need to mention Igor here, as it will require code tweaks on backend side.

Old users = users created more than two days ago since now :)

Here are screenshots for user Peter10:

<img width="1276" alt="screen shot 2016-06-30 at 08 01 04" src="https://cloud.githubusercontent.com/assets/225506/16478426/ec9ad9ac-3e99-11e6-8b97-be8afb0dc199.png">
<img width="822" alt="screen shot 2016-06-30 at 08 01 50" src="https://cloud.githubusercontent.com/assets/225506/16478427/ecb93906-3e99-11e6-8217-d8f31c8ef430.png">

**Comment by jterps08** [comment]
We have about 400 users in production. Is there a way to quickly update it to make sure they have their local groups, @igaponov ? If it's simple, we can make this a backend item...

**Comment by igaponov** [comment]
@jterps08 we can't just add it to db. There are some handlers on event `group join`. For example, we need to subscribe user with Mailgun API. But I can add console command to do this and we will run it on server once.

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/194

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#194 was deployed

**Comment by petervojtek** [comment]
@igaponov , I am not sure how is the PowerlineApp/powerline-server#194 supposed to work, but as far as I can see, user `Jesse1` si still missing the Buckin group (I am not sure at all this was  goal of PowerlineApp/powerline-server#194 at all.) Feel free to close to issue if I do not understand the point of PowerlineApp/powerline-server#194 properly.

**Comment by igaponov** [comment]
@petervojtek you should ask @austinpapp if he ran `app/console fix-local-user-groups` command on dev after deploy.

**Comment by austinpapp** [comment]
@igaponov / @petervojtek - sorry for the delay on this. the `fix-local-user-groups` was ran on dev database. Looks like 75 users were updated.

**Comment by petervojtek** [comment]
@igaponov , @austinpapp, however it seems to me user `Jesse1` (from Bucklin) is still missing the Bucklin group (or maybe I overlooked it?). Here is screenshot of `Jesse1` groups:

<img width="770" alt="screen shot 2016-07-22 at 07 48 46" src="https://cloud.githubusercontent.com/assets/225506/17047748/e9feef1e-4fe0-11e6-8232-b177f0936423.png">

**Comment by igaponov** [comment]
There is no user with username `Jesse1` on dev. User with a name `JTest1` has this group.

**Comment by petervojtek** [comment]
yes, I apologize for mistake. You are right @igaponov , the screenshot is from `JTest1`. However here is the list of groups I receive for `JTest1` via `GET https://api-dev.powerli.ne/api/v2/user/groups`:

```
["The United States of America", "Kansas", "Group2014", "Test", "Build Test Group", "Build Test Two", "App Group", "Developers", "Test Group for Web", "Notifications1", "Test 2015 Group", "DEV", "Earn & Learn", "Sandesh NGO", "test2", "test4", "test5", "test6", "test8", "Fletcher"]
```

It dones not contains Bucklin.

**Comment by igaponov** [comment]
@petervojtek try `GET https://api-dev.powerli.ne/api/v2/user/groups?page=2`

**Comment by petervojtek** [comment]
thanks @igaponov , I apologize I overlooked that. I confirm that `GET https://api-dev.powerli.ne/api/v2/user/groups?page=2` returns Bucklin.

However, I would like to ask -- what is the purpose of pagination in `GET https://api-dev.powerli.ne/api/v2/user/groups`. 

I cannot see any benefit of it from mobile app point of view. In mobile app the groups are rendered in two views:
- activity newsfeed
- group management view (groups are grouped by first letter)

In both cases all groups are provided all at once once without any pagination. I guess it is very unlikely that user will be member of more than 20 groups, and even if so, it is extremely unlikely she will be member of more than 50 groups, thus making the pagination (from mobile point of view) actually an obstacle.. but maybe I miss some context..

**Comment by igaponov** [comment]
@petervojtek I can change default value of `per_page` param to 50, is it ok?

**Comment by jterps08** [comment]
I think that's a good short term solution. It would be ideal if it were always returning the town/state/country groups first followed by all the other ones. This way those 3 always appeared in the group selector. I really can't imagine a user being in more than 50 groups, but I guess it could happen one day. We'll cross that bridge when we get to it.

**Comment by igaponov** [comment]
@jterps08 ok, let's add filter by `type=local`, that will return only town/state/country groups.

**Comment by jterps08** [comment]
Hmmm... So the app will have to do two calls for the group selector one for type local and one for everything else? I think the 50 thing works for now... We can come back to a solid fix later.

**Comment by petervojtek** [comment]
I would say the per_page=50 is just nice solution for the moment... if we find out that there is some particual user with 50+ groups, we can actually fix his "bug" easily only by altering this API endpoint without the necessity to modify and release mobile app.

**Comment by austinpapp** [comment]
fyi https://github.com/PowerlineApp/powerline-server/issues/206 was deployed

**Comment by petervojtek** [comment]
ok, thanks, it works well.
