### ISSUE TITLE
Newsfeed Loading Extremely Slow During Login

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#113]
When user completes registration process (new user jontaffert), the app is very slow to load the user's newsfeed (Group Selector icons and newsfeed content. Not sure if this is frontend or backend issue, but as I write this I am still waiting for newsfeed content to load....

Even if it's not a new user, the newsfeed loading is very slow for existing user when logging in (as JTest55). I have now logged out a few times, and I'm still not getting a newsfeed for JTest55

Tried logging out, but the problem persists. In terms of new user jontaffert, I don't know if I made a mistake during user registration or if the app never actually completed user registration the first time. In terms of existing user JTest55, maybe the cache is full?

**Comment by petervojtek** [comment]
@jterps08 , I cannot reproduce the problem.
I tried to login as `Jesse1` and `Peter7`, from browser and from smartphone, but in all cases the delay since the Login button is pressed until newsfeed content is displayed is cca 3 seconds.

**Comment by jterps08** [comment]
Okay - could be my device. I will close for now and re-open if it happens again.
