### ISSUE TITLE
Facebook register successfull, but login fails with "Error: facebook login failed"

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#115]
1. You must use android device/emulator, it is not working in browser.
2. click to "Register/Login via facebook" button
   3.. Facebook register wizard is opened, entered valid email and password
3. confirm that you allow powerline to access your facebook details.
4. It tells that registration is successful.
5. and then error popup is displayed "Error: facebook login failed".

**Comment by petervojtek** [comment]
maybe am I supposed to have facebook app installed on smartphone as well?

**Comment by jterps08** [comment]
@petervojtek - I believe this only works if the user has Facebook app installed as well.

Ideally, we would have it so that the user does not need the Facebook app installed (so that they can manually enter their Facebook credentials without needing the app), but that might need to be a separate enhancement...

**Comment by petervojtek** [comment]
Ok, I am now debugging it with with Facebook app installed, I will later test it without the app as well.

Registration seems fine, however login fails due to this error:

> Facebook error: Invalid key hash. The key hash PA1KZZ9an+gnqX4d+5454TzjNdc= does not match any stored key hashes. Configure your app key hashes at http://developers.facebook.com/apps/244141112405524"

@jterps08 , it seems we need to change some config settings in Powerline facebook app. I do not have access to the link  http://developers.facebook.com/apps/244141112405524

**Comment by jterps08** [comment]
I have added the key hash to the developer control panel. I will add you as a developer to the project as well - please provide your FB username on Slack.

**Comment by petervojtek** [comment]
@austinpapp , I face following backend issue:

I successfully handshake facebook auth on client side via [cordova-plugin-facebook4](cordova-plugin-facebook4), I successfully acquire auth token, and the last step is to `POST https://api-dev.powerli.ne/api/secure/facebook/login`, which fails in following manner:

```
Request URL:https://api-dev.powerli.ne/api/secure/facebook/login
Request Method:POST
Status Code:400 Bad Request
Remote Address:52.5.45.80:443

request:
facebook_token=EAADeC4hHrhQBAKnKMEIkTuCHnOU70ZByIfYrxvZA9ukbXUBCs6M89BnZAN1DLuxgfMTbhefTEIb9kFAfLJQyfL6RvjepGxBZC5vFZAWAqFwhe0YjG4i8IHJLjWLsA0D9p3iZBiegQZA7DlBQBn9ujJwVQPy5aEQ9zU3ZBeT4lNvzIZCG7Ck4JIgEoRBa9NzaoK0LGrRiY6UvZCVvHFPh3gswfN&facebook_id=309106456096856
```

According to API, status 400 corresponds to `Incorrect facebook token`. 
I tried that with two different facebook account, once with facebook app installed, once without the facebook app, but the behaviour is the same.

I use following facebook APP_ID:

```
        <variable name="APP_ID" value="244141112405524" />
        <variable name="APP_NAME" value="PowerlineApp" />
```

I am not sure how is the token validness checked on server side..

Any help is appreciated.

**Comment by jterps08** [comment]
I'm including @igaponov in this conversation as he may know better than Austin...

**Comment by igaponov** [comment]
@petervojtek for registration use `POST https://api-dev.powerli.ne/api/secure/registration-facebook`. 
400 can be returned if there is some troubles with connection to facebook, so try again if you get this error.

**Comment by petervojtek** [comment]
thanks for help @igaponov , now I moved one step forward and here is my workflow and problems I face:
1. I successfully login to facebook and obtain auth id and token
2. I successfully fetch user profile details from facebook server.
3. Now I want to submit this user profile data via `POST https://api-dev.powerli.ne/api/secure/registration-facebook` and I experience 500 Internal Server Error.
   
   I attach the request details via Slack because it is my own facebook user profile and this repo is public :)

I guess I do not attach some required attribute, or maybe it is a problem that I attach attributes which are not required at all?

**Comment by igaponov** [comment]
@petervojtek I see the error and it's easy to fix. But I don't really understand the goal of this endpoint, because according to docs and code you still should provide all user data (like username, email, name etc). So, probably we need to change this behavior in v2. Thoughts?

**Comment by jterps08** [comment]
I'm not sure if I understand the question. @austinpapp may need to respond...

Check out the current behavior of the production app. We need to replicate it in terms of 1) being able to log into the app with facebook, and 2) being able to register on the app with facebook. 

The primary benefit of registering with facebook is 1) not needing to define username/password/e-mail address during registration (quicker UX for user), and 2) not needing a username or password to login (again quicker UX for user)... However, in order to link them to their electeds and town/state/country groups, we still need to ask the user to provide their address.

**Comment by igaponov** [comment]
@jterps08 that means we need to change this endpoint, now username/password/email are required and `/facebook/login` returns 302 redirect to nowhere.

**Comment by jterps08** [comment]
So wait, why does this endpoint behave differently compared to v1? We need to be able to accomplish this: 

**The primary benefit of registering with facebook is 1) not needing to define username/password/e-mail address during registration (quicker UX for user), and 2) not needing a username or password to login (again quicker UX for user)... However, in order to link them to their electeds and town/state/country groups, we still need to ask the user to provide their address.**

@austinpapp do you know what's going on here?

**Comment by igaponov** [comment]
@jterps08 I understand, v2 will do this.

**But now v1 1) requires username/password/e-mail address during registration.**

**Comment by jterps08** [comment]
Hmm... Very strange. Thanks Igor... I thought we had that handled differently. Austin will have to clarify for me how this was working... 

I would _eventually_ like to be in a position where we have the official FB dialog boxes presented like so: 

![image](https://cloud.githubusercontent.com/assets/7582457/16938342/ca38f36c-4d44-11e6-949f-34578575669a.png)

My reasoning is this... In the not too distant future, we will want to give people the ability to click a button in the app to share a fundraiser/petition/event to their Facebook network (and we'll want the app to post that for the user without the user leaving Powerline to do it -- so that will require the user to give Powerline permission to post on behalf of the user to Facebook down the road)... Not sure how relevant this is now, but wanted to mention it...

**Comment by austinpapp** [comment]
i'm not really sure what i need to answer here but i'll try and register via our fb endpoint and report back with findings.

**Comment by igaponov** [comment]
After this issue we will have to add client_id/client_secret of facebook app to backend config

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/224 deployed.

**Comment by petervojtek** [comment]
@igaponov , When I try to post facebook auth details I experience following server behaviour:

```
Request URL:https://api-dev.powerli.ne/api/secure/registration-facebook
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:52.5.45.80:443

request data: in slack

response: no response body
```

I pasted additional details into https://powerline.slack.com/archives/mobile-app-bug-115

**Comment by austinpapp** [comment]
@petervojtek i see you issued a POST but logs are showing a GET

**Comment by petervojtek** [comment]
@austinpapp , from my point of view it seems like regular POST, this is copy&paste of the request details from google chrome inspector:

```
Request URL:https://api-dev.powerli.ne/api/secure/registration-facebook
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:52.5.45.80:443
```

and [this is the source code](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/session.js#L31)

**Comment by petervojtek** [comment]
ok, so it turns out that there is already v2 endpoint which I should give a try:
https://api-dev.powerli.ne/api-doc#get--api-v2-security-facebook

**Comment by petervojtek** [comment]
@austinpapp ,  tried the v2 api and it fails with 401 not authorized.
more details on [slack](https://powerline.slack.com/archives/mobile-app-bug-115)

**Comment by austinpapp** [comment]
fyi - @igaponov pointed to https://github.com/sahat/satellizer#-login-with-oauth-20 which should help to understand the flow.

**Comment by petervojtek** [comment]
waiting for Igor to resolve v1 api error 500 as described above. more details on https://powerline.slack.com/archives/mobile-app-bug-115

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/pull/230 deployed

**Comment by austinpapp** [comment]
@petervojtek igor has fixed v1 of the fb registration/login. so you shouldn't have much to do with the mobile side so please just confirm this works. we will eventually move to v2 but obviously that requires a new plugin.

**Comment by jterps08** [comment]
The Facebook V2 API will deprecate in a few days. We should make sure it works with v2.7.

**Comment by petervojtek** [comment]
thanks @igaponov , I managed to register one facebook user to powerline, but then failed during subsequent login.. more details on slack.

**Comment by igaponov** [comment]
`/v2/security/facebook` works with Facebook API v2.3

**Comment by jterps08** [comment]
We should make this work with v2.7 so we don't have to come back to this issue for a while. I believe that that FB is deprecating 2.2...

**Comment by igaponov** [comment]
``` bash
http POST https://api-dev.powerli.ne/api/secure/facebook/login facebook_token=EAADeC4hHrhQBAHtbawHI6isSWLT3ewZCc1eC3lao7M43WtP9qUV2MpTtenhRTZByFaI8ZC2nEFw3tMDtUkLwhtj0wQfCddyF2C6rEONwqNmfvR9hxgfUNJ4krvmNuiNtEkG76gcvPZBL6MuJGgbi0KCuzUis4XZAhRyCB4CNOugZDZD facebook_id=309106456096856
HTTP/1.1 200 OK
Access-Control-Allow-Headers: accept, origin, x-requested-with, Authorization, content-type, Token
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Thu, 04 Aug 2016 20:36:55 GMT
Server: nginx/1.4.6 (Ubuntu)
Transfer-Encoding: chunked
X-Debug-Token: b9da7d

{
    "id": 78, 
    "is_registration_complete": false, 
    "token": "587b8vt0g5sscg4wwsoccwskkws888w8404s48sw0owsw8ggoc78", 
    "username": "peter.vojtek"
}
```

**Comment by petervojtek** [comment]
@igaponov , I don't know what more can I do to debug this issue. I still experience error 400 on login attempt for user ID=78. Workflow.
1. I successfully handshake with facebook server and obtain following response:

```
{"status":"connected","authResponse":{"accessToken":"<censored>","expiresIn":"5183091","session_key":true,"sig":"...","userID":"309106456096856"}}
```

2 . I try to login to powerline

```
Request URL:https://api-dev.powerli.ne/api/secure/facebook/login
Request Method:POST
Status Code:400 Bad Request

facebook_token=<censored>&facebook_id=309106456096856

response:
{"code":400,"message":"","errors":null}
```

**Comment by igaponov** [comment]
@petervojtek you can use sandbox mode in api doc, endpoint works correctly. Probably something wrong with your request.

**Comment by petervojtek** [comment]
thanks @igaponov , I found out that I missed proper http headers.

Now I am able to login successfully.
