### ISSUE TITLE
Invite users to new group fails with XMLHttpRequest cannot load https://api-dev.powerli.ne/api/invites/.

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#116]
1. create new group
2. click Invite in top right corner

```
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/invites/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by petervojtek** [comment]
@igaponov , there used to be a call `POST https://api-dev.powerli.ne/api/invites/` to invite all user's followers to a group created by the user.

I am not sure which [v2 API call](https://api-dev.powerli.ne/api-doc) is meant to replace it - unless I overlooked it, I cannot see any POST call to invite users to a group, I discovered only this [GET](https://api-dev.powerli.ne/api-doc#get--api-groups-invites).

Current behaviour:

```
Request URL:https://api-dev.powerli.ne/api/invites/
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:52.5.45.80:443

request content:
[{"type":"user-to-group","group":{"id":283},"user":{"id":69}}]




```

**Comment by jterps08** [comment]
FYI: Eventually, in the future, we will want to allow the user to select "all followers" or choose specific  individual follower(s) to send invite to. I think the current functionality only allows for inviting all followers, which is fine for now.

**Comment by igaponov** [comment]
@jterps08 now it's possible only to choose specific users and specific groups.

P.S. Should it be possible to invite only followers? Now there is no this validation.

**Comment by jterps08** [comment]
This feature was originally intended to allow a user to invite all of his followers to join a specific group. It used to work, but it may have been changed. That's okay.

Given what you are saying @igaponov, I think we want this feature to behave this way moving forward: 
1 - User can invite specific users to join group (followers and non-followers) by manually selecting from user's followers list or by manually entering username of non-followers
2 - User can invite all of his followers only in a specific group B to join the group A... If I am in Save the Whales, and I want to invite all of my followers in the Kansas group or Save the Trees group to join, I can do that. 

Thoughts? The initial version of this was simply to invite ALL of my followers, regardless of the group, to join.

**Comment by jterps08** [comment]
@petervojtek - It may make sense to hide/disable/remove this UI element while we wait for the backend to update and simply re-purpose this issue as an enhancement. Your thoughts?

**Comment by petervojtek** [comment]
@jterps08 , ok, I removed the button.

**Comment by igaponov** [comment]
@petervojtek use `PUT /api/v2/groups/{id}/users` after merging https://github.com/PowerlineApp/powerline-server/issues/201

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/pull/201 was deployed

**Comment by petervojtek** [comment]
good job, it works.
