### ISSUE TITLE
After new group is created, user navigation is confusing

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#117]
Once I succcessfully create a group, I am on a screen presenting group detail.

I can navigate myself to other parts of the app only via back button in top left, which guides me back through following screens:
1. "create new group" form
2. Search for group
3. list of groups -- only here I can see in top left corner the toggle menu burger button.

I would rather expect to be guided from group detail screen directly to screen 'My groups'.

**Comment by jterps08** [comment]
Agreed - let's re-direct to My Groups instead.
