### ISSUE TITLE
After new group is created, it is not immidiately displayed in newsfeed in list of groups

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#118]
Currently user must logout and login to see the newly added group.

**Comment by petervojtek** [comment]
@igaponov, I am currently unable to create new group, response is `{"error":{"code":403,"message":"Forbidden"}}`.

```
Request URL:https://api-dev.powerli.ne/api/v2/user/groups
Request Method:POST
Status Code:403 Forbidden
Remote Address:52.5.45.80:443

{"manager_first_name":"Peter10","manager_last_name":"Peter10","manager_email":"peter10@test.com","manager_phone":"+1123","username":"Peter10Group3","official_type":"Non-Profit (Not Campaign)","official_name":"Peter10Group3","official_description":"Peter10Group3","official_address":"here","official_city":"Oklahoma","official_state":"NY","acronym":"ABC"}
```

**Comment by igaponov** [comment]
@petervojtek probably you've reached a limit of groups, each user can have only 5.

**Comment by jterps08** [comment]
@igaponov What is this group limit of 5? I don't remember limiting the number of groups a user could create or join... I do remember creating a leader-controlled limit on how many posts a user could create in a month in a given group. Please clarify when you get a chance. No rush.

**Comment by igaponov** [comment]
@jterps08 I've just copied this from the [old endpoint](https://github.com/igaponov/powerline-server/blob/312a9c98dff2cd13636e5dd4c4350f64b5dc8418/backend/src/Civix/ApiBundle/Controller/GroupController.php#L53):

``` php
        $groups = $em->getRepository(Group::class)->findBy(['owner' => $this->getUser()]);

        if (count($groups) > 4) {
            return $this->createJSONResponse(json_encode([
                'error' => 'You have reached a limit for creating groups',
            ]), 403);
        }
```

**Comment by jterps08** [comment]
@igaponov we're going to need to change this. I really have no idea where this requirement came from :-p ... I'm not sure why we have this limit and how it is enforced given that we only just now are in the process of allowing a user to create a group under his own existing credentials (instead of needing separate credentials for each group he creates/manages).... What's the level of effort to remove this limit? 

It is low priority to change this limit at this point - the higher priority is to get that single-sign-on stuff all complete.

**Comment by igaponov** [comment]
@jterps08 just need to delete this code, couple of minutes.

**Comment by jterps08** [comment]
If it's just a couple minutes, we can delete this limit code for now. Thanks.

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/178

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#178 deployed

**Comment by petervojtek** [comment]
thanks., it works.
