### ISSUE TITLE
switch social follows.js to v2 api (follow/unfollow/approve/unapprove)

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#122]

**Comment by petervojtek** [comment]
the new v2 api is tno working as expected, not sure what may be the problem, but given than that the old api still works properly and igor is occupied by plenty other issues, I rather freeze this issue.

Example of v2 api struggles:
```
Request URL:https://api-dev.powerli.ne/api/v2/user/followers/137
Request Method:PATCH
Status Code:404 Not Found
```

**Comment by petervojtek** [comment]
@igaponov , I try to replace "approve follower" API call from v1 to v2.

I have user `Peter21` (ID=77) which wants to follow `Peter9` (ID=71), and now `Peter9` is about to approve the follower:

here is working v1 call:

```
Request URL:https://api-dev.powerli.ne/api/follow/175
Request Method:PUT
Status Code:200 OK

request body:
{"status":1,"id":175,"date_create":"2016-08-01T09:41:30+0000","date_approval":null,"user":{"full_name":"Peter9 Peter9","id":71,"username":"Peter9","first_name":"Peter9","last_name":"Peter9","avatar_file_name":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png","birth":"01/01/1977","country":"US","bio":null,"slogan":null},"follower":{"full_name":"Peter21 Peter21","id":77,"username":"Peter21","first_name":"Peter21","last_name":"Peter21","avatar_file_name":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png","birth":"01/01/1977","country":"US","bio":null,"slogan":null}}

```

and this is what happens when I switch to v2 approval:

```
Request URL:https://api-dev.powerli.ne/api/v2/user/followers/175
Request Method:PATCH
Status Code:404 Not Found


request body:
{"status":1,"id":175,"date_create":"2016-08-01T09:41:30+0000","date_approval":null,"user":{"full_name":"Peter9 Peter9","id":71,"username":"Peter9","first_name":"Peter9","last_name":"Peter9","avatar_file_name":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png","birth":"01/01/1977","country":"US","bio":null,"slogan":null},"follower":{"full_name":"Peter21 Peter21","id":77,"username":"Peter21","first_name":"Peter21","last_name":"Peter21","avatar_file_name":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png","birth":"01/01/1977","country":"US","bio":null,"slogan":null}}

response;
{"code":404,"message":"Civix\\CoreBundle\\Entity\\UserFollow object not found.","errors":null}
```

I am not sure if I should send some other ID in the URL or what may be the issue.
I am also not sure if I am supposed to send anything the v2 request body.

And, my other question is what value should I set to `status` attribute when I want to 'unapprove' (in v1 api it was status=0).

**Comment by igaponov** [comment]
@petervojtek you should use id of user (follower). For `Peter9` it will look like `PUT https://api-dev.powerli.ne/api/follow/77`

In old version you can just revert status to `PENDING` (status=0). There is no this functionality in new version now.

**Comment by jterps08** [comment]
We probably need the ability to do this in API v2, right?

**Comment by igaponov** [comment]
Ok, I've made a mistake here. We have two roles: follower and followed, so need two different endpoint types:

for follower:
`PUT /followings/{id}` - follow a user 
`DEL /followings/{id}` - unfollow a user

for followed:
`PATCH /followers/{id}` - approve a follower
`DEL /followers/{id}` - unapprove a follower
`GET /followers` - return user's followers

**Comment by igaponov** [comment]
@petervojtek attributes `follower` and `user` in these endpoints were became inline and will be deleted when you change it on frontend. I see that you use only `GET /followers` and `GET /followers/{id}` now, check the last api doc for these endpoints please and make changes on frontend.

**Comment by petervojtek** [comment]
@igaponov , I try to follow an user using `PUT /followings/{id}`, however I experience _following_:

```
Request URL:https://api-dev.powerli.ne/api/v2/followings/74
Request Method:PUT
Status Code:404 Not Found

{"code":404,"message":"No route found for \"PUT \/api\/v2\/followings\/74\"","errors":null}
```

maybe it is not deployed?

**Comment by igaponov** [comment]
The right url is `https://api-dev.powerli.ne/api/v2/user/followings/74`. Docs are fixed in [PR](https://github.com/PowerlineApp/powerline-server/issues/250).

**Comment by petervojtek** [comment]
@jterps08 , in order to adopt the v2 API, I would need to refactor the [follow.js](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/follows.js) and [influences.js](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/influence.js), because the code in those two files reached state of epic mess, namely:
- those two files do almost the same, we should unite them (and lot of redundant code will be removed)
- the internal naming in JS is using terms `follows` and `following`, which are perfectly confusing (it is not clear who is following who), I would rather use `isFollowedByCurrentUser` and `isFollowingCurrentUser` in variable names. 
- in the v1 API, all the followers and followings were provided by single API call, but in v2 there are two calls (one for followers, one for followings)... which is better, but the old JS code in follows.js is all build around the v1 concept.

I rather ask for your permission to do this.. I expect it will take 3-4 hours (refactoring + adopting v2 api).

**Comment by jterps08** [comment]
Go for it.

**Comment by petervojtek** [comment]
@igaponov , based on you [comment above](https://github.com/PowerlineApp/powerline-mobile/issues/122#issuecomment-240394707) and [api doc](https://api-dev.powerli.ne/api-doc#put--api-v2-user-followings-{id}), logged in as user `Peter10` I try to follow user `Peter21` (ID=77). This is what I experience:

```
Request URL:http://localhost:8101/api/v2/user/followings/77
Request Method:PUT
Status Code:404 Not Found
```

**Comment by igaponov** [comment]
@petervojtek that means there is no user with ID=77. Are you sure `http://localhost:8101` points to dev server?

**Comment by petervojtek** [comment]
@igaponov , there is user with ID=77:

```
Request URL:https://api-dev.powerli.ne/api/profile/info/77
Request Method:GET
Status Code:200 OK

{"full_name":"Peter21 Peter21","id":77,"username":"Peter21","first_name":"Peter21","last_name":"Peter21","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png","birth":"01\/01\/1977","country":"US"}
```

**Comment by igaponov** [comment]
@petervojtek I don't understand why do you use localhost to follow a user and dev server to check if the user exists.

**Comment by petervojtek** [comment]
ok, the issue with http 404 status when trying to follow an user was my stupid mistake.

**Comment by petervojtek** [comment]
ok, hopefully it is done.
