### ISSUE TITLE
Create new Petition/Post -- in both cases the created entity is labeled as micro-petition

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#123]
When I create Petition (ID=177), currently the code is using:

```
URL:https://api-dev.powerli.ne/api/micro-petitions
Request Method:POST

{"group_id":6,"user_expire_interval":7,"type":"long petition","title":"Petition to save coal power plants","petition_body":"Whatever"}
```

and then in `GET /api/v2/activities` receive:

```
{"id":401,"title":"Petition to save coal power plants","description":"Whatever","sent_at":"2016-07-01T06:42:22.000Z","expire_at":"2016-07-02T06:42:22.000Z","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png"},"entity":{"type":"micro-petition","id":177,"group_id":6},"read":false,"updated_at":"2016-07-01T06:42:22+0000","quorum":1}
```

What is confusing is that in `GET /api/v2/activities`, the `entity.type` is `micro-petition`, despite in POST request it was labeled as `type: long petition`.

For completeness, when I create micro-petition (Post, ID=178), I use:

```
URL:https://api-dev.powerli.ne/api/micro-petitions
Request Method:POST

{"group_id":6,"user_expire_interval":7,"type":"quorum","petition_body":"Micropetition to work 20 hours a week only."}
```

and then in `GET /api/v2/activities` is:

```
{"id":402,"title":"","description":"Micropetition to work 20 hours a week only.","sent_at":"2016-07-01T06:51:52.000Z","expire_at":"2016-07-02T06:51:52.000Z","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png"},"entity":{"type":"micro-petition","id":178,"group_id":6},"read":false,"updated_at":"2016-07-01T06:51:52+0000","quorum":1}
```

and `entity.type` is `micro-petition`, which makes sense in this case.

**Comment by petervojtek** [comment]
@igaponov ,  I guess I could fix this bug by using v2 API, I would like to confirm which endpoints should I use:
- To create new micro-petition, I should use [POST /api/v2/groups/{id}/micro-petitions](https://api-dev.powerli.ne/api-doc#post--api-v2-groups-{id}-micro-petitions) -- the `type` attribute should be `quorum` in such case?
- I am not sure which endpoint am I supposed to use to create Petition

**Comment by igaponov** [comment]
@petervojtek 
- `type` can be `quorum`, `open letter` or `long petition`
- If you want to create a Petition that is a type of Poll, I'm working on this endpoint now.

**Comment by petervojtek** [comment]
thanks @igaponov , let's wait for @jterps08 's decision:

Jesse - currently it is possible from mobile app create only Micro petition due to missing/work-in-progress API calls on other types of content. please let us know what are the priorities regarding other types of content.

**Comment by jterps08** [comment]
@petervojtek - For the group member, they can create two items: Posts (quorum) and petitions (long petition). Both of these are possible with current API.

Per Igor's comment above, when group leaders create a petition, there are more options because it's actually a type of Question/Poll... Leaders (group creator/assigned-managers) do not need to create content through the mobile app at this time (although hopefully we can build that in the future with both you and Igor's help!).

**Comment by petervojtek** [comment]
@jterps08 , I am confused by your response "For the group member, they can create two items: Posts (quorum) and petitions (long petition). Both of these are possible with current API.".

In gui of mobile app, there is a button in top right corner, when you click it, it has two options:
- New Post
- New Petition

No matter if you use one, or the other way, you end up with activity item which is labeled as 'type: micro-petition' -- is this intended behaviour?

**Comment by jterps08** [comment]
"with activity item which is labeled as type: micropetition"

Newsfeed (3person icon) or Social Activity Feed (2person icon)?
Micropetition:quorum (post) vs micropetion:long petition (petition) -- Both are created by any group member with no special leader (group creator/managers) rights.

Group leaders (creator/managers) have their own set of content that they can create (polls, fundraisers, etc.)

Sorry for confusion - we need to fix labeling eventually, but it really is a system-wide effort that we can't undertake at this moment...

**Comment by petervojtek** [comment]
@jterps08 , My previous comment regards to newsfeed activities. No matter if I create a Post, or a Petition (as described in my first comment in this issue), backend will serve both of them labeled as `type: micro-petition` -- I only guess this is not intended behaviour. 

This results in rendering detail of both Post and Petition as a micro-petition template:

This one was creted as a Petition (ID=177):

<img width="710" alt="petition-177" src="https://cloud.githubusercontent.com/assets/225506/16551570/3d8c9d1e-41ba-11e6-8b7c-a6840ae0643d.png">

And this one was create as Micro-petition (ID=178):

<img width="709" alt="micropetition-178" src="https://cloud.githubusercontent.com/assets/225506/16551582/4c325048-41ba-11e6-8b36-eead231cf3b4.png">

Detail of both of these newsfeed activity items is rendered as micro-petition (due to the `type: micro-petition` attribute provided by backend). However in case of  of the Petition (ID=177) I guess we expect to see different detail given this [Glossary entry](https://github.com/PowerlineApp/powerline-server/wiki/Glossary): 

> Petition: Questions with one Option (sign) with Answer method. 

I am actually not sure which template is meant to be used for petition. [Here](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services.js#L38) are the available templates for newsfeed activity items. There is `petition`, but that one seems to be for `leader petition` rather than for `user petition`.

**Comment by austinpapp** [comment]
@petervojtek 
`id: 177` would be a _user petition_ 
`id: 178` would be a _user post_

technically these are both micro-petitions. however, the type should come back (IMHO) as a type of _micro-petition_ as a _long-petition_ and _quorum_ respectively. we can then handle display and options correctly. type of just _micro-petition_ is not clear enough

@jterps08 can you verify this please.

**Comment by jterps08** [comment]
If it's a user petition, there is only one answer (Sign). If its a user post, there are two answers (Upvote and Downvote).... Does this answer your question? A user cannot create a leader petition in the mobile app, only a user petition (long micropetition) or a user post (quorum micropetition).

**Comment by igaponov** [comment]
@petervojtek should I do something for this issue?

**Comment by petervojtek** [comment]
@igaponov, (please correct me if I am wrong), but currently given the information provided by `GET  /api/v2/activities` it is not possible to explicitly distinguish if activity is `User petition` or `User post`, because both of them has set `type=micro-petition`.

Well, technically it is possible to distinguish between them, because _it is known_ that `User post` has always blank attribute `title`, but this is rather a hack and I would expect that the API will clearly state whether an activity is `User petition` or an `User post` (and other activity types as well).

**Comment by igaponov** [comment]
@petervojtek petition must have `entity.type` = `petition` and post must have `entity.type` = `micro-petition`. Can you tell me ids of activities with a wrong type?

**Comment by petervojtek** [comment]
@igaponov, in `GET https://api-dev.powerli.ne/api/v2/activities` for user `Peter10`, every activity seems to have `type=micro-petition`:

```
{"page":1,"items":20,"payload":[{"id":410,"title":"Peter12Group1 Petition test","description":"blah..","sent_at":"Thu, 07 Jul 2016 07:24:34 +0000","expire_at":"Fri, 08 Jul 2016 07:24:34 +0000","responses_count":0,"owner":{"id":75,"type":"user","official_title":"","first_name":"Peter12","last_name":"Peter12","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577df93a7df44.jpeg"},"entity":{"type":"micro-petition","id":185,"group_id":289},"read":false,"updated_at":"2016-07-07T07:24:34+0000","quorum":0},{"id":409,"title":"Test 47","description":"Test 47","sent_at":"Thu, 07 Jul 2016 05:10:42 +0000","expire_at":"Fri, 08 Jul 2016 05:10:42 +0000","responses_count":0,"owner":{"id":75,"type":"user","official_title":"","first_name":"Peter12","last_name":"Peter12","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577df93a7df44.jpeg"},"entity":{"type":"micro-petition","id":184,"group_id":285},"read":false,"updated_at":"2016-07-07T05:10:42+0000","quorum":0},{"id":408,"title":"","description":"Test 45","sent_at":"Thu, 07 Jul 2016 05:10:05 +0000","expire_at":"Fri, 08 Jul 2016 05:10:05 +0000","responses_count":0,"owner":{"id":75,"type":"user","official_title":"","first_name":"Peter12","last_name":"Peter12","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577df93a7df44.jpeg"},"entity":{"type":"micro-petition","id":183,"group_id":285},"read":false,"updated_at":"2016-07-07T05:10:05+0000","quorum":0},{"id":407,"title":"","description":"test 6","sent_at":"Wed, 06 Jul 2016 06:17:33 +0000","expire_at":"Thu, 07 Jul 2016 06:17:33 +0000","responses_count":0,"owner":{"id":69,"type":"user","official_title":"","first_name":"Peter7","last_name":"Peter7","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":182,"group_id":284},"read":false,"updated_at":"2016-07-06T06:17:33+0000","quorum":0},{"id":406,"title":"Petition to live longer","description":"here, there, everywhere..","sent_at":"Wed, 06 Jul 2016 05:37:18 +0000","expire_at":"Thu, 07 Jul 2016 05:37:18 +0000","responses_count":0,"owner":{"id":74,"type":"user","official_title":"","first_name":"Peter11","last_name":"Peter11","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cac73df67a.jpeg"},"entity":{"type":"micro-petition","id":181,"group_id":285},"read":false,"updated_at":"2016-07-06T05:37:18+0000","quorum":0},{"id":402,"title":"","description":"Micropetition to work 20 hours a week only.","sent_at":"Fri, 01 Jul 2016 06:51:52 +0000","expire_at":"Sat, 02 Jul 2016 06:51:52 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition","id":178,"group_id":6},"read":false,"updated_at":"2016-07-01T06:51:52+0000","quorum":1},{"id":401,"title":"Petition to save coal power plants","description":"Whatever","sent_at":"Fri, 01 Jul 2016 06:42:22 +0000","expire_at":"Sat, 02 Jul 2016 06:42:22 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition","id":177,"group_id":6},"read":false,"updated_at":"2016-07-01T06:42:22+0000","quorum":1},{"id":400,"title":"Save the world","description":"again","sent_at":"Fri, 01 Jul 2016 06:34:53 +0000","expire_at":"Sat, 02 Jul 2016 06:34:53 +0000","responses_count":0,"owner":{"id":75,"type":"user","official_title":"","first_name":"Peter12","last_name":"Peter12","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577df93a7df44.jpeg"},"entity":{"type":"micro-petition","id":176,"group_id":285},"read":false,"updated_at":"2016-07-01T06:34:53+0000","quorum":0},{"id":399,"title":"","description":"Whatever","sent_at":"Thu, 30 Jun 2016 10:19:52 +0000","expire_at":"Fri, 01 Jul 2016 10:19:52 +0000","responses_count":0,"owner":{"id":75,"type":"user","official_title":"","first_name":"Peter12","last_name":"Peter12","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577df93a7df44.jpeg"},"entity":{"type":"micro-petition","id":175,"group_id":285},"read":false,"updated_at":"2016-06-30T10:19:52+0000","quorum":0},{"id":398,"title":"","description":"test 44","sent_at":"Thu, 30 Jun 2016 08:15:03 +0000","expire_at":"Fri, 01 Jul 2016 08:15:03 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition","id":174,"group_id":1},"read":false,"updated_at":"2016-06-30T08:15:03+0000","quorum":6},{"id":397,"title":"","description":"Test follow & ignore 2","sent_at":"Thu, 30 Jun 2016 08:10:37 +0000","expire_at":"Fri, 01 Jul 2016 08:10:37 +0000","responses_count":0,"owner":{"id":74,"type":"user","official_title":"","first_name":"Peter11","last_name":"Peter11","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cac73df67a.jpeg"},"entity":{"type":"micro-petition","id":173,"group_id":285},"read":false,"updated_at":"2016-06-30T08:10:37+0000","quorum":0},{"id":396,"title":"","description":"test follow & ignore","sent_at":"Thu, 30 Jun 2016 08:07:49 +0000","expire_at":"Fri, 01 Jul 2016 08:07:49 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition","id":172,"group_id":285},"read":false,"updated_at":"2016-06-30T08:07:49+0000","quorum":0},{"id":391,"title":"","description":"Peter10's Post to USA group","sent_at":"Wed, 29 Jun 2016 14:35:45 +0000","expire_at":"Thu, 30 Jun 2016 14:35:45 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition","id":170,"group_id":1},"read":false,"updated_at":"2016-06-29T14:35:45+0000","quorum":6},{"id":389,"title":"","description":"California post #3 by Peter8","sent_at":"Wed, 29 Jun 2016 08:04:41 +0000","expire_at":"Thu, 30 Jun 2016 08:04:41 +0000","responses_count":0,"owner":{"id":70,"type":"user","official_title":"","first_name":"Peter8","last_name":"Peter8","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":168,"group_id":6},"read":false,"updated_at":"2016-06-29T08:04:41+0000","quorum":0},{"id":388,"title":"","description":"California post #2 by peter8","sent_at":"Wed, 29 Jun 2016 08:01:41 +0000","expire_at":"Thu, 30 Jun 2016 08:01:41 +0000","responses_count":0,"owner":{"id":70,"type":"user","official_title":"","first_name":"Peter8","last_name":"Peter8","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":167,"group_id":6},"read":false,"updated_at":"2016-06-29T08:01:41+0000","quorum":0},{"id":387,"title":"","description":"California Post #1 by Peter7","sent_at":"Wed, 29 Jun 2016 07:58:31 +0000","expire_at":"Thu, 30 Jun 2016 07:58:31 +0000","responses_count":0,"owner":{"id":69,"type":"user","official_title":"","first_name":"Peter7","last_name":"Peter7","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":166,"group_id":6},"read":false,"updated_at":"2016-06-29T07:58:31+0000","quorum":0},{"id":373,"title":"","description":"test bug 74 3rd attemtp","sent_at":"Thu, 23 Jun 2016 05:51:56 +0000","expire_at":"Fri, 24 Jun 2016 05:51:56 +0000","responses_count":0,"owner":{"id":64,"type":"user","official_title":"","first_name":"Peter1","last_name":"Peter1","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/576b9b633f3fa.jpeg"},"entity":{"type":"micro-petition","id":153,"group_id":1},"read":false,"updated_at":"2016-06-23T05:51:56+0000","quorum":5},{"id":354,"title":"","description":"Test bug #74","sent_at":"Wed, 22 Jun 2016 07:26:42 +0000","expire_at":"Thu, 23 Jun 2016 07:26:42 +0000","responses_count":0,"owner":{"id":16,"type":"user","official_title":"","first_name":"Jesse","last_name":"Chen","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/5630c377e06b3.jpeg"},"entity":{"type":"micro-petition","id":149,"group_id":1},"read":false,"updated_at":"2016-06-22T07:26:42+0000","quorum":5},{"id":404,"title":"","description":"San Diego Post to rename Pacific ocean","sent_at":"Mon, 04 Jul 2016 12:30:28 +0000","expire_at":"Tue, 05 Jul 2016 12:30:12 +0000","responses_count":1,"owner":{"id":74,"type":"user","official_title":"","first_name":"Peter11","last_name":"Peter11","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cac73df67a.jpeg"},"entity":{"type":"micro-petition","id":179,"group_id":285},"read":false,"updated_at":"2016-07-04T12:30:28+0000","quorum":0},{"id":403,"title":"","description":"San Diego Post to rename Pacific ocean","sent_at":"Mon, 04 Jul 2016 12:30:12 +0000","expire_at":"Tue, 05 Jul 2016 12:30:12 +0000","responses_count":1,"owner":{"id":74,"type":"user","official_title":"","first_name":"Peter11","last_name":"Peter11","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cac73df67a.jpeg"},"entity":{"type":"micro-petition","id":179,"group_id":285},"read":false,"updated_at":"2016-07-04T12:30:12+0000","quorum":0}],"totalItems":26}
```

**Comment by igaponov** [comment]
@petervojtek that means they are all micropetitions. Do you know an id of a petition activity?

**Comment by petervojtek** [comment]
@igaponov , if you take a look at the [first comment on this issue](https://github.com/PowerlineApp/powerline-mobile/issues/123#issue-163333043), you will see that I am able to create only `User petitions` and `User posts`. Both of them are `micro-petitions`, so technically the `type=micro-petition` is valid infromation, however my question is how am I supposed to determine if a micro-petitions's subtype is `User petition` or `User post`.

**Comment by igaponov** [comment]
@petervojtek ok, I understand now. You can create only `micropetition` with `POST /api/v2/groups/{id}/micro-petitions` endpoint, so all your activities must have type `micro-petition` now. You will be able to create `petition` (that is a type of Poll) when I finish my task about a leader content.

**Comment by petervojtek** [comment]
@igaponov , I am not sure if we understand each other. let's rather wait for @jterps08 to read this conversation and tell us what is the API supposed to provide in context of the use cases which should be provided by mobile app.

**Comment by austinpapp** [comment]
@igaponov if a `user post` or a `user petition` is created, it's of type `micro-petition`. however, posts and petitions in this situation are different only by the options they contain. for example, you sign a petition and the obj details would show that. the problem here is that @petervojtek can't distinguish between a post and petition because either will **always** return `{'type' : 'micro-petition'}` . we need some way of explicitly defining the .. say .. _sub-type_ of the micro-petition. essentially we may need to change the json response to include a micro-petition _sub-type_. 

@petervojtek i believe this captures your problem. correct?

**Comment by jterps08** [comment]
Austin is correct... This is a labeling issue and a v2 issue... 

There are two types of micropetitions: quorum (post) and long petition (petition). https://github.com/PowerlineApp/powerline-server/wiki/Micropetition

The old API allowed a user to create both a "post" (micropetition: quorum) and a "petition" (micropetition: long petition) from the mobile app. We need the new API to allow a user to create both a "post" and a "petition" from the mobile app. We can utilize the micropetition object to achieve this, but the v2 API will need to be able to distinguish between a quorum type micropetition and a 'long petition' type micropetition.

The petition available to leaders (leader poll, leader petition, leader fundraiser, etc.) is a different type of object. The confusion is over the labeling of the leader petition vs the labeling of the 'long petition' type micropetition.

Does this help clarify?

**Comment by igaponov** [comment]
@jterps08  so we need to add `sub-type` attribute, right?

**Comment by austinpapp** [comment]
@igaponov would it make more sense to simple make this `{ 'type' : 'micro-petition:quorum' }` ? this keeps the signature the same but adds the subtype. i do realize this does mean we would have to split on `:` which is kinda... hackish imho but prevents this from changing. i'm open to suggestions, though.

**Comment by jterps08** [comment]
I defer to you two to figure out the best solution @austinpapp @igaponov

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/195

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#195 was deployed

**Comment by petervojtek** [comment]
thanks, done.
