### ISSUE TITLE
Newsfeed: add bookmark (star icon) not working at all

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#125]
No business logic is bind to the star button click.

**Comment by petervojtek** [comment]
this issue is currently blocked by #123 .

When I try to use `POST /api/bookmarks/add/{type}/{itemId}`, I don't know which `type` am I supposed to set in the post request, because each activity currently has `type=micro-petition`, however the [POST /api/bookmarks/add](https://api-dev.powerli.ne/api-doc#post--api-bookmarks-add-{type}-{itemId}) allow only following types: `petition|petition_comment|petition_answer|poll|poll_comment|poll_answer|post|all`

**Comment by jterps08** [comment]
@petervojtek I think you can save it with type = post. 

@habibillah can you confirm?

**Comment by habibillah** [comment]
The correct `type` to bookmark is `petition|petition_comment|petition_answer|poll|poll_comment|poll_answer|post`. `all` type just for `GET` method. 

`micro-petition` type is unknown type when I write for bookmark API. I believe it's a new type, a replacement of another, or something wrong(e.g it should be a `petition` instead of `micro-petition`)

**Comment by habibillah** [comment]
> @petervojtek I think you can save it with type = post.

Saving the type as another type may return success response, but you can't retrieve what you has been saved.

**Comment by petervojtek** [comment]
ok, I brought the bookmark icon in newsfeed to life.

Until things settle down in #123, I use [following hack](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/activity/activity-model.js#L86) to distinguish between User post and User petition: 
- when `type==micro-petition && title.length>0`, I treat it as a User petition (and send `type=petition` in `/api/bookmarks/add`)
- when `type==micro-petition && title.length == 0`, I treat it as a User post (and send `type=post` in `/api/bookmarks/add`)

**Comment by petervojtek** [comment]
```

**Comment by jterps08** [comment]
Crafty solution - thanks Peter
and thank you @habibillah for your quick reply.

**Comment by austinpapp** [comment]
we will just need to take note of the work around (it maybe useful to comment on that in code @petervojtek) .

**Comment by petervojtek** [comment]
@austinpapp , there is such a [comment in source code](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/activity/activity-model.js#L75)

**Comment by austinpapp** [comment]
man! clearly i did not have enough coffee this morning!!! thanks.
