### ISSUE TITLE
After user joins group, the group in not displayed in newsfeed's list of group

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#129]
user must logoout & login to see the new group.
Very similar to #118

**Comment by petervojtek** [comment]
I fixed it, however in order to make code more readable and app behaviour more deterministic, I removed the in-browser group cache -- this may slow down a bit the experience of visiting the newsfeed page.  
I will bring back the groups in-device cache some day later (I created an issue for that --#132), but currently I do not thing it is that important.

**Comment by jterps08** [comment]
Okay - as long as it does not have too negative of an impact on the newsfeed experience, I am good. I want to avoid a slow loading newsfeed as much as possible...
