### ISSUE TITLE
Follow All group Members

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#13]
Pending completion of issue #12. This will be a button on the Group Members screen that sends follow requests to all members of the group. The button "Follow All Members" will have a confirmation dialog box that says "Send follow request to every group member? (Not recommended!)" If Yes is selected, another note pops up saying "Follow requests sent to all group members. You can manage these in My Influences."

**Comment by austinpapp** [comment]
fyi - #18 didnt actually resolve this. this was a mistake.
