### ISSUE TITLE
Unjoin group fails with 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#133]
```
DELETE https://api-dev.powerli.ne/api/groups/join/284 405 (Method Not Allowed)
```

**Comment by petervojtek** [comment]
@igaponov , I have a problem that when I try to unjoin a group, backend throws `405 Method Not Allowed`:

I can join group successfully:

```
Request URL:https://api-dev.powerli.ne/api/groups/join/287
Request Method:POST
Status Code:200 OK
Remote Address:52.5.45.80:443
```

however when trying to unjoin a group, I receive:

```
Request URL:https://api-dev.powerli.ne/api/groups/join/287
Request Method:DELETE
Status Code:405 Method Not Allowed
Remote Address:52.5.45.80:443
```

I searched the API doc, however the `api/groups/join` calls seems to be undocumented and there does not seem to be `v2` replacement for join/unjoin api call for regular user.

**Comment by austinpapp** [comment]
@igaponov we moved `app_dev.php` to be `app.php` so i'm not sure if that altered any `DELETE` action. might be worth a look and/or clean up on `app_dev.php`

**Comment by igaponov** [comment]
@petervojtek actually, for unjoin you should use /api/groups/unjoin/287 endpoint, but I've made v2:
https://github.com/PowerlineApp/powerline-server/pull/168

**Comment by austinpapp** [comment]
@igaponov PowerlineApp/powerline-server#168 is merged. can you deploy to dev for me? thanks.

**Comment by igaponov** [comment]
deployed

**Comment by petervojtek** [comment]
thanks, I adopted the v2 api. it works.
