### ISSUE TITLE
notifications.js:7 Uncaught TypeError: Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#135]
`notifications.js:7 Uncaught TypeError: Cannot read property 'init' of undefined`

it happened on android devices/emulator. It probably prevents push notification from working at all.

**Comment by petervojtek** [comment]
the bug was caused by missing cordova push notification plugin.

I configured ionic in such a manner that push notification backend's `SENDER_ID` is [set here](https://github.com/PowerlineApp/powerline-mobile/blob/develop/config.xml#L68). Currently the `SENDER_ID` there is from [dev.js](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/config/dev.js#L7). We should not forget to change it to production `SENDER_ID` later, or find some way how to dynamically adopt the proper `SENDER_ID` given the production/development environment.

**Comment by jterps08** [comment]
Just to be clear, we should be leveraging this push notification plugin:

https://github.com/phonegap/phonegap-plugin-push

It has many features we require (action buttons, long notification messages/titles/avatars, badge control, etc.)... @petervojtek

**Comment by petervojtek** [comment]
yes, that is the one I resurrected..
