### ISSUE TITLE
flurry analytics not initialized properly: Uncaught TypeError: Cannot read property 'startSession' of undefined

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#139]
services/flurry.js:14.

**Comment by jterps08** [comment]
We really don't use Flurry - so if its easier to remove/disable it instead of fixing it, feel free to do so.

**Comment by petervojtek** [comment]
@jterps08 , currently flurry logging is spread all along the app - should I remove it?

**Comment by jterps08** [comment]
@petervojtek You should do whatever is less effort :-) As long as it doesn't cause any problems, you can just leave it there. I think we're going to need to use Mixpanel a lot more instead in the future using their JS library for certain actions.

**Comment by petervojtek** [comment]
ok, flurry is removed.
