### ISSUE TITLE
Newsfeed displays activities from group I am not subscribed to

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#141]
@jterps08 , I am not sure if this is intended behaviour or not:

Users Peter10 and Peter12 do follow each other.
1. as user `Peter12`, I create used group named `Peter12Group1`
2. as user `Peter12`, I poste new User petition to the group `Peter12Group1`
3. I login as user `Peter10`, and despite `Peter10` did not joined `Peter12Group1`, in his newfseed (tab All), he can see the User petition.

**Comment by austinpapp** [comment]
`peter12group1` would be public so any activities that `peter12` created would show up in `peter10`'s feed. @jterps08 correct?

**Comment by jterps08** [comment]
Let me respond by saying this:

Users should only see items in their newsfeed (3-person icon) from the groups that they are a part of. If I join Peter12Group1, I should see items from Peter12Group1 (leadership and its members) in my newsfeed. If I unjoin Peter12Group1, I should not see items from Peter12Group1 (leadership and its members) in my newsfeed. The All feed should only show the items from the groups that the user is explicitly or implicitly joined to (town, state, country, Peter12Group1, and other groups the user has joined). The all feed should also show content from the Powerline superuser account... I am unsure how the system is architected when it comes to elected representatives who, in the old system (https://admin.powerli.ne/representative/login), could login and send leader content directly to their specific constituents. The content would _appear_ in a town, state, or country group, but it was _not_ sent to all members of the town, state, or country group... I don't know if that utilized some sort of 'hidden' group concept or not.

In terms of following.... In the Social Activity Feed (2-person icon) under the Following tab, the user should see only social activities from people that he follows in groups that both the user and the followed user are a part of. We do not have the ability to distinguish (yet) between a public/private/secret group. Right now, we want to treat all groups as private groups. In other words, you should only be able to see what's going on in that private group if you're joined to it. In the future, we may allow group leaders to change this setting. 

Does this help? I'm not sure why the All feed behavior was changed.

**Comment by petervojtek** [comment]
Ok, so if I understand @jterps08's previous comment properly, the answer to my original question is that if user `Peter10` never joined group `Peter12Group1`, `Peter10` should not see activity from that group in his `All` newsfeed (i.e. answer to my [first comment](https://github.com/PowerlineApp/powerline-mobile/issues/141#issue-164247078) is "no, this is not desired behaviour"). 

@jterps08 , Can you please confirm I properly undestrand the desired behaviour, and if yes, we need to assign this issue to Igor or Austin, because what we experience here is result of [`GET /api/v2/activities`](https://api-dev.powerli.ne/api-doc#get--api-v2-activities)

**Comment by jterps08** [comment]
That's correct - we need to assign this issue to @igaponov . 

Austin - if you are aware of something I am not in regards to this, please let me know. Otherwise, I think Igor needs to update the activities resource.

**Comment by igaponov** [comment]
There are conditions to include activity to user's list:
- activity_condition.district in user.districts
- activity_condition is not superuser
- activity_condition.group in user.groups
- activity_condition.user in user.following
- activity_condition.group_section in user.group_sections
- user in activity_condition.users

They are all `OR`, not `AND`.

I've got these conditions from the [old code](https://github.com/PowerlineApp/powerline-server/blob/develop/backend/src/Civix/CoreBundle/Repository/ActivityRepository.php#L40).

**Comment by jterps08** [comment]
@petervojtek and @igaponov - What is the latest with this? Apparently #170 is blocked by this...

**Comment by petervojtek** [comment]
@jterps08 , it is possible that [the behaviour](https://github.com/PowerlineApp/powerline-mobile/issues/141#issue-164247078) is intented because the users were following each other (despite `Peter10` was not member of group `Peter12Group1`), and thus this condition may have been fulfilled:

> activity_condition.user in user.following

Unfortunately currently I am unable to confirm it due to this [backend change](https://github.com/PowerlineApp/powerline-server/pull/243), which altered follow/unfollow/approve/unapprove and until I do not resolve #122, mobile app follow/unfollow/approve/unapprove is broken and not working properly.

**Comment by jterps08** [comment]
@petervojtek A few thoughts:
- The "All" Feed does not display activities from ALL groups on the system. It only displays activities from the users town/state/country/other-joined-groups. This is on purpose. 
- Thus, if User A is following User B, we only want User A to be alerted about the content in the groups that both User A and User B are a part of. Otherwise, it doesn't make sense to alert them because they shouldn't be able to see the activity to begin with.

So, it's really "if user is following someone and they are both in same group"... 

Does this make sense?

**Comment by petervojtek** [comment]
@jterps08 , then please review the rules pasted [above](https://github.com/PowerlineApp/powerline-mobile/issues/141#issuecomment-231655452) by Igor -- the rules used currently by Igor contradict to your _mental model_.

Igor's rules are all joined via OR, so that only one of the rules needs to be fulfilled for a activity item to appear in All, and in particular this rule is the critical one:

> activity_condition.user in user.following

However you want this:

>  if User A is following User B, we only want User A to be alerted about the content in the groups that both User A and User B are a part of.

Actually, does the first part of the statement (`if User A is following User B`) really matters?
My guess -- When user A is member of group G, he should receive all activity from that group. It does not matter which other users are members of G and it does not matter whether or not A is following them. If my assumption is correct, then Igor just needs to remove this rule: `activity_condition.user in user.following`

**Comment by jterps08** [comment]
Before I comment any further: does all of this have to do with the Newsfeed or the Social Activity Feed? @petervojtek

**Comment by jterps08** [comment]
My comments are in reference to the Social Activity Feed (2-person icon), not the Newsfeed (3-person icon)

My SAF has two tabs "You" tab and "Following" tab... The rule I'm referring to "if User A is following User B, we only want User A to be alerted about the content in the groups that both User A and User B are a part of." is referring to the Social Activity Feed and Notifications. 

Of course, If user A is _not_ following User B, and they're both part of the same group, then User A should still be able to _see_ User B's content in the Newsfeed. He just does not receive any notifications of it (unless boosted) or see it in the Social Activity Feed Following tab.

Does this make sense?

**Comment by petervojtek** [comment]
@jterps08 , I was talking all the time about Newsfeed (3-person icon, where the groups filters are)  :)
Now I am not sure sure for which feed are actually the Igor's rules..

**Comment by jterps08** [comment]
@petervojtek  - Okay, I'm not sure what Igor's rules refer to either, but here's what I do know...

1) The newsfeed should list all content from the user's town, state, country, and joined groups (e.g. Save the Whales). 
2) This content should be listed Priority zone first, non-priority zone second, expired zone third. 
3) The order or visibility of this content is not currently related to following relationships.
3b) In the future, we may ask @igaponov to add a modification to the "non-priority zone" sorting so that items from followed users appear before items from non-followed users (within the non-priority zone).

> There are conditions to include activity to user's list:
> activity_condition.district in user.districts
> activity_condition is not superuser
> activity_condition.group in user.groups
> **> activity_condition.user in user.following**
> activity_condition.group_section in user.group_sections
> user in activity_condition.users
> They are all OR, not AND.

This is the statement I am unsure of... "activity_condition.user in user.following"... This can mean many things. What does it mean Igor?

If Jesse follows Michael and Jesse is in Hoboken, NJ, USA and Michael is in Bucklin, Kansas, USA THEN Jesse gets notified when Michael posts in USA group, but does not get notified when Michael posts in Bucklin or Kansas groups. Jesse can see when Michael posts in USA group because Jesse can see all posts in USA group, but Jesse cannot see Michael's posts in Bucklin or Kansas groups because Jesse is not part of Bucklin or Kansas groups...

**Comment by jterps08** [comment]
@igaponov what does "activity_condition.user in user.following" mean?

**Comment by petervojtek** [comment]
discussion has moved to #170
