### ISSUE TITLE
console warning: Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#143]
```
index.html#/login:1 Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.
```

it is not a bug, but a warning. happened on android 6

**Comment by petervojtek** [comment]
the transition from login screen -> activity newsfeed screen has potential to be optimized (that is what the warning was about), but given the circumstances, let us rather optimize only those screens/transitions, which will really feel slow -- let us address them in separate issues.

**Comment by jterps08** [comment]
I definitely would like to optimize that login -> activity newsfeed screen transition. I've noticed that too... I shall start a list of UX improvements in an issue for us to keep track of @petervojtek
