### ISSUE TITLE
clicking @mention is not leading to user profile

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#145]
this bug originated as #104 , but I moved it to separate issue to have focused discussion here.

Current state of the art:
- A: clicking @username mention in activity description is doing nothing
- B: clicking @username mention is petition/post/whatever detail description opens new browser window and goes to twitter
- C: clicking @username mention in comment leads to user profile - this is good behaviour

Use cases A and B should behave the same way as C (i.e. lead to user profile)

**Comment by petervojtek** [comment]
@austinpapp , @igaponov ,  I would like to discuss what is the best approach to get @mentioned username ID to be able to properly navigate to that user's profile.

There is existing infrastructure for comments (use case C), which works as following:

```
Request URL:https://api-dev.powerli.ne/api/micro-petitions/215/comments/
Request Method:GET
Status Code:200 OK

"comment_body":"@Peter10 is my hero..".
"comment_body_html":"<a data-user-id=\"73\">@Peter10<\/a> is my hero.."
```

Here backend API provides me enriched comment body with `data-user-id`so that I can transform that into user detail url.

However such enriched html is not provided by backend for use cases A and B. 

Example for use case A (newsfeed activity):

```
Request URL:https://api-dev.powerli.ne/api/v2/activities?page=1
Request Method:GET
Status Code:200 OK

{"page":1,"items":20,"payload":[{"id":442,"title":"","description":"@Peter10 is my hero..","sent_at":"Sat, 16 Jul 2016 12:09:15 +0000","expire_at":"Sun, 17 Jul 2016 12:09:15 +0000","responses_count":0,"owner":{"id":71,"type":"user","official_title":"","first_name":"Peter9","last_name":"Peter9","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition","id":215,"group_id":296},"read":true,"updated_at":"2016-07-16T12:09:15+0000","quorum":0},
```

As you can see, there is `description`, but no attribute like `description-html` with `data-user-id`.

The same goes for use case B, e.g. micro-petition and `petition_body`:  

```
Request URL:https://api-dev.powerli.ne/api/micro-petitions/215
Request Method:GET
Status Code:200 OK

{"id":215,"title":"","petition_body":"@Peter10 is my hero..","group":{"id":296,"group_type":0,"avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"Peter10Group3"},"group_id":296,"is_outsiders_sign":false,"created_at":"Sat, 16 Jul 2016 12:09:15 +0000","expire_at":"Sun, 17 Jul 2016 12:09:15 +0000","user_expire_interval":1,"user":{"full_name":"Peter9 Peter9","id":71,"username":"Peter9","first_name":"Peter9","last_name":"Peter9","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"publish_status":0,"type":"quorum","options":[{"id":1,"value":"Upvote","votes_count":0},{"id":2,"value":"Downvote","votes_count":0}],"cached_hash_tags":[]}

```

One solution would be to provide `*-html` attribute also for use cases A and B, so that it will work the same way as comments. If this approach is an issue for some reason, another solution would be to add endpoint like`GET /api/profile/info-by-username/{username}`.

**Comment by austinpapp** [comment]
if we can avoid a second look up that would be ideal. adding a `data-user-id` key seems easiest to me if @mention is found.

**Comment by jterps08** [comment]
@austinpapp are you asking Igor to do that?

**Comment by austinpapp** [comment]
@petervojtek are you looking for full html like we have for the comment body or just a data user id with the id of the user?

My suggestion would be a returned hashmap of usernames to ids so we can handle several mentions correctly. So an attribute of `data-user-ids` with a hashmap.

**Comment by petervojtek** [comment]
@austinpapp , I prefer "full html like we have for the comment body" so that we have this feature implemented consistently.

i.e. activity will feature:

```
"description":"@Peter10 is my hero..".
"description_html":"<a data-user-id=\"73\">@Peter10<\/a> is my hero.."
```

The same for petition/post/whatever which has a description.

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/pull/235 deployed

**Comment by petervojtek** [comment]
ok, this bug is fixed for User post (qourum and petition) so that clicking @mention anywhere leads to user profile. However for the other (leader) content types I was unable to test it as I do not have the option to create such content.
