### ISSUE TITLE
Follow/Unfollow User button is not consistent across app

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#148]
Current there are three ways the follow/unfollow can look like. We should unite the design:

in user profile:

<img width="768" alt="screen shot 2016-07-22 at 09 20 31" src="https://cloud.githubusercontent.com/assets/225506/17049436/a2e71162-4fed-11e6-8041-898548f580d3.png">

In newsfeed:

<img width="764" alt="screen shot 2016-07-22 at 09 20 52" src="https://cloud.githubusercontent.com/assets/225506/17049437/a2e83358-4fed-11e6-980a-42838585bb6b.png">

In influences/friend-finder/.. :

<img width="767" alt="screen shot 2016-07-22 at 09 20 59" src="https://cloud.githubusercontent.com/assets/225506/17049463/c429e5ac-4fed-11e6-9b43-0e87786234b6.png">

**Comment by jterps08** [comment]
Definitely agreed. I'd prefer to use the icons that we use in the newsfeed as the template for everywhere else.

**Comment by petervojtek** [comment]
newsfeed is currently using following icons (because they are out of the box from ionicons.com):

### Not following

<img width="47" alt="screen shot 2016-07-27 at 12 51 21" src="https://cloud.githubusercontent.com/assets/225506/17173072/ddc79fc2-53f8-11e6-86b1-39de40dcccc6.png">

This is ok..

### Waiting for approval

<img width="43" alt="screen shot 2016-07-27 at 12 52 30" src="https://cloud.githubusercontent.com/assets/225506/17173097/05af8bf8-53f9-11e6-987d-64df02cd1305.png">

I would rather use a grey person with hour-glass, this one is not very explanatory.

### Following

<img width="36" alt="screen shot 2016-07-27 at 12 53 32" src="https://cloud.githubusercontent.com/assets/225506/17173115/25eb9286-53f9-11e6-9901-2c6336c89ae3.png">

I would rather use blue person with minus sign to denote that it is possible to unfollow this person.

What do you think @jterps08 ?

If we would use the current icons above, on Influcences screen we will use only the last icon (Following). However blue person icon itself is not very explanatory.. I doubt whether users will understand that "clicking blue person icon" means "unfollow him".

**Comment by austinpapp** [comment]
this makes more sense to me.

**Comment by jterps08** [comment]
good plan. Thanks Peter.

**Comment by petervojtek** [comment]
ok, I altered it as visible on screenshots below. I had to make one adjustment -- unfortunately ionicons do not include hour-glass, so I employed clock to denote waiting-for-approval.

<img width="249" alt="screen shot 2016-07-28 at 10 58 44" src="https://cloud.githubusercontent.com/assets/225506/17207061/032128d2-54b3-11e6-8c5b-6e0847920e29.png">
<img width="792" alt="screen shot 2016-07-28 at 11 01 25" src="https://cloud.githubusercontent.com/assets/225506/17207063/032d2df8-54b3-11e6-81da-63baec04d971.png">
<img width="789" alt="screen shot 2016-07-28 at 11 02 15" src="https://cloud.githubusercontent.com/assets/225506/17207062/032ac5ea-54b3-11e6-8171-0a567e0f359f.png">

@jterps08 or @austinpapp  please confirm it makes sense to you :)

**Comment by jterps08** [comment]
Makes sense. Clock may need to be changed in the future based on user testing, but I think it certainly works for now!
