### ISSUE TITLE
Unable to create bookmark - backend endpoint not found (http 404)

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#149]
bookmarking was working few days ago, and now it fails in following manner:

```
Request URL:https://api-dev.powerli.ne/api/bookmarks/add/post/221
Request Method:POST
Status Code:404 Not Found

{"code":404,"message":"No route found for \"POST \/api\/bookmarks\/add\/post\/221\"","errors":null}
```

not sure if somehow related to this backend issue: https://github.com/PowerlineApp/powerline-server/issues/187#issuecomment-234491583

**Comment by petervojtek** [comment]
sorry for false alert -- I noticed that you change the endpoint signature, and now I must use type:micro_petition instead of type:post.

**Comment by jterps08** [comment]
Think this might have been Habibillah during the rewrite... Thanks.
