### ISSUE TITLE
newsfeed activity: switching between group filters is slow

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#150]
the slowest one is switching from some particular group (e.g. Bucklin) to "All", it may take 2-3 seconds. It depends on how many items are there in "All" newsfeed.

Observed on quite powerful smartphone (Snapdragon 615 CPU) with cca 30 items in "All" feed.

In the past there were already attempts to optimize rendering of activity newsfeed by adopting [bindonce](https://github.com/Pasvaz/bindonce).

Fast hack may be to display a loader when switching between group filters so that user has feedback that his touch request is being processed).
The longer way is to actually optimize rendering :)

What do you think @jterps08

**Comment by jterps08** [comment]
(sigh) let's display the loader for now and we'll add the group filter rendering to the UX improvements list

**Comment by petervojtek** [comment]
ok, loader is there.
