### ISSUE TITLE
Activity Prioritization Again

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#152]
Activity Prioritization was moved to server side back in April: https://github.com/PowerlineApp/powerline-server/pull/113

Ideally, the mobile app should not be doing any prioritization sorting. Right now, Peter has written logic here: https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/activity/activity-model.js#L96... And he started making a comment about it here: https://github.com/PowerlineApp/powerline-mobile/issues/84#issuecomment-229575296

We need activity prioritization (Priority Zones) to work in coordination with pagination/infinite-scrolling as well as the badge counters so that counters are accurate and that priority zone content is loaded before non-priority zone content. All leader content is priority zone until it is read/answered. Only **boosted** user content (user posts or user petitions) is considered priority zone. It is non-priority zone when it is not-boosted. More details on the priority zones is in the original issue: https://github.com/PowerlineApp/powerline-server/issues/58

@igaponov @austinpapp @petervojtek - In my view, frontend/backend are not on the same understanding right now.

**Comment by petervojtek** [comment]
from mobile app point of view I would expect the backend will provide for each activity item an attribute e.g. `is_in_priority_zone: boolean.`

**Comment by igaponov** [comment]
I've exposed `zone` attribute, it can be one of: `prioritized`, `non-prioritized` and `expired`.

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/219 was deployed

**Comment by austinpapp** [comment]
@petervojtek are you good with parsing based on the zone value? would it be easier to handle this as `(0,1,2)` ?

**Comment by petervojtek** [comment]
@austinpapp , I find the current approach perfect (prioritized, non-prioritized and expired as text), because is is self exaplaining and does not requires to use enum in source code.

**Comment by petervojtek** [comment]
ok, implemented.
