### ISSUE TITLE
toasts are not used consistently

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#156]
some actions do not display toasts (e.g. follow user from user profile).

**Comment by jterps08** [comment]
Upvoting/downvoting from newsfeed or from item detail screen
Following user from newsfeed, social activity feed, user profile, Friend Finder results, or group Members screen
Saving/Removing an item to Favorites  (Saved to Favorites / Removed from Favorites)
Subscribing/Unsubscribing to an Item (Subscribed to item / Unsubscribed from item)
Creating a post, user-petition, or making a comment (Post Successful! Petition Successful! Comment Successful!)
Creating any leader content (e.g. Poll sent! Event sent! Fundraiser sent! Announcement sent! Discussion sent! Petition Sent!)
Manually boosting an item (e..g Post boosted!)
Invite to Group (for Post/User-Petition Authors) #383 (e.g. "Invites sent!")
Group Manager invites (e.g. "Invites sent!")
User Post/Petition edited or deleted successfully (e.g. "Edits saved" or "Item Deleted")

**Comment by bakbanga** [comment]
@jterps08 @petervojtek do you want me to create a new branch for this work?

**Comment by bakbanga** [comment]
@jterps08 For some of above, toast messages have already been listed. Should I change the messages for them as you described or will I keep as those are?

**Comment by jterps08** [comment]
Keep them as they are. and for now let's use a new branch please but I
defer to Peter!

Thanks!

**Comment by petervojtek** [comment]
hi @bakbanga, please create a feature branch (fork it from `develop` branch) for this issue and once you're done create a merge request assigned to me.

**Comment by petervojtek** [comment]
merged
