### ISSUE TITLE
Influences: Empty screen when user has zero Following/Followers

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#157]
should display some message like "You have no followers" in such case..

**Comment by austinpapp** [comment]
Something like: "Well that's a bummer. It looks like no one is following you!"

do we have a help screen/page for this? we can add things like "how to get followers"

**Comment by jterps08** [comment]
"Well, that's a bummer. It looks like no one is following you." 
plus the bottom to the Friend Finder page.

I actually want to add these 'humanizing placeholder text' concepts around the app. I'll create an issue

**Comment by petervojtek** [comment]
done.
