### ISSUE TITLE
Too many items in main menu - they don't fit on screen

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#158]
There are "Share this app" and "Logout" items in menu which are not visible.
To access them user must scroll down the menu and it is easy to accidentally click other menu item while scrolling.

<img width="302" alt="screen shot 2016-08-01 at 08 20 25" src="https://cloud.githubusercontent.com/assets/225506/17285101/d356f29c-57c0-11e6-8bc7-27c274cec178.png">

The amount of items in main menu should be smaller so that all of them are visible without scrolling.

**Comment by jterps08** [comment]
Hmmm... Can we have two columns on the menu instead of one? Like Windows 8 Start Menu style almost where it's like 8-10 large tiles 2x4 or 2x5...

It's probably better to show Share this App compared to Other Apps, but I really don't want to remove any of these items.... Another idea might be to combine My Profile & Settings screens into a tabbed page and/or make the "Find friends" screen accessible from the My Influences screen.

Open to your thoughts

**Comment by petervojtek** [comment]
two columns sound good. When In future I find my way to this low-priority issue, I will re-position the main menu items into two columns and provide screenshot for acknowledgement/feedback.

**Comment by jterps08** [comment]
sounds great thanks Peter

**Comment by petervojtek** [comment]
@jterps08 , this is how the main menu can look like:

<img width="302" alt="screen shot 2016-08-01 at 08 20 25" src="https://cloud.githubusercontent.com/assets/225506/17361020/924575e4-596e-11e6-875a-1d392cb6169e.png">

the search icon is just a reuse of Help icon, I would rather use there a magnifier icon, however I will do that after you confirm this menu appeareance change (because to change icons requires to alter the sprites file).

I had to rename "My Representatives" to "Representatives" due to lack of space.

This design is implemented on separate feature branch, I will merge it into `develop` branch only when you confirm that you want it this way.

**Comment by jterps08** [comment]
This looks great. Definitely the magnifier icon for search. 

Representatives works for now... We may want to switch to My Electeds to continue the "My" pattern, but let's keep it as Representatives for now.

**Comment by petervojtek** [comment]
ok, search icon added and feature merged to `develop` branch.
