### ISSUE TITLE
toggle main menu button behaviour is confusing

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#159]
1. I am in newsfeed activity screen
2. I click the burger icon in top left corner
3. main menu is displayed
4. I click the same place again (top right corner) and I am displayed search screen -- I find it confusing, I would expect clicking the same place would keep me on the screen I am (newsfeed activity) and only hide the menu menu.

**Comment by jterps08** [comment]
Agreed. Maybe replace search field with a search icon to open up search screen?

**Comment by petervojtek** [comment]
if we resolve how to position the main menu items to fit on screen (#158), we can just add "Search" as additional main menu entry.

**Comment by petervojtek** [comment]
already fixed long time ago, we just forgot to close this issue
