### ISSUE TITLE
Groups search screen is confusing

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#160]
When I visit search for (unjoined) groups, I looks like this:
### Screen 1

<img width="779" alt="screen shot 2016-08-01 at 11 01 51" src="https://cloud.githubusercontent.com/assets/225506/17288876/6b5a8aac-57d7-11e6-992f-3a4b8bb36df8.png">
### Screen 2

Then when I search for `Peter` string, I see following results:

<img width="788" alt="screen shot 2016-08-01 at 11 02 42" src="https://cloud.githubusercontent.com/assets/225506/17288896/81bedc26-57d7-11e6-8c86-a72e599e431b.png">

Those `Peter*` groups are not visible in Screen 1, I guess that is an intention because screen 1  displays only new groups.
### Screen 3:

and when I search for `another` string, no results are displayed:

<img width="793" alt="screen shot 2016-08-01 at 11 04 09" src="https://cloud.githubusercontent.com/assets/225506/17288943/c0e1a1fe-57d7-11e6-9454-5a42561f041f.png">

I would expect here to see all the `another*` groups here..
#### Other

I am also not sure if it is an intention that the Groups search screen has the bar to switch between nesfeed/social feed/messages -- from UX point of view I find it confusing and I would not expect it to be present here.

**Comment by jterps08** [comment]
This is definitely confusing.

First, the New Groups & Popular Groups should only show the top 5. No need to show all. So we should limit this down to 5. 

I would expect to see the "another" groups as well, but I am unsure why they are not displaying. Is this a search issue on the backend?

I do not think the search screen should have the bar to switch between newsfeed, social feed, messages.

Agreed on all.

**Comment by petervojtek** [comment]
@jterps08 , please assign this issue a priority :)

**Comment by petervojtek** [comment]
@igaponov , I am trying to implement "search for group(s)" use case - so that user enters text query and only groups where title/acronym is matching the text query are displayed. I want to search groups with group_type == 0.

It seems there is no api endpoind to perform such search, so out of curiosity I tried another approach -- get all existing groups (once) and then perform the search locally.
However when I try to get all the groups I receive following error:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups
Request Method:GET
Status Code:500 Internal Server Error

{"code":500,"message":"An exception occurred while executing 'SELECT count(DISTINCT g0_.id) AS sclr0 FROM groups g0_ LEFT JOIN users_groups u1_ ON g0_.id = u1_.group_id WHERE g0_.group_type = ? GROUP BY g0_.id, g0_.group_type, g0_.username, g0_.password, g0_.salt, g0_.avatar_file_name, g0_.avatar_source_file_name, g0_.manager_first_name, g0_.manager_last_name, g0_.manager_email, g0_.manager_phone, g0_.official_name, g0_.official_description, g0_.acronym, g0_.official_type, g0_.official_address, g0_.official_city, g0_.official_state, g0_.created_at, g0_.questions_limit, g0_.petition_percent, g0_.petition_duration, g0_.membership_control, g0_.membership_passcode, g0_.fill_fields_required, g0_.petition_per_month, g0_.required_permissions, g0_.permission_changed_at, g0_.location_name, g0_.token, g0_.transparency, g0_.user_id, g0_.local_state, g0_.local_district, g0_.parent_id' with params [0]:\n\nSQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size","errors":null}
```

Technically  - to have a search endpoint would be better, becuase this `GET api/v2/groups` is unable to serve all groups at once due to pagination.

**Comment by jterps08** [comment]
I seem to recall us having a search endpoint at some point in time. There are different searches performed throughout the application:
- For hashtags / posts
- For groups
- For people
- Maybe even for My Representatives (I can't remember)

But ideally we have an endpoint that can be flexible for these different uses.

**Comment by igaponov** [comment]
The same error again.
http://stackoverflow.com/questions/29575835/error-1038-out-of-sort-memory-consider-increasing-sort-buffer-size

**Comment by petervojtek** [comment]
fine, I discovered this endpoint and it actually works `GET https://api-dev.powerli.ne/api/search`.

I take this issue back to me. I apologize @igaponov for bothering you :)

**Comment by petervojtek** [comment]
after additional research it seems the endpoint `GET https://api-dev.powerli.ne/api/search` returns only those groups which the current user has already joined. So this endpoint does not meet our requirement to display the opposite -- search for groups which the user has not joined.

due to this reason I assign this issue to @jterps08

**Comment by igaponov** [comment]
@petervojtek after https://github.com/PowerlineApp/powerline-server/pull/233 you can use `GET /api/v2/groups` with parameter `query`

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/pull/233 was deployed

**Comment by petervojtek** [comment]
@igaponov , the search request keeps failing:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups?query=Peter
Request Method:GET
Status Code:500 Internal Server Error

{"code":500,"message":"An exception occurred while executing 'SELECT count(DISTINCT g0_.id) AS sclr0 FROM groups g0_ LEFT JOIN users_groups u1_ ON g0_.id = u1_.group_id WHERE g0_.group_type = ? AND (g0_.acronym LIKE ? OR g0_.official_name LIKE ?) GROUP BY g0_.id, g0_.group_type, g0_.username, g0_.password, g0_.salt, g0_.avatar_file_name, g0_.avatar_source_file_name, g0_.manager_first_name, g0_.manager_last_name, g0_.manager_email, g0_.manager_phone, g0_.official_name, g0_.official_description, g0_.acronym, g0_.official_type, g0_.official_address, g0_.official_city, g0_.official_state, g0_.created_at, g0_.questions_limit, g0_.petition_percent, g0_.petition_duration, g0_.membership_control, g0_.membership_passcode, g0_.fill_fields_required, g0_.petition_per_month, g0_.required_permissions, g0_.permission_changed_at, g0_.location_name, g0_.token, g0_.transparency, g0_.user_id, g0_.local_state, g0_.local_district, g0_.parent_id' with params [0, \"%Peter%\", \"%Peter%\"]:\n\nSQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size","errors":null}
```

**Comment by austinpapp** [comment]
`sort_buffer_size = 4M` on devdb

**Comment by petervojtek** [comment]
@igaponov , it seems `GET api/search?query=` behaves the same way as `GET https://api-dev.powerli.ne/api/search` -- it returns only groups the user is member of. However as I wrote [here](https://github.com/PowerlineApp/powerline-mobile/issues/160#issuecomment-237467533), we need the opposite -- we want to seach for those groups which do not have the user as member.

Example query for user `Peter22`which  is not member of any user group.

```
Request URL:https://api-dev.powerli.ne/api/search?query=Peter
Request Method:GET
Status Code:200 OK

response:
{"groups":[],"representatives":[],"users":[{"full_name":"Peter1 Peter1","id":64,"type":"user","username":"Peter1","first_name":"Peter1","last_name":"Peter1","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/576b9b633f3fa.jpeg"},{"full_name":"Peter2 Peter2","id":65,"type":"user","username":"Peter2","first_name":"Peter2","last_name":"Peter2","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/576ba723a3058.jpeg"},{"full_name":"Peter6 Peter6","id":66,"type":"user","username":"Peter6","first_name":"Peter6","last_name":"Peter6","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},{"full_name":"Peterx1 Peterx1","id":67,"type":"user","username":"Peterx1","first_name":"Peterx1","last_name":"Peterx1","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},{"full_name":"Peterx1 Peterx1","id":68,"type":"user","username":"Peterx6","first_name":"Peterx1","last_name":"Peterx1","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},{"full_name":"Peter7 Peter7","id":69,"type":"user","username":"Peter7","first_name":"Peter7","last_name":"Peter7","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/5786285eccab6.jpeg"},{"full_name":"Peter8 Peter8","id":70,"type":"user","username":"Peter8","first_name":"Peter8","last_name":"Peter8","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},{"full_name":"Peter9 Peter9","id":71,"type":"user","username":"Peter9","first_name":"Peter9","last_name":"Peter9","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},{"full_name":"Peter10 Peter10","id":73,"type":"user","username":"Peter10","first_name":"Peter10","last_name":"Peter10","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg"},{"full_name":"Peter No 11","id":74,"type":"user","username":"Peter11","first_name":"Peter","last_name":"No 11","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cac73df67a.jpeg"},{"full_name":"Peter12 Peter12","id":75,"type":"user","username":"Peter12","first_name":"Peter12","last_name":"Peter12","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/579ee69e5e9df.jpeg"},{"full_name":"Peter20 Peter20","id":76,"type":"user","username":"Peter20","first_name":"Peter20","last_name":"Peter20","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},{"full_name":"Peter21 Peter21","id":77,"type":"user","username":"Peter21","first_name":"Peter21","last_name":"Peter21","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},{"full_name":"Pavlik Morozov","id":78,"type":"user","username":"peter.vojtek","first_name":"Pavlik","last_name":"Morozov","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/57a2d7d76088f.jpeg"}]}
```

**Comment by petervojtek** [comment]
my fault, I overlooked that v2 in url name

**Comment by petervojtek** [comment]
ok, it works.
