### ISSUE TITLE
Humanizing Placeholder Text

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#161]
Empty Newsfeed - "The world belongs to those who speak up! Be the first to create a post!" - DONE
Empty Followers - "Well, that's a bummer. You don't have any followers yet." - DONE
Empty Social Activity Feed - "Seems quiet in here. Are you following anyone?" - DONE
Empty Announcements/Messages - "The only announcement right now is that there are no announcements." - DONE

Empty New Post Field - "Words can move the masses. And yours can, too - if you get enough people to support your post. Be nice!"
Empty New Petition Field - "Start by telling a story. Then, close with a call for action or change."
Empty Comments Field - "It's all about exploring different perspectives. Be kind."

**Comment by jterps08** [comment]
@petervojtek - Can you implement the following and we'll mark this as complete:
Empty Comments Field - "It's all about different perspectives. Be kind."
Empty Groups List - "If you want to go fast, go alone. If you want to go far, join a group."
Empty New Post field - "Words have #power. Choose them wisely, @username."
Empty New Petition field - "Real #change comes from the bottom, not the top. Speak up."

**Comment by eriklouis129** [comment]
fixed
![simulator screen shot nov 14 2016 10 37 58 am](https://cloud.githubusercontent.com/assets/20544710/20259686/79057730-aa56-11e6-8ca3-ec94ab26f198.png)
![simulator screen shot nov 14 2016 10 38 55 am](https://cloud.githubusercontent.com/assets/20544710/20259695/8c329676-aa56-11e6-8dd7-ace7bd632865.png)

**Comment by jterps08** [comment]
@eriklouis129 - Please confirm all requirements from the Upwork description have been incorporated. I have re-pasted below for clarity... Sorry for confusion, but it seems that my edits did not get into original job posting:

Field Placeholder Text - Create rotating placeholder text a) "It's all about different perspectives. Be kind." b) "Don't attack people. Understand them." c) "Listen first. Then ask questions" for new comments field... Empty New Post Field - a) "Words can move the masses. And yours can, too - if you get enough people to support your post. Be nice!" and b) "Write what you mean and mean what you write! But don't be mean!"... Empty New Petition Field placeholder text- "Start by telling a story. Then, close with a call for action or change." https://github.com/PowerlineApp/powerline-mobile/issues/161

Also, small typo - it's masses (not messes)

**Comment by jterps08** [comment]
@eriklouis129 - Please confirm all requirements from the Upwork description have been incorporated. I have re-pasted below for clarity... Sorry for confusion, but it seems that my edits did not get into original job posting:

Field Placeholder Text - Create rotating placeholder text a) "It's all about different perspectives. Be kind." b) "Don't attack people. Understand them." c) "Listen first. Then ask questions" for new comments field... Empty New Post Field - a) "Words can move the masses. And yours can, too - if you get enough people to support your post. Be nice!" and b) "Write what you mean and mean what you write! But don't be mean!"... Empty New Petition Field placeholder text- "Start by telling a story. Then, close with a call for action or change." https://github.com/PowerlineApp/powerline-mobile/issues/161

Also, small typo - it's masses (not messes)

**Comment by eriklouis129** [comment]
Create rotating placeholder text???

in which screen?

**Comment by eriklouis129** [comment]
Empty New Post Field - a) "Words can move the masses. And yours can, too - if you get enough people to support your post. Be nice!" and b) "Write what you mean and mean what you write! But don't be mean!"????

in which screen, there are two placeholder?

**Comment by jterps08** [comment]
Using new content menu (pencil paper icon in upper right corner of home screen), tap "New Post" 

We want the user to see either of these messages as placeholder text. The text should change each time you create a new post.

**Comment by jterps08** [comment]
![image](https://cloud.githubusercontent.com/assets/7582457/20270851/bbc54a32-aa56-11e6-8d0c-0deb5129059d.png)

**Comment by eriklouis129** [comment]
fixed.
![screen shot 2016-11-14 at 6 37 49 pm](https://cloud.githubusercontent.com/assets/20544710/20275635/a7cf30cc-aa99-11e6-8c8d-c074645fc901.png)
![screen shot 2016-11-14 at 6 38 01 pm](https://cloud.githubusercontent.com/assets/20544710/20275640/ab86fee8-aa99-11e6-9727-88b4c7ce1e39.png)
![screen shot 2016-11-14 at 6 38 28 pm](https://cloud.githubusercontent.com/assets/20544710/20275647/aef00ffc-aa99-11e6-830c-22b739bba412.png)
![screen shot 2016-11-14 at 6 38 42 pm](https://cloud.githubusercontent.com/assets/20544710/20275652/b19b39e8-aa99-11e6-9668-aba4b49ba63c.png)
![screen shot 2016-11-14 at 6 38 51 pm](https://cloud.githubusercontent.com/assets/20544710/20275659/b57c2676-aa99-11e6-9892-c25db0ef77b4.png)
![screen shot 2016-11-14 at 6 38 59 pm](https://cloud.githubusercontent.com/assets/20544710/20275662/b87c0512-aa99-11e6-9879-24c6eabcd5ac.png)

**Comment by jterps08** [comment]
The Comment Placeholder text is not for New Group Discussions, it's for the comments field. You can keep what you've put in New Group Discussions or remove it. Your choice, but the Comments field is where the placeholder information needs to be. 

Open any item in your newsfeed (post / poll / anything), scroll down to find ability to add comment - this is the field for :
a) "It's all about different perspectives. Be kind." b) "Don't attack people. Understand them." c) "Listen first. Then ask questions"

**Comment by eriklouis129** [comment]
any screenshot???

**Comment by jterps08** [comment]
i will send to you in slack - I can't post here for some reason

**Comment by eriklouis129** [comment]
need your explain how I can reach that screen.

**Comment by eriklouis129** [comment]
fixed.
![screen shot 2016-11-14 at 9 18 17 pm](https://cloud.githubusercontent.com/assets/20544710/20281217/eaca937e-aaaf-11e6-9633-bf5834936002.png)
![screen shot 2016-11-14 at 9 18 07 pm](https://cloud.githubusercontent.com/assets/20544710/20281218/eacf49f0-aaaf-11e6-86e8-0e9cf474ea05.png)
