### ISSUE TITLE
Austin's Profile Avatar

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#163]
Is missing or broken.
Blocked by @austinpapp

**Comment by austinpapp** [comment]
not sure what this is...

**Comment by jterps08** [comment]
![image](https://cloud.githubusercontent.com/assets/7582457/17423306/c8128bac-5a87-11e6-9465-6154a5b01d88.png)

**Comment by austinpapp** [comment]
my avatar on github?

**Comment by jterps08** [comment]
Yes.

**Comment by austinpapp** [comment]
that is my actual picture... and if anything if it were a problem its a github problem not powerline.
