### ISSUE TITLE
User not prompted to confirm new group permissions

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#164]
When user is already member of a group and group permissions do change, detection of the newly added group permissions is not working (and thus the "confirm new permissions" prompt is not displayes for the user).

In the old code to check if group permissions has been altered was performed by comparing `permission-settings.permissions_approved_at` timestamp and `group.permissions_changed_at` timestamp. However, current it seems backend provides only the first timestamp and lacks the second one.

permissions data:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/289/permission-settings
Request Method:GET
Status Code:200 OK

{"required_permissions":["permissions_phone"],"permissions_changed_at":"Thu, 04 Aug 2016 08:30:44"}
```

group data:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/289
Request Method:GET
Status Code:200 OK

{"total_members":1,"id":289,"group_type":0,"avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","manager_phone":"ff","official_title":"Peter12Group1","official_description":"Peter12Group1","acronym":"P12G","official_address":"Peter12Group1","official_city":"Peter12Group1","official_state":"Peter12Group1","joined":1,"membership_control":"public","fill_fields_required":false}
```

However the second request (group info) has no `permissions_approved_at` timestamp.

**Comment by jterps08** [comment]
Wow - good find. Thanks Peter.

**Comment by igaponov** [comment]
@petervojtek I've moved an endpoint from v1 to check/change user group permissions, see api doc (`/api/v2/groups/{group}/permissions`) after deploy

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/pull/238 was deployed

**Comment by petervojtek** [comment]
I am blocked here because the API doc is not generated properly

**Comment by jterps08** [comment]
API doc should be available. Please let us know if there's anything else blocking this issue that Igor needs to work on.

**Comment by petervojtek** [comment]
@igaponov , can you confirm that below is the proper workflow to check if group permissions has changed?
1. get group permissions `/api/v2/groups/{group}/permission-settings`
2. get permissions for user  `GET /api/v2/groups/{group}/permissions`
3. compare the permissions from step 1 and step 2. 
4. If they are the same, permissions has not changed.
5. if they are different, ask user to confirm on the permissions change, and if user confirms, make `PUT /api/v2/groups/{group}/permissions`.

**Comment by igaponov** [comment]
@petervojtek I think it should work. There is also a social activity with a type `group-permissions-changed` (and a push notification for this activity as well).

**Comment by jterps08** [comment]
@petervojtek this has been a push notification in the past (per igor's comment above). When the push comes in, the social activity item comes in too alerting the user... I think this is what we need to confirm is happening... not the manual comparison that you are outlining above.

In the future (not now), we will want to give 24 hours before allowing leaders to access the new changes (e.g. step 1) alert all group members of changed permissions, step 2) wait 24 hours, step 3) update access conditions for group leader to reflect new permissions... This gives time for people to react.

**Comment by petervojtek** [comment]
I confirm the social notification arrives:

<img width="974" alt="screen shot 2016-09-22 at 08 04 11" src="https://cloud.githubusercontent.com/assets/225506/18738336/2f807630-809b-11e6-9a05-46d3771f0d7e.png">

**Comment by petervojtek** [comment]
@jterps08 , and what should happen when user won't confirm the new permissions?

when the user will return again to the group page, should he be again asked to confirm the permission?

**Comment by petervojtek** [comment]
@igaponov , the [scenario above](https://github.com/PowerlineApp/powerline-mobile/issues/164#issuecomment-248557815) works well when user is already member of the group (and permissions change).

However when user is not member of the group and is about to join, I experience following problem (as Peter10 trying to join group 309):

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/309/permissions
Request Method:GET
Status Code:404 Not Found
```

**Comment by petervojtek** [comment]
for anyone who would like to test this use case, you cn use this JS console helper to change group permissions: https://github.com/PowerlineApp/powerline-mobile/wiki/HOWTO-Create-leader-content-from-JS-console#change-group-permissions

**Comment by jterps08** [comment]
FYI I received the new permissions change push notification for a group this morning Peter.

In terms of not confirming the new permissions, if user does not accept, user leaves the group. If user accepts, user stays in the group.

**Comment by petervojtek** [comment]
ok, done.
