### ISSUE TITLE
micro-petition:long-petition appears multiple times in activity newsfeed after sign/unsign

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#165]
@igaponov , I am not sure if this is intention or bug:
1. when the micro-petition is created, it appears only once in newsfeed (activity ID=497)
2. When I sign the petition, another activity for the micro-petition appears (so that there are two of them, 497 and 498). 

After another unsign and another sign, the micro-petition has three activity items (497, 498 and 499).

from UX point of view I find this behaviour confusing...

```
{"zone":"non_prioritized","id":499,"title":"Desalinate pacific ocean","description":"test.","sent_at":"2016-08-05T07:47:48.000Z","expire_at":"2016-08-06T07:47:16.000Z","responses_count":1,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition:long-petition","id":237,"group_id":285},"picture":null,"read":true,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-08-05T07:47:48+0000","metadata":null,"comments_count":1,"answers":[{"id":83,"option_id":1,"created_at":"2016-08-05T07:47:48+0000"}],"quorum":1,"owner_info_1":"San Diego"}

{"zone":"non_prioritized","id":498,"title":"Desalinate pacific ocean","description":"test.","sent_at":"2016-08-05T07:47:27.000Z","expire_at":"2016-08-06T07:47:16.000Z","responses_count":1,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition:long-petition","id":237,"group_id":285},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-08-05T07:47:27+0000","metadata":null,"comments_count":1,"answers":[{"id":83,"option_id":1,"created_at":"2016-08-05T07:47:48+0000"}],"quorum":1,"owner_info_1":"San Diego"}

{"zone":"non_prioritized","id":497,"title":"Desalinate pacific ocean","description":"test.","sent_at":"2016-08-05T07:47:16.000Z","expire_at":"2016-08-06T07:47:16.000Z","responses_count":1,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition:long-petition","id":237,"group_id":285},"picture":null,"read":true,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-08-05T07:47:16+0000","metadata":null,"comments_count":1,"answers":[{"id":83,"option_id":1,"created_at":"2016-08-05T07:47:48+0000"}],"quorum":1,"owner_info_1":"San Diego"}
```

**Comment by igaponov** [comment]
There is new activity for every action (sign, unsign etc). It was in old code, so I've moved it to v2. Probably, we should ask @jterps08 about it.

**Comment by austinpapp** [comment]
@jterps08 can you confirm appropriate action(s) for when this should or shouldn't be in the newsfeed?

**Comment by jterps08** [comment]
Every group has a boosting level (aka quorum level) that is controlled by the group leaders. At the current moment, that boosting level is a percent of total group members. So, if there are 80 group members and the boosting level is 10%, that means that if a post gets about 8 upvotes/downvotes, then the post is 'boosted'. Boosted posts = push notification alert to ALL group members + priority sorting. See screenshot below from old admin screen.

It is possible that you are upvoting/downvoting a post in a group that is so small that, by upvoting/downvoting that post, you are boosting it. I'm not sure. (2 quick notes: 1) There is no way to un-boost a post. 2) a group leader can manually boost a post, although I'm not sure if this functionality was transferred to api v2)...

When the post is boosted, _ideally_ it only appears once, not twice - the boosted version does not need to look any different than the non-boosted version. If the post is 'boosted', it is in priority zone until user responds to it (upvote/downvote/ignore) or it expires (this setting is also controlled by group leaders)... Boosted posts are one of the more powerful features this platform provides for large groups - they should work in town, state/province, and country groups as well as other groups.

![image](https://cloud.githubusercontent.com/assets/7582457/17459572/fb3e3f00-5c0b-11e6-89ed-1df7e908359b.png)

**Comment by igaponov** [comment]
@jterps08 the question is not about boosting. When user creates, signs or unsigns a petitions, the same activity is added to his newsfeed, so we have many identical activities after some actions.

**Comment by jterps08** [comment]
Hm, okay, I didn't understand the question... So, are you referring to the Newsfeed or to the Social Activity Feed?

The newsfeed should only show an item once. For example, a post (micropetition) should not appear multiple times in the newsfeed...

If you're referring to the Social Activity Feed, the situation is different. A new social activity may be shown that "User X created a post in Group Y". I know that new social activities were being created when a user answered a poll and commenting on any type of object. I cannot remember if we had social activities for signing/unsigning a petition. It seems like we would want that (for followed users), but we would not want duplicate entries, just the latest activity only. 

I realize I still may not be understanding the question :-)

**Comment by igaponov** [comment]
@jterps08 there are two activities in newsfeed for petition now: one appears after creation and one - after boosting. Should I delete one?

**Comment by jterps08** [comment]
After boosting, I only want one. Preferably the one that was boosted.

Right now, I believe production changes the author of the boosted post to be the name of the community, but I don't want that.

For example: Igor creates a post in Save the Whales.
Unboosted Post appears as Igor Gapanov | Save the Whales 
People upvote/downvote the post and it gets boosted.
Boosted Post appears as "Save the Whales"
Boosted Post should still appear as "Igor Gapanov | Save the Whales"

This might be a frontend issue. I'm not sure. But I do want the duplicate removed. Only the boosted one should stay. 

Thanks.

**Comment by austinpapp** [comment]
sorry i missed this but https://github.com/PowerlineApp/powerline-server/issues/246 was deployed

**Comment by petervojtek** [comment]
ok, this issue is fixed.
