### ISSUE TITLE
First facebook login -- unable to fill in user profile data

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#166]
I successfully login via facebook to powerline app, and I experience following behaviour when trying to save the user profile form.
 This step is mandatory for first time facebook login (to complete profile info).

```
Request URL:https://api-dev.powerli.ne/api/profile/update?step=0
Request Method:POST
Status Code:500 Internal Server Error

request:
{"full_name":"Pavlik Morozov","id":78,"username":"peter.vojtek","first_name":"Pavlik","last_name":"Morozov","email":"petervojtek@gmail.com","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/57a2d7d76088f.jpeg","country":"US","facebook_link":"https://www.facebook.com/app_scoped_user_id/309106456096856/","sex":"Male","interests":[],"facebook_id":"309106456096856","do_not_disturb":false,"is_notif_questions":true,"is_notif_discussions":true,"is_notif_messages":true,"is_notif_micro_following":true,"is_notif_micro_group":true,"is_notif_scheduled":false,"is_notif_own_post_changed":true,"is_registration_complete":false,"address1":"san","address2":"123","zip":"123","city":"San Diego","state":"CA","phone":"123","birth":"01/01/1977"}
Name

response:
{"code":500,"message":"Unable to connect.","errors":null}
```

**Comment by igaponov** [comment]
Seems there is a problem with https://api.balancedpayments.com/, wait some time and try again please.

**Comment by jterps08** [comment]
We should not be using Balanced Payments anywhere any longer. All payments are now handled by Stripe. If I'm not mistaken, this _may_ be related to updating the stored "customer" information for the Payments service. I'm not sure why its related to this save profile screen, but we should definitely be using Stripe for anything payments related.

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/pull/248 was deployed

**Comment by petervojtek** [comment]
blocked by #185

**Comment by petervojtek** [comment]
perfect, now it works. This means there is no blocker in the facebook register & login use workflow.
