### ISSUE TITLE
Post Subscriptions Not Working

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#168]
Users should be able to subscribe/unsubscribe to any item for notifications (new comments only for non-authors... comments and upvotes/downvotes for authors). The subscribe/unsubscribe button (bell) does not work. Default subscribed for authors. Default unsubscribed for non-authors.

This might be a duplicate, but I believe it's a frontend issue first.

**Comment by petervojtek** [comment]
@igaponov , I successfully subscribed to a user petition via 

```
Request URL:https://api-dev.powerli.ne/api/v2/user/micro-petitions/243
Request Method:PUT
Status Code:204 No Content
```

However, how can I then determine that user is subscribed or not from activity data?
This is how the activity looks like after user is subscribed to its petition. Unless I overlooked some attribute it does not seems to bear some flag indication whether user is subscribed or not.

```
{"zone":"prioritized","id":509,"title":"Another @mention test in long-petition","description":"Another @Peter21 test in long-petition","description_html":"Another <a data-user-id=\"77\">@Peter21</a> test in long-petition","sent_at":"2016-08-17T10:21:42.000Z","expire_at":"2016-08-18T10:21:29.000Z","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition:long-petition","id":243,"group_id":6},"picture":null,"read":true,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-08-17T10:21:42+0000","metadata":null,"comments_count":1,"answers":[],"quorum":1,"owner_info_1":"California"}

```

I need to gather this information from the activity (to avoid any additional request) to properly style to subscribe/unsubscribe button in activity newsfeed.

**Comment by igaponov** [comment]
@petervojtek use `activity.petition.is_subscribed` and `activity.post.is_subscribed`.

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/pull/252 was deployed

**Comment by petervojtek** [comment]
the endpoint for subsciption is no longer working but it is probably may be due to #187... this issue is blocked by #187.

```
Request URL:https://api-dev.powerli.ne/api/v2/user/micro-petitions/238
Request Method:PUT
Status Code:404 Not Found
```

**Comment by igaponov** [comment]
@petervojtek probably micropetition with ID=238 is a post, not a user petition.

**Comment by jterps08** [comment]
@petervojtek - You should proceed wherever you can on this issue. 

@igaponov - Please advise on the work effort required for the intended requirements below:
A user should be able to subscribe/unsubscribe to **any** item (polls/leader-petitions/discussions/fundraisers/events/user-posts/user-petitions) to be notified for new comments on that item. 

The author of a "user post" should be subscribed to his own post by default. For authors, they are notified for comments _and_ upvotes/downvotes. For non-authors, comments only.

**Comment by igaponov** [comment]
@jterps08 I think it'll not take more than half a day

**Comment by jterps08** [comment]
alright - let's do it then. Thanks @igaponov

**Comment by petervojtek** [comment]
@igaponov , not sure if I should play now with the subscribe/unsubscribe given the changes you have in mind (as described above).
 this is my current experience with subscribe/unsubscribe to user-petition:

subscribe work well (`PUT /api/v2/user/user-petitions/{id}`) and it properly assigns `activity.petition.is_subscribed`, however when I try to unsubscribe, I end up with this:

```
Request URL:https://api-dev.powerli.ne/api/v2/user/user-petitions/242
Request Method:DELETE
Status Code:500 Internal Server Error

{"code":500,"message":"An exception occurred while executing 'DELETE FROM user WHERE id = ?' with params [75]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`civixdevdb`.`activities_read`, CONSTRAINT `FK_1DFA339AA76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`))","errors":null}
```

**Comment by igaponov** [comment]
@petervojtek the last error must be fixed after deploy

**Comment by petervojtek** [comment]
I still experience the issue above, so I guess the fix is not deployed.

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/261 was deployed

**Comment by petervojtek** [comment]
ok, subscribe/unsubscribe works for post.
