### ISSUE TITLE
Author Notification Muting/Unmuting Not Working

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#169]
Authors should be able to mute/unmute author notifications for any of their own created posts. The mute/unmute button (bell) does not work. I am marking this as an enhancement, but I'm not sure. I believe this is a frontend issue.

**Comment by petervojtek** [comment]
@jterps08, I am confused from the terminology.
In #168 you refer to bell button as "subscribe/unsubscribe", while here you refer to "mute/unmute".

Do I understand properly that owner should be automatically subscribed to a post she just created (i.e. the bell button should be active)?

**Comment by jterps08** [comment]
@petervojtek The terminology changes depending on the scenario, but it is the same icon in both circumstances. I will use word 'subscribe' only for clarity. 

Yes, the owner should be automatically subscribed to a post she just created. Bell button should be active. For non-owners, the default is unsubscribed.

The backend should automatically subscribe an author to her own post she created. For authors, the notifications include 1) new upvotes/downvotes, and 2) new comments. Authors can unsubscribe from their post and subscribe again at any time.
The backend should only subscribe a non-author to a post if the non-author subscribes to it. For non-authors, the notifications include: 1) new comments only. Non-authors can subscribe/unsubscribe at any time.

**Comment by petervojtek** [comment]
blocked by #187

**Comment by petervojtek** [comment]
blocked by #168

**Comment by petervojtek** [comment]
@igaponov , for newly created Post, the `"post":{"is_subscribed":true}` in activity item is set by default for every user which can see the post. E.g., this post was created by user `Peter10`, and this is how the post activity item looks for `Peter21`:

```
{"zone":"prioritized","id":535,"title":"","description":"notification subscription should be enabled by default for Peter10 for this Post","description_html":"notification subscription should be enabled by default for Peter10 for this Post","sent_at":"2016-09-01T07:42:21.000Z","expire_at":"2016-09-02T07:42:21.000Z","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"post","id":247,"group_id":285},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-01T07:42:21+0000","petition":null,"post":{"is_subscribed":true},"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":0,"answers":[],"quorum":1,"owner_info_1":"San Diego"}
```

While setting  `"post":{"is_subscribed":true}` by default for Peter10 is desired behaviour because he is the post author, for all the other users it should be `"post":{"is_subscribed":false}` by default  given this Jesse's comment:

> The backend should only subscribe a non-author to a post if the non-author subscribes to it.

Another topic I am not sure if it is intention or bug is that for newly created UserPetition by Peter21, in activity item I see `"petition":null,"post":{"is_subscribed":true},"`, while I would expect the opposite: `"petition":{"is_subscribed":true},"post":null,"`. Actually I am not sure what is the purpose of `petition` attribute at all.. if it should exhibit some information relevant to user-petition, I would not expect it be named `petition` as that is confusing.

Activity item for user-petition created by Peter21 viewed by Peter21:

```
{"zone":"prioritized","id":536,"title":"UserPetition by Peter21","description":"UserPetition by Peter21 desc","description_html":"UserPetition by Peter21 desc","sent_at":"2016-09-01T07:47:55.000Z","expire_at":null,"responses_count":0,"owner":{"id":77,"type":"user","official_title":"","first_name":"Peter21","last_name":"Peter21","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png"},"entity":{"type":"user-petition","id":246,"group_id":285},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-01T07:47:55+0000","petition":{"is_subscribed":false},"post":null,"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":1,"answers":[],"quorum":1,"owner_info_1":"San Diego"}
home.js:335 {"zone":"prioritized","id":531,"title":"","description":"Another Post to test upvote/downvote","description_html":"Another Post to test upvote/downvote","sent_at":"2016-09-01T05:00:12.000Z","expire_at":"2016-09-02T05:00:12.000Z","responses_count":0,"owner":{"id":75,"type":"user","official_title":"","first_name":"Peter12","last_name":"Peter12","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/579ee69e5e9df.jpeg"},"entity":{"type":"post","id":246,"group_id":6},"picture":null,"read":true,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-01T05:00:12+0000","petition":null,"post":{"is_subscribed":true},"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":0,"answers":[],"quorum":1,"owner_info_1":"California"}
```

**Comment by igaponov** [comment]
Fixed, changed attr name to `user_petition`

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/270

**Comment by petervojtek** [comment]
@igaponov , for Post it all works as expected.

However for UserPetition, the `activity.user_petition.is_subscribed` is set to `false` for it's owner. Expected behaviour is:
- `activity.user_petition.is_subscribed` is by default `true` for owner
- and false for everyone else

**Comment by igaponov** [comment]
@jterps08 can you confirm it? According to your [comment](https://github.com/PowerlineApp/powerline-mobile/issues/169#issuecomment-240404935) author should be automatically subscribed to a post, not to a user petition.

**Comment by jterps08** [comment]
@igaponov I will test and confirm. Peter is correct and I made a mistake when I wrote the requirement above. It should be true for owner for both user post and user petition by default. Can you make the change when you get a chance? Not a high priority, but as soon as you are able...

Owners should be notified about votes and comments. Non-owners should be notified about comments only.

**Comment by petervojtek** [comment]
thanks @igaponov , I confirm it works now as expected.
