### ISSUE TITLE
Newsfeed Post's Group Display

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#170]
Some posts are missing the group/location in which the post was published (see Peter9 example compared to Peter1... Peter1 has United States, Peter 9 does not).

**Comment by jterps08** [comment]
![screenshot_2016-08-05-22-57-28 1](https://cloud.githubusercontent.com/assets/7582457/17458982/5fae3312-5bf5-11e6-83e7-e0d22166b4ca.png)

![screenshot_2016-08-05-23-01-54](https://cloud.githubusercontent.com/assets/7582457/17458986/68d0d09e-5bf5-11e6-8dc8-720cca3fae2e.png)

**Comment by petervojtek** [comment]
I cannot reproduce the issue for `Peter9` as I see properly US group name near activity item when logged as `Peter9`.

However, there are User posts where the group name is not displayed due to bug #141.

**Comment by petervojtek** [comment]
@jterps08, the issue here is that activity itself bears only ID of the group, e.g.:

```
{"zone":"expired","id":502,"title":"","description":"trying www.kickstarter.com link","description_html":"","sent_at":"2016-08-05T10:04:55.000Z","expire_at":"2016-08-06T10:04:54.000Z","responses_count":0,"owner":{"id":77,"type":"user","official_title":"","first_name":"Peter21","last_name":"Peter21","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png"},"entity":{"type":"post","id":238,"group_id":309},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-08-05T10:04:55+0000","petition":null,"post":{"is_subscribed":false},"metadata":{"title":"Kickstarter","description":"Kickstarter is the world's largest funding platform for creative projects. A home for film, music, art, theater, games, comics, design, photography, and more.","image":null,"url":"www.kickstarter.com"},"comments_count":0,"answers":[],"quorum":0,"owner_info_1":null}
```

i.e. `,"entity":{"type":"post","id":238,"group_id":309}`

Now I can resolve the group name from group ID via two approaches:
- (A) I already have fetched groups which have my current user as a member -- and so I can easily derive the group name from group ID -- currently I use only this approach, but it works only for newsfeed activity items published in the groups which have the current user as a member.
- (B) however the activity newsfeed displays also items which are from groups which do not have the current user a as member (as explained in #141). If we want to hold on the #141 behaviour, then I can determine the group name from group ID in two ways:
  - make additional http request for almost each activity item to resolve group name -- we don't want this, it will slow down the activity newsfeed
  - ask Igor to add `groupName` to `activity.entity` hash.

@jterps08 , now to resolve this issue you should first tell if #141 is intended behaviour or not. Unfortunately from your comments in #141 I am unable to make a conclusion if behaviour #141 is what you want, or not.
- If you will tell that #141 is not expected behaviour, then (B) should not happen at all and #141 is a backend bug.
- If you will tell that #141 is desired behaviour, the we will ask Igor to add `groupName` to `activity.entity` hash..

**Comment by jterps08** [comment]
@petervojtek - Per our conversation on Slack, I think that 141 is NOT expected behavior. So, (A) is the correct scenario to take to your previous comment.

I got clarification from @igaponov  that "activity_condition.user in user.following" means that "the post's author is being followed by the current authenticated/logged-in user?" 

@igaponov - The newsfeed should show all content in any groups that the logged-in user is a part of and display them in priority order. Whether the logged-in User is following another user should have NO impact on if that content appears in his feed. The feed should show priority zone content first, non-priority zone content second, and expired content third from all groups that the user is joined to. Please remove that condition as we should not see content from followed users who are posting in groups that the logged-in user is not joined to.

Now, if it is easy, as you are making this change, I would prefer that non-priority zone content be sorted as follows: 1) First, non-priority content from followed users in the logged-in user's groups, 2) Second non-priority content from other users in the logged-in user's groups... (if this takes more than 2 hours, ignore this request).

So, the feed would load like so:
1) Priority Zone Content (Chronologically) - Unread Petitions, Unread Discussions, Unanswered Polls/Fundraisers/Events/Boosted-Posts/Boosted-user-Petitions... only from groups that the user is joined to. Priority Zone Content should never be expired. If expired, it is in Expired Zone.
2) Non-Priority Zone Content from Followed Users (Chronologically) - Unboosted and Unexpired Users Posts and Unboosted and Unexpired User Petitions... only from groups that the user is joined to.
3) Non-Priority Zone Content from Non-Followed Users and Answered/Read Leader Content (Chronologically) - Unboosted and Unexpired Users Posts and Unboosted and Unexpired User Petitions... Answered Polls/fundraisers/events/boosted-posts/boosted-user-petitions & Read Leader petitions and Read discussions... only from groups that the user is joined to.
4) Expired Zone Content... only from groups that the user is joined to that has expired.
WHERE _all_ content is only from groups that the user is joined to (town / state / country / save the whales /etc.)

Let me know if this makes sense.

**Comment by igaponov** [comment]
@jterps08 I think I've fixed activities for followers, now condition looks like
- activity_condition.user in user.following
- AND
- activity_condition.district in user.districts
- OR activity_condition is not superuser
- OR activity_condition.group in user.groups
- OR activity_condition.group_section in user.group_sections
- OR user in activity_condition.users
  so user should see only activities from his groups.

User can see activities of followed user only if he add a parameter `following`= user id. So activities in priority zone can be only from user or only from followed user.

**Comment by jterps08** [comment]
This is not correct. Please remove "activity_condition.user in user.following" as a condition. Once again, if User A follows user B, that should have NO IMPACT on the content that appears in User A's feed.

The logged-in user A should see ALL content from every group that he is joined to (town/state/country/Group1/Group2) from both followed and not-followed users...

If User A follows User B and User B creates content in Group 5 that User A is not joined to, then User A should not see User B's content in his feed.

**Comment by jterps08** [comment]
Let me try to add more background and example here. I know it is hard to understand via text...

CONTENT
- Logged-in User A needs to see all content from all of the groups that he is joined to - Bucklin, Kansas, United States of America, Save the Whales, and Save the Trees. 
- If User A follows User B, this has no impact on the content that appears in User A's feed.
- If User A joins group "Save the Birds", this does have impact on the content that appears in User A's feed.
- If User A follows User B and User B creates content in Save the Turtles, this does not have impact on the content in User A's feed. User A cannot see content in Save the Turtles in his feed because User A is not a member of Save the Turtles. 
- If User C is joined to Hoboken, New Jersey, United States of America, and Save the Whales, then User A will see any posts that User C makes in USA or Save the Whales groups even though User A is not following User C. 

SORTING
Above is content in the user's feed. This is how that content is sorted in order from first to last:
1) Priority Zone Content (Chronologically) - Unread Petitions, Unread Discussions, Unanswered Polls/Fundraisers/Events/Boosted-Posts/Boosted-user-Petitions... only from groups that the user is joined to. No Priority Zone Content is expired. If expired, it is in Expired Zone.
2) Non-Priority Zone Content from Followed Users (Chronologically) - Unboosted and Unexpired Users Posts and Unboosted and Unexpired User Petitions... only from groups that the user is joined to.
3) Non-Priority Zone Content from Non-Followed Users and Answered/Read Leader Content (Chronologically) - Unboosted and Unexpired Users Posts and Unboosted and Unexpired User Petitions... Answered Polls/fundraisers/events/boosted-posts/boosted-user-petitions & Read Leader petitions and Read discussions... only from groups that the user is joined to.
4) Expired Zone Content... only from groups that the user is joined to that has expired.
WHERE all content is only from groups that the user is joined to (town / state / country / save the whales /etc.)

EXAMPLE SORTING ORDER (User A from above)
_Priority Zone (Unread/Unanswered Leader Content + Boosted Content, Chronologically, From Joined Groups)_
Unanswered Poll from Save the Whales group leader 3PM Today
Unanswered Boosted Post in USA group 2:30PM Today
Unread Leader Petition in Save the Whales group leader 1:30PM Today
_Non-Priority Zone, Followed Users First (User Posts / User Petitions from Followed Users in Joined Groups, Chronologically)_
Unexpired Post from Followed-User-C (User C is author) 3PM Today
Unexpired Petition from Followed-User-B (User B is author) 2:30 PM Today
Unexpired Post from Followed-User-C (User C is author) 1:24PM Today
_Non-PriorityZone, (Non-Followed Users & Answered/Read Leader Content in Joined Groups, Chronologically)_
Answered Poll from Save the Whales group leader 2:46 PM Today
Unexpired Post from NonFollowed-User-G (User G is author) in Save the Whales 2:45 PM Today
Answered Petition from Save the Whales group leader 2:30PM Today
Answered Boosted Post in Save the Whales 1:26PM Today
Unexpired Petition from NonFollowed-User-H (User H is author) in USA group 1:25 PM Today
_Expired Zone_ (All Other Content)
Expired Post from User H in Hoboken group Last week
Expired Post from User B in Save the Whales Last month
Expired Poll from Save the Whales Last year

-- So, two things:
1 - Feed _content_ does not depend on following any users. Feed content depends on groups joined (including town/state/country)
2 - Feed _sorting_ **does** depend on following other users. This is new. Non-priority zone has two pieces: first followers users. second all other non-priority zone content.

I know this may be hard to communicate over GH about, so let's Slack or Skype if needed. The most important thing for you to know is that Following Relationships should have no impact on CONTENT in newsfeed. They could have impact on sorting.

**Comment by igaponov** [comment]
@jterps08 there is no impact on content, user just can filter his feed by followed user, but it's optionally. 
I've sorted feed with new rules.

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/260 was deployed

**Comment by petervojtek** [comment]
ok, now [this behaviour](https://github.com/PowerlineApp/powerline-mobile/issues/141#issue-164247078) is not happening, i.e. user seems to be shown only activity items from groups the user is member of, and thus we can always determine group name.
