### ISSUE TITLE
Upvote/Downvote a Post Newsfeed Shortcuts

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#171]
All unexpired posts should have upvote/downvote shortcut buttons in the quick action bar in the newsfeed. Currently only displaying "reply" button.  Authors should not see upvote/downvote buttons on their own posts.

**Comment by jterps08** [comment]
![screenshot_2016-08-05-23-01-54](https://cloud.githubusercontent.com/assets/7582457/17458976/3a56b134-5bf5-11e6-8858-83fc8676fee8.png)

**Comment by petervojtek** [comment]
fixed the bug, but another two bugs were revealed: #179, #180
