### ISSUE TITLE
Newsfeed Item Icons

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#172]
The newsfeed icons for post/poll/fundraiser/etc. are being cut off. 

Posts should show a flag
Petitions should show a pencil
Fundraisers should show fundraiser symbol
Events should show calendar symbol
Polls should show bar graph symbol
Discussions should show chat bubble symbol. 

Please discuss with me to confirm icons first.

**Comment by jterps08** [comment]
![screenshot_2016-08-05-22-57-28](https://cloud.githubusercontent.com/assets/7582457/17458973/2dba2cee-5bf5-11e6-81a6-0b6b587f0051.png)

**Comment by petervojtek** [comment]
@jterps08 , I am able to test this only for non-leader content, i.e. micro-petition:long-petition and micro-petition:quorum.

here are icons which I can reuse from post and petition:

<img width="342" alt="screen shot 2016-08-17 at 13 38 44" src="https://cloud.githubusercontent.com/assets/225506/17734982/006f1bf8-6480-11e6-8437-b008fdc02848.png">

From UX point of view I find the pen icon confusing -- it looks almost the same as "Edit" icon.

**Comment by jterps08** [comment]
Good point, no pun intended.... Petition looks good. Maybe a flag icon makes more sense for the post. 

Something like: 

http://image.flaticon.com/icons/png/512/9/9790.png

**Comment by jterps08** [comment]
Icons are located here: https://drive.google.com/open?id=0B2Loy21ehREydURoZVZ0SXJ4Skk

**Comment by petervojtek** [comment]
@jterps08 , I am not sure -- which of the currently used icons in app is not user properly in regard to the data type? 
here are the icons used currently for newsfeed items:
https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/images/v2/icons/post-icons.png

**Comment by jterps08** [comment]
I think we want posts to show a 'flag' and petitions to show the 'pencil'... I thought the flag was contained in the icon attachment I provided but I can't open PSD on my current computer...

**Comment by petervojtek** [comment]
@jterps08   my problem is don't own photoshop products so that I am unable to gather the flag icon from the PSD :(

**Comment by jterps08** [comment]
haha okay we both have same problem... 

I think that post/flag icon should look something like this: 
![image](https://cloud.githubusercontent.com/assets/7582457/19036659/1edf7fea-893f-11e6-9e43-11c2f51c6124.png)

**Comment by jterps08** [comment]
But I am open to your thoughts...

**Comment by petervojtek** [comment]
ok, I adjusted it.
Post has a flag icon.
Petition and user Petition has pencil icon.
