### ISSUE TITLE
Empty Favorites Screen Placeholder Text

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#173]
Empty Favorites Placeholder Text - "Got a good discussion going? Great! Don't forget it - save it in your favorites by clicking on the Star icon in the newsfeed!"

**Comment by jterps08** [comment]
![screenshot_2016-08-05-22-58-05](https://cloud.githubusercontent.com/assets/7582457/17458970/1ed95ec0-5bf5-11e6-8f73-fc26e5f1f775.png)

**Comment by petervojtek** [comment]
done
