### ISSUE TITLE
My Reps Avatars Not Displaying / FrontEndBundle Issue

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#174]
The My Representatives screen is not displaying Cicero or Sunlight Foundation API-provided avatars correctly. We need the FrontEndBundle restored so that I have superuser controls (which can refresh these images, and make other changes) including testing local representative registration.

**Comment by jterps08** [comment]
![screenshot_2016-08-05-22-59-10](https://cloud.githubusercontent.com/assets/7582457/17458966/11783a44-5bf5-11e6-9ceb-211430b6db2e.png)

**Comment by austinpapp** [comment]
it wasn't removed. it should still be present. did you try to log in?

**Comment by jterps08** [comment]
I have not. Thought I read somewhere else that it had been removed.
Admin-dev.powerli.ne I will try

**Comment by jterps08** [comment]
I can't reach admin-dev.powerli.ne -- if there's another way to access this, please let me know.

**Comment by jterps08** [comment]
???

**Comment by austinpapp** [comment]
see https://github.com/PowerlineApp/powerline-server/issues/281

**Comment by jterps08** [comment]
Can we restore the CSS to the FrontEnd bundle? It seems to gone missing.

**Comment by igaponov** [comment]
@jterps08 fixed
