### ISSUE TITLE
NG-Letter Implementation 2

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#175]
When creating a new post for Build Test Two, the placeholder icon was displayed instead of the ng-letter in what I assume was a group with no avatar. On the New post/petition screen.

**Comment by jterps08** [comment]
![screenshot_2016-08-05-23-01-04](https://cloud.githubusercontent.com/assets/7582457/17458963/03adec2e-5bf5-11e6-8041-da03f2f8c464.png)

**Comment by jterps08** [comment]
This may be better implemented via backend?

**Comment by petervojtek** [comment]
currently it will be faster to fix it on frontend.

**Comment by jterps08** [comment]
ok thanks
