### ISSUE TITLE
Sign button is displayed in user-petition:long-petition for creator in activity newsfeed

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#184]
creator should be probably not allowed to sign his own petition.

this issue is present only in activity newsfeed, in petition detail the sign button is not available for owneer.

**Comment by jterps08** [comment]
Correct. Author should not be able to sign his own petition.

**Comment by austinpapp** [comment]
2 things.
1. we should prevent from frontend any user signing own petition
2. backend should not allow it (if it doesn't already)

**Comment by petervojtek** [comment]
fixed on frontend.
backend is preventing owner from signing user petition:

```
Request URL:https://api-dev.powerli.ne/api/v2/user-petitions/244/sign
Request Method:POST
Status Code:403 Forbidden
```
