### ISSUE TITLE
activity newsfeed is empty

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#186]
since yesterday we face this issue for all users:

```
Request URL:https://api-dev.powerli.ne/api/v2/activities?page=1
Request Method:GET
Status Code:200 OK

{"page":1,"items":20,"payload":[],"totalItems":0}
```

it is blocking lot of other issues.

**Comment by igaponov** [comment]
@petervojtek I've updated dev db, should work without deploy

**Comment by petervojtek** [comment]
thanks @igaponov , I confirm now the activity items are served.
