### ISSUE TITLE
add bookmark API call no longer working for user petition and post

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#188]
this endpoint does not seem to work any longer for `user-petition` and `post` content types introduced in #187:

```
Request URL:https://api-dev.powerli.ne/api/bookmarks/add/micro-petition/518
Request Method:POST
Status Code:404 Not Found
```

however the `type` option [mentions](https://api-dev.powerli.ne/api-doc#post--api-bookmarks-add-{type}-{itemId}) only following types:

```
petition|micro-petition|question|leader-news|payment-request|crowdfunding-payment-request|leader-event
```

there is no `post`, nor `user-petition`.

which endpoint should I use to create bookmarks for `user-petition`, and `post` ?

**Comment by jterps08** [comment]
@igaponov  - can you update this to replace micropetition with user-petition and post now that we've refactored micropetitions... I think this was originally @habibillah's work...

**Comment by petervojtek** [comment]
done

**Comment by jterps08** [comment]
:laughing:
