### ISSUE TITLE
Unable to add comment to Post and User petition

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#190]
due to changes in #187.

**Comment by jterps08** [comment]
For clarity - this is related to the micropetition refactoring work...  https://github.com/PowerlineApp/powerline-mobile/issues/187

**Comment by jterps08** [comment]
What's the status with this?

**Comment by petervojtek** [comment]
@igaponov , I have following problem with adding comment to Post:

How can I find out the `parent_comment` ID I am supposed to submit when creating new comment under a Post which has 0 comments yet ?

When I submit it without `parent_comment` ID, I face this error:

```
Request URL:https://api-dev.powerli.ne/api/micro-petitions/253/comments/
Request Method:POST
Status Code:500 Internal Server Error

{"comment_body":"test comment 1","privacy":0}

{"code":500,"message":"The identifier id is missing for a query of Civix\\CoreBundle\\Entity\\UserPetition\\Comment","errors":null}
```

before backed changes were made (#187), adding comments was working and somehow the parent_comment ID was propagating there, but I don't know how the mechanism works because I have not inspected it at all (as it was working), and now when it is broken I cannot determine how it is supposed to work. There does not seem to be api doc for the `api/micro-petitions/253/comments/` endpoint.

**Comment by petervojtek** [comment]
ok, I will use v2 endpoints for Post and UserPetition comments.

**Comment by petervojtek** [comment]
@igaponov , when I delete Post comment via v2 api, it's `comment_body` is properly set to `Deleted by author`, however `comment_body_html` keeps the old value, example:

```
{"page":1,"items":20,"payload":[{"rate_value":"","is_owner":true,"author_picture":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg","user":{"full_name":"Peter10 Peter10","id":73,"type":"user","username":"Peter10","first_name":"Peter10","last_name":"Peter10","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg"},"privacy":"public","id":527,"comment_body":"Try Post comments, 44","comment_body_html":"Try Post comments, 44","created_at":"Wed, 07 Sep 2016 07:33:47 +0000","parent_comment":0,"rate_sum":0,"rates_count":0},{"rate_value":"","is_owner":true,"author_picture":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg","user":{"full_name":"Peter10 Peter10","id":73,"type":"user","username":"Peter10","first_name":"Peter10","last_name":"Peter10","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg"},"privacy":"public","id":528,"comment_body":"Deleted by author","comment_body_html":"comment NO 1","created_at":"Wed, 07 Sep 2016 07:36:16 +0000","parent_comment":527,"rate_sum":0,"rates_count":0}],"totalItems":2}
```

the same for update.
the same for UserPetition update and delete.

**Comment by igaponov** [comment]
@petervojtek fix won't touch previously deleted comments

**Comment by petervojtek** [comment]
@igaponov , I confirm it works for delete comment, but update comment seem to be still affected by the issue -- maybe you overlooked it, because I added the text only later to the comment:

> the same for update. the same for UserPetition update and delete.

**Comment by igaponov** [comment]
deployed

**Comment by petervojtek** [comment]
thanks, now update comment text works as expected
