### ISSUE TITLE
Post and User Petition results not displayed in detail

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#191]
the original code to display `post` and `user-petition` voting results was build around `options` attribute, but that one is no longer provided by v2 api due to #187 . probably I should use `answers` and `signatures` attributes for the purpose..

**Comment by petervojtek** [comment]
@jterps08 , can I ask you to provide me screenshot of how Post detail screen is supposed to look like when the post is expired (i.e. voting is over). 

I know how the User petition detail results should look like.

**Comment by jterps08** [comment]
If expired, it simply shows the upvote/downvote results screen (see below). Ignore red outline box on this screen (first screenshot I could find in my files)... Users can continue to comment on expired post. Users cannot upvote/downvote expired posts. Expired posts cannot get boosted. 

User petition shows the unsign button forever. 

![author notification muting](https://cloud.githubusercontent.com/assets/7582457/18009968/8da4f4ea-6b7c-11e6-98c6-410a9be925a8.png)

**Comment by petervojtek** [comment]
@igaponov , I am not sure what is your intention with post/user-petition voting results:
-  currently the api provide `answers` and `signatures` respectively which I guess provides me enough information to determine the voting results (please correct me if I am wrong)
- however you mentioned via slack that maybe you plan to resurrect summary results (via something like was the`options` attribute in the past). 

I am not sure if I should wait for the second possibility while you implement it, or proceed with the first one.

**Comment by petervojtek** [comment]
ok, I discussed with Igor that I will try to use "signatures" for user-petition and "votes" for post to render results. `answers` is deprecated.

**Comment by petervojtek** [comment]
for posts I am blocked by #189.

**Comment by petervojtek** [comment]
@jterps08 , given that it is now mobile app which should calculate result percents, I would like to ask on user-petition result:

Do I properly guess that`user-petition` results is supposed to display in percents number of users who signed the `user-petition` divided by the total number of users in the group the petition belongs to?

E.g., when group San Diego has 8 members, and user-petition was signed by 2 users, it should display "25%" ?
And actually, should be the petition creator user be taken into the formula? I.e., group has 8 members, but one of them is the creator of the petition who is not allowed to sign the petition -- so that even if all other seven members do sign, the result will never reach 100%, but in this case 87.5 %.

**Comment by jterps08** [comment]
@petervojtek good question. Let's do this:
- user-post results should be percent of respondents who answered A, vs B, vs C, etc. 10 people chose A out of 25 total respondents = 40% for A... 
- user-petition results can just be a simple count. No need to do percentage. But petition creator should count as a signature.

**Comment by petervojtek** [comment]
let's not forget the poll:petition results as well.

**Comment by jterps08** [comment]
leader-petition (poll:petition) results would be displayed the same way as user-petition results.

**Comment by petervojtek** [comment]
@jterps08  the user-petition detail looks now as following when petition is expired:

<img width="802" alt="screen shot 2016-08-31 at 06 52 07" src="https://cloud.githubusercontent.com/assets/225506/18116377/97f1c6b6-6f47-11e6-95ce-af77ab7a2220.png">

The top left corner contains `Responses: 2`, which is the numbed of people who signed the petition. The current results section shows `Votes for this petition: 3` - it is simple the responses count + 1, due to 

> But petition creator should count as a signature.

Please confirm that this is the way you want the user-petition detail to look like, so that I can adjust the poll:petition detail the same way.

**Comment by jterps08** [comment]
Confirmed!

**Comment by petervojtek** [comment]
ok, done for petitions and user-petitions. for post results I am still blocked by #189

**Comment by petervojtek** [comment]
ok, done.
