### ISSUE TITLE
Information about user (creator) is missing in poll activity newsfeed data

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#194]
@jterps08 , I have a (event) poll created by `Peter10` into group `San Diego` which currently renders as following in activity newsfeed:

<img width="797" alt="screen shot 2016-08-29 at 08 24 02" src="https://cloud.githubusercontent.com/assets/225506/18042533/370c018a-6dc2-11e6-8a0a-fdb262c70d06.png">

I would like to ask if following is ok:
- as a poll owner is displayed group (San Diego) and not the person which created it (Peter10).
- if the above is ok, then the "person+" icon should not be displayed I guess.
- should be Peter10 allowed to answer the poll?

**Comment by jterps08** [comment]
Really good question. This is a new scenario as a result of the single sign-on / Angel work... 

Short Answer:
- Poll Author should be displayed (with group) -- Peter10First Peter10 Last | San Diego
- Person+ Icon should remain. 
- Peter10 should not be allowed to answer a poll he created...

Other comments/thoughts:
- Event items should show the event-calendar icon (not the bar graph icon), and the "Answer" button should show "RSVP" instead (will be solved in #197)
- It is unclear to me what your other priority-zone items are. Only unread petitions/discussions and unanswered polls/leader-petitions/fundraisers/events/boosted-posts/boosted-petitions should be in the priority zone.
- Only group creators and group managers should be able to create leader content (polls/leader-petitions/discussions/fundraisers/events/announcements) and manage their groups. It is unclear to me why Peter10 could create an event in this group if he was not group creator or group manager. 
- San Diego is a public community group. Peter10 should not be the group creator. System is group creator for San Diego. 
- If issue #244 in server repo was finished, then Peter10 could be assigned 'representative rights' (by System with manual superuser approval) for San Diego as a Mayor or City Council Member, for example, per https://github.com/PowerlineApp/powerline-server/issues/244... but that doesn't seem to be the case here.
- If Peter10 is only group member of San Diego (not creator/manager/representative rights), then he should be able to create posts and user-petitions... but not events.

**Comment by petervojtek** [comment]
@igaponov , I am not sure what are the particular right assigned to user `Peter10` (ID=73) in group `San Diego` (ID=285), but I use him as a special user to create leader content from JS console. 

I successfully created a poll as Peter10 and this is ho the poll looks like via `GET v2/activities`:

```
{"zone":"prioritized","id":523,"title":"","description":"test Poll no2 subject","description_html":"test Poll no2 subject","sent_at":"2016-08-29T05:39:22.000Z","expire_at":null,"responses_count":0,"owner":{"id":285,"type":"group","group_type":3,"official_title":"San Diego","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png"},"entity":{"type":"question","id":196},"picture":null,"read":true,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-08-29T05:39:23+0000","petition":null,"post":null}
```

Jesse wrote above, that "Poll Author should be displayed (with group) ". However for the poll above, I am unable to determine the author name, because `owner` attribute bears only group information (San Diego), and there is no information that `Peter10` is the person which was in charge of creating the poll. 

So if the requirement by Jesse ("Poll Author should be displayed (with group)") is compatible with the privileges assigned to Peter10 in group San Diego, I miss the person owner info in the activity item data.

**Comment by igaponov** [comment]
@petervojtek @jterps08 we don't persist the user who creates a poll, we only persist a group and the attribute name is "owner". Should I add a user? We will not be able to get users for old polls.

**Comment by jterps08** [comment]
yeah, I think we should @igaponov. We don't have to worry about backwards compatibility with this. We want the item to appear in the newsfeed from the specific user who created it (e.g. Peter Smith) in whatever group they're in (e.g. Save the Whales)... 

Related terminology note:
"Group leaders" = group owners and group managers. At this time, only group leaders can create leader content (polls/leader-petitions/discussions/fundraisers/events/announcements) or manage group settings. 
"Group owner" = user who creates the group.
"Group managers" = users who are assigned group manager rights by the group owner. Same rights as group owner except 1) unable to change group subscription (Silver/Gold/etc) or 2) assign group manager rights to other users.

**Comment by jterps08** [comment]
Can we proceed @petervojtek or do we need @austinpapp intervention?

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/272 was deployed

**Comment by petervojtek** [comment]
ok, it works.

it works only for new leader content items.
