### ISSUE TITLE
Make sure leader petitions are rendered properly

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#195]
this issue originated from #130.
https://github.com/PowerlineApp/powerline-mobile/issues/130#issuecomment-243109178

leader petitions (poll of subtype petition): 

> They look the same as a user-petition.

**Comment by petervojtek** [comment]
ok, it is working. few remarks:
- unsign button in activity newsfeed works instantly (the same way as in user-petition activity)
- sign button redirects to petition detail (where is the real Sign button),  because when the petition is not signed, the activity data itself do not bear the option_id required to perform the sign action.
- creator (user name) is not displayed due to #194 
- results will be rendered the samy way as in #191, i.e. "results can just be a simple count. No need to do percentage. But petition creator should count as a signature."

**Comment by jterps08** [comment]
Sign button should sign the petition directly from within the newsfeed. The option ID required to sign should be 1. We need to confirm with @igaponov and this way he can provide that info to you or we can update activity data as needed to support this along with creator name.

**Comment by igaponov** [comment]
@petervojtek `option_id` could have the next values: upvote, downvote, ignore. Now you don't need it for petition, because you can only sign a petition (previously - upvote) and can't downvote (only completely delete your signature).

**Comment by petervojtek** [comment]
actually, we can do it also other way:

when user clicks Sign, I can fetch petition detail, which will provide me the option_id, and then call the sign petition api call -- with this approach there is no need for Igor to change anything.

**Comment by petervojtek** [comment]
ok, thanks for info Igor, I use the `upvote` for the purpose.

**Comment by igaponov** [comment]
@petervojtek look at the endpoint's [doc](https://api-dev.powerli.ne/api-doc#post--api-v2-micro-petitions-{id}-sign), you don't need to provide any `option_id`

**Comment by petervojtek** [comment]
ok, resolved by following approach. it is not possible to determine option_id directly from activity item data, and the suggestions above are working for micro-petitions, but not for poll:petition.
we agreed with Igor that I use following approach:

when user clicks Sign button, I fetch the poll:petition data, thus find out the proper option_id, and then submit the sign action.  the means I make there one more http request, but it is fired only when user clicks the Sign button.
