### ISSUE TITLE
Cannot add comments to poll due to HttpRequest cannot load https://api-dev.powerli.ne/api/poll/196/comments/

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#198]
@igaponov ,  adding new comment ends up with:

```
Request URL:https://api-dev.powerli.ne/api/poll/196/comments/
Request Method:POST
Status Code:500 Internal Server Error

XMLHttpRequest cannot load https://api-dev.powerli.ne/api/poll/196/comments/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8101' is therefore not allowed access. The response had HTTP status code 500.
```

but actually the comment itself is added properly, but the server response (or preflight response) lacks the Access-Control-Allow-Origin' header.

update and delete comment work properly.

**Comment by igaponov** [comment]
@petervojtek I think data is corrupted on dev, there is no user for parent comment that you used to add a new one. After deploy you can start to use new version of API or I can try to fix data in dev db.

**Comment by jterps08** [comment]
Does this need to be re-tested?

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/267 was deployed

**Comment by petervojtek** [comment]
this problem is fixed, but another one emerged which prevents me from adding comments to poll: #206

**Comment by petervojtek** [comment]
sorry, I created a duplicate bug #206 -- i.e. this problem is still present.
