### ISSUE TITLE
new UserPetition/Post: show only groups for which user has not exceeded number of posts per month

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#204]

**Comment by petervojtek** [comment]
@jterps08 , currently when creating new user-petition/post, all groups of which the user is member of are displayed.

the old business logic in mobile app worked as following (explained for Post, but it is the same for UserPetition): 
1. user clicked Create New Post
2. GET request was made to [download all Posts](https://api-dev.powerli.ne/api-doc#get--api-micro-petitions) the user created since the start of the month
3. For each of the Posts it was resolved to which group it belongs and then for each group counter was incremented. When the counter overreached `group.petition_per_month` (=5) attribute, the group was removed from list of the groups available in Create new post form.

Now, I can resurrect this behaviour, but I think it is not very smart approach, because:
- such business logic should be located on backend and not on frontend
- anytime user is about to enter Create new post form a HTTP get request is made to fetch list of Posts with all their details just to determine to which group each Post belongs to

From my point of view, ideally the following changes should be made on backend:
- it should no longer provide `group.petition_per_month` atrribute.
- instead, it should provide attribute like `group.remaining_posts_for_this_month`. In mobile app, I will simple check that if `group.remaining_posts_for_this_month > 0`, I can list that group in Create new post.

And similarly for user-petition.
The overall point is, that the more business logic is on backend, the easier is to maintain mobile app along with web app (or merge them).

**Comment by jterps08** [comment]
Agreed.

I would still want all potential groups shown otherwise it might cause confusion to the user. If the user has no more posts available for this month, then we can let them know "You have reached your limit of posts to this group for the month." This way they don't think there's a bug...

**Comment by petervojtek** [comment]
@jterps08 , the feature "You have reached your limit of posts to this group for the month." is independent from what I have described above and works as following:
only when you write post/petition text and submit it, you will receive a warning that "You have reached your limit of posts to this group for the month" -- because that warning is issued by backend in response to the create-new-post/petition http request.

From UX point of view I find that frustrating for an user -- she will learn that she cannot create new post/petition only after she spent time composing the post/petition text.

Now what would make sense to me is following:
- create new post/user-petition form will display all groups the user is member of, but groups where limit is reached will be distinguished in e.g., grey color. when user tries to pick such a "grey" group, a info message will appear "You have reached your limit of posts to this group for the month" 

and given your remark "I would still want all potential groups shown otherwise it might cause confusion to the user. " -- I face very similar confusion when I visit My groups screen and the non-user groups (e.g. USA) are not displayed there.

**Comment by jterps08** [comment]
Good thoughts, Peter. Thank you... 

To reply:
1. I agree with your suggestion re: info message and greyed-out options for new post/petition creation. 
2. Perhaps we could add the town, state/province, and country groups to "My Groups" screen. I just don't know what we would display when the user clicked/tapped on the group. Perhaps we could show Newsfeed with that group's filter pre-selected. E.g. In My Group screen, you click on "New Jersey" item and it shows Newsfeed with filter on NJ?

in any case, definitely P3 for now.
