### ISSUE TITLE
Upvote/downvote (rate) comments does not seem to work at all

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#207]
@jterps08 , not sure what is the priority of this bug

upvote(rate) fails on backend with:

```
Request URL:https://api-dev.powerli.ne/api/poll/comments/rate/139/up
Request Method:POST
Status Code:500 Internal Server Error

{"code":500,"message":"Controller \"Civix\\ApiBundle\\Controller\\PollController::rateCommentAction()\" requires that you provide a value for the \"$comment\" argument (because there is no default value or because there is a non optional argument after this one).","errors":null}
```

**Comment by jterps08** [comment]
Upvoting or downvoting a comment on any item is a required function of the app. Let's have Igor investigate first.

**Comment by petervojtek** [comment]
@igaponov , it seems rate comment returns some other comment in response:

I have this comment:

```
{"rate_value":"","is_owner":false,"author_picture":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg","user":{"full_name":"Peter10 Peter10","id":73,"type":"user","username":"Peter10","first_name":"Peter10","last_name":"Peter10","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg"},"privacy":"public","id":146,"comment_body":"comment A, update 1","comment_body_html":"comment A","created_at":"Thu, 08 Sep 2016 04:02:43 +0000","parent_comment":145,"rate_sum":0,"rates_count":0}
```

and this is how the response to upvote (rate) looks like:

```
Request URL:https://api-dev.powerli.ne/api/poll/comments/rate/146/up
Request Method:POST
Status Code:200 OK

{"author_picture":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png","user":{"full_name":"Nikita Anikeev","id":26,"type":"user","username":"nanikeev1","first_name":"Nikita","last_name":"Anikeev","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"id":146,"comment_body":"@$(56,&","comment_body_html":"@$(56,&","created_at":"Thu, 08 Sep 2016 04:12:42 +0000","parent_comment":213,"rate_sum":"1","rates_count":1,"rate_status":1,"privacy":0}
```

this is problably the reason why `"rate_sum":0,"rates_count":0` remain zero after rate up.

**Comment by igaponov** [comment]
@petervojtek you are trying to rate user petition's comment with endpoint that is used to rate poll comments.

**Comment by jterps08** [comment]
FYI: When I upvote a comment, it seems to work with Tuesday build Peter provided me but the comment is replaced at least in the mobile app. When I downvote a comment, it decreases the 'score' by 0.5 points instead of 1 full point. See screenshot below:

![screenshot_2016-09-08-08-26-48](https://cloud.githubusercontent.com/assets/7582457/18352553/dd1e5f68-75ac-11e6-99c8-ec171ffe83b0.png)
![screenshot_2016-09-08-08-26-52](https://cloud.githubusercontent.com/assets/7582457/18352552/dd0fb5ee-75ac-11e6-8434-adc641a99d8d.png)

**Comment by petervojtek** [comment]
i will have to change the endpoint as Igor suggested.
regarding the points -- they are computed in mobile app js, it is the legacy code, I will look at that as well

**Comment by petervojtek** [comment]
ok, so for leader content it seems to work properly (upvote/downvote, points).
for user-petition and post I am blocked by currently non-working API doc as I need to use another endpoint when rating them

**Comment by petervojtek** [comment]
ok, fixed.
