### ISSUE TITLE
Poll:Event detail design tweaks

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#208]
@jterps08 , who is supposed to be displayed in poll:event avatar - the person (=creator) or the group (=owner)? In the past it was the group, but now we have the option to display the person instead, if we want to..

More tab is empty -- when I inspected the source code, it seems it is supposed to display "education content", however when there is no such content for the poll:event, maybe there should be at least some message "no content".

<img width="844" alt="screen shot 2016-09-08 at 06 37 49" src="https://cloud.githubusercontent.com/assets/225506/18337211/d190d7e8-758e-11e6-936a-b4eac6802288.png">

**Comment by jterps08** [comment]
Good question, Peter... 

1) For More Tab, add "No attachments" when empty.
2) When group leader (owner/manager) creates leader content in a group (poll/leader-petition/discussion-news/event/fundraiser/announcement), the avatar should display the group's avatar. When the group leader creates user content (user-petition, user-post), the avatar should display the user's avatar. 

What do you think?

**Comment by petervojtek** [comment]
@jterps08 , this issue was specifically aimed at poll:event which is leader-content, so in this case it will display group.  

I will also check that the avatar's are displayed properly (user vs group) for other types..

**Comment by petervojtek** [comment]
ok, fixed.
