### ISSUE TITLE
Not Working: Sign/Unsign & Upvote/Downvote from Newsfeed 

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#209]
I cannot sign a petition or upvote/downvote a post from the newsfeed... However, I can sign a petition or upvote/downvote a post from the Item Detail screen... Once tapped, the button just shows the loading screen and eventually times out. 

I should be able to sign any leader/user petition or upvote/downvote a user post directly from the newsfeed. If the item is in the priority zone, the action of signing or voting should immediately put it into non-priority zone (remove red dot, counter, update sorting, etc.). 

Screenshots:
(Signing a Petition... Waiting...)
![screenshot_2016-09-07-22-49-10](https://cloud.githubusercontent.com/assets/7582457/18354066/4cbddb00-75b2-11e6-9101-4858ab8d880e.png)

(Upvote a post... Waiting...)
![screenshot_2016-09-07-22-49-21](https://cloud.githubusercontent.com/assets/7582457/18354067/4cc07f68-75b2-11e6-8573-f0f9f3b72c1c.png)

**Comment by petervojtek** [comment]
this issue was fixed after tuesday (that is the APK you used for testing), please retest with latest APK.
I tried it now and it works properly.
