### ISSUE TITLE
Expired Items should not show Upvote/Downvote buttons in Newsfeed

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#214]
Upvote/Downvote buttons should not appear in the newsfeed on a post that is expired.

First I tried upvoting/downvoting from newsfeed
![screenshot_2016-09-08-08-52-02](https://cloud.githubusercontent.com/assets/7582457/18354838/15de6d7c-75b5-11e6-83ae-161eef7b3a87.png)

Then I realized that the item was expired on 8/30.
![screenshot_2016-09-08-08-52-06](https://cloud.githubusercontent.com/assets/7582457/18354839/1600743a-75b5-11e6-83a2-4f3a56f3f0ca.png)

**Comment by petervojtek** [comment]
@jterps08 , this bug was fixed 2 days ago in #199, but your APK was release day before the fix.
Please retest with latest APK.
