### ISSUE TITLE
Back button from Post Detail Screen not working

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#216]
I'm not sure if this was my device or what, but please investigate. The back button on the Item Detail screen does not seem to work. I had to use the Android back button. If unable to reproduce, close and I will test again in next build.

**Comment by petervojtek** [comment]
cannot reproduce, please try again with latest APK if you can reproduce it -- and if yes, please provide info which particular Post it was..

**Comment by jterps08** [comment]
unable to reproduce
