### ISSUE TITLE
Item Detail Screen Not Updated after Edit

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#217]
The Item Detail screen is not refreshed after an edit has been saved. Edit button should also not appear if the post has been boosted.

**Comment by petervojtek** [comment]
> The Item Detail screen is not refreshed after an edit has been saved.

@jterps08 , which item?  I tried it with User-petition and also with Post and I cannot reproduce the bug.

regarding this:

> Edit button should also not appear if the post has been boosted.

Also delete button should be not available when post has been boosted?

**Comment by jterps08** [comment]
It was the only post that I made yesterday. with #hashtag and @austin mention... I will try again on next build. It may have been the build I had. 

I think we can leave the delete button in place. We just don't want a bunch of people to upvote "version 1" of a post and then, once it's boosted, the author can change it to "I love humpback whales" later. So let's keep Delete in there for now and remove Edit when something is boosted. Thanks.

**Comment by petervojtek** [comment]
ok, this is done: 

> remove Edit when something is boosted
