### ISSUE TITLE
Consistent "Pending Approval" Icons for Followed Users

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#218]
On My Influences and Group Membership List screens, the users that are 'pending approval' do not show the icon with the clock. The icon with the clock should be shown for pending approval.

![screenshot_2016-09-08-08-55-58](https://cloud.githubusercontent.com/assets/7582457/18355038/e6282676-75b5-11e6-8954-7ff11ce71fa1.png)
![screenshot_2016-09-08-08-35-37](https://cloud.githubusercontent.com/assets/7582457/18355037/e6250482-75b5-11e6-90f3-7dfd8ba3eee3.png)

**Comment by petervojtek** [comment]
ok, fixed.
