### ISSUE TITLE
Search for Friends Function Not Working

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#219]
After tapping "Search Address Book Now" button, an alert should appear with text "Let's see if you have any friends who are already on Powerline. No contact data is being sent to Powerline during this process." (OK / Cancel)... And then results should be shown. 

Currently, results are not shown, but I'm not sure if its because the process isn't working or if it's taking a long time. 

Perhaps we update with some sort of pagination method (i.e. Search displays first 10, Search for More? displays next 10, and so on?) to speed it up? I don't think we want to do the entire Address Book at once.

![screenshot_2016-09-07-22-50-49](https://cloud.githubusercontent.com/assets/7582457/18355246/8a10c32e-75b6-11e6-898a-8c63882c3e15.png)

**Comment by petervojtek** [comment]
I'll check that first and assign to Igor with details if it will be related to backend..

**Comment by petervojtek** [comment]
it was broken due to changes made on frontend in #122. 
fixed and should be working.
