### ISSUE TITLE
Post Embedded Link MetaData Inclusion

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#22]
Ability to retrieve and display the metadata around any embedded link on a user's post in the newsfeed

**Comment by petervojtek** [comment]
@jterps08, please provide more details on what does it means "to display metadata around link".

when user post description contains url, current behaviour is following:
-  in newsfeed activity: the url is displayed as and clicking it triggers no action
-  in post detail: only part of url with http:// is displayed, and clicking it opens web browser with the url.

Currently in newsfeed

**Comment by jterps08** [comment]
@petervojtek a few points on this

Correct URL Behavior:
In newsfeed activity: the URL itself triggers no action. I was told in the past that this was too difficult to differentiate the "tap zone" for opening post detail vs the tap zone for opening the link itself.
In post detail: abbreviated URL is displayed and clicking it opens web browser.

That said, metadata link inclusion is when the newsfeed loads the metadata associated with the URL inside the post (image, title, description). It is similar to how Facebook gives you a preview of a website when you copy/paste a link into a new Facebook post. Here's how it looked previously:

Original Mockup:
![image](https://cloud.githubusercontent.com/assets/7582457/16806745/c7b01040-48e3-11e6-80b3-4a615e852df3.png)

Actual App Screen (Title/Description only - missing image) -- only putting this here to show that code was written at some point to address this. i think the backend hadn't fully been developed yet to provide image when this screenshot was made.
![image](https://cloud.githubusercontent.com/assets/7582457/16806984/c9676be4-48e4-11e6-9a4d-693411525548.png)

**Comment by petervojtek** [comment]
I spend some time searching for the code which should be able to deliver the link preview functionality, but it does not seems to be present in the current mobile app repo. I only discovered some ability to handle [youtube links](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/utils.js#L3).

Maybe the code was not moved from the old app.
@jterps08 , can you tell me which repo in bitbucket is the old mobile app you used to made screenshots with link previews? https://bitbucket.org/powerlineapp/

**Comment by austinpapp** [comment]
@petervojtek the cordova one should be it.

**Comment by petervojtek** [comment]
@jterps08 , the old mobile app app also does not seem to include business logic to parse&transform urls to previews. My guess is this was performed on backend and then `activity.description` served from server was rich html (rendering such html is already supported by the mobile app):

dummy example how html enhanced `activity.description`:

```
hello, this is meta test. www.google.com. 
<div>
<h3 style="color: blue">Google</h3>
<p>google is the best search engine</p>
<img src='google.logo.png'></img>
</div>
```

If my assuption is correct, then this is a backend issue.

**Comment by jterps08** [comment]
@petervojtek - The image preview concept was built in April. It is not included in the Bitbucket v1 repo. If anything it would be somewhere around this commit. We referred to it as metadata link preview. https://github.com/PowerlineApp/powerline-mobile/commit/4daf0eb449b47ed15deb8cdca2b8a64fc77087f0

**Comment by petervojtek** [comment]
thanks for hint @jterps08, I managed to resurrect it.

Current behaviour is following:

<img width="773" alt="screen shot 2016-07-27 at 12 04 13" src="https://cloud.githubusercontent.com/assets/225506/17171785/7b28372e-53f2-11e6-9fcf-19e190475c5d.png">

Few remarks:
- backend properly generates metadata link title and description, but image is always null.
- When you click the metadata link (title or description), you are guided to petition/post/.. detail. I personally find this confusing, I would expect to go the www.google.com in new browser window. If we want to alter this behaviour (to go to www.google.com), we need the backend to send us in 'metadata' also the url (technically the url is in the activity description, but it is not very comfortable to parse it from there).

**Comment by jterps08** [comment]
Peter - Ok. Let's assign this to Igor. We need the URL provided and the metadata Image URL provided. I agree that we want the click-through  of title/description/image to go to the actual URL not the activity-post-detail screen... We may end up turning this off in the future. One of the risks of this concept is porn/spam... I'm open to your suggestions on this. WhatsApp shows a blurred image first and allows you to click on the blurred image to load a crisp/clean image. Ideas? 

Igor - it's an enhancement so it can wait until bug-related work is done. Let me know if you have any questions.

**Comment by petervojtek** [comment]
there is [css-blur](http://caniuse.com/#feat=css-filters) filter so blurring/unblurring the image onclick in mobile should be easy.

**Comment by igaponov** [comment]
@jterps08 `metadata` attribute is currently available only for micropetition activity.

**Comment by austinpapp** [comment]
@jterps08 i assume you want all activities including leader questions to have this functionality?

**Comment by jterps08** [comment]
We certainly want the metadata for micropetitions updated to include URL image.

I will create a separate issue for Igor (lower priority) regarding making metadata possible on all leader content.

**Comment by igaponov** [comment]
@jterps08 currently metadata has `title`, `description` and `image`.

**Comment by jterps08** [comment]
That's the URL for the image?

**Comment by igaponov** [comment]
@jterps08 yes

**Comment by jterps08** [comment]
@petervojtek let us know what else needs to be done

**Comment by petervojtek** [comment]
@igaponov , I'd like to ask for following:
- currently `metadata.image` seems to be always null, please fill in there some image url.
- please add `metadata.url` which will contain the same url which triggered the whole metadata workflow (e.g. `metadata.url=www.google.sk`)

**Comment by igaponov** [comment]
`metadata.image` is not null only if there is an image on petition page. I use the first url in `description` of a petition.

**Comment by jterps08** [comment]
I'm not sure if we have common understanding of what the metadata is. If a user includes a link in the body of the text of a micropetition (e.g. www.google.com), then the metadata should capture the title, description, and image from google.com. for google.com, for example, I believe the metadata url would be www.google.com/images/branding/googleg/1x/googleg_standard_color_128dp.png (or something similar from header content)

**Comment by petervojtek** [comment]
@igaponov , regarding this sentence:

> I use the first url in description of a petition.

yes, and I would like to ask you to just provide me the url in `metadata.url` so that I don't have to parse the url from `description` because you already did that job.

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/234 was deployed

**Comment by petervojtek** [comment]
done.

**Comment by jterps08** [comment]
I am reopening this issue... including www.google.com in a user post is not displaying the metadata in the newsfeed. We may have lost this during the transition from micropetition to post...

**Comment by igaponov** [comment]
Fixed

**Comment by jterps08** [comment]
Okay - I can see the metadata title and meta data description, but I'm not sure if we're pulling the right metadata image... Difference between Facebook's metadata pull for weather.com vs ours... 

See below: 

![screenshot_20161121-164123](https://cloud.githubusercontent.com/assets/7582457/20501969/151d961c-b00a-11e6-8aa5-e483782efdfc.png)
![screenshot_20161121-164405](https://cloud.githubusercontent.com/assets/7582457/20501968/151ca6da-b00a-11e6-957b-d745cd2b3cc3.png)

**Comment by jterps08** [comment]
@petervojtek also, it would be good if all of the meta data (title/description/image) was hyperlinked to the actual hyperlink so that the user can tap on the meta data to go to the link...

**Comment by igaponov** [comment]
@jterps08 I can't find Facebook's image on the original page. I use `meta` tag with a name "image" to get a preview.

**Comment by jterps08** [comment]
Okay - we'll just stick with that. Thanks @igaponov
