### ISSUE TITLE
Author not automatically subscribed to Poll:event and Poll:petition

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#224]
this already works for userPetition and Post.

not sure if is also should work for leader-content, please confirm Jesse.

**Comment by jterps08** [comment]
I never thought about it until now. For leader content, we'll make this an enhancement at P2

**Comment by petervojtek** [comment]
this feature needs to implemented on backend.

**Comment by jterps08** [comment]
@igaponov is #298 (merged above), the closure of this item?

**Comment by igaponov** [comment]
@jterps08 yes

**Comment by petervojtek** [comment]
thanks @igaponov , I overlooked the reference from other repo.
I confirm it works.
