### ISSUE TITLE
Confirm: Correct Push Notification Messages & Buttons

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#226]
Igor - Please double-check each of these items are producing avatars, titles, messages, and buttons according to spec below. When complete with backend work, please assign to Peter. Thanks.

**General Push Notification Detail**
- #233 : **Social @Mention:** Main Avatar (User avatar who tagged me), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message ("mentioned you in a comment"). Buttons: Open, Ignore
- #232 : **Social Follow Request:** Main Avatar (User avatar who wants to follow me), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message ("wants to follow you. Approve?"). Buttons: Approve, Ignore 
-  DONE: **Post Created by Followed User:** Main Avatar (Post Author / Followed User avatar), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message (posted: PostText) where PostText is up to 300 characters long (minus 8 characters for "posted: "). Buttons:  Upvote, Ignore
- #235: **Petition Created by Followed User:** Main Avatar (Post Author / Followed User avatar), Small Avatar (Powerline logo), Title ("FirstName LastName Petition"), Message ("PetitionText") where PetitionText is up to 300 characters long. Buttons:  Sign, Ignore
- #302 : **Boosted Post:** Main Avatar (Post Author Avatar), Small Avatar (Powerline logo), Title ("FirstName in GroupName", Message("Boosted Post: PostText) where PostText is up to 300 characters long (minus 14 characters for "Boosted Post: "). Buttons: Upvote, Downvote
- #251: **Group Invite:** Main Avatar (Group Avatar), Small Avatar (Powerline logo), Title ("GroupName"), Message ("You have been invited to join this group"). Buttons: Join, Ignore.
- #300:  **Group Permissions Changed:** Main Avatar (Group Avatar), Small Avatar (Powerline logo), Title("GroupName"), Message ("GroupName has changed the information it is asking for from you as a group member. Open to learn more."). Buttons: Open, Ignore.
- #238, #239 : **Author Notifications** (For comments [all items], upvotes [posts only], and signatures [petitions only]): Main Avatar (Commenter/Voter Avatar), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message("commented on your post") OR ("voted on your post") (or 'petition' for petitions). Buttons: View, Mute. 
- #237 : **Non-Author Notifications** (Only for comments): Main Avatar (Commenter Avatar), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message("commented on the post you subscribed to") . Buttons: View, Mute. 

**Leader Content Push Notification Detail**
- #249: **New Announcement:** Main Avatar (Group Avatar), Small Avatar (Powerline logo), Title("GroupName"), Message ("AnnouncementText") (Up to 300 characters). Buttons: Share, Ignore
- DONE: **New Poll:** Main Avatar (Group Avatar), Small Avatar (Powerline logo), Title("GroupName Poll"), Message ("PollText") (Up to 300 characters). Buttons: Respond, Ignore.
- DONE: **New Petition:** Main Avatar (Group Avatar), Small Avatar (Powerline logo), Title("GroupName Petition"), Message ("PetitionTitle"). Buttons: Sign, View.
- DONE: **New News/Discussion:** Main Avatar (Group Avatar), Small Avatar (Powerline logo), Title("GroupName Discussion"), Message ("DiscussionText") (Up to 300 characters). Buttons: Open, Ignore.
- DONE: **New Event:** Main Avatar (Group Avatar), Small Avatar (Powerline logo), Title("GroupName Event"), Message ("EventTitle"). Buttons, RSVP, Ignore.
- DONE: **New Fundraiser/Crowdfunder:** Main Avatar (Group Avatar), Small Avatar (Powerline logo), Title("GroupName Fundraiser"), Message ("PaymentRequestTitle"). Button: Donate, Ignore. 
#253: For Main Avatar vs Small Avatar, read https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images (Large Icon from remote location is Main Avatar. Small Icon would be from assets? folder.
#252: IF EASY - Please include badge number update in the push notification payload details. https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#badges Badge number is the same as the count of the user's total priority items. If not easy, ignore badge. https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushsetapplicationiconbadgenumbersuccesshandler-errorhandler-count---ios--android-only

Additional Information Relating to #8 (For Peter)
- **Upvote/Downvote** - Should send an "upvote" or "downvote" response for the user, ideally without the app opening.
- **Ignore** - Destroys the notification from the OS notification drawer.
- **Open** - For announcements notification, opens Announcements tab. For Group Permissions changed notification, opens Announcements tab. For all other items, opens the Item Detail screen for the item.
- **Approve** - Approves a follow request and opens the Social Activity Feed (You Tab)
- **Join** - Accepts the invitation request to join a group and opens the Join Screen (if additional info required) and/or the Group Profile screen. 
- **Share** - Opens the announcements screen
- **Respond** - Opens the poll detail screen
- **Sign** - Signs the petition for the user, ideally without the app opening.
- **Donate/RSVP/Respond/View** - All open the item detail screen.
- **Mute** - Should unsubscribe from notifications for that post (as author or non-author) to prevent further notifications, ideally without opening the app.

Tapping any button should always destroy the notification in the OS drawer, but it will also result in a callback action for most items as explained above (except Ignore, which simply destroys the notification without any callback action). 

PS - For titles and messages, be sure that the system does not include UI tags like "<strong>". This appeared in one of the "someone commented on a post you subscribed to" notifications.

**Comment by jterps08** [comment]
FYI @igaponov : I just received a push notification that "Peter10 Is Leader" commented on a petition. But I (1.JesseChen) did not subscribe to that petition (petition 4456 by Peter 10). I should not have received a notification unless I either a) authored the post, or b) subscribed to that item's notifications.

**Comment by petervojtek** [comment]
to All -- please do not discuss the particual items here as we will get lost, but rather open a separate issue for each of the items above and discuss there (and reference this master issue)

**Comment by jterps08** [comment]
Not sure who made this edit above 'currently it is not possible to invite an user to a group' for Invite User to Group, but this is possible via two methods:
1) User's "Invite Followers to Group" function (user receives group invitation in app via Announcements feed)
2) Group leader invites users to a group using e-mail address (current users registered with same e-mail address receive group invitation in app via Announcements feed)

Unfortunately, I do not have a screenshot of the UI in-action (scenario 2 only), but it does exist in production currently today. When user receives group invite, it appears in the user's Announcements feed.

**Comment by petervojtek** [comment]
@jterps08 , I wrote that "'currently it is not possible to invite an user to a group'".
thanks for reminding me that it is possible.. I will return back to that use case in separate issue

**Comment by jterps08** [comment]
we can close this after open notification items in P1/P2 are closed I believe.

**Comment by petervojtek** [comment]
@jterps08, one last use case remains here to be tested:

> Boosted Post: Main Avatar (Post Author Avatar), Small Avatar (Powerline logo), Title ("FirstName in GroupName", Message("Boosted Post: PostText) where PostText is up to 300 characters long (minus 14 characters for "Boosted Post: "). Buttons: Upvote, Downvote

I am not sure know how to trigger a Post to be boosted..

**Comment by jterps08** [comment]
If it's a small group of people (less than 10), the boosting level of the group should be 10%. If not, we should have a group setting endpoint that allows the group creator or managers to set it to 10%. (all group settings should be accessible via endpoints now)... 

If the boosting level is 10% in a group of 10 people, only 1 person is needed to upvote an item in order for it to be boosted to all 10. Same with 1 person out of a 3 person group. 

There should also be an endpoint that allows a group creator/manager to manually boost a particular post/petition in a group. I'm not sure if that endpoint exists, but it's something that was part of the old admin.powerli.ne bundle that should have its own endpoint now...

**Comment by petervojtek** [comment]
ok, I created #302 to deal with boosted Post.

**Comment by petervojtek** [comment]
I close this issue because we successfully split it into sub-issues.
