### ISSUE TITLE
Push notification on upvote/downvote Post is confusing

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#231]
Based on #226.

When another user upvotes by Post, I receive following Push notification:

<img width="313" alt="screen shot 2016-09-12 at 07 42 23" src="https://cloud.githubusercontent.com/assets/225506/18425866/2bacafc8-78bd-11e6-9973-9d52644dab7d.png">

As creator of the Post I find the "Upvote" button confusing, from UX point of view it feels like clicking it will allow me to Upvote my own Post. Actually when I click it, the button only opens the app, but no upvote seems to be performed.

I am not sure if this is intention or bug.

When the user posts comments, this is what notification looks like:

<img width="317" alt="screen shot 2016-09-12 at 07 55 29" src="https://cloud.githubusercontent.com/assets/225506/18425995/6022b99a-78be-11e6-97f7-452411a49aa1.png">

the Upvote button is still there.

**Comment by austinpapp** [comment]
Is that the same user commenting on the post? If so I think this should not send a notification to to the author.

Also I agree that this should be either just open button or something else. Upvote shouldn't be there.

**Comment by jterps08** [comment]
As you can see in #226 there is a specific message that should be shown with specific button choices. The correct notification for this would be:

Author Notifications (For comments and upvotes): Main Avatar (Commenter/Voter Avatar), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message("commented on your post") **OR** ("voted on your post"). **Buttons: View, Mute.**
Non-Author Notifications (Only for comments): Main Avatar (Commenter Avatar), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message("commented on the post you subscribed to") . Buttons: **View, Mute.**

This is a backend issue. Closing because #226 is open already.

**Comment by jterps08** [comment]
Reopening so we can track the bug separately...

**Comment by petervojtek** [comment]
maybe this helps @igaponov -- when I downvote a Post, following data comes from server to create the Push notification:

```
{"message":" voted on your post","additionalData":{"collapse_key":"do_not_collapse","type":"social_activity","foreground":true,"actions":[{"callback":"app.upvote","icon":"Upvote","title":"Upvote"},{"callback":"app.open","icon":"Open","title":"Open"}],"entity":{"target":{"last_name":"Peter21","id":270,"image":null,"first_name":"Peter21","user_id":77,"type":"post"},"id":1244}},"image":"http://powerline-dev.imgix.net/?dpr=0.75&h=400&ixlib=php-1.1.0&w=320","title":"Peter21 Peter21"} 
```

**Comment by petervojtek** [comment]
ok, now it works as following:
on Post upvote/downvote, push notification arrives and two buttons are displayed: View and Mute.
- clicking View opens powerline app and displayes the Post detail
- clicking Mute opens the app main view (activity newsfeed)

@jterps08 , should the Mute button have some other behaviour?
Maybe prevent any upcoming push notifications for that particular Post ?

**Comment by jterps08** [comment]
Yes - Mute should unsubscribe the author from that post/user:petition to prevent further push notifications (FYI: non-authors should not get notifications about votes, only comments)...

**Comment by petervojtek** [comment]
@igaponov , it seems user receives Push notification on post upvote/downvote even after he is unsubcsribed from notifications from the Post.

Here is post as seen by `peter.vojtek` (Pavlik Morozov), and as you can see, he is `{"is_subscribed":false},`. But despite that when some other user upvotes that Post, `peter.vojtek` receives push notification.

```
{"zone":"prioritized","id":601,"title":"","description":"UserPost to test priority zone","description_html":"UserPost to test priority zone","sent_at":"2016-09-13T07:14:49.000Z","expire_at":"2016-09-14T07:14:49.000Z","responses_count":0,"owner":{"id":78,"type":"user","official_title":"","first_name":"Pavlik","last_name":"Morozov","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/57a2d7d76088f.jpeg"},"user":{"full_name":"Pavlik Morozov","id":78,"type":"user","official_title":"Pavlik Morozov","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/57a2d7d76088f.jpeg"},"entity":{"type":"post","id":275,"group_id":1},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-13T07:14:49+0000","poll":null,"user_petition":null,"post":{"is_subscribed":false},"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":0,"answers":[],"quorum":3}
```

**Comment by igaponov** [comment]
@petervojtek push notification on post upvote/downvote is sending only to owner and `peter.vojtek` is an owner of post with id=275

**Comment by petervojtek** [comment]
@igaponov , yes, he is owner, but he has unsubscribed from notifications -- and thus he should not receive them, no? Otherwise the unsubscribe (Mute) action will make no sense for authors i guess.

**Comment by jterps08** [comment]
FYI. Authors should have ability to unsubscribe/subscribe to notifications. They are default subscribed.

**Comment by igaponov** [comment]
@petervojtek there is an option in user profile called `isNotifOwnPostChanged` that can mute notification when his post is voted. I can also add a check if author is subscribed to a post or not. There was no directive that author should get notification about `post voted` event only if he is subscribed, so subscription affects ONLY other users and comments. Notifications for author were in the old code and weren't changed after subscriptions were added. @jterps08 what do you think?

**Comment by jterps08** [comment]
I can see how this is confusing... as usual, I apologize for making this more difficult for everyone than it needs to be...

Notifications for authors should be able to be activated/deactivated (subscribed/unsubscribed) at any time. Notifications for authors includes comments (all items), upvotes (posts), or signatures (petitions). Authors are subscribed to these notifications by default. 

Non-authors can subscribe/unsubscribe to any item at any time. However, non-authors will only be notified for comments. Non-authors are unsubscribed to an item by default. 

Regarding 

> There was no directive that author should get notification about post voted event only if he is subscribed

I think this is where the confusion is. Author Notifications = Author Subscribed to Own Post (same thing, not two different things).... Author should get notifications per rules above if he is subscribed (which he is subscribed by default). He can unsubscribe from all notifications on his item if unsubscribes.

Did that help or did I make it even more messy? :-)

**Comment by igaponov** [comment]
@jterps08 I understand, but why do we need `isNotifOwnPostChanged` option in profile? Should I check it too?

**Comment by jterps08** [comment]
I'm not sure what `isNotifOwnPostChanged` actually is... Seems like it may be duplicative of other capability? My assumption would be to lump it in with the Author Notification/Subscription but I'm not exactly sure...

**Comment by igaponov** [comment]
@jterps08 there must be a checkbox with this name in a user's profile

**Comment by jterps08** [comment]
Ah I see... Will show screen in slack

**Comment by petervojtek** [comment]
@jterps08 , I am not sure what is the outcome from the discussion above, I just report following behaviour persists:
1. user A created Post
2. user A unsubscribes from notification from the post (via bell icon)
3. user B upvotes the Post
4. user A receives push notification that the Post was upvoted.

**Comment by jterps08** [comment]
@petervojtek Your scenario is a bug. If User A unsubscribed, he shouldn't receive push notifications regarding that particular post anymore. 

If User A is subscribed, he should receive push notifications for new comments (all items), upvotes (posts only), and signatures (petitions only)

**Comment by petervojtek** [comment]
yes, tha leatest behaviour is my fault -- Igor helped me to discover the bug in frontend code via slack. it is fixed.
