### ISSUE TITLE
Push notification: Social Follow Request content does not looks as expected

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#232]
> # 226: Social Follow Request: Main Avatar (User avatar who wants to follow me), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message ("wants to follow you. Approve?"). Buttons: Approve, Ignore

this is how it looks like:

<img width="304" alt="screen shot 2016-09-12 at 08 00 01" src="https://cloud.githubusercontent.com/assets/225506/18426056/eca816ee-78be-11e6-83ed-ea8f6f5246dd.png">

Please confirm Jesse if this is what we want ot fix.

**Comment by jterps08** [comment]
These buttons are incorrect. They should be Approve or Ignore as per #226. @igaponov  needs to go through and confirm all buttons and messages as defined in 226. I'm not sure if he started on that yet. As such, I think that we should close this (232) for now given its a duplicate of 226.

**Comment by austinpapp** [comment]
Again. We need a way to verify these objects return correctly . This needs to be captured in some unit tests and/or integration tests

**Comment by jterps08** [comment]
Reopening so that we can track the bugs separately.

**Comment by igaponov** [comment]
~~There are no button definitions on backend, I think it's frontend issue.~~
Found it

**Comment by petervojtek** [comment]
@igaponov ,  I receive push notification that user wants to follow me.
I click approve, but I am unable to make proper Approve request to backend, because the push notification data does not contains the user ID required for `PATCH /api/v2/user/followers/{userID}`.

In the push notification `entity.target.id = 241`. I would expect `entity.target.id` to be `75`, because that is the userID of `Peter12`. I guess the 241 is some legacy follower ID for v1, while I already use v2 api.

```
{"message":" wants to follow you. Approve?","additionalData":{"collapse_key":"do_not_collapse","type":"follow-request","foreground":true,"actions":[{"callback":"app.approve","icon":"Approve","title":"Approve"},{"callback":"app.ignore","icon":"Ignore","title":"Ignore"}],"entity":{"target":{"type":"user","id":241},"id":1284}},"image":"http://powerline-dev.imgix.net/579ee69e5e9df.jpeg?dpr=0.75&h=400&ixlib=php-1.1.0&w=320","title":"Peter12 Peter12"} 
```

**Comment by igaponov** [comment]
Fix works only for new notifications

**Comment by petervojtek** [comment]
I confirm it works now.
