### ISSUE TITLE
Push notification on UserPetition Created by Followed User

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#235]
> # 226 Petition Created by Followed User: Main Avatar (Post Author / Followed User avatar), Small Avatar (Powerline logo), Title ("FirstName LastName Petition"), Message ("PetitionText") where PetitionText is up to 300 characters long. Buttons: Sign, Ignore

@jterps08 , what should happen when Ignore button is clicked?
Currently an UserPetition has action Sign (and Unsign). Ignore is not used in the mobile app for UserPetitions.

**Comment by jterps08** [comment]
"Ignore" simply destroys the push notification from the OS notification drawer. 

Per #226: 

> When a post is created by followed user, the option choices are upvote, ignore.
> When a post is boosted, the option choices become upvote, downvote.

**Comment by petervojtek** [comment]
@igaponov , Ignore button on push notification should just remove the push notification without opening the app.
I think this must be set on backend, because currently clicking the Ignore button has attached "app.ignore" callback which opens the powerline-mobile app automatically.

**Comment by igaponov** [comment]
@petervojtek which callback should I use?

**Comment by petervojtek** [comment]
@igaponov, is it possible to provide a button without callback?

because when there is (any) callback, the app is opened when user clicks the button.
Technically I am able to shut down the app from the callback, but that is not good approach because the app must first launch (wich takes cca 1-2 seconds) and then is immidiately closed -- this does not looks good.

**Comment by petervojtek** [comment]
so this is how currently looks like the notification when followed user created a UserPetition:

the Ignore button is not there at all:

<img width="306" alt="screen shot 2016-09-15 at 14 50 06" src="https://cloud.githubusercontent.com/assets/225506/18550371/c75cfa5c-7b53-11e6-94ff-5a052525b561.png">

despite the notification contains the Ignore button:

```
{"message":"test 69","additionalData":{"collapse_key":"do_not_collapse","type":"user-petition-created","foreground":true,"actions":[{"callback":"app.sign","icon":"Sign","title":"Sign"},{"icon":"Ignore","title":"Ignore"}],"entity":{"target":{"type":"user-petition","id":267,"body":"test 69","title":"test 69"},"id":1383}},"image":"http://powerline-dev.imgix.net/576b9b633f3fa.jpeg?dpr=0.75&h=400&ixlib=php-1.1.0&w=320","title":"Peter1 Peter1"} 
```

so, we have learned is that when a button has no callback, Android will not display it.
this means that @igaponov  you can probably remove the Ignore button completely from the notification as the effect will be the same.
