### ISSUE TITLE
Push notifications: Vote on UserPetition -- text is wrong

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#239]
when user petition is signed, the text says something about Post and voting:

<img width="300" alt="screen shot 2016-09-13 at 15 50 58" src="https://cloud.githubusercontent.com/assets/225506/18476357/fbd7e8fe-79c9-11e6-9267-0e83a87fa5c3.png">

**Comment by jterps08** [comment]
Correct Language in #226

**Comment by igaponov** [comment]
@jterps08 I see only
`Author Notifications (For comments and upvotes): Main Avatar (Commenter/Voter Avatar), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message("commented on your post") OR ("voted on your post"). Buttons: View, Mute.`

nothing about user petition.

**Comment by jterps08** [comment]
@igaponov you are correct. This is a mistake on my part. I should have included the following:

Author Notifications (For comments/signs): Main Avatar (Commenter/sign Avatar), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message("commented on your petition") OR ("signed your petition"). Buttons: View, Mute.

**Comment by petervojtek** [comment]
ok, confirm it is fixed
