### ISSUE TITLE
Push Notification Detail for "poll commented/answered" event

### ISSUE THREAD

**Issue by igaponov** [PowerlineApp/powerline-mobile#242]
#226 doesn't contain info for "Poll commented/answered" events.

**Comment by jterps08** [comment]
Author notifications for polls, discussions, fundraisers, and events would be related to comments only. 
Author notifications for posts, petitions (user/leader) would be related to comments, upvotes, and signatures.

**Comment by igaponov** [comment]
@jterps08 fixed, can you check it?

**Comment by jterps08** [comment]
I will check in the next available build. I am in a conference Thurs/Fri daytime. I will try to test tonight or over the next couple of days.
