### ISSUE TITLE
Is Poll (Group) properly rendered?

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#243]
this is how Poll:group looks like in activity newsfeed:

<img width="751" alt="screen shot 2016-09-14 at 17 12 39" src="https://cloud.githubusercontent.com/assets/225506/18517969/86a700ee-7a9e-11e6-847f-54209c93bddc.png">

and this is its detail:

<img width="752" alt="screen shot 2016-09-14 at 17 12 47" src="https://cloud.githubusercontent.com/assets/225506/18517975/89227bf0-7a9e-11e6-9ebc-9bdc8a678b66.png">

Should author of the Poll be able to answer it?

**Comment by jterps08** [comment]
Sure. I think that's okay.... Leaders can answer their own content I think.
