### ISSUE TITLE
Poll:News rate up/down fails

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#244]
activity newsfeed:

<img width="742" alt="screen shot 2016-09-14 at 17 31 41" src="https://cloud.githubusercontent.com/assets/225506/18518641/2236d956-7aa1-11e6-8adf-8c65c7de42b8.png">

detail:

<img width="753" alt="screen shot 2016-09-14 at 17 31 48" src="https://cloud.githubusercontent.com/assets/225506/18518651/25ee8094-7aa1-11e6-8e62-d71ed164896d.png">

I  don't know what is the purpose of this content type at all.

Clicking the rate up or down currently fails (due to frontend code)

**Comment by jterps08** [comment]
This is correct. News/Discussion is simply a space for discussion/comments on some topical matter created by a group leader (owner/managers)... 

Background context:
The difference between a user post and a news/discussion item is that only the author's _followers_ receive a notification when a user post is created vs _all group members_ receive a notification when a news/discussion item is created. Same with userPetition vs leader petition.

If User A creates a user post or user petition, only his followers receive notifications (until it gets boosted potentially). Even if User A is a leader in the group (owner/manager), only his followers receive notifications when user post or user petition is created. However, if User A has permission to create news/discussion item, all group members receive notification immediately for news/discussion item.

Only authorized group leaders (owner and manager(s)) can create leader content: polls, leader-petitions, news/discussions, fundraisers/crowdfunders, events, and announcements.

**Comment by petervojtek** [comment]
@jterps08 , I am confused with the term `news/discussion`. Is it s single data type, or two data types?

I am aware of `poll:news` data type. So far I thought `discussion` is some other (leader) data type, but api doc does not mentions `discussion` at all.

On the other hand, the [key terms](https://docs.google.com/spreadsheets/d/1C7KZetAByn3klFP9PdgyivMTf1_QMMwqWNKJ6QLSQm0/edit#gid=0) do not mention `news` at all.

**Comment by jterps08** [comment]
News = discussion. Same thing. Single data type. I didn't know what it was called on the backend which is why I used both terms. Poll:news is what I'm referring to.

**Comment by petervojtek** [comment]
ok fixed.
