### ISSUE TITLE
Poll:payment layout is broken

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#245]
activity newsfeed. the icons should be aligned to left side as are in all the other activity items.

<img width="750" alt="screen shot 2016-09-14 at 18 04 00" src="https://cloud.githubusercontent.com/assets/225506/18519911/e9756c36-7aa5-11e6-8069-8eecbc9d449a.png">

and detail:

<img width="742" alt="screen shot 2016-09-14 at 18 04 08" src="https://cloud.githubusercontent.com/assets/225506/18519916/ed2a71aa-7aa5-11e6-928b-edbc2560d1a8.png">

the same for crowdfunding item

**Comment by petervojtek** [comment]
ok, fixed

**Comment by jterps08** [comment]
Every fundraiser layout should always offer an option "$0 - Ignore" by default in addition to whatever options are defined by the fundraiser-author. 

So, if fundraiser author creates fundraiser with 3 options ($5 - Tshirt, $10 - Sticker, $25 - Car) then the system automatically adds a 4th option $0 - Ignore that the user sees. 

I'm not sure if this is done on the frontend or the backend (should be done on the backend). This enables any user to "answer" a fundraiser (marking it as read, taking it out of priority zone), while not donating to a fundraiser with the $0 option or donating with a $ option. 

Another test we need to do with fundraisers are 1) custom amounts (answer choices where dollar amount is defined by user when responding, not by fundraiser author), and 2) Stripe processing. I'll create a separate issue for this when I test this weekend.

**Comment by jterps08** [comment]
@petervojtek not sure if we reopen the above or create new issue for my comment above.
