### ISSUE TITLE
Comment: rate up + rate delete end up with rates_count:1

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#247]
I have a comment under a Post which has 0 rates.

I up rate the comment:

```
Request URL:https://api-dev.powerli.ne/api/v2/post-comments/579/rate
Request Method:POST
Status Code:200 OK

{"rate_value":"up"}

```

and the rate numbers are as expected:

```
"rate_sum":"1","rates_count":"1"
```

Now I change my mind and want to undo my rate (i.e. delete it). I call:

```
Request URL:https://api-dev.powerli.ne/api/v2/post-comments/579/rate
Request Method:POST
Status Code:200 OK

{"rate_value":"delete"}
```

but in response I receive following numbers:

```
,"rate_sum":"0","rates_count":"1"
```

However I would expect the `rates_count` to be `0`.

The consequence of  `"rate_sum":"0","rates_count":"1"` is that the computed number of upvotes and downvotes is `0.5`:

<img width="744" alt="screen shot 2016-09-15 at 09 15 07" src="https://cloud.githubusercontent.com/assets/225506/18541364/17c451ae-7b25-11e6-8240-04873f142fef.png">

[here is business logic](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/discussion.js#L130) to compute number of upvotes and downvotes. Actually, it would be much better if the backend will just provide number of `upvotes` and `downvotes` for the comment, so that frontend is not required to compute it on its own.

the same applies for comment under every other entity type (poll/user petition)

**Comment by jterps08** [comment]
Agreed

**Comment by igaponov** [comment]
Fix will work when the next comment will be added.

**Comment by petervojtek** [comment]
ok, works.
