### ISSUE TITLE
On un/subscribe from activity from Favorites, the change (button color) is not instantly propagated to the main Activity feed.

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#248]
When I view a poll:news activity via activity newsfeed, it has `poll:is_subscribed = true`:

```
{"zone":"prioritized","id":634,"title":"","description":"news 4","description_html":"news 4","sent_at":"2016-09-15T14:13:50.000Z","expire_at":"2016-09-16T14:13:50.000Z","responses_count":0,"owner":{"id":285,"type":"group","group_type":3,"official_title":"San Diego","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png"},"user":{"full_name":"Peter10 Is Leader","id":73,"type":"user","official_title":"Peter10 Is Leader","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"leader-news","id":242},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-15T14:13:50+0000","poll":{"is_subscribed":true,"answers_count":null},"user_petition":null,"post":null}
```

however when I add this item to favorites and fetch it via favorites API, the `poll:is_subscribed` is missing:

```
{"id":634,"title":"","description":"news 4","description_html":"news 4","sent_at":"2016-09-15T14:13:50.000Z","expire_at":"2016-09-16T14:13:50.000Z","responses_count":0,"owner":{"id":285,"type":"group","group_type":3,"official_title":"San Diego","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png"},"user":{"full_name":"Peter10 Is Leader","id":73,"type":"user","official_title":"Peter10 Is Leader","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"leader-news","id":242},"read":false,"updated_at":"2016-09-15T14:13:50+0000"}
```

**Comment by igaponov** [comment]
@petervojtek yes, because we've never added this functional for bookmarks (also for post and user petition) and it's not easy to add. Do you really need it here?

**Comment by petervojtek** [comment]
let's see what will tell us @jterps08.

I can easily remove the subscribe (bell icon) button from activities in Favorites in case it is too complicated to adjust it backend..which means user will be able to subscribe/unsubscribe to activity only from activity newsfeed.

**Comment by jterps08** [comment]
User should be able to subscribe/unsubscribe to notifications from any item that's in Favorites list simply by clicking the bell icon... but we can move this to a P3 Enhancement if it's not going to be easy.

**Comment by petervojtek** [comment]
ok, it works.

now there is one minor bug:
when I un/subscribe from activity from Favorites, the change (button color) is not instantly propagated to the main Activity feed.

the other way button color propagation works -- (un/subscribe from activity newsfeed and then go to favorites and the button color is properly adjusted)
