### ISSUE TITLE
push notifications: large and small avatars not displayed properly

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#253]
this is how avatars looks like for every push notification now:

<img width="305" alt="screen shot 2016-09-16 at 09 48 40" src="https://cloud.githubusercontent.com/assets/225506/18578912/dbe74fbe-7bf2-11e6-9cd4-7ee6f071db9e.png">

while @jterps08 wants  in #226  each push notification to contain both Main Avatar (Group or Author Avatar depending on datatype) and Small Avatar (Powerline logo).

here is a e.g. a push notification for crowdfunding:

```
{"message":"kickstart me 2","additionalData":{"collapse_key":"do_not_collapse","type":"group_payment_request_crowdfunding","foreground":true,"actions":[{"callback":"app.donate","icon":"Donate","title":"Donate"},{"icon":"Ignore","title":"Ignore"}],"entity":{"id":256}},"image":"http://powerline-dev.imgix.net/?dpr=0.75&h=400&ixlib=php-1.1.0&w=320","title":"San Diego Fundraiser"}
```

there is some image url ([http://powerline-dev.imgix.net/?dpr=0.75&h=400&ixlib=php-1.1.0&w=320](http://powerline-dev.imgix.net/?dpr=0.75&h=400&ixlib=php-1.1.0&w=320)), but that url seems to contain no avatar image.

**Comment by igaponov** [comment]
This link is invalid, now if user doesn't have an avatar push body will contain `"image":null`.
We can add default avatar on backend or frontend, need to discuss it first.

**Comment by jterps08** [comment]
This comes back to the NG-letter thing. If we don't have an image on file for the user, NG-Letter should be displayed instead. Currently that's being handled on the frontend for the newsfeed (and a few other places). But, for notifications, I think it would have to originate from the backend.

Thoughts @petervojtek ?

**Comment by petervojtek** [comment]
@jterps08 , yes, the ng-letter avatars must be produced on backend if we want them to appear in notification.
as this may require more time to implement, as a quick hack we can do following (on backend):
- when user does not has a photo avatar, use some stock "person" clipart
- the same for group with some stock "group of people" clipart

or even easier hack:
- provide the powerline logo instead of ng-letter.

**Comment by jterps08** [comment]
Let's use the powerline logo for those users/groups who do not have a photo avatar... I will provide via Slack

**Comment by petervojtek** [comment]
@jterps08 , you provided me the logo via Slack private channel, however the logo should be adopted by backend -- the way which icons are displayed in push notification is matter of backend, frontend has no way to influence it.

The procedure should be as following:
1. backend will adjust its push notifications business logic to adopt the logo
2. we will just test it from frontend

**Comment by jterps08** [comment]
So, I will provide logo to @igaponov

**Comment by petervojtek** [comment]
this is how the push notification appears now on Android:

<img width="300" alt="screen shot 2016-09-23 at 06 39 28" src="https://cloud.githubusercontent.com/assets/225506/18774359/7f43b3fe-8158-11e6-8cca-d81027f90596.png">

it does not seem to be fixed.

here is the related push notification:

```
{"title":"Peter10 Is Leader","message":" commented on your post","type":"own-post-commented","entityData":{"id":1580,"target":{"id":295,"preview":"test1","type":"post","label":"post","comment_id":609}},"image":"http://powerline-dev.imgix.net/577cb68e6f276.jpeg?dpr=0.75&h=400&ixlib=php-1.1.0&w=320","arn":"arn:aws:sns:eu-west-1:863632456175:endpoint/GCM/powerline_android_dev/8024c99b-dec9-37b9-9b07-377f943fcb9f","user":{"id":78,"username":"peter.vojtek"}}
```

the image url does not seem to serve any image:
http://powerline-dev.imgix.net/577cb68e6f276.jpeg?dpr=0.75&h=400&ixlib=php-1.1.0&w=320

**Comment by igaponov** [comment]
@petervojtek user Peter10 has an avatar and it equals to `577cb68e6f276.jpeg`. Probably, it's not uploaded to imgix.
@jterps08 did imgix work before?

**Comment by jterps08** [comment]
When the server passes the imgix URL, it needs to include the appropriate folder, not just the filename. 

Yes, Imgix worked before. Images do not get "uploaded" to imgix. They are only processed through imgix on-the-fly. The path that the server provides needs to be very precise. 

For example, http://powerline-dev.imgix.net/577cb68e6f276.jpeg does not work. 
but http://powerline-dev.imgix.net/avatars/577cb68e6f276.jpeg does work.

Imgix is directly connected to our S3 buckets. It works by taking an address (like the one above) and processing our image on-the-fly using the properties passed to Imgix in the URL. The S3 bucket on AWS shows me a structure of two folders: 1) educational, and 2) avatars. See screenshot below.  We need the imgix URL link provided by the server to work whether the image is in either of these folders, thus the server needs to pass the folder as part of the address.

**Comment by jterps08** [comment]
We will need to make sure the Imgix functionality is working everywhere images (user avatars, group avatars, item attachments) are displayed guys @petervojtek @igaponov ... not sure if this impacts backend or frontend.

**Comment by petervojtek** [comment]
@igaponov , now when I receive push notification, the image url is following:

```
{"message":"crowdfund 6","additionalData":{"collapse_key":"do_not_collapse","type":"group_payment_request_crowdfunding","foreground":true,"actions":[{"callback":"app.donate","icon":"Donate","title":"Donate"}],"entity":{"id":296}},"image":"dev.powerli.ne/bundles/civixfront/img/logo.jpg","title":"San Diego Fundraiser"} 

```

the [dev.powerli.ne/bundles/civixfront/img/logo.jpg](dev.powerli.ne/bundles/civixfront/img/logo.jpg) is not an image, but redirect to main page:

```
$ curl dev.powerli.ne/bundles/civixfront/img/logo.jpg

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

```

**Comment by petervojtek** [comment]
I confirm the url is correct, but it is not displayed in push notification

This is what I experience:

When there is push notification from an user with avatar image, this is how the notification looks like:

<img width="311" alt="screen shot 2016-09-27 at 07 19 46" src="https://cloud.githubusercontent.com/assets/225506/18861245/3415c780-8484-11e6-8d74-8fa765bc32e1.png">

And here is the corresponding notification content:

```
{"message":" commented on your petition","additionalData":{"collapse_key":"do_not_collapse","type":"own-user-petition-commented","foreground":true,"actions":[{"callback":"app.view","icon":"View","title":"View"},{"callback":"app.mute","icon":"Mute","title":"Mute"}],"entity":{"target":{"id":257,"comment_id":193,"label":"petition","type":"user-petition","preview":"test 9"},"id":1738}},"image":"http://powerline-dev.imgix.net/avatars/577cb68e6f276.jpeg?dpr=0.75&h=400&ixlib=php-1.1.0&w=320","title":"Peter10 Is Leader"} 
```

Now when comes a notification from user without avatar/photo, this is how it looks like:

<img width="315" alt="screen shot 2016-09-27 at 07 31 38" src="https://cloud.githubusercontent.com/assets/225506/18861284/73b53286-8484-11e6-99e9-80634a4a1986.png">

and here is notification content:

```
{"message":" commented on your petition","additionalData":{"collapse_key":"do_not_collapse","type":"own-user-petition-commented","foreground":true,"actions":[{"callback":"app.view","icon":"View","title":"View"},{"callback":"app.mute","icon":"Mute","title":"Mute"}],"entity":{"target":{"id":257,"comment_id":192,"label":"petition","type":"user-petition","preview":"test 8"},"id":1735}},"image":"api-dev.powerli.ne/bundles/civixfront/img/logo.jpg","title":"Peter30 Peter30"} 
```

The logo api-dev.powerli.ne/bundles/civixfront/img/logo.jpg is not rendered -- my assumption is that it is because the `image` attribute is not a full path because is missing `https://`

**Comment by igaponov** [comment]
Schema is added

**Comment by petervojtek** [comment]
I cannot confirm the icon url is fixed, because no push notifications are being produced on backend when using the same device and same use case as in my previous comment.
no new entries appear in `/dev/shm/powerline/logs/push_dev.log`

**Comment by igaponov** [comment]
fixed

**Comment by petervojtek** [comment]
ok, now the image is there, but it is not automatically fitted into proper width and height:

<img width="323" alt="screen shot 2016-09-28 at 08 20 52" src="https://cloud.githubusercontent.com/assets/225506/18902647/9a5e3f74-8554-11e6-82b9-d81eb6ceb307.png">

**Comment by igaponov** [comment]
fixed

**Comment by petervojtek** [comment]
thanks. I consider this as fixed:

<img width="328" alt="screen shot 2016-09-28 at 10 47 57" src="https://cloud.githubusercontent.com/assets/225506/18906751/18f33484-8569-11e6-9557-06934234f271.png">
