### ISSUE TITLE
add JS console helper: Group leader invites users to a group using e-mail address

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#254]
to allow us to test following push notification scenario: https://github.com/PowerlineApp/powerline-mobile/issues/226#issuecomment-247013055

**Comment by petervojtek** [comment]
@igaponov , can you please tell if this API endpoint is the proper one to invite some specific user to a group ?
https://api-dev.powerli.ne/api-doc#put--api-v2-groups-{id}-users

as a leader I want to invite people to a group by using their logins or emails -- only invite them, so that they decide on their own if they want to join or not.

**Comment by jterps08** [comment]
@igaponov - This functionality is currently available in production via the admin.powerli.ne dashboard where a group leader can invite users via e-mail address(es) to join the group. An endpoint should be available for this capability in v2.

**Comment by igaponov** [comment]
@petervojtek yes, you can invite users by username with this endpoint.

**Comment by petervojtek** [comment]
thanks @igaponov 
I successfully invite an user to a group, but the user receives no push notification.

Igor, can you confirm that you produce a push notification after this API call?

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/311/users
Request Method:PUT
Status Code:204 No Content

{"users":["peter.vojtek"]}
```

**Comment by petervojtek** [comment]
UPDATE: it seems I no longer receive any push notification to any of my android devices/emulators.. (#241).. I am inspecting it..

**Comment by jterps08** [comment]
Can we close this? Original issue seems resolved now that Helper has this functionality? @petervojtek

**Comment by petervojtek** [comment]
yes, it works.
