### ISSUE TITLE
Unable to Login/Register with Facebook on iOS

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#255]
1. On iPhone 6 v9.3.4 the user taps Register/Login with Facebook
2. The Facebook Auth Permissions page ("Do you want to give Powerline permission to access blah blah blah from your Facebook") shows and user taps Okay. 
3. App returns to login screen (wrong). 
4. User tries to Login/register with Facebook again. This time Facebook's "You have already authorized Powerline" message appears. 
5. (expected behavior) After user taps okay in step 2, app should show the address screen for user to enter street address information.

**Comment by petervojtek** [comment]
@jterps08 , when you confirm that you give permissions to powerline app, currently then the app should return to the login screen for cca 1-3 seconds (and then automatically go to activity newsfeed screen). In understand that this may be confusing, but getting instantly from Facebook Auth Permissions page to Home page may take some time to develop and test.

Currently I made following UI adjustment so that the user is not that confused:
1. on Login screen, you click Register/Login via facebook
2. The Facebook Auth Permissions page is displayed. you click Okay.
3. The powerline login page is displayed for cca 1-3 seconds, BUT there is loader (spinner) displayed over the page.
4. after those 1-3 seconds the screen is redirected to Home page (activity newsfeed).

Please let me know if this behaviour is satisfactory..

**Comment by jterps08** [comment]
@petervojtek The UI change is acceptable, but the correct sequence here should be this:
1) User taps on Login/Register with Facebook
2) User sees and confirms Facebook Auth page
3) User is brought to address entry form and enters address [otherwise we can't link to electeds or town/state/country groups]. Clicks next.
4) User is brought to Home screen.

**Comment by petervojtek** [comment]
@jterps08 , yes, the steps above are relevant for user who has already filled in profile.

user who registered via facebook for the first time is in step 4. redirected to Profile screen and is asked to fill in his profile details. Only when he fills in the details he is allowed to go elsewhere.

**Comment by jterps08** [comment]
Correct @petervojtek 

Chris Mino was never registered on Powerline before yesterday when I manually registered him (I tried registering him with Facebook first). When registration with Facebook failed, i tried manual registration. If you are unable to test on emulator, maybe it's because I didn't wait long enough on Login screen, but I would have expected to see address entry screen immediately after Auth screen... (for the user who was never previously registered on Powerline with FB)

**Comment by petervojtek** [comment]
ok, there was bug in the code which affected only iOS (while on Android it was working). 
please retest this Jesse with latest IPA.

I put here details on the problem, maybe someone else will find them useful someday:

when fetching user profile from facebook via `facebookConnectPlugin.api` call, we requested following provileges to be allowed by user: `['public_profile', 'email', 'user_friends']`.

On android this privileges were confirmed by user in following manner:
1. first a facebook modal was displayed telling user that powerline app will access his public profile and email.
2. after confirming, another facebook modal was displayed telling user that powerline app will access his user_friends (i don't know why facebook did not displayed this privilege request in the first modal).
3. after confirming, user was registered and logged in to powerline app.

However on iOS, the `facebookConnectPlugin.api` call provided no response (even no error callback), it was completely silent. What helped was changing the requested privileges from `['public_profile', 'email', 'user_friends']` to `['public_profile', 'email']`. Then both on Android and iOS the behaviour is following:
1.  facebook modal is displayed telling user that powerline app will access his public profile and email.
2. when user confirms, he is registered  and logged in to powerline app.

I put the request for `'user_friends'` privilege to the point when it is really requested -- and that is when user is about to populate his Influences from his friends. I created a separate issue for testing that: #294

**Comment by jterps08** [comment]
sounds good thank you Peter
