### ISSUE TITLE
iOS: Groups not loading in Group Selector

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#257]
User does not see town / state / country groups or any other groups he is joined to in the Group Selector/Filter on the newsfeed..

Groups are shown in My groups screen. Newsfeed is populated with content from groups.

**Comment by jterps08** [comment]
Logout/Login does not solve the problem. However, force closing and restarting the app does solve the problem.

**Comment by petervojtek** [comment]
I cannot reproduce the bug on iOS emulator.

steps:
1. I login as Peter30 (is from Las Vegas). I see following groups: NV, US.
2. I go to My Groups and join group `Pavlik Group 1`
3. I go to Gome (activity newsfeed) and the `Pavlik Group 1` (PG1) is immidiately there.

Can you please post the steps you perform @jterps08 which result in the bug?

**Comment by jterps08** [comment]
@petervojtek A couple thoughts:
1) You should see Las Vegas, Nevada, and US groups... not only Nevada and US groups... 
2) Please see steps below:

1) User installs app
2) User registers as new user with e-mail
3) User is automatically logged into app after registering as new user (this may be where the issue is occurring because the user has not been linked to his groups yet on the backend before being logged in).
4) The user sees the "all" and "more" button, but no town / state / country group. User should see town / state / country groups during first login. 

Force-closing and restarting the app was enough to get this linkage to reload.

**Comment by petervojtek** [comment]
@jterps08 , I cannot reproduce your behaviour.
the is what I do:
1. launch the app
2. register new user `Peter31`
3. right after successful registration I go to Main screen and this is what I see:

<img width="748" alt="screen shot 2016-09-19 at 15 24 27" src="https://cloud.githubusercontent.com/assets/225506/18633592/57ebd7ce-7e7d-11e6-876a-ba09a811f7d5.png">

I would attribute the missing Las Vegas group to backend, but the other groups are there.

**Comment by jterps08** [comment]
We definitely need the Las Vegas group to appear. I'm not sure why it is not @igaponov ? 

Again, this was an issue I experienced on the device I had. I think the user was brought to the Home screen before the backend had finished matching the user to new groups. Maybe there's a command we can add to help update the Home screen after first login to make sure? @petervojtek

**Comment by petervojtek** [comment]
> Maybe there's a command we can add to help update the Home screen after first login to make sure?

unless I am able to reproduce it, I would rather not apply any code changes. @jterps08 , please try to reproduce the issue and let me know the sequence of the steps which led to it.

**Comment by igaponov** [comment]
There is no group with the name `Las Vegas` on dev.

**Comment by jterps08** [comment]
This is strange. Las Vegas should _definitely_ be there... @igaponov if someone registers with a Las Vegas, Nevada, United States address than they should be linked to Las Vegas group, Nevada group, and United States group. Can you look at Peter30 on the backend and see why he doesn't have a local group?

**Comment by igaponov** [comment]
@jterps08 he doesn't have a local group because there is no group with the name `Las Vegas`. We need to add the group and then new users will be joined to it after registration.

**Comment by jterps08** [comment]
@igaponov Anytime a user registers, the town, state, and country groups should be created for the user by the system if they don't already exist. This is currently working in production.

For example, if you registered a new user with address 120 De Korte St, Johannesburg, South Africa then the user is linked to Johannesburg group (local), Gauteng group (state/province), and South Africa group (country). In this case, the user would also be linked to African Union AU group (although similar feature exists for European Union EU group for EU countries)... The system leverages Google, I believe, for determining these groups.

In the United States, it's necessary to use Google for local group creation/linking because towns are sometimes part of something larger... For example, the address 1409 Wickapecko Dr, Wanamassa, NJ 07712 will link the user to Ocean, New Jersey, and United States of America groups. Wanamassa is part of Ocean Township. The user is not linked to Wanamassa group....

The system knows how to do this and currently does it in production. 

@petervojtek was Peter30 originally registered as Las Vegas or was he registered at a different address and then changed to Las Vegas? I am wondering if the "Update Profile / Change Address" capability is not executing the group linking process correctly. If the user changes to an address and those groups don't exist, the system needs to create those groups...

**Comment by petervojtek** [comment]
@jterps08 , Peter30 was located in Las Vegas on registration.

**Comment by jterps08** [comment]
If Peter30 was located in Las Vegas during registration, then the system should have created a local group for him.

**Comment by igaponov** [comment]
This is the algorithm to join a user to local groups:
1. Build query: address1,city,state,country
2. Ask Google to parse it and return normalized names
3. Create new groups (only if google returns something)
4. If not, try to find groups in our db

Peter30 has addres1=Las Vegas, query = Las Vegas,Las Vegas,NV,US. Google **can't** parse it, need normal address1 (not the same as city name). We can't create Las Vegas group and it's not in our db, so Peter30 now has only two groups, found in our db: NV and US.

**Comment by jterps08** [comment]
@igaponov my guess is that this problem occurred (257) because Peter30 didn't provide a _street_ address to google when registering. Is that true? @petervojtek did you provide a street address? If you did, then we have a problem with how google parsed this and our reaction to google... If you did not provide a street address for Peter30, system is functioning normally. 

In other words:
System **can** handle: 3355 Las Vegas Blvd S, Las Vegas, NV 89109 address and link user to town / state / country group
BUT system **cannot** handle (no street address), Las Vegas, NV 89109 address

**Comment by jterps08** [comment]
Closing - issue was due to incomplete address1 line provided to google. street address must b eprovided for successful linking.

**Comment by petervojtek** [comment]
yes, it is true, I have actually not provided street address in "street address" field.
