### ISSUE TITLE
iOS: User signs petition, newsfeed not updated

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#259]
User signs petition, returns to newsfeed, item does not show "unsign" in quick action bar in newsfeed

**Comment by petervojtek** [comment]
@jterps08 , I cannot reproduce the bug.

I experience following behaviour:
1. poll:petitition is created
2. user logs in on iOS
3. user signs the petition in detail
4. user clicks back button, and in newsfeed the button near petition is UNSIGN
