### ISSUE TITLE
iOS: Counters not displaying on Group Selector Filters

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#260]
There are several items in the newsfeed with red 'priority zone' dots but the group selector filters do not show the counters correctly.

**Comment by jterps08** [comment]
The counters returned when I tried to visit My Representatives screen and returned back to newsfeed.

**Comment by petervojtek** [comment]
@jterps08 , I can't reproduce this bug.
After login I am headed into Main page (activity newsfeed) and the counters are there.

<img width="321" alt="screen shot 2016-09-21 at 11 49 17" src="https://cloud.githubusercontent.com/assets/225506/18706257/8bab6f00-7ff1-11e6-93a5-bbdf0a714278.png">
