### ISSUE TITLE
iOS: Pull to Refresh "hangs" 

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#263]
User pulls newsfeed to refresh and the 'loading' icon just shows. 

Needed to force close and restart the app in order to get newsfeed updates.

**Comment by jterps08** [comment]
If the pull-to-refresh does complete, the group selector disappears.

**Comment by petervojtek** [comment]
@jterps08 , I cannot reproduce this bug.. even on the ancient Iphone 4S the refresh pull works.
