### ISSUE TITLE
"Peter No 11" user post "Post to test voting results no1" showing as priority zone

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#264]
This seems to be a bug for anyone viewing this item for the first time... 
This item was expired on 8/30, but it somehow still had a red dot (until it was viewed). Any item that is past it's expiration date should automatically be moved to non-priority zone (once it expires).

**Comment by jterps08** [comment]
I tested this with account JTest55 as well as with new account Chris Minotest

Chris Minotest also displayed this post for the first time to the user. As it was expired, it should not be in priority zone.

**Comment by jterps08** [comment]
Relatedly, upvote/downvote button is still visible on newsfeed for this item even tho it is expired @petervojtek 

As a reminder, unexpired user posts are only in the priority zone if they are boosted. They can only be moved to non-priority zone if they are answered with Upvote, Downvote, or Ignore answer choices. Once they expire, they are moved to expired zone (not priority or non-priority).

**Comment by igaponov** [comment]
It was fixed before https://github.com/PowerlineApp/powerline-mobile/issues/199 (fix date is 8/30), old data wasn't touched.

**Comment by jterps08** [comment]
Got it. Can you delete that post or mark it as priority so that this doesn't keep on coming up in testing? If not, that's okay.

**Comment by igaponov** [comment]
@jterps08 I've added `expireAt` date for that post, it should move to `expired` zone now.
