### ISSUE TITLE
iOS Email Registration

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#265]
user taps register with e-mail button on login screen
User enters first name, last name, username, password, re-enters password.
After finishing entering password for second time, keyboard shows "Go". User taps Go. and the screen returns to Login screen. Tapping Register with email button again shows all information and user can hit Next.

User should be able to tap "Go" to proceed to Next screen instead of kicking out to Login screen.

**Comment by petervojtek** [comment]
I confirm this issue on iPhone. the problem is in general following:
in registration screen when you enter some text and hit Go button on the iphone keyboard, you are redirected to Login screen.

the same happens on Android (the Enter button on android virtual keyboard)

**Comment by petervojtek** [comment]
ok, I fixed it.
but now Enter (Go) is doing nothing, I created following task for it: #307
