### ISSUE TITLE
Selecting "Build Test Two" from Group Selector causes hang

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#269]
The newsfeed correctly shows a new post in BT2 group in the newsfeed. However, when selecting the group selector filter for BT2, the "loading' icon shows with no end.

**Comment by petervojtek** [comment]
@jterps08 , cannot reproduce. I can add myself to the "Build Test Two" group and then see its content in newsfeed via group selector:

<img width="753" alt="screen shot 2016-09-20 at 12 57 11" src="https://cloud.githubusercontent.com/assets/225506/18667675/d7a21dde-7f31-11e6-8850-17dd66658002.png">
