### ISSUE TITLE
Notification Not Created for New Leader Petition on iOS

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#270]
BT2 group leader JTest1 creates new leader petition.
No push notification delivered to iOS device.
Push notification successfully delivered to Android 4.4 device. 
Content appears correctly in newsfeed

**Comment by igaponov** [comment]
User `JTest1` doesn't  registered devices on dev server now. I think the problem is in handling SNS errors. I tried to fix it in #326, try to send another notification after deploy (you need to register all your devices again).

**Comment by jterps08** [comment]
When you say "need to register all of your devices again", will that be solved by logging out and logging back in or uninstalling/reinstalling? Or something else @petervojtek

**Comment by petervojtek** [comment]
@jterps08, to register the device to push notifications, you need to stop and start again the powerline app (logout from app is not necessary)

**Comment by petervojtek** [comment]
it works now
