### ISSUE TITLE
Notification Action Button: Event RSVP should load Item Detail Screen

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#272]
currently shows the newsfeed. It should show the item detail screen for the event.

**Comment by petervojtek** [comment]
@jterps08 , I cannot reproduce the issue.
When I click "RSVP" button in activity newsfeed, I am forwarded to the event detail.

can you tell which is the event did you experienced the bug?

**Comment by jterps08** [comment]
That's good enough for me. I cannot recall which event it was so I will close and retest it instead when we get a working push notifications build.
