### ISSUE TITLE
All Fundraisers/Crowdfunders should show "$0 - Ignore" option by default

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#280]
All fundraisers/crowdfunders need to include a "$0 - Ignore" option that 1) does not require credit card information to select, and 2) helps a user mark the fundraiser as answered even if they are not donating. 

Without this option, a fundraiser will continue to appear in priority zone until user makes a donation, which isn't the behavior we want.

**Comment by austinpapp** [comment]
or we add a "has read". idk if we made a `question` a mixin or parent class to inherit from but it would seem the common attribute of "has_read" or "read" would be useful here. @igaponov can we easily add that? 

imho, $0 seems awkward and ambiguous. the point here is if we have to do the work anyway, let's do this right if we can.

**Comment by jterps08** [comment]
I would prefer keeping the $0 option in place as it is currently in production and it makes it harder for a user to forget about a fundraiser. They have to select an option. I don't want them to open it, it gets marked as read, it's lost in the non-priority zone, and then we haven't helped the leader accomplish their goal. By forcing them to tap $0, they are proactively acknowledging a choice not to donate. 

I'm not sure if this is a frontend issue or a backend issue, but every fundraiser/crowdfunder should have an answer choice that allows the user to 'mark the item as answered' without donating. The language could be "**I don't want to donate. Mark as read.**" instead of "$0 - Ignore"... I just don't know how the answer choice is constructed (amount + description) vs (text only)... Not sure if this is implemented on frontend in production or backend.

**Comment by igaponov** [comment]
@austinpapp it's possible to manually mark an activity as "read" with https://api-dev.powerli.ne/api-doc#patch--api-v2-activities

**Comment by petervojtek** [comment]
ok, so I adopted following approach:
when you call JS content helper to create payment or crowdfunding, after all the payment options are added, automatically is also added a "non-payment" option with value "I don't want to donate. Mark as read."

This option is presented this way:

<img width="582" alt="screen shot 2016-10-03 at 09 01 19" src="https://cloud.githubusercontent.com/assets/225506/19029626/35c156da-8948-11e6-9876-37257986ab5c.png">

When you choose the last option and you have not yet entered your credit card info, you are not asked to fill in your credit card detail (as with the other payment options), but you can immidiately "answer", and after you confirm following screen is displayed:

<img width="803" alt="screen shot 2016-10-03 at 09 01 33" src="https://cloud.githubusercontent.com/assets/225506/19029645/65715696-8948-11e6-81fd-9dd90e7002dd.png">

@jterps08 , Please confirm if this approach is satisfactory.

**Comment by jterps08** [comment]
Absolutely satisfactory. Thank you Peter!
