### ISSUE TITLE
Payments Not Occurring on Fundraisers

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#281]
It is unclear whether or not this is a mobile app problem or a JS leader content helper problem...

User JTest1 is leader in BT2
JTest1 creates new fundraiser with answer options $1 and $5.
JTest1 publishes fundraiser.

Users Chris Minotest and 1.JesseChen receive fundraiser. 
Both Chris and 1.JesseChen select $1 option
App shows "Thank you! Your receipt: $0 - 1"

I believe this is a JS leader content helper issue. 

Neither Chris or 1.JesseChen have a CC stored on Stripe. 
If app or content-helper worked correctly, selecting $1 option would result in following behavior:
1) User would see CC entry modal with billing address pre-populated based on user profile information. 
2) User would enter Cc information and save to account. 
3) User would see payment confirmation + comment dialog. User would click "pay"
4) Receipt screen would show and payment would be processed.
5) Once CC is saved, all future payment requests would skip CC entry screen and utilize CC on file to proceed directly to payment confirmation dialog box.

**Comment by petervojtek** [comment]
@igaponov , how can I add to poll:payment answer which will be understood as payment?

here are my attempts:

```
Request URL:https://api-dev.powerli.ne/api/v2/polls/266/options
Request Method:POST
Status Code:400 Bad Request

{"payment_amount":11,"is_user_amount":true,"value":11}
or
{"payment_amount":11,"value":11}

end up with
{"code":400,"message":"Validation Failed","errors":{"errors":["This form should not contain extra fields."],"children":{"value":[]}}}
```

and when I try this:

```
Request URL:https://api-dev.powerli.ne/api/v2/polls/268/options
Request Method:POST
Status Code:400 Bad Request

{"payment_amount":11}

I end up with:
{"code":400,"message":"Validation Failed","errors":{"errors":["This form should not contain extra fields."],"children":{"value":{"errors":["This value should not be blank."]}}}}
```

**Comment by igaponov** [comment]
@petervojtek the endpoint `https://api-dev.powerli.ne/api/v2/polls/266/options` is used only to add options to a question. You should use `/api/question/{question_id}/answer/add` to add an answer. There is no new version for this endpoint in API yet. Should I add it for this issue?

**Comment by jterps08** [comment]
FYI: For fundraisers/crowdfunders, each answer choice in the poll has two components 1) the amount, and 2) the description.... It is possible that an answer choice be 'custom' in which case 1) the amount is defined by the user during the payment confirmation & comment dialog box, and 2) the description is still defined by the leader. This is working in production.

All fundraisers/crowdfunders should automatically include a "$0 - Ignore" answer choice that a user can select that does not require CC entry.

**Comment by petervojtek** [comment]
@igaponov, I am confused :(

I do not understand know what is the difference between option and answer, and the API doc for `/api/question/{question_id}/answer/add` provides no information on what should be actually submitted:

<img width="1237" alt="screen shot 2016-09-20 at 06 31 13" src="https://cloud.githubusercontent.com/assets/225506/18657585/ebd6e6ee-7efb-11e6-8724-120e832397c2.png">

unfortunately api doc is unreachable for me at the moment (This site can’t be reached).

what I want to achieve is following:
1. Create poll of type:payment via `POST /api/v2/groups/'+groupID+'/polls` - works fine.
2. add payment options to the poll:payment -- currently I am doing that via `POST /api/v2/polls/'+pollID+'/options`, which works, but later is not recognized as a payment option, but as a "text" answer -- this is what I need to change and that is why I tried to use `payment_amount` and `is_user_amount` attributes.
3. publish the poll:payment -works fine.

[The legacy code](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/controllers/payment-request.js#L34) is expecting the `payment_amount` and `is_user_amount` attributes to properly process the option/answered/whatever-is-it as payment

**Comment by jterps08** [comment]
At it's heart, this issue is about being able to create fundraisers/crowdfunders via API and accommodating the fact that every answer choice has both an **amount** and a **description** (e.g. $25 - Tshirt). The API needs to handle that. And the JS content helper needs to as well.

**Comment by igaponov** [comment]
I'm working on a new version of this endpoint.

@petervojtek a question has options. For example, "Where are you from? - A) USA, B) Russia" and you should choose one of these options in your answer: `{"option_id": "A"}`

**Comment by igaponov** [comment]
@petervojtek check new endpoint please

**Comment by petervojtek** [comment]
@igaponov , I am really confused.
I see that this new endpoint appeared: https://api-dev.powerli.ne/api-doc#put--api-v2-polls-{id}-answers-{option}

But I still do not fully undertand the relationship betwen a **poll**, an **option** and an **answer**.

I know that a poll can have an option (1:N relationship), and I can add new option to a poll via 
`POST /api/v2/polls/{id}/options`.

But I have no idea what is the purpose of the newly added endpoint:
https://api-dev.powerli.ne/api-doc#put--api-v2-polls-{id}-answers-{option}

It seems like it is designed to add an **answer** to an **option** (option:answer is 1:N relationship) via a HTTP PUT ? I cannot imagine what may be the sense of doing this..

Also I still don't know how to create an option which will be recognized as a payment. The behaviour [described here](https://github.com/PowerlineApp/powerline-mobile/issues/281#issuecomment-248001012) persists.

**Comment by jterps08** [comment]
Igor will have to answer this question, but FYI, in production, creating a fundraiser looks like this. You add an option. Each option has a description AND ('Payment Amount' OR 'User Amount Flag'). If 'Payment Amount' is defined, the option has a leader defined amount with it (e.g. "$25 - Tshirt"). If 'User Amount Flag' is checked, the option has a description only (e.g. "name your price!") and the user provides the custom amount via the frontend's payment confirmation dialog box. 
![image](https://cloud.githubusercontent.com/assets/7582457/18785371/d2f47dc8-8165-11e6-8e51-62f829bafae0.png)

(Scenario 1: Payment Amount defined by Leader for Option)
![screenshot_2016-07-19-13-10-01 1](https://cloud.githubusercontent.com/assets/7582457/18785591/0a8dfb96-8167-11e6-9303-164c988f23b5.png)

(Scenario 2: User Amount Flag checked by Leader for Option; Payment Amount defined by User)
![screenshot_2016-07-19-13-10-29 1](https://cloud.githubusercontent.com/assets/7582457/18785592/0a8f31be-8167-11e6-82b7-55d1af3d8845.png)

Hope this helps. 

@igaponov - The problem Peter is facing is that he does not know where/how to submit create an option/answer choice that includes both a description and a payment amount.  It would be helpful if you can provide example.

**Comment by igaponov** [comment]
@petervojtek 
Now `POST /api/v2/polls/{id}/options` should works with `payment_amount` and `is_user_amount`.

About answers: you should choose one option of question, then use the endpoint: `POST /api/v2/polls/[the question you want to answer]/answers/[chosen option id]`. You can also add comment/privacy/payment_amount (if option's `is_user_amount`=true)

**Comment by petervojtek** [comment]
thanks @igaponov.

ok, I successfully adjusted the JS console helper to add payment options to poll:payment and poll:crowdfunding. @jterps08, here are the helpers:
https://github.com/PowerlineApp/powerline-mobile/wiki/HOWTO-Create-leader-content-from-JS-console#to-create-pollpayment

@jterps08 , now when as an user click the payment option, in mobile app I am displayed a popup asking me for credit card details -- however I was not willing to provide my real card details :)

 Please either provide me some Stripe testing credit card details, or please test this use case.

**Comment by jterps08** [comment]
information sent via Slack... Stripe test mode activated.

**Comment by petervojtek** [comment]
@igaponov , I try to add a credit card to test Peter10's payment to poll:payment, and this is what I experience:

I successfully add the card itself (I use a [testing card number from Stripe](https://stripe.com/docs/testing)):

```
Request URL:https://api.stripe.com/v1/tokens
Request Method:POST
Status Code:200 OK

key=pk_test_QUgSE3ZhORW9yoDuCkMjnaA2&payment_user_agent=stripe.js%2F6ea8d55&card[name]=Peter10+Is+Leader&card[number]=4242424242424242&card[cvc]=345&card[exp_month]=10&card[exp_year]=2020

response:
{
  "id": "tok_18yIsrGH6acUMInAcR64GORQ",
  "object": "token",
  "card": {
    "id": "card_18yIsrGH6acUMInAcJSTk5Zm",
    "object": "card",
    "address_city": null,
    "address_country": null,
    "address_line1": null,
    "address_line1_check": null,
    "address_line2": null,
    "address_state": null,
    "address_zip": null,
    "address_zip_check": null,
    "brand": "Visa",
    "country": "US",
    "cvc_check": "unchecked",
    "dynamic_last4": null,
    "exp_month": 10,
    "exp_year": 2020,
    "funding": "credit",
    "last4": "4242",
    "metadata": {},
    "name": "Peter10 Is Leader",
    "tokenization_method": null
  },
  "client_ip": "178.143.117.23",
  "created": 1474972341,
  "livemode": false,
  "type": "card",
  "used": false
}

```

and then the next request ends up with:

```
Request URL:https://api-dev.powerli.ne/api/cards/
Request Method:POST
Status Code:500 Internal Server Error

{"source":"tok_18yIsrGH6acUMInAcR64GORQ"}

{"code":500,"message":"No such token: tok_18yIsrGH6acUMInAcR64GORQ; a similar object exists in test mode, but a live mode key was used to make this request.","errors":null}
```

I am actually not sure what is the purpose of the second api call, I only use the legacy code as is.

**Comment by jterps08** [comment]
This looks like we're trying to add or reference a token for a Stripe customer in production when the token exists in test environment... Stripe has production and test environments. I thought I 'turned on' test environment for Peter from Stripe dashboard, but it may be a parameters issue too... 

I can also try testing this with real payment ($1) later today...

Jesse

**Comment by igaponov** [comment]
Stripe credentials are changed to test ones.

**Comment by jterps08** [comment]
Give it another shot Peter and see if error generates again..

**Comment by petervojtek** [comment]
ok, this time it fails with different error:

```
Request URL:https://api-dev.powerli.ne/api/cards/
Request Method:POST
Status Code:500 Internal Server Error

{"code":500,"message":"No such customer: cus_9GqaED14RgFDHB; a similar object exists in live mode, but a test mode key was used to make this request.","errors":null}
```

btw it would be faster if Igor will go here: http://litava.eu/powerline-mobile/
1. Login there as Peter12/Peter12
2. Go to http://litava.eu/powerline-mobile/#/payment-polls/payment-request/300
3. and try to pay and observe the http/ajax errors in JS developer console :)

**Comment by igaponov** [comment]
@petervojtek this customer exists only in live mode. Try to create a new one in test mode to work with this issue.

**Comment by jterps08** [comment]
That makes sense.

**Comment by petervojtek** [comment]
@igaponov , ok, I took another user and managed to add him a card successfully.

Now I experience following:

#### poll:fundraising

for poll:fundraising I can successfully pick and payment option and proceed.
But then I experience this:

```
Request URL:https://api-dev.powerli.ne/api/answers/201/charges/
Request Method:GET
Status Code:500 Internal Server Error

{"code":500,"message":"Unrecognized field: questionId","errors":null}
```

#### For poll:payment

I cannot submit a payment option due to:

```
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/v2/polls/293/answers/472. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by igaponov** [comment]
Fixed. But Peter12 is not an author of answer#201 and will get 404 for this address.

**Comment by petervojtek** [comment]
hmm, not sure what has been fixed.. I experience this. I login as Peter31 and try pay in Poll:payment 302.

```
Request URL:https://api-dev.powerli.ne/api/v2/polls/302/answers/496
Request Method:PUT
Status Code:500 Internal Server Error

XMLHttpRequest cannot load https://api-dev.powerli.ne/api/v2/polls/302/answers/496. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

And for poll:funraising, as Peter31 I pay in poll:crowdfunding 296 successfully, but then receive:

```
Request URL:https://api-dev.powerli.ne/api/answers/209/charges/
Request Method:GET
Status Code:500 Internal Server Error

{"code":500,"message":"Unrecognized field: questionId","errors":null}
```

**Comment by igaponov** [comment]
Peter31 doesn't have permission to answer on poll 302, now you should get 403 instead of error.
For the second issue, there is another bug and I'll fix it. But you will not get charge for poll:crowdfunding, because it's not created for this type. Can see it only for non-crowdfunding payment requests.

**Comment by jterps08** [comment]
Please connect via Skype or Slack if necessary to clarify the issue here.

Crowdfunding is delayed - the system will only charge the user's card if condition is met: "pledges meet or exceed goal amount (e.g. $10) by the deadline (Friday Sept 10).... Fundraiser does not wait to charge user's card.

**Comment by igaponov** [comment]
The second call should work now

**Comment by petervojtek** [comment]
I separate the poll:payment issue here #304 so we don't mix it with crowdfunding.

**Comment by petervojtek** [comment]
and for the crowdfunding -- in the legacy code the `GET https://api-dev.powerli.ne/api/answers/209/charges/` request is made also for the crowdfunding. 

Do I understand I should not make the request?
I actually don't know what is the request's purpose and what it is supposed to return at all, there is no api doc.

**Comment by igaponov** [comment]
@petervojtek you don't need to do it for `crowdfunding`, it'll always return 404

**Comment by petervojtek** [comment]
ok, removed `charges` request for poll:crowdfunding
