### ISSUE TITLE
My Influence screen shows White Bar instead of Followers/Following tabs

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#282]
For new user only. Once a follower request is received, tabs display correctly.
For existing user, the tabs show as expected

**Comment by petervojtek** [comment]
this happens on every OS when there are no followers/followings:

<img width="359" alt="screenshot 2016-11-24 08 54 29" src="https://cloud.githubusercontent.com/assets/225506/20590501/b4407b72-b223-11e6-8af7-5c0345e452b6.png">

**Comment by petervojtek** [comment]
done
