### ISSUE TITLE
New Group Creation Form - Remove "Username"

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#292]
Per https://github.com/PowerlineApp/powerline-server/issues/207, I do not think we need to provide "username" as part of the new group creation process from the frontend.

It would be better if system auto-creates group username based on the provided "group name" (e.g. SaveTheWhales-3) on the backend rather than asking the user to enter this during group creation process.

**Comment by austinpapp** [comment]
This really shouldn't be needed as the user who created the group should be allowed the appropriate access to do leader/owner actions when they navigate to the group. 

Igor should remove any ties to this.

**Comment by jterps08** [comment]
True, but we may need the username as the thing that we use in the URL routing for the web app

**Comment by jterps08** [comment]
@igaponov - Can you make it so that group usernames are auto-created by the backend via some standardized process? For example, maybe slugify the group name and append number as needed (e.g. SaveTheWhale35). 

We would want to provide group owners with the ability to update the group name later as it will be an important part of URL routing / permalinks strategy once implemented (e.g. www.powerli.ne/s/WeLoveWhales may be a more preferable address for the group than www.powerli.ne/s/SaveTheWhales35)... 

I basically don't want the group creator to need to provide a group username as part of the registration process, but I want them to be able to change it later.

**Comment by igaponov** [comment]
@jterps08 why do you want to add a number? To make it unique?

**Comment by jterps08** [comment]
Yes - My assumption is that we will have many groups with the same name... The number is added only if needed... Thoughts?

**Comment by igaponov** [comment]
@jterps08 it make sense.

**Comment by austinpapp** [comment]
URL routing would be the group name and not the group username. Again. I fail to understand the purpose of username now. It was used to login when we did not have owner/manager username tied to the group.

**Comment by jterps08** [comment]
URL Routing could not be the group name. I think the confusion is the field name/label 'username'...

For the moment, forget about using a username to login anywhere... We can change the field name from username to 'nickname' if we want. It's the field content that I'm focused on. Here's an example:

**Group 1**
Group Name (Visible to Group Members): Save the Whales of North Long Branch
Group Description (Visible to Group Member): We are a group of North Long Branch citizens who care about Whales of all kinds in _New Jersey_.
Group Acronym (Visible to Group Member): STW
Group Type (Visible to Group Member, Impacts Subscriptions): Non-Profit (Non-Campaign)
Group Username (Not Visible to Group Member, initially auto-populated by system based on group name, but visible/modifiable by group owner): SaveTheWhalesOfNorthLongBranch

VERSUS

**Group 2**
Group #2 Name (Visible to Group Members): Save the Whales of North Long Branch
Group #2 Description (Visible to Group Member): We are a group of North Long Branch citizens who care about Whales of all kinds in _Dodge City, Kansas_
Group #2 Acronym (Visible to Group Member): STW
Group #2 Type (Visible to Group Member, Impacts Subscriptions): Non-Profit (Non-Campaign)
Group #2 Username (Not Visible to Group Member, initially auto-populated by system based on group name, but visible/modifiable by group owner): SaveTheWhalesOfNorthLongBranch33

In URL Routing situation, www.powerli.ne/s/SaveTheWhalesOfNorthLongBranch is longgg. In the future, we want to give the group owner the ability to change this username/nickname/slug/whatever-you-want-to-call-it to "WeLoveWhalesNJ" which would make the URL for group 1 above to be www.powerli.ne/s/WeLoveWhalesNJ instead...

If we want to rename the field to reduce confusion, that's fine... We just need _some_ dedicated field specifically for storing/modifying the URL routing extension... The system should automatically create this username/nickname/slug and it should support allowing the group owner to change it later.

In the future this slug may be used for @mentions of groups (which would notify all group leadership), too...

**Comment by igaponov** [comment]
@austinpapp @jterps08 lets add a column `slug` and remove username in the future.

**Comment by igaponov** [comment]
@jterps08 column `slug` is added

**Comment by jterps08** [comment]
@igaponov does the backend auto-fill this column when a new group is registered? If so, I think we are finally good to remove 'username' field from the new group creation form on the mobile app @petervojtek

**Comment by igaponov** [comment]
@jterps08 yes, it does. Fills with "official-name-12345...". Should I remove group's username on backend?

**Comment by jterps08** [comment]
Great thanks, Igor. Yes, I think we should remove the group's username. It's no longer used anywhere else. Just make it a separate commit so that we can easily reverse it if it breaks something...

**Comment by igaponov** [comment]
Group's username is removed on backend

**Comment by petervojtek** [comment]
ok, username is gone in frontend as well
