### ISSUE TITLE
Convert dates to UTC timezone

### ISSUE THREAD

**Issue by igaponov** [PowerlineApp/powerline-mobile#293]
All dates are sent to the server must be converted from user's timezone to UTC timezone.
All dates are received from the server must be converted to user's timezone from UTC.

**Comment by austinpapp** [comment]
are these dates being stored in database or are they called from a date class (in code)?

**Comment by austinpapp** [comment]
1. are dates stored UTC or US/Eastern ?
2. are we localizing at the frontend or API ?

**Comment by igaponov** [comment]
@austinpapp 
0. Database
1. UTC
2. Only frontend knows user's timezone. Backend works with UTC.

**Comment by austinpapp** [comment]
Ah. Ok I get what is happening now. Last questions.

Are we expecting tzinfo to always be passed with the day time object? We need to make that clear in docs if we require it.

**Comment by igaponov** [comment]
@austinpapp we can use any date format, but tz always must be UTC

**Comment by petervojtek** [comment]
this issue was fixed to some extent, when creating event and fundraiser, the datetimes are converted to UTC before submitting to server, and convert from utc to local time when getting datetimes from server. #348, #344,

**Comment by jterps08** [comment]
Closing for now
