### ISSUE TITLE
Cannot add comment to poll:event due to No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#296]
```
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/poll/205/comments/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by jterps08** [comment]
why does this access control issue keep coming up?

**Comment by igaponov** [comment]
There was a problem with deploy, now it works. But you shouldn't use this endpoint, it's deprecated.

**Comment by petervojtek** [comment]
@igaponov, it is still not working:

```
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/poll/205/comments/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

the mobile app is still using several v1 endpoints -- they are in the legacy code and when they do work, I have not spent time switching them to v2 (it may be time consuming) -- when you will tell me that I should stop using some particular v1 endpoint and turn to v2, I will do that, but in general I want to avoid switching all api calls to v2 due to lack of time.

**Comment by petervojtek** [comment]
ok, works now.
