### ISSUE TITLE
date picker in profile (date of birth) is not working

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#297]

**Comment by jterps08** [comment]
I understand the issue... Just marking this comment here.

Related: Per your previous feedback and suggestion @petervojtek, I think that we will move DOB out of the registration process and into some pop-up that the user gets in their first week of having the app. It can be replaced with a "I am 13 or older checkbox" in registration. We'll also want to pre-populate the phone field with the device number...

**Comment by petervojtek** [comment]
it was easy to fix it (only needed to install the proper cordova plugin), so I fixed the existing behaviour.
