### ISSUE TITLE
Push notifications on Android: no notification on group permissions changes

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#300]
I have android where I successfully receive other push notifications.
1. user `peter.vojtek` is member of group 310.
2. leader of the group adjusts permissions to the group.
3. user `peter.vojtek` will not receive push notification to his phone.

also the `/dev/shm/powerline/logs/push_dev.log` seems to miss the notification.

from #226:

> Group Permissions Changed: Main Avatar (Group Avatar), Small Avatar (Powerline logo), Title("GroupName"), Message ("GroupName has changed the information it is asking for from you as a group member. Open to learn more."). Buttons: Open, Ignore.

**Comment by petervojtek** [comment]
I cannot see any notification to appear in `/dev/shm/powerline/logs/push_dev.log`.

I did the same steps as above.

**Comment by igaponov** [comment]
@petervojtek 
First, I see only social activities and pushes that I received yesterday when tested this bug.
Second, if you don't see social activity for this action, there will be no push notification.
Third, this notification is sent only when you **ADD MORE** permissions, not when you delete them.

**Comment by jterps08** [comment]
@igaponov "Third, this notification is sent only when you ADD MORE permissions, not when you delete them." I didn't know this, but of course this makes sense and is acceptable.

@petervojtek try adding permissions, not removing to test...

**Comment by igaponov** [comment]
@jterps08 it was like this in the old code, I didn't change.

**Comment by jterps08** [comment]
That works for me

**Comment by petervojtek** [comment]
ok, I took group 310, where permissions were: `email`, and changed it to `email, name`.

and - nothing appears in `/dev/shm/powerline/logs/push_dev.log`

but the social activity is there:

<img width="307" alt="screen shot 2016-09-27 at 19 11 52" src="https://cloud.githubusercontent.com/assets/225506/18884094/4b647b68-84e6-11e6-9c59-82cc0a1ad963.png">

**Comment by igaponov** [comment]
fixed

**Comment by petervojtek** [comment]
ok, it works.
