### ISSUE TITLE
Push notification text on UserPetition comment is probably wrong

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#301]
There is User Petition 257 created by `peter.vojtek`. When Peter10 adds comment to it, this is how the push notification looks for the UserPetition author:

<img width="311" alt="screen shot 2016-09-27 at 07 19 46" src="https://cloud.githubusercontent.com/assets/225506/18861118/1544bfec-8483-11e6-9e43-6c967f1e3616.png">
#226 says that:

> Author Notifications (For comments [all items], upvotes [posts only], and signatures [petitions only]): Main Avatar (Commenter/Voter Avatar), Small Avatar (Powerline logo), Title ("FirstName LastName"), Message("commented on your post") OR ("voted on your post") (or 'petition' for petitions). Buttons: View, Mute.

Please confirm @jterps08 first that this is not an intention, but a bug.

**Comment by jterps08** [comment]
This is fine. Closing. 

https://github.com/PowerlineApp/powerline-mobile/issues/238
The scenario is scenario 3. As long as the comment was 'test 6' we're good to go

**Comment by petervojtek** [comment]
yes, the comment text is correct.
