### ISSUE TITLE
Push notifications: confirm notification is sent after Post is boosted

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#302]
from #226:

> Boosted Post: Main Avatar (Post Author Avatar), Small Avatar (Powerline logo), Title ("FirstName in GroupName", Message("Boosted Post: PostText) where PostText is up to 300 characters long (minus 14 characters for "Boosted Post: "). Buttons: Upvote, Downvote
> 
> If it's a small group of people (less than 10), the boosting level of the group should be 10%. If not, we should have a group setting endpoint that allows the group creator or managers to set it to 10%. (all group settings should be accessible via endpoints now)...
> 
> If the boosting level is 10% in a group of 10 people, only 1 person is needed to upvote an item in order for it to be boosted to all 10. Same with 1 person out of a 3 person group.
> 
> There should also be an endpoint that allows a group creator/manager to manually boost a particular post/petition in a group. I'm not sure if that endpoint exists, but it's something that was part of the old admin.powerli.ne bundle that should have its own endpoint now...

**Comment by jterps08** [comment]
If you cannot test with automatic boosting, you may need Igor to help you figure out manual boosting for a user post or user petition.

**Comment by petervojtek** [comment]
@jterps08 , it is not clear to me - who should receive the Post is boosted push notification?
The group members?

And if the Post becames boosted "naturally", i.e. via upvotes, on every upvote the author will receive "voted on your post" push notification -- in such case do you want the author to receive aso second notification that the post is boosted? (they will arrive at the sime time)

**Comment by jterps08** [comment]
Good questions...

Everyone receives a push notification when a post is boosted. That's key to something being 'boosted' - the point is to bring everyone's attention to the item. (Consider this: when a leader posts something, everyone gets a notification. The leader can 'reach' all group members. When a group member's item becomes boosted, everyone gets a notification. The group member can 'reach' all group members, but only if he got enough support for it to be boosted).

The author will receive the upvote notifier every single time (unless they mute their notifications), and the author should receive the notification that the post/userpetition is boosted. When the two last notifications compete (that someone upvoted the post and that upvote is what made something get boosted, the author should receive the boosted post - that's higher priority. Let me know if that's clear.

**Comment by petervojtek** [comment]
@jterps08 , I experience following behaviour regarding boosted Post:

There is group `Peter10Group7` with 4 members.

as `peter.vojtek` I created a Post in the group.

Now as `Peter31` who is also member of the group `Peter10Group7` I see the following activity related to the Post in newsfeed:

```
{"zone":"prioritized","id":718,"title":"","description":"Post 1 to test boosting","description_html":"Post 1 to test boosting","sent_at":"2016-09-29T07:35:20.000Z","expire_at":"2016-10-01T07:35:20.000Z","responses_count":0,"owner":{"id":78,"type":"user","official_title":"","first_name":"Pavlik","last_name":"Morozov","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/57a2d7d76088f.jpeg"},"user":{"full_name":"Pavlik Morozov","id":78,"type":"user","official_title":"Pavlik Morozov","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/57a2d7d76088f.jpeg"},"entity":{"type":"post","id":314,"group_id":312},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-29T07:35:20+0000","poll":null,"user_petition":null,"post":{"is_subscribed":false},"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":0,"answers":[],"quorum":0}
```

As you can see, the Post is immidiately in "zone":"prioritized".  No-one voted for the Post yet so I am not sure if this is corrent behaviour or not.

When I enter Post detail, I see that it has `"boosted":true`:

```
{"quorum_count":0,"share_picture":null,"answers":[],"is_subscribed":true,"id":314,"body":"Post 1 to test boosting","html_body":"Post 1 to test boosting","group":{"total_members":4,"id":312,"type":"group","group_type":0,"username":"Peter10Group7","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","manager_first_name":"Peter10","manager_last_name":"Peter10","manager_email":"peter10@test.com","manager_phone":"+1123","official_title":"Peter10Group7","official_description":"Peter10Group7","acronym":"10G7","official_type":"Non-Profit (Not Campaign)","official_address":null,"official_city":null,"official_state":null,"joined":1,"picture":null,"created_at":"Wed, 27 Jul 2016 12:44:56 +0000","petition_percent":null,"petition_duration":null,"membership_control":"public","fill_fields_required":false,"petition_per_month":5,"required_permissions":[],"permissions_changed_at":null,"group":null,"token":null},"created_at":"Thu, 29 Sep 2016 07:35:20 +0000","expired_at":"Sat, 01 Oct 2016 07:35:20 +0000","user_expire_interval":2,"user":{"full_name":"Pavlik Morozov","id":78,"type":"user","username":"peter.vojtek","first_name":"Pavlik","last_name":"Morozov","official_title":"Pavlik Morozov","email":"petervojtek@gmail.com","zip":"082 12","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/57a2d7d76088f.jpeg","birth":"01\/04\/1977","address1":"san diego","address2":"11","city":"San Diego","state":"CA","country":"US","phone":"111","facebook_link":"https:\/\/www.facebook.com\/app_scoped_user_id\/309106456096856\/","twitter_link":null,"race":null,"sex":"Male","orientation":null,"marital_status":null,"religion":null,"employment_status":null,"income_level":null,"education_level":null,"party":null,"philosophy":null,"donor":null,"bio":null,"slogan":null,"interests":[],"registration":null,"token":"39r2dburxfqcocg404ko8okkc8sc4s4gcs0s0c4cgg04gssw0g78","facebook_id":"309106456096856","ios_device":null,"android_device":null,"do_not_disturb":false,"is_notif_questions":true,"is_notif_discussions":true,"is_notif_messages":true,"is_notif_micro_following":true,"is_notif_micro_group":true,"is_notif_scheduled":false,"is_notif_own_post_changed":true,"scheduled_from":null,"scheduled_to":null,"is_registration_complete":true,"plain_password":null},"boosted":true,"votes":[],"cached_hash_tags":[],"metadata":{"title":null,"description":null,"image":null,"url":null}}
```

Since the Post was created the server generated no push notification related to it (in `/dev/shm/powerline/logs/push_dev.log`)

**Comment by jterps08** [comment]
"As you can see, the Post is immidiately in "zone":"prioritized". No-one voted for the Post yet so I am not sure if this is corrent behaviour or not." -- This is _incorrect_ behavior. New posts and user petitions are NOT boosted until they have hit quorum. I have reported this in a separate issue and thought it was closed.

https://github.com/PowerlineApp/powerline-mobile/issues/268

It is not closed. This is still an issue.

Let's distinguish between the scenarios:

1) Post/UserPetition created by Group Member - Notification delivered to the author's followers. No priority zone for Newsfeed (no red dot, no counter, etc.). The Social Activity Feed shows the update as Someone posted in X group (or similar) for the author's followers only. 
2) Post/UserPetition boosted in a Group - Notification delivered to all group members. Priority zone for newsfeed. Boosting depends on the number of people who upvoted the post relative to the number of group members (check out how this works correctly in production).

**Comment by petervojtek** [comment]
hmm, so I guess we are blocked here by #268

**Comment by petervojtek** [comment]
I confirm  boosted push notification is sent after Post or user Petition is (naturally) boosted.
