### ISSUE TITLE
Leader content creation: Add form to create poll:poll (= Question)

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#309]

**Comment by petervojtek** [comment]
@jterps08 , I created simple form to add new Poll (question), it looks like this:

<img width="707" alt="screen shot 2016-10-04 at 12 58 51" src="https://cloud.githubusercontent.com/assets/225506/19071820/5390f7d4-8a32-11e6-826e-0571e322a654.png">

<img width="855" alt="screen shot 2016-10-04 at 12 47 53" src="https://cloud.githubusercontent.com/assets/225506/19071795/2b902eda-8a32-11e6-8ed3-b4349ecaa3b6.png">

It is fully working, but I need help from backend with following use case:

On first screen, the "Make a poll" option in top right corner should be visible only when following conditions are met:
- when some particual group is selected in Activity newsfeed, and the user has right to create poll there (i.e. is leader or owner)
- or, when no group is selected in Activity newsfeed, and there exists at least one group where the user is allowed to create poll.

Currently there exists [`GET /api/groups/is-manager/{id}`](https://api-dev.powerli.ne/api-doc#get--api-groups-is-manager-{id}) api call which can tell if the current user is manager of a particual group or not, however this is not effective approach, because I would rather know that information in bulk for all the groups the user is member of (because in the second screenshot you can pick from list of groups and it would be innefective to make http request for each group to find out if user can create there poll or not).

Therefore my suggestion is to enrich [`GET /api/v2/user/groups`](https://api-dev.powerli.ne/api-doc#get--api-v2-user-groups) so that it also provides information whether user is manager/owner of the group. I already make request to `GET /api/v2/user/groups` to get the list of groups to display in activity newsfeed filter so I will get it almost for free. However this requires Igor to adjust the endpoint and that is why I leave this to you to decide when is the proper time to assign him this task.

This `GET /api/v2/user/groups` is relevant also for all other create-leader-content forms.

Currently to make sure regular users are not misleaded with the leader content options, the "Make a poll" option is available only to user `Peter10` and `JTest1`.

The form itself is missing following features:
- in design there is some picker with name "Sent To: All group members". Not sure what are the other options
- add attachments 
- it seems I miss there title or subject.

**Comment by jterps08** [comment]
Thanks Peter... 

1) I agree with your endpoint enhancement suggestion. Igor can do it _after_ he has done P1/P2 bug fix work. 
2) "Sent to: All Group Members" - This relates to "group divisions". A group leader can create subgroups in his group and assign users to those subgroups (e.g. Save the Whales might have "Members" vs "Donors" vs "Volunteers"). I do not know if group divisions have an endpoint. If they do, we need to provide the user with Sent to: All/Division1/Division2/etc... If we do not have divisions, simply create a field that says "Sent to: " with dropdown, only option "All Group Members" by default. 
3) Adding attachments is adding video link or picture to the item. Picture is a file. video is a hyperlink. 
4) Polls don't use title/subject... Events, Petitions, and Fundraisers have title/subject.

**Comment by petervojtek** [comment]
@jterps08 

> 4) Polls don't use title/subject... Events, Petitions, and Fundraisers have title/subject.

what puzzles me is  the text area on bottom here with text "it is along established..".. I thought that that is meant to be poll subject, but it is rather an attachment of type:text ?

<img width="297" alt="screen shot 2016-10-04 at 13 54 04" src="https://cloud.githubusercontent.com/assets/225506/19073222/2393fb64-8a3a-11e6-9f91-8396350a5b93.png">

**Comment by jterps08** [comment]
Correct, it attachment type text. You can ignore that for the sake of creating the form. We'll limit what the user can add on the mobile app to a poll vs what they can add on the web app..

Also, let's stick with "New Group" phraseology... this way people get the sense that it goes out to all group members. We'll probably want to put an alert between the Submit button and the actual publish action that warns the user "You are about to send this to all X group members. Are you sure?" where X is the number of group members...

New Group Poll
New Group Petition
New Group Discussion
New Group Event
New Group Fundraiser
New Group Crowdfunder
New Group Announcement

**Comment by petervojtek** [comment]
@jterps08 , there does not seem to be API endpoint to create subgroups, maybe @igaponov can correct me.

from UX point of view I personally find it confusing if there will be select box with only one option:

> field that says "Sent to: " with dropdown, only option "All Group Members" by default. 

---

> We'll probably want to put an alert between the Submit button and the actual publish action that warns the user "You are about to send this to all X group members. 

ok, I will add it there.

**Comment by igaponov** [comment]
@petervojtek yes, you can't create subgroups.

**Comment by jterps08** [comment]
@igaponov group divisions is part of frontbundle functionality that needs to be available as API endpoint. Create/delete group division(s), name/rename group division(s), assign/remove users to (potentially multiple) group divisions... This is low priority compared to notifications or anything relating to Peter's questions.

**Comment by petervojtek** [comment]
I split this issue to smaller ones and close this one
