### ISSUE TITLE
Registration ZipCode / First E-mail Address Field Error

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#31]
User enters account information on page 1 of registration successfully.
Next.
User enters contact information on page 2. User's address fields are "auto-filled" correctly with Google assistance for street address field.
User enters remaining required information correctly.
User taps "register" - error thrown for Zipcode and first e-mail address fields "Correct the errors and try again" (but no error exists).

User unable to complete registration

**Comment by luckydevstar** [comment]
This error is related by cordova plugin issue. this issue is passed with beta testing. (using apk)
