### ISSUE TITLE
Investigate: "Peter10 commented on a post you subscribed to"

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#310]
I got a notification on my Android 5 device this morning "Peter10 commented on a post you subscribed to" -- I have a feeling this is a bug. Either an old message that is stuck in the queue OR I'm being subscribed to posts I did not actuallly subscribe to OR the system is notifying me of anytime Peter10 comments on something even though it should only notify me when Peter10 comments on something I subscribed to

I could not find a post that Peter10 had commented on this morning. Peter did you use the Peter10 account over the last 12 hours in testing?

I cannot determine which item this actually refers to. It may require some investigation. I am logged in with the 1.JesseChen account

**Comment by petervojtek** [comment]
@jterps08 , I use the Peter10 account almost all the time.

it will be fairly time consuming to sort out what happened.
next time it would be useful if you could click the View button on push notification to find out which Post id it was. I searched the server logs for string "commented on a post you subscribed to" but found no matches (maybe the text is slightly different?).

**Comment by jterps08** [comment]
Yeah, I clicked view. It did not open the item... :-/ 

I will look out for it again...

**Comment by petervojtek** [comment]
@jterps08 , ok, i such case please keep track if the time when you received the push notification so that we can try to locate it in logs..

**Comment by jterps08** [comment]
I will... challenge is that I am waking up to them after turning off
airplane mode.   Will try.

**Comment by petervojtek** [comment]
@igaponov , we have following bug:
1. User Peter10 adds comment to user petiiton 272
2. user '1.JesseChen' receives following push notification "Peter10 commented on a post you subscribed to" - but he is not subscribed to the user petition nor is its author.

user 1.JesseChen should not receive such notification.
