### ISSUE TITLE
Create Leader Content Forms

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#311]
this is a master issue for all the sub-issue related to forms to create Leader content from mobile app.

sub tasks:
- DONE: create poll: #309
- DONE: create announcement
- DONE: create news: #343
- DONE: create petition #346
- DONE: create event: #344
- DONE: create poll:payment: #312
- DONE: create poll:crowdfunding: #313 
- add attachments when creating leader content: #338
- DONE: handle group divisions: #414
- DONE: show only groups where user can create leader content: #345

**Comment by petervojtek** [comment]
all the forms are created and working. the remaining tasks related to this master-task have lower priority.

**Comment by jterps08** [comment]
:+1: That works - can't wait to test :-)
