### ISSUE TITLE
iOS push notifications: user name and action buttons not displayed in notification 

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#314]
as user 'Beata Dubasova'  I receive this notification that Peter10 commented my Post 320:

```
{"title":"Peter10 Is Leader","sound":"default","image":"http://powerline-dev.imgix.net/avatars/577cb68e6f276.jpeg?dpr=0.75&h=400&ixlib=php-1.1.0&w=320","message":" commented on your post","additionalData":{"type":"own-post-commented","foreground":false,"coldstart":false,"entity":"{\"id\":1923,\"target\":{\"id\":320,\"preview\":\"c1\",\"type\":\"post\",\"label\":\"post\",\"comment_id\":675}}"}}
```

the notification does not display username and has no buttons:

![img_0010](https://cloud.githubusercontent.com/assets/225506/19119368/d6371c02-8b1f-11e6-9613-124080d1147e.PNG)

**Comment by petervojtek** [comment]
ok, title is fixed.

I have to adopt the button callbacks
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-1

**Comment by petervojtek** [comment]
@igaponov , I inspected the push notification buttons and we need to do following:

currently the push notification looks like (this is probably content of the `alert` attribute as I don't see the whole notification content):

```
{"title":"Peter10 Is Leader","sound":"default","image":"http://powerline-dev.imgix.net/avatars/577cb68e6f276.jpeg?dpr=0.75&h=400&ixlib=php-1.1.0&w=320","message":" commented on your post","additionalData":{"type":"own-post-commented","foreground":false,"coldstart":false,"entity":"{\"id\":1939,\"target\":{\"id\":320,\"preview\":\"c9\",\"type\":\"post\",\"label\":\"post\",\"comment_id\":683}}"}}
```

however to successfully recognize the notification type (and thus display proper buttons), it should [contain the category attribute](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-1):

```
{
    "aps": {
        "alert": <notification content as above>,
        "category": <notification-type-as-string>
    },
}
```

in the particular push notification above the you should set`"category":"own-post-commented"`.

 I only guess you are currently not doing it, because I attached a handler to `"category":"own-post-commented"` with some buttons and they do not appear.

**Comment by igaponov** [comment]
`category` was added

**Comment by petervojtek** [comment]
@igaponov , are you sure you add the category?

e.g., when I send from amazon aws following message:

```
{
"APNS_SANDBOX":"{\"aps\":{\"alert\":\"hi\", \"category\":\"own-post-commented\"}}"
}
```

I successfully see on the push notification the buttons I defined for `own-post-commented`.

However when I trigger the push notification from powerline, I see that it is generated and it arrives to phone, but the buttons are not displayed. I cannot see the whole message, I see only the `alert` part of it, and thus I am not sure if you attach the `own-post-commented` value to `category` attribute the same way as in example above.

```
[2016-10-07 07:06:32] push.DEBUG: Message is pushed {"title":"Peter10 Is Leader","message":" commented on your post","type":"own-post-commented","entityData":{"id":1995,"target":{"id":326,"preview":"c2","type":"post","label":"post","comment_id":708}},"image":"http://powerline-dev.imgix.net/avatars/577cb68e6f276.jpeg?dpr=0.75&h=400&ixlib=php-1.1.0&w=320","token":"f0d9d1d26e973f74bcf8b9fddacec0fa509c1c5d080d8c633b5299750f56164b","arn":"arn:aws:sns:us-east-1:863632456175:endpoint/APNS_SANDBOX/poweline_ios_dev/60aee855-8435-3b41-8aae-cd368262daad","user":{"id":86,"username":"test3"}} []

```

ALSO:

the push notification title is not displayed ("Powerline" text is there instead).

This is how I achieve to have my own title on iOS push notification:

```
{
"APNS_SANDBOX":"{\"aps\":{\"alert\":{\"title\":\"title text\", \"body\":\"body text\"}, \"badge\":10}}"
}
```

![img_0016](https://cloud.githubusercontent.com/assets/225506/19183312/004b5cb6-8c78-11e6-9037-ade8b4350758.PNG)

**Comment by jterps08** [comment]
unable to test

**Comment by petervojtek** [comment]
btw - this is currert bahaviour.

When then notification arrives, it looks like this (i.e. app name is in the title)

![img_0025](https://cloud.githubusercontent.com/assets/225506/19228641/7b5a4cb8-8ec7-11e6-953b-d78c9cd3dc68.PNG)

And when you later check the notification area, it looks like this (i.e. our custom title is set at title):

![img_0026](https://cloud.githubusercontent.com/assets/225506/19228651/85580818-8ec7-11e6-96e3-3fa3fe9b69d4.PNG)

This seems the be the way how Apple wants to have it and also other people [confirm this behaviour](http://stackoverflow.com/a/34029734/4606227). I think it is fine from UX point of view, the only drawback we have is that in the first case the message sentence is weird.

This could be fixed by changing the msg body texts from "commented to the petition you subscribed to" to passive style like "New comment on petition you subscribed to."

I keep this up to @jterps08 also due to the fact that he was unable to receive th enotification at all.

**Comment by jterps08** [comment]
Let's leave the language the way it is now. I just want to get the notifications. We can change the backend language for iPhone later...

**Comment by petervojtek** [comment]
ok, so then I receive the push notifications and the title and buttons are visible, so I close this issue. let's treat the problem that @jterps08 is not receiving the notifications in other issue
