### ISSUE TITLE
android: push notification not arrives when user petition commented/signed

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#315]
as `peter.vojtek`, I am registered on Android to push notification with id `c5Nieq14mXk:APA91bEhdox0L2c8B4hHbVzgUUn1tSi-8WQ6slc4rWAvQW7-SwLpuvYz4jPsGkLR-Yqii5uolbs1Lp_7WJVlijWkF-lSsRZmvzYyYQItpEpRjhrnKWW7z3ZUz8SmsFgGDxeUFV_dZs23`

as `peter.vojtek`  I created UserPetition 274.

As Peter10 I add there a comment.

The server logs shows that push notification was generated:

```
[2016-10-06 08:24:43] push.DEBUG: Message is pushed {"title":"Peter10 Is Leader","message":" commented on your petition","type":"own-user-petition-commented","entityData":{"id":1979,"target":{"id":274,"preview":"c1","type":"user-petition","label":"petition","comment_id":205}},"image":"http://powerline-dev.imgix.net/avatars/577cb68e6f276.jpeg?dpr=0.75&h=400&ixlib=php-1.1.0&w=320","token":"eUpS2omGdCM:APA91bEkuVGtKl4Nf10v-7iSoAvmg5K2aQlv5rec-9p5CwOEY1IrQ8JsaKRfjNP-74WYQ8bzq41ilOk9A_gWHpT_tkAsvZZnGnea4O05fgZy_ip2T50iouGvt8KVkrDufVxIorBb1i-c","arn":"arn:aws:sns:us-east-1:863632456175:endpoint/GCM/powerline_android_dev/5c17c7bd-12a1-3bc5-bea0-702b3625324e","user":{"id":78,"username":"peter.vojtek"}} []

```

but the notification has not arrived to phone.

the same happens (no push notification arrives to peter.vojtek) when Peter10 signs to the petition, but other group members receive push notification with text "Boosted: test 44"

in general the problem is -- we will face plenty of such bugs in future. without the ability to trace the push notification lifecycle through all the push notification infrastructure, we will be unable to determine what is going on :(

**Comment by igaponov** [comment]
@petervojtek `push_dev.log` gives you ability to trace a notification to SNS. If the text is `Message is pushed` message was successfully sent to SNS, so now you need to trace it with another instrument, I can't do anything here. We have an email powerlinefailures@gmail.com where you can see errors from SNS, but i don't see any today. Maybe something wrong with your client?

**Comment by petervojtek** [comment]
> Maybe something wrong with your client?

well, that is the issue -- how can I detect that is "something wrong my client" ?

the workflow of the push message is following:
1. it is generated on powerline server and I can see such message`push_dev.log` 
2. then the notification is handled by amazon servers and delivered (or not) -- and this stage is complete blackbox to me with no option to see inside, so this is where I would like to search for what is wrong with my client. Does it has some logs, or some ability to trace a particular push message?

for me it will be useful if I could use this:
http://www.pushwatch.com/gcm/

to produce push messages on my own.
However for android I need to provide there some API Key.

**Comment by jterps08** [comment]
I messaged you in Slack @petervojtek ... Not sure if I gave you the right access for AWS or GCM, but I tried. Let me know...

**Comment by petervojtek** [comment]
ok, the issue is fixed. it was my fault, because i have not properly registered the device token.
