### ISSUE TITLE
iOS Notifications not delivered on iPhone 6

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#316]
Tried to use Jon Stamos account. Did not work. 
Then I registered user christophermino9 registered via Facebook. 

Neither resulted in:
- Event notification
- Leader Petition notification
- Crowdfunder notification, unable to test Fundraiser due to 500 issue (might be related to the fact that BT3 group does not have bank account info setup, in which case the same error should occur for Crowdfunders, not just Fundraisers)
- Announcement notification (believe this is a contentHelper issue)
- Poll notification
- New post or user petition by followed user (Android and iOS)

I am grouping these together because it seems like it's all one issue, but we can split out if needed.

**Comment by petervojtek** [comment]
@jterps08 , I do not understand if you received no notification at all, or you do not received notifications only for the use cases and for the other you did.

currently the [AWS console](https://console.aws.amazon.com/sns/v2/home?region=us-east-1#/applications/arn:aws:sns:us-east-1:863632456175:app/APNS_SANDBOX/poweline_ios_dev) shows only one iOS device successfully registered, which is my iPhone.

**Comment by petervojtek** [comment]
currently the AWS console shows only one iOS device successfully registered, which is my iPhone:

<img width="996" alt="screen shot 2016-10-10 at 10 51 47" src="https://cloud.githubusercontent.com/assets/225506/19230958/a0dc0cbe-8ed7-11e6-8c7e-91ae7b3c30bc.png">

**Comment by jterps08** [comment]
@petervojtek - I did not receive notifications at all. I tested those scenarios specifically and they failed. 

I downloaded the iOS build to my friend's phone using the Diawi build you provided in Slack. Tried using an existing user, logged out, registered a new user (with Facebook), no notifications... Based on what you're saying, it looks like his phone never registered for notifications.

**Comment by petervojtek** [comment]
@jterps08 , the reason is here: #328
