### ISSUE TITLE
Adding CC to User's Profile Results in Server Error

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#317]
BT3 group leader created crowdfunder, could not create fundraiser
BT3 group did not have bank account info setup (explains why fundraiser couldn't be created)
Published crowdfunder arrived on Android and iOS
Tapping an answer choice resulted in CC entry modal popup. 
User submitted real CC information. Server Error.
User submitted test CC information. Server Error.

User visits Settings screen to manually add CC info.
User submitted test CC information. No server Error. No CC shown as added.

**Comment by petervojtek** [comment]
@jterps08 , I do not understand this sentence:
> BT3 group leader created crowdfunder, could not create fundraiser

what is the difference between `crowdfunder` and `fundraiser` ?

**Comment by petervojtek** [comment]
@jterps08 , I confirm the above. 
regargind errors while adding CC, it seems to be backend issue, see comment below.

regarding this:

> could not create fundraiser

it is an feature (to return error 500) because of:

> "You must have a Stripe account to create a payment request.

more info here:
https://github.com/PowerlineApp/powerline-mobile/issues/304#issuecomment-251304263

**Comment by petervojtek** [comment]
@igaponov, as user `test3` I try to add myself a credit card.
 The former business logic containts following http request and currently it ends up with error 404:

```
GET https://api-dev.powerli.ne/api/cards/

Failed to load resource: the server responded with a status of 404 (Not Found)

{
    "code": 404,
    "message": "No route found for \"GET /api/cards/\"",
    "errors": null
}
```

it must have been working cca 1 week ago, when I was able to pay successfully.

**Comment by igaponov** [comment]
Should work now, but this endpoint is deprecated, I've updated api doc.

**Comment by petervojtek** [comment]
ok, I switched to v2 and now can successfully add CC.

**Comment by petervojtek** [comment]
@jterps08 , regarding the issue with creating a fundraiser, I already work on leader form to create fundraiser (#312) so that we will treat it there.
