### ISSUE TITLE
Facebook Registration - Address Entry

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#318]
When a user registers with Facebook for the first time, they still need to provide their address. The second screen of the e-mail registration flow (showing address + DOB + phone number fields) should be displayed to user. 

On iOS, the user is clicking the REgister with Facebook button and is being brought to their user profile screen instead of two the "Address" screen from the registration flow. The user should be brought to the Address screen.

Same behavior should apply on Android, but unable to test on Android. 

Since we're working on this screen anyway, we should replace the DOB field with an "I am 13 or older" checkbox (do not allow users less than 13 to register). We should also remove Phone Number field from this screen for the time being.

**Comment by petervojtek** [comment]
> The second screen of the e-mail registration flow (showing address + DOB + phone number fields) should be displayed to user.

@jterps08 , it will be time consuming to display the "2nd screen from registration process" because the code was not written to be used that way.

It will be much less time consuming if we e.g. display the profile for facebook newcomer as we do it now, but the it will be already open in Edit mode and the Contact section will be expanded.

**Comment by jterps08** [comment]
I'm not sure how I feel about this. I feel like going directly to Profile screen makes providing the address as more optional and less required to the user. How much effort would it be to implement the 2nd screen as requested?

Originally, this is how the process worked:
If registering via e-mail, the user was presented with screen 1 (account setup) and screen 2 (address).
If registering via FB, the user was presented went directly to screen 2. 

We need that address for the product to work. Without it, they're not linked to elected leaders or town/state/country groups, which are core to the mission... Please let me know what the estimate is.

**Comment by petervojtek** [comment]
@jterps08 , I expect this:

> If registering via FB, the user was presented went directly to screen 2.

would take 2-3 hours to implement.

**Comment by jterps08** [comment]
Yeah, I think we have to do this unfortunately... I just don't see the Profile screen as being sufficiently "in-your-face" about needing to provide that information, which is critical for the mission.

**Comment by petervojtek** [comment]
ok, it is there. when you register via facebook you are brought to this screen:

<img width="508" alt="screen shot 2016-10-13 at 12 58 52" src="https://cloud.githubusercontent.com/assets/225506/19346708/191402da-9145-11e6-85e3-f899690268d1.png">

Also the register via email form has been changed according to this:

> replace the DOB field with an "I am 13 or older" checkbox (do not allow users less than 13 to register). We should also remove Phone Number
