### ISSUE TITLE
iOS Poll Item Detail Back Button

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#320]
iOS: Poll Item Detail screen back button not tappable (after answering poll)

**Comment by petervojtek** [comment]
hmm, cannot reproduce. I created a poll:poll with ID 327, and on iPhone managed to answer it and then clicked back button and went to Main screen successfully.

**Comment by jterps08** [comment]
Maybe it was frozen on my end. Can you just make sure that the 'tappable area' is generous for the back button from that screen and we'll call this closed?

**Comment by petervojtek** [comment]
ok, I increased the back button area.
