### ISSUE TITLE
When creating Leader Content, I should be default subscribed to my notifications for the item.

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#325]
User 1.JesseChen is the creator of BuildTest3 group.
Using the contenthelper tool, Jesse creates new leader content (poll, leader petition, event, crowdfunder, and discussion)
The items correctly appear in the priority zone and in the newsfeed. 
However, the bell-icon is not blue, indicating that the author (1.JesseChen) has not been subscribed to his own created _leader_ content by default. (incorrect).

When creating a user post or a userpetition, the author is subscribed to his items by default and the icon is blue (correct)

**Comment by petervojtek** [comment]
I could subscribe the author to the newly created item from frontend right after creating it, but because for UserPetition and Post the describe-author-by-default is performed on backend, let us do it the same way also for the leader content -- i.e. that is why I assign this issue to Igor.

**Comment by igaponov** [comment]
@jterps08 this feature was already added for polls. Can you tell me which poll did you create? I can't find any, created by  user 1.JesseChen.

**Comment by jterps08** [comment]
It may have been created by JTest1 and I forgot that I was in two separate accounts. My mistake...

Is this feature added for all leader types (polls/petitions/discussions/fundraisers/crowdfunders/events)?

**Comment by igaponov** [comment]
@jterps08 yes

**Comment by jterps08** [comment]
great we can close then... thanks
