### ISSUE TITLE
@mention in user petition comment - author receives two notification

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#326]
when author of an user petition is @mentioned in comment by other user, the author receives two push notifications at the same time:
- you were mentioned
- someone commented on your petition

@jterps08 , not sure if this is intended behaviour.

**Comment by jterps08** [comment]
This is P3. It's according to spec, but it's not what we want the user to experience. We'll leave it as P3 for now.

**Comment by jterps08** [comment]
@petervojtek do we need Igor to address this or is this frontend work?

**Comment by petervojtek** [comment]
@jterps08 , this is backend issue.

**Comment by igaponov** [comment]
@jterps08 which notification should I send in this case?

**Comment by jterps08** [comment]
the notification for "You were mentioned" should be sent. Good question...

Kindly prioritize #519 first as that is blocking our deployment to production

**Comment by jterps08** [comment]
confirmed closed
