### ISSUE TITLE
Unable to register token to push notifications due to Incorrect Token or userType.

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#328]
Igor, I suddently started to receive following response both on iOS and Android:

```
GET https://api-dev.powerli.ne/api/endpoints/

response: 401
Incorrect Token or userType.
```

**Comment by igaponov** [comment]
@petervojtek add please your user and token.

```
$ http get https://api-dev.powerli.ne/api/endpoints/ "Token: $TOKEN"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: accept, origin, x-requested-with, Authorization, content-type, Token
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Mon, 10 Oct 2016 23:55:47 GMT
Server: nginx/1.4.6 (Ubuntu)
Transfer-Encoding: chunked
X-Debug-Token: 3ae3bb

[
    {
        "id": 300, 
        "token": "..."
    }
]
```

I think somebody has logged in with your user at the same time and your token has became invalid.

P.S. I've added `type` field for endpoint (value = android/ios)

**Comment by petervojtek** [comment]
@igaponov , I still experience the issue.

I reset the app (cleared all its data) on Android so that I have new token, but then I still receive 

```
GET https://api-dev.powerli.ne/api/endpoints/

response: 401
Incorrect Token or userType.
```

for this token: `e_Byh908xm4:APA91bGkZIQNrLVjsRR90ThtkiJcWnRxFaGigAC3HCOYzuLlEDLd-sAB1JQadPdEJRL8xdFzxW8s8smW-xLBymukF-9Q7jyrwkIKodVx5ZJgoViIaxS8ZVyqg8yGEKy5ERwzBCsti9VE`

I am not sure how should i use `type` field -- during `POST /api/endpoints/` ?

I actually do not reach `POST /api/endpoints/` at all, because the workflow is following:
1. `GET https://api-dev.powerli.ne/api/endpoints/`
2. if my token is in response, I know I am already registered
3. if my token is not present, call `POST /api/endpoints/`
4. login to powerline with username..

However due to error thrown on Step 1, the process is halted there.

**Comment by igaponov** [comment]
@petervojtek the right workflow:
1. login to powerline with username..
2. `GET https://api-dev.powerli.ne/api/endpoints/`
3. ...

By `type` field you can see tokens for which devices you already have.

**Comment by petervojtek** [comment]
ok, thanks for details @igaponov , when I altered the workflow sequence I can successfully registed the token and receive notifications both on Android and iOS.

however I still do not understand the purpose of `type` attribute you suggest to use during `GET /endpoints`.
I.e. -- what can happen when I do not use the `type` attribute? 

the token is so unique that there is no chance the same token will be generated both on android and iphone.

**Comment by igaponov** [comment]
@petervojtek when you use `GET /endpoints` there can be only one endpoint and without `type` attribute you can't determine which your device already has it, android or ios.

**Comment by petervojtek** [comment]
> can't determine which your device already has it

@igaponov ,so then you will send in response in `GET /endpoints` all the tokens you have for the user, no?

and in smartphone I know which token I currently own and thus can check if it is in the response or not.
