### ISSUE TITLE
Push notifications: make transitions to final view faster after button click on notification

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#331]
currently, e.g. when user clicked View button on new post comment notification, there was 2 seconds delay before user was actualyl navigated to the Post detail.

it is possible to use angular $state.go transition.

however there is following $state.go behaviour to resolve before we can use it:
when the app is already open on some detail view, then the app is minimized and then notification arrives and button is clicked, the app is properly navigated to the detail, but back button is not visible.

when app is not launched and notification arrives and button is clicked, the app is properly navigated to the detail and back button is there.

**Comment by petervojtek** [comment]
as a temporary solution I display a loader while desired final screen is reached.

**Comment by jterps08** [comment]
Temporary solution works... It would be good to figure out how we can speed all of that up and maybe have a different back button? I'm not sure...

**Comment by petervojtek** [comment]
we have this issue done for free thanks to code changes in #351
