### ISSUE TITLE
Push notifications - boosted Post and UserPetition: Sign/Upvote/Downvote button is also displayed to owner

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#332]
on Android Igor could remove the buttons on backend conditionally.
however on iOS it is not possible because the buttons are specified on frontend in mobile app and it is not possible conditionally show/hide some buttons based on other push notification payload details other than type (`category`).

Therefore, I  I see following solution both for Android and iOS:

when Post is boosted and push notification is being delivered to author, the notification `type` (category) will be e.g. `own-post-is-boosted` and `own-user-petition-is-boosted.`

when Post is boosted and notification is being delivered to non-author the behaviour remains as is.
Currently when Post is boosted, push notification type (category) is `post`, resp. `user-petition`, disregarding whether it is being delivered to owner or other user.

Igor will also have to set that `own-post-is-boosted` and `own-user-petition-is-boosted` push notifications have no Sign/Upvote/Downvote buttons on Android, but they carry e.g. View button.

Then on iOS I will configure that `own-post-is-boosted` and `own-user-petition-is-boosted` display View button.

@jterps08 , please review this and adjust priority if necessary.. then it should be assigned to Igor.

**Comment by jterps08** [comment]
Works for me!

**Comment by petervojtek** [comment]
@jterps08 , I do not understand you response -- what works for you? :)

**Comment by jterps08** [comment]
"Therefore, I I see following solution both for Android and iOS:

when Post is boosted and push notification is being delivered to author, the notification type (category) will be e.g. own-post-is-boosted and own-user-petition-is-boosted.

when Post is boosted and notification is being delivered to non-author the behaviour remains as is.
Currently when Post is boosted, push notification type (category) is post, resp. user-petition, disregarding whether it is being delivered to owner or other user.

Igor will also have to set that own-post-is-boosted and own-user-petition-is-boosted push notifications have no Sign/Upvote/Downvote buttons on Android, but they carry e.g. View button.

Then on iOS I will configure that own-post-is-boosted and own-user-petition-is-boosted display View button."

let's proceed with that plan or is it a huge amount of effort?

**Comment by igaponov** [comment]
@petervojtek now old pushes have type `xxx-is-boosted`, pushes for owner have type `own-xxx-is-boosted` and only a `View` button for android

**Comment by petervojtek** [comment]
ok, works now.
