### ISSUE TITLE
push notifications: @mention in comment - push notification not send for all content types

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#333]

**Comment by petervojtek** [comment]
@igaponov , when I @mention user in UserPetition and Post comment the user will properly receive `comment-mentioned` push notification.

However for leader content it seems such notification is not generated -- tested on poll:news and poll:crowdfunding comments.

**Comment by jterps08** [comment]
Needs to work for all content.

**Comment by petervojtek** [comment]
@igaponov,  as Peter10 in group San Diego I add following comment to crowdfunding-payment-request 355:

```
Request URL:https://api-dev.powerli.ne/api/poll/355/comments/
Request Method:POST
Status Code:200 OK

{"parent_comment":688,"comment_body":"test 5 @Peter30","privacy":0}
```

And Peter30 who is member of San Diego group has not received the push notification that was mentioned.

When as Peter10 I add this comment to user-petition 264 which is in group SanDiego, Peter30 will receive the mentioned push notification:

```
Request URL:https://api-dev.powerli.ne/api/v2/user-petitions/264/comments
Request Method:POST
Status Code:200 OK

{"comment_body":"test @Peter30","parent_comment":170}
```

**Comment by igaponov** [comment]
@petervojtek ok, now I see. You use deprecated v1 endpoint for polls and v2 for posts and petitions, that's why.

**Comment by petervojtek** [comment]
@igaponov , when I try to add a comment via v2 api, I experience this:

```
Request URL:https://api-dev.powerli.ne/api/v2/polls/355/comments
Request Method:POST
Status Code:400 Bad Request

{"parent_comment":688,"comment_body":"test @Peter30 now","privacy":0}

{"code":400,"message":"Validation Failed","errors":{"children":{"comment_body":{"errors":["This value should not be blank."]},"parent_comment":[]}}}
```

while when I create Post the payload seem sto be the same and it works:

```
Request URL:https://api-dev.powerli.ne/api/v2/posts/354/comments
Request Method:POST
Status Code:200 OK

{"comment_body":"test 1","parent_comment":757}
```

Actually I am still wondering what is the purpose of having three different v2 endpoints to treat comment separately for Post, UserPetiton and Polls, when comments behave exactly the same way for all entity types. I cannot not see any benefits, it just makes the business logic on frontend side 3 times larger and 3 times more prone to bugs. 

If the reason was the entity.id's are not unique among all entity types (i.e., there can be Post with id=30 and also UserPetition with ID=30), I believe it is fairly simply to start assigning unique IDs to entities.

**Comment by igaponov** [comment]
@petervojtek 

```
$ http post https://api-dev.powerli.ne/api/v2/polls/355/comments "Token: $TOKEN" parent_comment=688 comment_body="test @Peter30 now"         
HTTP/1.1 200 OK
Access-Control-Allow-Headers: accept, origin, x-requested-with, Authorization, content-type, Token
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Fri, 14 Oct 2016 07:00:36 GMT
Server: nginx/1.4.6 (Ubuntu)
Transfer-Encoding: chunked
X-Debug-Token: 0d7341

{
    "author_picture": "http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg", 
    "comment_body": "test @Peter30 now", 
    "comment_body_html": "test <a data-user-id=\"80\">@Peter30</a> now", 
    "created_at": "Fri, 14 Oct 2016 07:00:36 +0000", 
    "id": 705, 
    "is_owner": true, 
    "parent_comment": 688, 
    "privacy": "public", 
    "rate_sum": 0, 
    "rates_count": 0, 
    "user": {
        "avatar_file_name": "http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg", 
        "first_name": "Peter10", 
        "full_name": "Peter10 Is Leader", 
        "id": 73, 
        "last_name": "Is Leader", 
        "type": "user", 
        "username": "Peter10"
    }
}
```

Maybe you have a problem with headers again.
There is no `privacy` in this form, I'll add it soon.

Post, UserPetiton and Polls are different entities, that's why we have different endpoints. Of course I use the same logic on backend to add a comment, but need to determine which entity use to comment. And I believe you can use the same logic with different urls on frontend too.

Entity's id can't be unique among all entity types, it's possible only if we use uuid.

**Comment by petervojtek** [comment]
yes, I missed there json header. thanks.

now it works.
