### ISSUE TITLE
Social Activity Feed: `following` attribute is null

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#334]
@igaponov , I had a business logic which is parsing `GET /api/v2/user/social-activities`

so that when it is follow request, it expects an item to have `following` attribute.

However suddenly the `following` is `null`. The json below is notification received by Peter10 that Peter35 wants to follow Peter10:

```
{"tab":"you","html_message":"<p><strong>Peter35 Peter35</strong> wants to follow you</p>","id":2198,"group":null,"following":null,"type":"follow-request","created_at":"2016-10-12T08:41:54.000Z","target":{"id":92,"type":"user","full_name":"Peter35 Peter35","image":null},"ignore":null,"sa-icon":"sa-icon-request-1"}
```

I see that there is `target` attribute which holds details of `Peter35`, but I believe my business logic for working with the `following` until very recently.

I am not sure if some changes were made on the backend.

**Comment by igaponov** [comment]
@petervojtek `following` attribute for type `follow request` is wrong. What data do you need? I'll add it to `target`

Also, for other notifications you should'n rely on `recipient` and `following` attributes, it's used only on backend to determine where to send a notification. Use `target` attribute to get any data you need and tell me if you need to add something.

**Comment by petervojtek** [comment]
@igaponov , all the required data seems to be already in the `target` and I will use them.

, I just do not understand what and when has happened to the `following` -- I believe there was some content maybe 1-2 weeks ago and it seems to me that it suddently disappeared. 

the problem in general is that when I am not notified on such such changes, there is no good way to reveal them because there are no automated tests.
