### ISSUE TITLE
Push notification button Reply not properly processed on child comment

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#336]

**Comment by petervojtek** [comment]
@jterps08 , now when user makes a reply to a comment, author of the first comment will receive push notification with Reply button.

When you click Reply, you should be guided to the comment thread with the reply.

However from UX point of view I find the screen really confusing. Actually, since today I was completely unaware that it is possible to respond to some particular comment and then to see screen like this:

<img width="822" alt="screen shot 2016-10-12 at 12 23 45" src="https://cloud.githubusercontent.com/assets/225506/19306660/f8ded09a-9076-11e6-9442-0815f9b831d0.png">

I do not understand why must user enter another screen to see the discussion.

Also there is problem with reliability of screen trasitions when you click Reply button in push notification. E.g. on iPhone I have not yet managed the iPhone to make it to the screen, it may be a combination of timeouts (because three screen transitions are needed Main Page -> User Petition -> Comment thread screen). On Android it seems to work.

Even if the above will work reliably, the user will land on a page which looks like the above and can be fairly confused what is the whole discussion about, because there is no information if the discussion is about some Post, or User Petition, what is the text of the Post, etc.

I would rather suggest that when clicking Reply in push notification user will end up on the Post/user Petition screen. and in future the whole discussion threads should displayed in the same page as well.

**Comment by jterps08** [comment]
I agree with your suggestion, Peter.

I also want to redesign the Item Detail screen in the future anyway to figure out how we can better unify everything without needing separate screens and tabs etc...

**Comment by petervojtek** [comment]
ok, for the moment @jterps08  I suggest that when user clicks Reply, he will be guided to the item detail (e.g. Post detail) and not to the discussion branch detail, ok?

**Comment by jterps08** [comment]
that's fine

**Comment by petervojtek** [comment]
done
