### ISSUE TITLE
Avatar/Picture Loading

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#34]
Dev environment

The user avatars in the newsfeed are messed up. It should show the user's default avatar (loaded through imgix) or the ng-letter avatar if no avatar is present. This seems to be all image avatars throughout the app (My Representatives, My Influences, etc.) - I believe this is an ​_Imgix_​ implementation issue. contact me for imgix info if needed.

**Comment by petervojtek** [comment]
related to #62 and #78

**Comment by petervojtek** [comment]
I observe following behaviour: if user has updated his profile image to some photo from phone gallery, this profile photo is properly displayed in his profile, but anywhere else ng-letter remains displayed. @jterps08 , I am not sure if this is a feature, or a bug.

**Comment by jterps08** [comment]
I will confirm that this is still a problem during next testing cycle. It was originally a bug.

If user chooses avatar from phone gallery (or registered/logged-in with Facebook), s/he has a profile photo that should be displayed. If user does not provide avatar, ng-letter should be displayed.

**Comment by petervojtek** [comment]
there was a bug in frontent business logic.
