### ISSUE TITLE
Activity newsfeed - after more items are loaded on bottom, position is reset (to top)

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#340]
there are e.g. 20 items in activity newsfeed.
I scroll to bottom, and next 20 items (older) are being loaded.
when loading is finished, there are 40 items, but the screen position does not remains on item 20, but will jump to top to item 1.

**Comment by eriklouis129** [comment]
in which screen?
any screenshot?

**Comment by jterps08** [comment]
The main newsfeed

![screenshot_2016-10-23-19-29-30](https://cloud.githubusercontent.com/assets/7582457/20252518/01496202-a9f1-11e6-9450-ec1640b30635.png)

**Comment by jterps08** [comment]
The main newsfeed will paginate and load 1-20 items first. When you scroll to bottom, the app will load next items 21-40, but does not say in scroll position for item 20/21. Instead it returns to top. We want to stay in scroll position whenever it loads more data (eg. 41-60 etc etc).

**Comment by eriklouis129** [comment]
fixed

**Comment by jterps08** [comment]
awesome - marking ready for retest - can you reference the commit ID for reference please?

**Comment by eriklouis129** [comment]
fixed in "Erik" branch

**Comment by jterps08** [comment]
@petervojtek please double-check this work. I want to make sure newsfeed is operating correctly and that local caching hasn't been removed as part of Erik's work.

**Comment by eriklouis129** [comment]
returns server error now.
![screen shot 2016-11-22 at 3 54 21 am](https://cloud.githubusercontent.com/assets/20544710/20509211/6fe405c4-b067-11e6-96d4-1c0b21e3eec5.png)
please check and let me know what is the error.

**Comment by jterps08** [comment]
@petervojtek I need you to fix.

@eriklouis129 I don't think you have the knowledge of the system to fix this so I want to leave this to Peter. Thanks.

**Comment by jterps08** [comment]
I cannot seem to load more than 15 items into my feed. When i scroll to the bottom, it should load the next 15 items...  I do not want Erik's work from above to have removed either a) infinite scrolling or b) local caching
