### ISSUE TITLE
Leader content creation: create event

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#344]

**Comment by jterps08** [comment]
Can we create a solution for adding fields for timezone to this? Currently no time zone is involved in creating leader events (or crowdfunding deadlines) and it is confusing I think... The simplest solution is the one we should pursue, but I feel like this is a particularly important enhancement given that we're working on this at this point... Thoughts?

**Comment by petervojtek** [comment]
@jterps08 , I suggest following approach (it is simple to implement):

the datetime picker will be in local time as is provided by browser `new Date()` which also includes information of the timezone the user is using. 

Label od a datepicker will feature text like this:
"Choose deadline/event-time in local time. You are using timezone GMT+05:00". 

this way user will reference the to the deadline/event-time relative to his local time which he should be familiar with. The timezone is provided to browser by operating system. on android this means that user is supposed to go to android settings and pick there other timezone if the currently presented is not the desired one.

**Comment by jterps08** [comment]
Okay - So, just so I'm understanding this, if I create an event in the Save the Whales group in San Diego (Pacific Time, -8) for 9AM and I look at the event from New York (Eastern Time, -5), my device will tell me that the event is at 12PM noon my time.... When the native OS event calendar shows up for Android or iOS, it will be populated with the equivalent of the local time for the event. Sooo, when I save the 12PM noon event to my device, it is saved in Eastern time. Let's say I fly out to California for this event, my Android/iOS calendar should know that the event was saved in the "previously-local" time zone (Eastern) and shift the event on my calendar accordingly when my device time has changed automatically to the Pacific Time zone... Just trying to follow this end-to-end... 

If that works, I think we're good to go.

**Comment by petervojtek** [comment]
@jterps08 , yes -- the date-time worfklow should be following:

when creating an event:
1. you select local time from date picker
2. on mobile app the local time is tranformed to UTC time
3. UTC time is sent to backend where the event time is stored

when looking at an event:
1. server sends UTC time of the event
2. in mobile app I transform it to be local time + timezone offset
3. I display local time

**Comment by jterps08** [comment]
perfect thank you

**Comment by petervojtek** [comment]
it's done.
