### ISSUE TITLE
Create Leader Content: Show only groups where user can create leader content

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#345]
"Make a leader content" option in top right corner in Main screen should be visible only when following conditions are met:
- when some particual group is selected in Activity newsfeed, and the user has right to create leader content there (i.e. is leader or owner)
- or, when no group is selected in Activity newsfeed, and there exists at least one group where the user is allowed to create leader content.

Currently there exists `GET /api/groups/is-manager/{id}` api call which can tell if the current user is manager of a particual group or not, however this is not effective approach, because I would rather know that information in bulk for all the groups the user is member of (because in create form detail one can pick from list of groups and it would be innefective to make http request for each group to find out if user can create there  poll or not).

Therefore my suggestion is to enrich `GET /api/v2/user/groups` so that it also provides information whether user is manager/owner of the group. I already make request to `GET /api/v2/user/groups` to get the list of groups to display in activity newsfeed filter so I will get it almost for free.

**Comment by jterps08** [comment]
agreed with above, but want to be clear that user should be able to create leader content if user is group owner OR group manager (not only is manager). Not sure if the API distinguishes between the two, but there is a difference that was previously communicated:

group owner creates the group, can assign manager privileges to group members, can change subscription settings and payment information... can create leader content and manage other group settings. 

group manager is assigned his role, can do everything that group owner can _except_ assign manager privileges to other group members, change subscription settings, and payment information... Can create leader content and manage other group settings.

**Comment by igaponov** [comment]
added `user_role` attribute (owner|manager|member)

**Comment by petervojtek** [comment]
@igaponov , and where should I find the `user_role` ? I does not seem to be here:

```
Request URL:https://api-dev.powerli.ne/api/v2/user/groups
Request Method:GET
Status Code:200 OK

{"page":1,"items":50,"payload":[{"join_status":"active","id":1,"group_type":1,"username":"US","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"The United States of America","acronym":"US","joined":1,"picture":null,"created_at":"Mon, 10 Mar 2014 10:10:51 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5},{"join_status":"active","id":6,"group_type":2,"username":"CA","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"California","acronym":"CA","joined":1,"picture":null,"created_at":"Mon, 10 Mar 2014 10:10:51 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5},{"join_status":"active","id":285,"group_type":3,"username":"San Diego5773cfb9ea05a","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"San Diego","acronym":null,"joined":1,"picture":null,"created_at":"Wed, 29 Jun 2016 13:40:09 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5},{"join_status":"active","id":295,"group_type":0,"username":"SavePlanet","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"Save the Planet Now","acronym":"STP","joined":1,"picture":null,"created_at":"Wed, 13 Jul 2016 13:39:30 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5},{"join_status":"active","id":309,"group_type":0,"username":"Peter10Group4","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"Peter10Group4","acronym":"10G4","joined":1,"picture":null,"created_at":"Mon, 25 Jul 2016 06:53:13 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5},{"join_status":"active","id":311,"group_type":0,"username":"Peter10Group6","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"Peter10Group6","acronym":"10G6","joined":1,"picture":null,"created_at":"Wed, 27 Jul 2016 12:43:39 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5},{"join_status":"active","id":312,"group_type":0,"username":"Peter10Group7","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"Peter10Group7","acronym":"10G7","joined":1,"picture":null,"created_at":"Wed, 27 Jul 2016 12:44:56 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5},{"join_status":"active","id":330,"group_type":0,"username":"Peter10Group9","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"Peter10Group9","acronym":"P10G","joined":1,"picture":null,"created_at":"Fri, 14 Oct 2016 06:41:24 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5},{"join_status":"active","id":331,"group_type":0,"username":"Peter10Group10","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"Peter10Group10","acronym":"A10","joined":1,"picture":null,"created_at":"Mon, 17 Oct 2016 05:28:19 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5},{"join_status":"active","id":332,"group_type":0,"username":"AA20","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"AA20","acronym":"AA20","joined":1,"picture":null,"created_at":"Fri, 21 Oct 2016 06:38:26 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5}],"totalItems":10}


```

**Comment by petervojtek** [comment]
@jterps08 , now the content creation works as following;
- in Main screen (activity newsfeed) -- when about to create new content in top right corner popup, if no group is selected (i.e. filter All), and user is manager/owner in at least one group, he is displayed there "New Group Poll/Discussion/.."
-  in Main screen (activity newsfeed) if some group filter is selected -- when about to create new content in top right corner, the "New Group Poll/Discussion/.." are displayed there only when user is manager/owner in the group chosen in filter.
- in create content detail screen when creating a leader content type -- when you click the group picker, only those groups are displayed where the current user is owner/manager.

**Comment by jterps08** [comment]
very nice
