### ISSUE TITLE
Create Leader Content: create petition

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#346]
#311

**Comment by petervojtek** [comment]
@jterps08 , I would like to ask how this form (create group petition) should deal with "create user petition" form.

I can think of following behaviour, please correct me if I am wrong or there is better approach:
- in main screen, in top left corner, there will be only one option -- "Create Petition" 
  - or should it be named "Create Group Petition" because of #339  ?
- if user will create the petiiton in a group where is is only regular user, the petition will be created as user petition.
- when user will create the petition in a group where he is a leader, the petition will be created as a leader petition

the result of this workflow is that leader will be unable to create user petition in a group where he is a leader.

**Comment by jterps08** [comment]
We should keep both. 

The difference between the User Petition and the Group Petition is basically:
1) Group Petitions are sent to all members with a push notification and get treated as priority zone immediately. They can only be sent by group owner/managers
2) User Petitions result in push notifications only for the author's followers, not all group members. They are not treated as priority zone unless they are boosted. Everyone can create these.

I know it's a little confusing but, for now, we want to give group managers/owners the ability to create BOTH of these. There may be times, especially in large group scenarios (1,000+ in a group), where a group manager wants to create a petition that does not go out to all group members. The ability to reach all group manager is a "great power that comes with great responsibility" and may not be appropriate to use in all circumstances, specifically when it comes to creating petitions...

It's not perfect and it will probably be confusing but I want to try it this way first. We can always change it later...

I am hoping that group managers figure out the difference based on the alert dialog box that was explained in #309 here: https://github.com/PowerlineApp/powerline-mobile/issues/309#issuecomment-251419948

"You are about to send this to all X group members. Are you sure?" -- Hopefully that will reduce some of the confusion that is associated with having two petition options...

**Comment by petervojtek** [comment]
@jterps08 , the point of my previous comment was that I though you want to avoid this (i.e. now there are two Petition items in menu):

<img width="627" alt="screen shot 2016-10-18 at 09 57 07" src="https://cloud.githubusercontent.com/assets/225506/19468906/440c6522-9519-11e6-995c-8f215716453b.png">

I am still not sure how you want to deal with it.

**Comment by jterps08** [comment]
I understand your concern. I am okay with two Petition-related items on the menu, but this is how they should be labeled and listed: 

New Post
New Petition
New Group Poll
New Group Discussion
New Group Petition
New Group Event
New Group Fundraiser
New Group Crowdfunder
New Group Announcement

I know this isn't ideal language and I don't like that we have two listings. This is only a challenge for group leaders, though and it's not a problem I think we can resolve before the release.

Maybe we add a signifier/icon that helps indicate that the leader tools go to all group members (e.g. with an asterisk or something)... Or we can make a thick line between New Post and New Petition vs the rest of the list... We definitely don't want to put them right next to each other. 

I'm open to other UI-related ideas at this point, but let's definitely keep both options and space them apart visually by changing the order... Let's also make the labeling consistent in the menu.

**Comment by petervojtek** [comment]
@jterps08 , ok, the renaming of th eitems has already it's own issue and I updated it:
#339
