### ISSUE TITLE
leader content: before Send content show alert "You are about to send this to all X group members. Are you sure?" 

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#347]
from #309:

> We'll probably want to put an alert between the Submit button and the actual publish action that warns the user "You are about to send this to all X group members. Are you sure?" where X is the number of group members...

part of #311

**Comment by jterps08** [comment]
This is only for group leader items. Do you think we should use different language?

**Comment by petervojtek** [comment]
@jterps08 , I find it ok.

**Comment by petervojtek** [comment]
done in #339
