### ISSUE TITLE
Home Screen Group Selector

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#35]
Upon logging in with the test credentials, the "All" button is shown in the group selector, but it is missing the town, state/province, and country group buttons as well. It should also show any other groups that the user has joined (including EU or AU groups if registering with an address in Europe or Africa). 

The app does not seem to be picking up which groups the user is associated with. The More Button disappears when the user logs out and logs in again.

Will update with screenshot examples

**Comment by petervojtek** [comment]
related to #71

**Comment by jterps08** [comment]
Note: I'm not sure if this is still a problem. The "More Button" should always appear next to the country icon (from left to right: All, town, state, country, More). More icon should display the group avatar of the selected group within the More menu. The more icon should always be available to tap on to expand the menu to display all other groups the user is a part of. At minimum, the more menu includes a button to Add a Group.

**Comment by petervojtek** [comment]
the town, state/province, and country group buttons are already there.
the "more" button is missing, will fix it in #86
