### ISSUE TITLE
group management: Manual Boosting Button (Visible to Group Leaders Only)

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#350]
For group owners/managers who are looking at any posts that are in their groups that they own/manage they will see inside the item detail screen a 'lightning' icon that, when pressed, displays a "Manually boost this item? All group members will be notified immediately. Consider adding a comment to help guide the conversation." (with Boost/Cancel options). 

This will leverage the manual boosting API endpoint available for posts and petitions only. https://github.com/PowerlineApp/powerline-server/pull/358

The button should appear for group owners/managers automatically for all posts or user petitions in their owned/managed groups.

**Comment by jterps08** [comment]
@igaponov can you confirm the API endpoint is exposed for manual boosting (by group owner/manager) of a user post/petition in a group?

**Comment by igaponov** [comment]
@jterps08 
https://api-dev.powerli.ne/api-doc#patch--api-v2-micro-petitions-{id}
https://api-dev.powerli.ne/api-doc#patch--api-v2-posts-{id}

**Comment by jterps08** [comment]
Edited original requirements.

**Comment by petervojtek** [comment]
@igaponov , I miss the group.id information in user petition detail in order to determine if user is group manager/owner (post detail contains the `group.id`):

```
Request URL:https://api-dev.powerli.ne/api/v2/user-petitions/307
Request Method:GET
Status Code:200 OK

{"quorum_count":0,"share_picture":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg","petition_body_html":"tb4","petition_body":"tb4","expire_at":"2017-11-15T08:29:12+0000","user_expire_interval":0,"type":"long petition","link":"","publish_status":0,"answers":[],"is_subscribed":true,"id":307,"title":"Test boost 4","body":"tb4","html_body":"tb4","is_outsiders_sign":false,"created_at":"Tue, 15 Nov 2016 08:26:41 +0000","user":{"full_name":"Peter10 Is Leader","id":73,"type":"user","username":"Peter10","first_name":"Peter10","last_name":"Is Leader","official_title":"Peter10 Is Leader","email":"peter10@test.com","zip":"123","avatar_file_name":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg","birth":"01\/01\/1977","address1":"San Diego","address2":"123","city":"San Diego","state":"CA","country":"US","phone":"+1123","facebook_link":null,"twitter_link":null,"race":null,"sex":null,"orientation":null,"marital_status":null,"religion":null,"employment_status":null,"income_level":null,"education_level":null,"party":null,"philosophy":null,"donor":null,"bio":"whatever bio be heree","slogan":"live and let die","interests":[],"registration":null,"token":"24hntlysce3ow84880cgs8884wossg08owoo4s8gccsc0wogsw73","facebook_id":null,"ios_device":null,"android_device":null,"do_not_disturb":false,"is_notif_questions":true,"is_notif_discussions":true,"is_notif_messages":true,"is_notif_micro_following":true,"is_notif_micro_group":true,"is_notif_scheduled":false,"is_notif_own_post_changed":true,"scheduled_from":null,"scheduled_to":null,"is_registration_complete":true,"plain_password":null},"boosted":false,"organization_needed":false,"signatures":[],"cached_hash_tags":[],"metadata":{"title":null,"description":null,"image":null,"url":null}}
```

**Comment by igaponov** [comment]
@petervojtek `group_id` attribute is added

**Comment by petervojtek** [comment]
done.

the icon looks like this:

<img width="425" alt="screenshot 2016-11-17 09 31 57" src="https://cloud.githubusercontent.com/assets/225506/20381668/be577ae6-aca8-11e6-9a53-38a8bb7337a9.png">
