### ISSUE TITLE
After content is created user should see it

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#351]
currently when user creates item content (Post, Petition, Announcement, whatever), he is guided to activity newsfeed to the All view, but the item is not immidiatealy visible.

User should either see the created item in activity newsfeed (would require to refresh the newsfeed), or should be automatically forwarded to the item detail view (I personally prefer the later -- so that it behaves the same way as when you create new issue on github).

**Comment by jterps08** [comment]
I prefer the latter as well. 

How do we handle creating vs publishing leader content? Do we have a concept of saving drafts still or no? If so, how does it work?

**Comment by petervojtek** [comment]
@jterps08 , currently from user point of view the content is immidiately published.
however from API point of vie the create and the publish actions are two different actions.. it would be possible to create a "draft" and return to it later and finish it. also it would be possible to schedule an item to be published on some specific date -- it is all matter of gui screen which are missing to support it (e.g. a screen where user can browse his drafts, and another screen/popup to allow scheduled publish).

**Comment by jterps08** [comment]
Right, okay... We'll come back to the Draft v Publish concept later. Thanks, Peter

**Comment by petervojtek** [comment]
ok, the original issue is solved here -- when you successfully create content you are redirected to content detail screen. we should deal with the Draft v Publish idea in other issue.
