### ISSUE TITLE
Crowdfunder Deadline: Frontend 24 hour minimum

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#352]
Peter - I haven't actually tested this, but I expect it will be an issue:

When a group leader creates a crowdfunder with deadline, we now have the UTC conversion, which is great... However, I _believe_ the backend has a rule that requires the crowdfunder to be at least 24 hours away. If so, we will need a frontend rule that ensures the deadline (date/time) is at least 24 hours beyond current date/time otherwise it will give a server error. In fact, it might be good to pre-fill those fields with the current_date+1day and same time+1hour. 

Igor - Can you confirm whether or not this rule is hard-coded in the backend or not? It was previously implemented in the FrontEndBundle when creating a crowdfunder, but it's unclear whether or not that rule actually existed in the FrontEndBundle or tied to the crowdfunder itself (such as when a group must have an account setup prior to creating fundraiser/crowdfunder, etc.).

**Comment by petervojtek** [comment]
there is no such rule enforced on backend side.

**Comment by jterps08** [comment]
Okay, thanks. 

We need to figure out what we want to do here... I can imagine short-term "Help us by midnight tonight" types of fundraisers, but I also want to discourage really, really short timeframes because not all group members might see it in time. Any thoughts? I think we want something implemented on frontend to prevent entry. No need to establish formal logic on backend.

**Comment by petervojtek** [comment]
@jterps08 , it is easy to add such validation to frontend.

**Comment by jterps08** [comment]
I think we want to pre-fill the time with current_time+1 hour. We probably want to leave the date blank to force the user to select the date (otherwise, we might have a few mis-fires since we don't have Drafts capability in UI yet).

**Comment by petervojtek** [comment]
it's done, it works as following:
- by default deadline date is blank. user must click it at least once -- on such first click the date is filled with tomorrow date
  - this actually works properly in browser and android. in iOS the date picker will enforce there today's date.
- the hour is set to current_hour + 1
- when you try to Send and date is blank (i.e. user has not clicked the date field), you receive validation alert
- when you try to set deadline sooner than 24h from now, you receive validation alert

**Comment by jterps08** [comment]
Perfect thanks!
