### ISSUE TITLE
Upvoting/Downvoting a discussion should mark it as read

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#354]
Currently the user needs to open the discussion to mark it as read. If they decide to upvote/downvote from the newsfeed, that should mark it as read as well.

**Comment by jterps08** [comment]
This is something I had thought of from a couple weeks ago. Assigning to myself to retest.

**Comment by jterps08** [comment]
This is only for upvoting/downvoting a news/discussion type item @igaponov - please confirm that was what #377 was.

**Comment by igaponov** [comment]
@jterps08 I think it doesn't matter which type of poll will be marked as read because if you vote on any poll it'll not appear in prioritized zone. Or do you need this mark for another purpose?

P.S. we still use confusing terms for polls. There are no discussions on backend, only news. It's better to call it the same name every time.

**Comment by jterps08** [comment]
Understood... It's called news on backend and discussion on frontend... 

I will need to defer to @petervojtek -- everything was working fine before you merged https://github.com/PowerlineApp/powerline-server/pull/377... I just want to make sure when a user upvotes/downvotes a discussion/news item on the frontend that we mark the item as read... 

You may need to undo PR 377...

**Comment by petervojtek** [comment]
not sure what is my task here @jterps08 , but currently I see following behaviour:
when Discussion (News) is upvoted from activity newsfeed, the item is still considered as in priority zone by backend:

```
{"zone":"prioritized","id":957,"title":"","description":"D1","description_html":"D1","sent_at":"2016-10-31T06:43:33.000Z","expire_at":"2016-11-02T06:43:33.000Z","responses_count":0,"owner":{"id":295,"type":"group","group_type":0,"official_name":"Save the Planet Now","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png"},"user":{"full_name":"Peter10 Is Leader","id":73,"type":"user","official_title":"Peter10 Is Leader","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"leader-news","id":415},"picture":null,"read":false,"rate_up":1,"rate_down":0,"image_src":null,"updated_at":"2016-10-31T06:43:51+0000","poll":{"is_subscribed":false,"answers_count":null},"user_petition":null,"post":null}
```

**Comment by igaponov** [comment]
@petervojtek news with id=415 are unanswered:

```
$ http get https://api-dev.powerli.ne/api/v2/polls/415/answers "Token: $TOKEN"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: accept, origin, x-requested-with, Authorization, content-type, Token
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Mon, 31 Oct 2016 12:05:46 GMT
Server: nginx/1.4.6 (Ubuntu)
Transfer-Encoding: chunked
X-Debug-Token: b9ba66

{
    "items": 20, 
    "page": 1, 
    "payload": [], 
    "totalItems": 0
}
```

**Comment by jterps08** [comment]
@petervojtek - I'm not sure what Igor did in PR 377, but I'm not sure we actually needed PR 377 (Igor, I think you might want to roll that PR back)... 

Re: "not sure what is my task here @jterps08 , but currently I see following behaviour:
when Discussion (News) is upvoted from activity newsfeed, the item is still considered as in priority zone by backend:" --> This is what I'm trying to achieve: When Discussion/News is upvoted from activity feed, the item is no longer considered priority zone by backend.

**Comment by petervojtek** [comment]
@igaponov , in the payload of the activity related to the News/Discussion 415 is following attribute:
`"rate_up":2`

which refers to the fact the Peter30 and Peter10 upvoted the item via `POST https://api-dev.powerli.ne/api/poll/comments/rate/795/up`.
 not sure if some other api call should be used to denote that the item has been `answered`.

**Comment by igaponov** [comment]
@petervojtek attribute `rate_up` refers to the fact that comments of that poll were rated up via `POST https://api-dev.powerli.ne/api/poll/comments/rate/795/up`

If item is answered by user you'll see `answers` attribute.

**Comment by jterps08** [comment]
@igaponov I'm concerned that PR 377 changed the priority zone algorithm in a way that I did not want. Things were working fine before 377. I just wanted a rate-up/down event to result in the item being marked as read.... I believe it might be prudent to roll back 377...

**Comment by igaponov** [comment]
@jterps08 #377 doesn't change priority zone algorithm, it just marks poll's activity as read if user votes.

**Comment by jterps08** [comment]
Okay cool... @petervojtek can you verify? This sounds good to me.

**Comment by petervojtek** [comment]
I am not sure how should I proceed here.

currently the Discussion is using following legacy workflow:
when discussion activity item is displayed, there are two buttons (rate up and rate down) available. clicking those buttons triggers `POST https://api-dev.powerli.ne/api/poll/comments/rate/up or down`, which technically rates the Discussion via ratings its root comment (=the discussion itself).

Now if i understand properly @igaponov  wants me to change this and use options/answers instead.

@jterps08 , currently when you create Discussion, user fills in there only the discussion topic, no options/answers are provided. How should I treat this? should I automatically add there two options (Up and Down), invisible to the user but submitted when creating the Discussion? Or should I give the user in create discussion form ability to customize the options?

**Comment by igaponov** [comment]
Ok, now I've got it. There is a problem with terms again. When you want to upvote/downvote a poll, you use "answer". But we don't have answers for news. Now we use a hack: rate comments (!!!) of news to rate news. This is totally wrong of course. News have to be a separate entity, not a poll, but we already have this wrong domain model. So I see two variants: 
- I can add this feature for comment rates (this time only for news)
- We can change domain model somehow, but takes more time

**Comment by jterps08** [comment]
Let's do the easier quickest version. At some point we can rebuild officially but for now its the experience I'm focused on.... thanks Igor

**Comment by petervojtek** [comment]
ok, I confirm that now the Discussion is marked as read after voting via comment.
