### ISSUE TITLE
group management: subscription plan

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#357]
#356

**Comment by petervojtek** [comment]
@igaponov , I am trying to find out how can I determine which subscription plan is assigned to a group (Free/Silver/Gold/Platinum/Commercial).

I tried to use `GET /api/v2/groups/{group}/subscription`, but e.g. for group Peter10Group10 the response is following:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/331/subscription
Request Method:GET
Status Code:200 OK

{"id":null,"package_type":null,"expired_at":null,"next_payment_at":null,"enabled":null}
```

I am not sure if I use proper endpoint at all, and if yes, I am not sure how can I resolve the subscription plan from the data provided in response.

**Comment by petervojtek** [comment]
@jterps08, what should happen when user clicks "Cancel subscription" in subscription plan settings?  

I only guess following behaviour would make sense:
- when group is using Free plan, there should be option to "cancel subscription"
- for other plans when "cancel subscription" is clicked and confirmed, the group subscription plan is set to Free plan.

fyi, I had to orient the design of the list of subscription plan vertically so that they fit into mobile screen:

<img width="357" alt="screen shot 2016-10-21 at 08 21 52" src="https://cloud.githubusercontent.com/assets/225506/19588659/86afbffa-9767-11e6-872c-aa0f7935e376.png">

while here is the original design:

<img width="597" alt="screen shot 2016-10-21 at 08 23 12" src="https://cloud.githubusercontent.com/assets/225506/19588681/a7461f48-9767-11e6-8234-2c6be12694f3.png">

**Comment by jterps08** [comment]
Peter - Good improvisation for subscription design, vertical works.

If Silver/Gold/Platinum cancels a subscription, the group returns to Free subscription. You cannot cancel a free subscription. We do not yet off the ability to disable/remove a group. 

Please do not offer Corporate. We're a long way off from LDAP integration and behind-the-firewall hosting... right? :-P

**Comment by igaponov** [comment]
@petervojtek fixed

**Comment by petervojtek** [comment]
@igaponov , the `GET groups/{id}/subscription` works for user groups, but when I try it for San Diego group, I experience following error:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/285/subscription
Request Method:GET
Status Code:500 Internal Server Error

{"code":500,"message":"No such customer: cus_7FCHdilX4A2vTX; a similar object exists in live mode, but a test mode key was used to make this request.","errors":null}
```

**Comment by petervojtek** [comment]
@igaponov , when I try to change subscription plan from Free to Gold, I experience this:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/312/subscription
Request Method:PUT
Status Code:500 Internal Server Error

{"package_type":"gold"}


XMLHttpRequest cannot load https://api-dev.powerli.ne/api/v2/groups/312/subscription. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by igaponov** [comment]
@petervojtek you need to add a bank account for this group first

**Comment by jterps08** [comment]
Scroll down for test CC numbers, accounts, and routing numbers... https://stripe.com/docs/testing

Group must have a CC number or bank account for subscription, preferable CC. 
Group must have a bank account for fundraisers/crowdfunders.

**Comment by petervojtek** [comment]
blocked by #373

**Comment by petervojtek** [comment]
@igaponov , I am unable to change group subscription plan due to:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/295/subscription
Request Method:PUT
Status Code:500 Internal Server Error

XMLHttpRequest cannot load https://api-dev.powerli.ne/api/v2/groups/295/subscription. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by igaponov** [comment]
fixed

**Comment by petervojtek** [comment]
@igaponov , now I can successfully change plan from Free to Silver for group 295.

However when I want to cancel the Silver subscription (i.e. go from Silver to Free) I experience this:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/295/subscription
Request Method:PUT
Status Code:400 Bad Request

{"package_type":"free"}

{"code":400,"message":"Validation Failed","errors":{"children":{"package_type":{"errors":["This value should not be blank."]},"coupon":[]}}}
```

**Comment by igaponov** [comment]
@petervojtek try `DELETE https://api-dev.powerli.ne/api/v2/groups/295/subscription`

**Comment by petervojtek** [comment]
@igaponov , DELETE does not seem to change the subscription plan to Free:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/295/subscription
Request Method:DELETE
Status Code:200 OK

{"id":7,"package_type":"platinum","expired_at":"2016-12-01T13:10:26+0000","next_payment_at":null,"enabled":false}

Request URL:https://api-dev.powerli.ne/api/v2/groups/295/subscription
Request Method:GET
Status Code:200 OK

{"id":7,"package_type":"platinum","expired_at":"2016-12-01T13:10:26+0000","next_payment_at":null,"enabled":false}
```

**Comment by igaponov** [comment]
Seems we don't delete a subscription, but change flag `enabled` to false. If you see it, it means your subscription is cancelled and you can consider it like a "free" plan.

**Comment by jterps08** [comment]
We will want to display the information of when the next "Charge" will occur for the group (if subscribed) or indicate if "You've cancelled your group's subscription. Your group is now at the free tier."

**Comment by petervojtek** [comment]
@jterps08 , I do not understand you comment. is it something we should implement now in this issue, or not?

**Comment by jterps08** [comment]
We need to provide group owner with ability to cancel subscription - message label to display once Cancelled, is "You've cancelled your group's subscription. Your group is now at the free tier."

We need to display the fact that a group subscription is active and the next "charge" will be on November 17 (for example). e.g. "The next charge for your group will be on (date) using card ending in (4digits)"

**Comment by petervojtek** [comment]
@igaponov , please add the date of next charge to `GET /api/v2/groups/295/subscription`.
Currently it looks as following:

```
{"id":7,"package_type":"silver","expired_at":"2016-12-03T09:19:58+0000","next_payment_at":null,"enabled":true}
```

the `next_payment_at` is null.

@jterps08 , regarding cancelling subscription, this is how currently the UI looks like. there are two ways how to cancel subscription -- either by clicking on Revoke subscription button, or clicking on Free select button.

<img width="344" alt="screen shot 2016-11-03 at 10 20 07" src="https://cloud.githubusercontent.com/assets/225506/19960814/5ea5ab1c-a1af-11e6-8b30-f9e67a36b4f1.png">

**Comment by jterps08** [comment]
Works for me. I'll create a P4 to change "Revoke" to "Cancel" in label.

**Comment by petervojtek** [comment]
ok, next_payment_at is displayed, it looks like this:

<img width="342" alt="screen shot 2016-11-07 at 08 37 26" src="https://cloud.githubusercontent.com/assets/225506/20049766/86b5bfc0-a4c5-11e6-97df-2cebd5a7ebe2.png">
