### ISSUE TITLE
group management: group permissions

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#358]
#356

**Comment by petervojtek** [comment]
ok, done. it looks like this:

<img width="341" alt="screen shot 2016-10-21 at 10 12 57" src="https://cloud.githubusercontent.com/assets/225506/19591366/f7ab8504-9776-11e6-93e1-45d5eca74bde.png">

**Comment by jterps08** [comment]
beautiful thanks
