### ISSUE TITLE
Notification Action Buttons on Android

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#359]
- Sign button on Android notification doesn't sign petition and open item detail screen. Please confirm iOS for Petition too
- RSVP button on Android notification doesn't open item detail screen for Event. Please confirm iOS for Event too
- Respond button on Android notification doesn't open item detial screen for Poll. Please confirm on iOS for Poll too
- Share button on Android notification doesn't open Announcements screen. Please confirm on iOS too
- Open button on Android notification doesn't open Group Profile screen for Group Permissions. Would expect this to open the group profile screen. Please confirm for iOS too

I was unable to test boosted post (Upvote/Downvote) and boosted petition (Sign) or follow request (Approve) or group invitation (Join), but these should behave similarly --> action submitted + routed to item detail screen (post/petition) or social activity feed (follow request) or Announcement screen (group invitation).

**Comment by petervojtek** [comment]
@jterps08 , I tested all the 5 items above both on Android and iPhone and they work for me.

Were you using this release?
powerline-dev-2016-10-19-commit-541b3.apk

**Comment by jterps08** [comment]
I will try again. Perhaps I installed the wrong release. I already deleted the APK from my downloads folder on my device for space so I don't know which one I have installed
