### ISSUE TITLE
Hashtag Searching

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#361]
Hashtag searching doesn't seem to work when hashtag hyperlink is tapped or through Search item on Menu... Seems to work for users only, not leader items or user content. See screenshot below (TBD)

**Comment by jterps08** [comment]
![screenshot_2016-10-14-07-28-33](https://cloud.githubusercontent.com/assets/7582457/19615995/ed2cdc8a-97d6-11e6-9f8e-f24a7978ead9.png)

**Comment by petervojtek** [comment]
@jterps08 , i cannot reproduce this bug, I can see the search work properly:

<img width="338" alt="screen shot 2016-10-25 at 07 46 04" src="https://cloud.githubusercontent.com/assets/225506/19674259/2702a8ce-9a87-11e6-994b-5e915fda201d.png">
