### ISSUE TITLE
Announcements screen missing Group Avatar and Group Name information

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#363]
Announcements screen missing Group Avatar and Group Name information. Please see screenshot below (TBD)

**Comment by jterps08** [comment]
![screenshot_2016-10-21-11-08-42](https://cloud.githubusercontent.com/assets/7582457/19616003/1b76acce-97d7-11e6-8930-8ca3486ac414.png)

**Comment by petervojtek** [comment]
@igaponov , there seems to be missing group information in announcements:

```
Request URL:https://api-dev.powerli.ne/api/v2/announcements?start=Wed,+04+May+2016+07:28:54+GMT
Request Method:GET
Status Code:200 OK

{"page":1,"items":20,"payload":[{"share_picture":null,"user":{},"id":134,"content_parsed":"Announcement 1 by Peter30","published_at":"Mon, 31 Oct 2016 07:22:28 +0000"}],"totalItems":1}
```

**Comment by petervojtek** [comment]
fixed. now looks like this:

<img width="820" alt="screen shot 2016-10-31 at 15 20 12" src="https://cloud.githubusercontent.com/assets/225506/19857347/a23abb4e-9f7d-11e6-8cb5-7d0462094a8a.png">
