### ISSUE TITLE
Deleting Post/Petition Font Color Hard to Read

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#365]
Please see screenshot below. Delete confirmation dialog box is hard to read. (TBD)

**Comment by jterps08** [comment]
![screenshot_2016-10-21-11-11-56](https://cloud.githubusercontent.com/assets/7582457/19616005/2998cdd2-97d7-11e6-9983-4ff9f76b2d8e.png)

**Comment by eriklouis129** [comment]
fixed
![simulator screen shot nov 14 2016 10 33 23 am](https://cloud.githubusercontent.com/assets/20544710/20259531/c92619d2-aa55-11e6-96ab-dc12e81018fb.png)

**Comment by jterps08** [comment]
awesome - Can you confirm the font color change also works for Deleting a Post... Create new post in some group. Open your post. Click trash can icon... A similar popup should appear... 

Please reference the commit ID... Thanks

**Comment by eriklouis129** [comment]
confirmed and worked.
![screen shot 2016-11-14 at 4 03 11 pm](https://cloud.githubusercontent.com/assets/20544710/20269562/fdaa7a08-aa83-11e6-8399-c4e0eb524d78.png)

**Comment by jterps08** [comment]
great thanks.
