### ISSUE TITLE
Change request data for `PUT /api/v2/user/groups/{id}` endpoint

### ISSUE THREAD

**Issue by igaponov** [PowerlineApp/powerline-mobile#367]
relevant when user is joining a group which requires fields to fill in.

check ApiDoc:
![image](https://cloud.githubusercontent.com/assets/4271889/19620778/269e2cda-98ae-11e6-82ff-6e7f20d2e820.png)

Backend changes will be merged after

**Comment by petervojtek** [comment]
will be relevant once we will be able to add question fields in group management

**Comment by igaponov** [comment]
@petervojtek https://api-dev.powerli.ne/api-doc#post--api-v2-groups-{group}-fields

**Comment by petervojtek** [comment]
ok, adopted.

**Comment by igaponov** [comment]
Merged and deployed
