### ISSUE TITLE
Unable to create new user post/petition

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#368]
I think we need to restore the "posts remaining" counter. I don't know if I'm getting an error because I ran out of posts for the month in NJ or USA (I don't think so)... Screenshots below shown when creating new post in NJ group or USA group

**Comment by jterps08** [comment]
![screenshot_2016-10-23-18-35-35](https://cloud.githubusercontent.com/assets/7582457/19630194/0ea33bf2-9953-11e6-91b9-31309f19a610.png)
![screenshot_2016-10-23-18-34-42](https://cloud.githubusercontent.com/assets/7582457/19630193/0e9ffd98-9953-11e6-8fc4-1c7a33274f1d.png)

**Comment by jterps08** [comment]
More information: The post does actually create. It's listed twice in USA group and once in NJ group. 

![screenshot_2016-10-23-19-29-30](https://cloud.githubusercontent.com/assets/7582457/19630420/44b77a3c-9958-11e6-8742-94f3dc2883d0.png)

**Comment by petervojtek** [comment]
@igaponov, creating Post fails with:

```
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/v2/groups/1/posts. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by petervojtek** [comment]
now i am  blocked due to 

```
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/v2/user/groups. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by jterps08** [comment]
I keep seeing this "No Access Control Allow" message/error. Why does this keep happening @igaponov @austinpapp @petervojtek ?

**Comment by igaponov** [comment]
@jterps08 https://github.com/PowerlineApp/powerline-server/issues/278 can't do anything with it

**Comment by igaponov** [comment]
@petervojtek fixed

**Comment by petervojtek** [comment]
I confirm it works now
