### ISSUE TITLE
Opening posts seems to be malfunctioning

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#369]
When trying to open one of the posts I just created (in issue #368 ), details are not loading

![screenshot_2016-10-23-19-28-31](https://cloud.githubusercontent.com/assets/7582457/19630406/18cf66f0-9958-11e6-9166-9319b7e70366.png)

**Comment by petervojtek** [comment]
@igor, we have this problem when getting Post details:

```
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/v2/posts/371. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by petervojtek** [comment]
I confirm it works now
