### ISSUE TITLE
The user who changed group permissions should be not displayed popup "group permissions have changed".

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#371]
the popup "group permissions have changed" is displayed to every group member and user must confirm the permission changes to stay in the group.
the user who made the changes in Manage group screen is also displayed the popup, which is unnecessary.

**Comment by jterps08** [comment]
Actually, I"m going to allow this behavior for now. I think it's a nice confirmation of what all group members will experience... Closing...
