### ISSUE TITLE
group management - send invites

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#372]
#356

**Comment by petervojtek** [comment]
@jterps08 , the invites design screen is expecting email to be entered, however current [API](https://api-dev.powerli.ne/api-doc#post--api-groups-invites-{status}-{group}) requires to enter user IDs.

<img width="678" alt="screen shot 2016-10-24 at 09 35 59" src="https://cloud.githubusercontent.com/assets/225506/19637075/6582c0e4-99cd-11e6-9707-4aedefd081bb.png">

It makes more sense to me to fill in there emails. (user ID is e.g. `JTest1`).
what do you think?

**Comment by jterps08** [comment]
Agreed - this used to be emails on FrontEndBundle for the backend.... it should be e-mails still.

**Comment by petervojtek** [comment]
@igaponov , please can you create such an endpoint which will allows to submit in a bulk list of email addresses of users I want to invite into a group?

**Comment by jterps08** [comment]
Previously, we limited the number of e-mail addresses that a user can invite at one time to 10 unless they were Silver or higher, I think, in which case it was 100+ at a time I think (will need to investigate in the code to be sure)... 

We certainly want to support inviting users by e-mail as part of this feature... Ideally, we want to limit the number of e-mails that a user can invite at one time based on what package they have -- HOWEVER, if that is more than an hour worth of work, don't do it, we'll come back to it later. We definitely want to be able to invite users by e-mail though...

**Comment by igaponov** [comment]
@petervojtek `PUT /api/v2/groups/{id}/users`
There is a mistake in docs, must be "Invite users from a list to join a group"

**Comment by petervojtek** [comment]
done.
