### ISSUE TITLE
group management: payment setup

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#373]
#356

**Comment by petervojtek** [comment]
@igaponov , which API endpoints should I use to CRUD credit card with a group ?

I am aware of this endpoint: https://api-dev.powerli.ne/api-doc#post--api-v2-cards
but I guess that one is meant for card-person relationship and not card-group relationship.

**Comment by jterps08** [comment]
My assumption is that you should be using the Stripe API directly. Our API/server should not be handling any payment information. We must use the remotely-hosted version of the Stripe.js library for processing. https://stripe.com/docs/custom-form for more information.

**Comment by petervojtek** [comment]
@jterps08 , yes, I communicate with stripe API to submit them the card details, but then I receive a token from stripe (after successful card registration) and this token is then stored on powerline backend. otherwise the powerline backend will lack the relationship between CC and user/group.

**Comment by jterps08** [comment]
Got it - just wanted to confirm. This is one of the more sensitive areas of the application that we need to be careful with. All customer data must be protected behind Stripe's secure system...

**Comment by igaponov** [comment]
@petervojtek https://api-dev.powerli.ne/api-doc#get--api-v2-groups-{group}-bank-accounts

**Comment by petervojtek** [comment]
@igaponov , when I try to add card to group, I experience this error:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/311/bank-accounts
Request Method:POST
Status Code:500 Internal Server Error

{"currency":"usd","type":"company","first_name":"1","last_name":"1","ssn_last_4":1235,"business_name":"1","address_line1":"1","address_line2":"1","city":"1","state":"1","postal_code":"1","country":"US","source":"tok_198PQgGH6acUMInAiz8fH8BC"}

{"code":500,"message":"You must provide a card that has the 'currency' field set when adding a card to a Stripe account.","errors":null}
```

I fill in the request `currency:usd`, so I am not sure what is the error message trying to say me..

**Comment by igaponov** [comment]
@petervojtek I think you need to create a bank account token (has prefix `btok_`): https://stripe.com/docs/api#create_bank_account_token, not a simple token (prefix `tok_`)

**Comment by petervojtek** [comment]
@jterps08 , can you please explain how the group payments should proceed?

regular users are charged directly via their credit card (no bank account info is provided).
however Igor suggests that group should provide their bank account information (along with the credit card information).

Also the design suggests that both account information and card information should be gathered for a group:

<img width="565" alt="screen shot 2016-10-26 at 10 30 31" src="https://cloud.githubusercontent.com/assets/225506/19718809/4bc5eabe-9b67-11e6-89c8-23971f310dfd.png">

I just want to make sure this is what you want, given that it will be more time consuming to implement bank account info gathering (compared to using just credit card).

I am not sure what is the purpose to gather the bank account information in case of a group  -- maybe some accounting/legal reasons?

please correct me if I am wrong -- if I understand it properly the money is always charged from credit card (not directly from bank account).. from purely money transactional point of view I do not see any added value in obtaining the bank account information (given that the money will always flow only in one direction -- from group back account to powerline back account)

**Comment by petervojtek** [comment]
i just realized that group can also receive money from crofdfunding so maybe that is the reason it needs a bank account..

**Comment by jterps08** [comment]
@petervojtek exactly - **receiving** money into a bank account is the reason for setting up a bank account with Stripe. According to Stripe, we can send money to a group's bank account **OR** to debit card (https://stripe.com/docs/connect/bank-transfers#bank-accounts) for crowdfunders/fundraisers... This is a key option for groups that fundraise/crowdfund.

For group subscriptions, we can **charge** the group on their card. We don't want to **charge** them on their bank account at this point as it's more of a hassle for us to set it up then we need. 

In the United States, we have something called "Know Your Customer" regulations that help us avoid theft/corruption/etc.... The way that we can act as a responsible vendor to reduce our risk is by providing Stripe the following information: (https://stripe.com/docs/connect/required-verification-information) name and address associated with the account PLUS:
legal_entity.dob.day  
legal_entity.dob.month  
legal_entity.dob.year  
legal_entity.first_name 
legal_entity.last_name  
legal_entity.ssn_last_4 (this can also be an EIN, basically the SSN equivalent for a business in the US)

we should be able to provide most of this information based on the user profile of the person entering the CC or bank account info automatically. Obviously we want to do all that we can to reduce the level of effort on the user's part for filling any of this out, while at the same time providing them the opportunity to edit it (similar to how we handle CC entry field from a group member' perspective)

We may need to ask for the DOB and the last 4 digits of the SSN when it comes to setting up crowdfunding/fundraisers...

**Comment by petervojtek** [comment]
@igaponov , i'd like to ask:

I can register bank account successfully to stripe and then associate bankAccount<->group via `POST api/v2/groups/{group}/bank-accounts`.

However when I will register a payment card (for a group), as far as I get it I can use only the user-card relationship `POST /api/v2/cards`, thus e.g. a group manager will register a card via stripe and then the relationship user-card will be stored to powerline backend.

the issue is, some other group manager will go to the manage group screen, he will see the associated bank account there (because of the bankAccount<->group relationship), but he will not see the card, because the card is not related to the group but to the other manager.

Please correct me if I misunderstand something in the relationship between card, group and bank account.

**Comment by jterps08** [comment]
I'm not sure what a00d3a1 is but we should try to pre-fill as much of the form as possible based on the user's profile or the group to help expedite data entry...

**Comment by petervojtek** [comment]
@jterps08, yes, I will prefill there the address fields from group profile.

**Comment by igaponov** [comment]
@petervojtek if I understand right, stripe uses two terms, cards and account. Cash is moving from cards to accounts. So our users have cards to make payments to groups with accounts. Why do you need to add a card for a group?

**Comment by jterps08** [comment]
@igaponov - for a group to pay for a subscription, they'll provide a CC... for a group to collect funds from a fundraiser, they'll provide a bank account. For a user to donate to a fundraiser, they'll provide a CC.

**Comment by igaponov** [comment]
@petervojtek check docs for `.../groups/{id}/cards`

**Comment by petervojtek** [comment]
ok, now it is possible to add card to group.

**Comment by jterps08** [comment]
@petervojtek Can you confirm that the Bank Account form includes the "country" field for the user to select from? I just remembered that Stripe only supports bank accounts in certain countries for collecting funds... https://stripe.com/docs/api#country_specs

We want to make sure that a group in England and a group in Mexico and a group in the US can all use this form properly

**Comment by petervojtek** [comment]
yes, currently I hardwired there 'country:US'.

@jterps08 , and which countries should be present in the dropdown -- all countries in the world?

**Comment by jterps08** [comment]
@petervojtek - same countries (and codes) as compatible with Stripe. Go here: https://stripe.com/docs/connect/required-verification-information and find the dropdown next to _"Viewing verification info for:"_ 

![image](https://cloud.githubusercontent.com/assets/7582457/19970781/6cdda492-a1b3-11e6-9d12-7db028160ca4.png)

**Comment by petervojtek** [comment]
ok, the list of countries is there.

@jterps08  I am not sure how we want to proceed with the bank account currency.
currently there is hardwired USD, however this does not seem to be satisfactory, e.g. when I tried to add a bank account from a Luxembourg bank, I was not allowed to do that with USD currency.

I can show there a currency dropdown with USD preset as default, however I am not sure if it makes sense to show all currencies in the world..or only currencies of the countries present in the dropdown..

**Comment by jterps08** [comment]
Thanks @petervojtek - I think the full list of currencies is: https://support.stripe.com/questions/which-currencies-does-stripe-support#currencygroup1 but I agree with you - I think only the currencies of the countries in the list (auto-selected to match: eg USD for US) makes sense...

I would assume that you could only select certain currencies based on the country your bank is in. For example, if you have a US bank account, it should only allow USD. 

The country specs API might be the easiest way of doing this: https://stripe.com/docs/api#country_specs

**Comment by jterps08** [comment]
But we can keep it simple and stick with currencies for only the countries present/supported in the dropdown.

**Comment by petervojtek** [comment]
@jterps08 , ok, now the list of currencies will change dynamically when you change country and will contain only those currencies which are [supported by stripe](https://support.stripe.com/questions/which-currencies-does-stripe-support) in given country .

@igaponov , is it possible that you have hardwired `country:US` when you communicate with stripe from backend regarding new bank account?

E.g. here I add japan testing bank account:

```
this is my payload to stripe, which is successsfull (and I receive token):
bank_account[account_number]:00012345
bank_account[routing_number]:110000000
bank_account[country]:JP
bank_account[currency]:JPY
bank_account[account_holder_name]:a
bank_account[account_holder_type]:company

and the here is my subsequent request to powerline:

Request URL:https://api-dev.powerli.ne/api/v2/groups/332/bank-accounts
Request Method:POST
Status Code:500 Internal Server Error

{"first_name":"a","last_name":"a","ssn_last_4":"1234","address_line1":"under bridge","address_line2":"a","city":"Los Angeles","state":"Nebraska","postal_code":"123","currency":"JPY","type":"company","business_name":"a","source":"btok_9WWMfeekUJo1zP","country":"JP"}

{"code":500,"message":"Stripe currently doesn't support currency jpy with country US.","errors":null}
```

**Comment by igaponov** [comment]
@petervojtek request to Stripe from backend:

```
POST /v1/accounts/acct_19BJamBeBqhPevnf

{"bank_account":"btok_9WWMfeekUJo1zP","email":"peter10@test.com","default_currency":"JPY","legal_entity":{"type":"company","first_name":"a","last_name":"a","ssn_last_4":"1234","business_name":"a","address":{"line1":"under bridge","line2":"a","city":"Los Angeles","state":"Nebraska","postal_code":"123","country":"JP"}}}
```

I think the problem is in your account's county. Maybe you should create another account (with country=JP) to test this case.

**Comment by petervojtek** [comment]
I am not sure if I understood you properly @igaponov, this is what I done now:
I created new powerline user PeterJP1 who has country Japan.

then I created new user group 346. and when i want to add japan bank account, I experience the same error as above, i.e.

```
the stripe communication is successful:

Request URL:https://api.stripe.com/v1/tokens
Request Method:POST
Status Code:200 OK

bank_account[account_number]=00012345&bank_account[routing_number]=1100000&bank_account[country]=JP&bank_account[currency]=JPY&bank_account[account_holder_name]=a&bank_account[account_holder_type]=company&key=pk_test_QUgSE3ZhORW9yoDuCkMjnaA2&payment_user_agent=stripe.js%2F15cb6da

{
  "id": "btok_9WtidRbkMxQ7EF",
  "object": "token",
  "bank_account": {
    "id": "ba_19DpujGH6acUMInAV9sA4xyD",
    "object": "bank_account",
    "account_holder_name": "a",
    "account_holder_type": "company",
    "bank_name": "STRIPE TEST BANK",
    "country": "JP",
    "currency": "jpy",
    "last4": "2345",
    "routing_number": "1100000",
    "status": "new",
    "name": "a"
  },
  "created": 1478674229,
  "livemode": false,
  "type": "bank_account",
  "used": false
}

but then powerline backend fails:

Request URL:https://api-dev.powerli.ne/api/v2/groups/346/bank-accounts
Request Method:POST
Status Code:500 Internal Server Error

{"first_name":"b","last_name":"c","ssn_last_4":"1234","address_line1":"d","address_line2":"e","city":"f","state":"g","postal_code":"1","currency":"JPY","type":"company","business_name":"a","source":"btok_9WtidRbkMxQ7EF","country":"JP"}

{"code":500,"message":"Stripe currently doesn't support currency jpy with country US.","errors":null}
```

**Comment by igaponov** [comment]
@petervojtek account's country is US, because we don't provide it on account creation.
@jterps08 which country should I use to create group's account? Group doesn't have a country.

**Comment by jterps08** [comment]
@igaponov use the group creator's country...

**Comment by igaponov** [comment]
@jterps08 note that group creator can be changed and a new creator can have another country

**Comment by jterps08** [comment]
good point @igaponov -- use the _current_ group creator's bank account when creating the account... but @petervojtek the frontend should be providing this input field to the user during bank account setup, right?

**Comment by petervojtek** [comment]
@jterps08 , during bank account creation the `country` is filled in in form once, but the value (e.g. JP)  is actually submitted twice:
- to the stripe api (which accepts JP without problems)
- and then to powerline api (which fails with JP)

I can submit the user provided country in 1st request and 'US' in the 2nd request if you want me to do that.

**Comment by igaponov** [comment]
@petervojtek Stripe doesn't allow to update account's country, so you need to create another one

**Comment by jterps08** [comment]
Okay, this is an important issue so I want to make sure I understand what's happening... 

> to the stripe api (which accepts JP without problems)
> and then to powerline api (which fails with JP)

@petervojtek Why are we storing the bank account country with the Powerline API? 

@igaponov Right now, the Stripe API accepts bank account country which is good... You are saying: "If user wants to update bank account, and new bank account is different country, this is not possible with Stripe - will need to delete account and create new account?" I just want to clarify what you're saying...

**Comment by igaponov** [comment]
@jterps08 yes, need to create a new account, but first update group owner's country

**Comment by petervojtek** [comment]
> Why are we storing the bank account country with the Powerline API?

@jterps08 , I have not designed the api, I don't know who made the decisition to require the country in [`POST /api/v2/groups/{group}/bank-accounts`](https://api-dev.powerli.ne/api-doc#post--api-v2-groups-{group}-bank-accounts) and I don't know how is it used on backend.

> Stripe doesn't allow to update account's country, so you need to create another one

@igaponov , currently when I try to add JP bank account I experience this:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/347/bank-accounts
Request Method:POST
Status Code:500 Internal Server Error

{"first_name":"b","last_name":"a","ssn_last_4":"1111","address_line1":"a","address_line2":"a","city":"a","state":"a","postal_code":"123","currency":"JPY","type":"company","business_name":"a","source":"btok_9XeXWKdEr9Vieb","country":"JP"}

{"code":500,"message":"SSN last 4 is only available for US accounts.","errors":null}
```

and when I try to submit the data without `ssn_last_4`, I experience this:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/347/bank-accounts
Request Method:POST
Status Code:500 Internal Server Error

{"first_name":"a","last_name":"a","address_line1":"a","address_line2":"a","city":"a","state":"a","postal_code":"1111","currency":"JPY","type":"company","business_name":"a","source":"btok_9XebyJEGpv9sOs","country":"JP"}

{"code":500,"message":"SSN last 4 must be exactly 4 digits.","errors":null}
```

**Comment by petervojtek** [comment]
ok, works now.
so last 4 numbers of SSN field is displayed only when US bank account is created.
