### ISSUE TITLE
group management: basic group settings

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#374]
#356

**Comment by petervojtek** [comment]
@igaponov , how can I update existing group settings (e.g. group Name, acronym, group type) ?

I am using `POST /api/v2/user/groups`  to create a group, however `PUT /api/v2/user/groups/{id}` does not seems to be meant to update group data but rather to `Join a group`
https://api-dev.powerli.ne/api-doc#put--api-v2-user-groups-{id}

**Comment by igaponov** [comment]
@petervojtek try `PUT /api/v2/groups/{id}`, check api doc for more information please.

**Comment by petervojtek** [comment]
@igaponov , i don't fully understand the fields being used in group CRUD methods.

For example, this is how I gather group details:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/311
Request Method:GET
Status Code:200 OK


{"total_members":5,"id":311,"group_type":0,"avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","manager_phone":"+1123","official_title":"Peter10Group6","official_description":"Peter10Group6","acronym":"10G6","official_address":null,"official_city":null,"official_state":null,"joined":1,"membership_control":"public","fill_fields_required":false}
```

there is a field named `official_title`.
However when using [`PUT /api/v2/groups/{id}`](https://api-dev.powerli.ne/api-doc#put--api-v2-groups-{id}), there is no  `official_title` field. On the other hand in the PUT endpoint description is some `official_name` field not present in GET.

Another confusing field is `official_type`. this is provided as integer in `GET`, but supposed to be submitted as string (e.g. `Educational`). I do not understand why is the API designed this way.

Next, according to api doc I am supposed to submit `username` field in PUT, but such field is not provided in GET and thus I don't know what is the value.

**Comment by igaponov** [comment]
@petervojtek it was like this in the old code. I can change and before deploy you'll adapt frontend code.

**Comment by petervojtek** [comment]
ok, I prefer to wait for @igaponov to update the GET and PUT methods to use same set of attributes.

**Comment by igaponov** [comment]
@petervojtek I'm ready to merge
1. group.official_title => group.official_name
2. activity.owner.official_title => activity.owner.official_name
3. `official_type` is a text field in db. You can probably get number for old records, but for new ones you should get text
4. We're going to delete group.username

**Comment by jterps08** [comment]
Let's make sure modifyinggroup.official_title doesn't screw things up... 

Official type is just a way for us to categorize the type of group -- it's used in the pricing strategy... business type groups cannot be silver tier - they can only be free/gold/platinum

**Comment by petervojtek** [comment]
@igaponov , feel free to change `official_title` -> `official_name`, it is easy for me to accomodate to that.

regarding `official_type` -- I am not sure if this means I would have to suppoed both integer and string to appear in GET group info. 

Currently for e..g. San Diego there is `group_type`field and it is integer:

```
{"total_members":13,"id":285,"group_type":3,"avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","manager_phone":null,"official_title":"San Diego","official_description":null,"acronym":null,"official_address":null,"official_city":null,"official_state":null,"joined":1,"membership_control":"public","fill_fields_required":false}
```

**Comment by jterps08** [comment]
(For Jesse's Reference: This is Edit Group Profile)

**Comment by igaponov** [comment]
@petervojtek `official_type` and `group_type` are different fields. Official type is a string. If you submit a string you will get a string. Do you want to change `group_type` to string too?

**Comment by jterps08** [comment]
I have no idea what the difference between these two actually is

**Comment by igaponov** [comment]
@jterps08 
`group_type`: common, country, state, local, special
`official_type`: Educational, Non-Profit (Not Campaign), Non-Profit (Campaign), Business, Cooperative/Union, Other

**Comment by jterps08** [comment]
Ah then we definitely need to keep each of these fields separately...

**Comment by petervojtek** [comment]
@igaponov , now I see I wrongly understood the difference between group_type and official_type. I prefer to be both strings so that I can easily understand the value and thus prevent confusion later.

**Comment by igaponov** [comment]
deployed

**Comment by petervojtek** [comment]
ok, so here is the state of the art:

<img width="819" alt="screen shot 2016-11-02 at 08 56 27" src="https://cloud.githubusercontent.com/assets/225506/19920641/4b4a0746-a0da-11e6-8acc-d25a07b967e0.png">

currently the form is missing following data:
- manager_first_name
- manager_last_name
- manager_email
- manager_phone

because they are not provided in `GET /api/v2/groups/{id}` (expect manager_phone).

@jterps08 , do you want these `manager_*` fields to be editable as well?

**Comment by jterps08** [comment]
@petervojtek for now, we do not need to expose these manager fields because we know who the group creator is on the backend... It would be good to display the group creator's name in the group profile screen, but we do not need to actually store any of those 4 bullets now.

**Comment by petervojtek** [comment]
@jterps08 , can I close this issue, or do you want to have this done as part of this issue? :

> It would be good to display the group creator's name

**Comment by jterps08** [comment]
Please include the group creator's name int he group profile screen.

**Comment by petervojtek** [comment]
@igaponov, it seems the group creator name is not present in the group details:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/332
Request Method:GET
Status Code:200 OK

{"total_members":1,"joined":1,"group_type_label":"common","id":332,"avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","manager_phone":"+1123","official_name":"AA20 R1","official_description":"AA20","acronym":null,"official_type":"Business","official_address":"under bridge","official_city":"Los Angeles","official_state":"Nebraska","membership_control":"public","fill_fields_required":false,"transparency":"public"}
```

**Comment by petervojtek** [comment]
thanks Igor.

done.
