### ISSUE TITLE
group management: manage users

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#375]
#356

**Comment by jterps08** [comment]
Group might be Open, Manual Approval, or Passcode... If Manual Approval, this screen must be able to Approve/Reject pending users. It should also provide owner/managers with the ability to remove any user. It should also provide the owner (not managers) with the ability to giver any user(s) manager rights.

**Comment by petervojtek** [comment]
@igaponov , which api endpoint am I supposed to use to remove user from group?

There is this endpoint [POST `/api/members/{id}/remove`](https://api-dev.powerli.ne/api-doc#post--api-members-{id}-remove), but it is not clear to me why it is POST and how to submit there both group ID and user ID.

Next, I am not sure how can I obtain member status info in a bulk, i.e. for each member of the group I need to find out:
- if his membership approval is pending
- if the user is owner or manager or regular user
- user email

I would prefer if the information will be provided via `GET /api/v2/groups/{id}/users`, which currently looks as following:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/311/users
Request Method:GET
Status Code:200 OK

{"page":1,"items":20,"payload":[{"id":73,"username":"Peter10","first_name":"Peter10","last_name":"Is Leader"},{"id":75,"username":"Peter12","first_name":"Peter12","last_name":"Peter12"},{"id":78,"username":"peter.vojtek","first_name":"Pavlik","last_name":"Morozov"},{"id":80,"username":"Peter30","first_name":"Peter30","last_name":"Peter30"},{"id":92,"username":"Peter35","first_name":"Peter35","last_name":"Peter35"}],"totalItems":5}
```

**Comment by igaponov** [comment]
@petervojtek 
1. added `DELETE /api/v2/groups/{id}/users/{user}`
2. added `email`, `join_status`, `user_role`

**Comment by jterps08** [comment]
@petervojtek it may make sense to combine group divisions into this tab as well - your choice... create/remove group divisions and add users to specific group divisions... else, it might make sense to define/manage the divisions elsewhere and have some sort of button here that allows users to be assigned to _multiple_ divisions...

**Comment by petervojtek** [comment]
@jterps08 , not sure what is the priority of group subdivisions -- as far as I get it it is not implemented on backend -- see #337

**Comment by petervojtek** [comment]
regarding the UI -- I would rather use two "sections"  -- one for user management and the other one for subgroups. they should be next to each other. i.e. I prefer to follow the design, because trying to have only one table with users which will also serve for subgroups will be harder to implement and more confusing to use.

<img width="504" alt="screen shot 2016-10-27 at 11 14 22" src="https://cloud.githubusercontent.com/assets/225506/19761506/9dd6d83e-9c36-11e6-878f-402fa5a52ed9.png">

<img width="596" alt="screen shot 2016-10-27 at 11 14 32" src="https://cloud.githubusercontent.com/assets/225506/19761507/a037e852-9c36-11e6-9883-f933b0b983de.png">

**Comment by petervojtek** [comment]
@igaponov , the `GET /api/v2/groups/{id}/users/{user}` does not seem to include user.id, which prevents me from using `DELETE /api/v2/groups/{id}/users/{user}` (which seems to accept only id as `{user}`:

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/295/users
Request Method:GET
Status Code:200 OK

{"page":1,"items":20,"payload":[{"join_status":"active","username":"1.JesseChen","first_name":"Jesse","last_name":"Chen","email":"jterps08z@gmail.com","user_role":"member"},{"join_status":"active","username":"austin","first_name":"Austin","last_name":"Papp","email":"austin@powerli.ne","user_role":"member"},{"join_status":"active","username":"Peter9","first_name":"Peter9","last_name":"Peter9","email":"peter9@test.com","user_role":"member"},{"join_status":"active","username":"Peter10","first_name":"Peter10","last_name":"Is Leader","email":"peter10@test.com","user_role":"owner"},{"join_status":"active","username":"Peter11","first_name":"Peter","last_name":"No 11","email":"peter11@test.com","user_role":"member"},{"join_status":"active","username":"Peter12","first_name":"Peter12","last_name":"Peter12","email":"peter12@test.com","user_role":"member"},{"join_status":"active","username":"Peter21","first_name":"Peter21","last_name":"Peter21","email":"peter21@test.com","user_role":"member"},{"join_status":"active","username":"Peter30","first_name":"Peter30","last_name":"Peter30","email":"peter30@test.com","user_role":"member"},{"join_status":"active","username":"Peter31","first_name":"Peter31","last_name":"Peter31","email":"peter31@test.com","user_role":"member"}],"totalItems":9}
```

**Comment by petervojtek** [comment]
@jterps08:
- can group owner delete himself from group?
- can manager remove owner?
- can manager remove other managers from group?

I know that:

> only group owners (not managers) can assign/remove 'group manager' privileges to their users.

**Comment by petervojtek** [comment]
@igaponov , it seems to be there is no endpoint to change group member `user_role` (usually from `member` to `manager` and vice versa) -- or did I missed it when searching the API doc?

**Comment by jterps08** [comment]
@petervojtek Yes, a group owner should be able to leave the group. once he leaves, ownership goes to the oldest (by membership) group manager or group member... If old group owner rejoins the group, he is joined as normal member...

**Comment by igaponov** [comment]
@petervojtek `POST /api/groups/join-group-manager/{id}` to join as a manager (you should be a member already)

**Comment by jterps08** [comment]
Only an _owner_ can assign group manager privileges to a group member. 

Group managers cannot assign group manager privileges to group members - this is a special permission limited to the grown owner/creator... Same with changing the subscription/payment information.

**Comment by igaponov** [comment]
@jterps08 with this endpoint user can join to a group as a manager, but owner should approve it (if membership control != public). But there is no endpoint to approve, so I think need to add both to v2 API.

**Comment by jterps08** [comment]
User always join group as a member. 
Owner may assign any member(s) with group manager rights. 

The word 'approve' is confusing me. There needs to be an endpoint to 'assign/remove' group manager privileges, not approve... The user does not request to be a group manager. The user does not join a group as a potential group manager... The group owner goes through the membership list and assigns a particular user with group manager rights...

**Comment by igaponov** [comment]
@petervojtek https://api-dev.powerli.ne/api-doc#put--api-v2-groups-{id}-managers-{user}

**Comment by petervojtek** [comment]
@igaponov , `PUT /api/v2/groups/{id}/managers/{user}` works properly to promote normal user to manager. But how can I downgrade user from manager to normal user?

**Comment by petervojtek** [comment]
@igaponov , when user membership is Approval and user Peter12 wants to join, he is properly listed as group member with `"join_status":"pending"`. 
Which API endpoint should I use to approve this user's membership? When I try to use `PATCH /api/v2/groups/{id}/invites/{user}`, the request is successful but user remains in `"join_status":"pending"`.

```
Request URL:https://api-dev.powerli.ne/api/v2/groups/340/invites/75
Request Method:PATCH
Status Code:204 No Content

Request URL:https://api-dev.powerli.ne/api/v2/groups/340/users
Request Method:GET
Status Code:200 OK

{"page":1,"items":20,"payload":[{"join_status":"active","id":73,"username":"Peter10","first_name":"Peter10","last_name":"Is Leader","email":"peter10@test.com","user_role":"owner"},
{"join_status":"pending","id":75,"username":"Peter12","first_name":"Peter12","last_name":"Peter12","email":"peter12@test.com","user_role":"member"},
{"join_status":"active","id":80,"username":"Peter30","first_name":"Peter30","last_name":"Peter30","email":"peter30@test.com","user_role":"manager"}],"totalItems":3}
```

**Comment by igaponov** [comment]
@petervojtek to approve user use `PATCH https://api-dev.powerli.ne/api/v2/groups/:group/users/:user`

**Comment by igaponov** [comment]
@petervojtek `DELETE /api/v2/groups/{id}/managers/{user}`

**Comment by petervojtek** [comment]
ok, hopefully all done here.
