### ISSUE TITLE
New Content Menu Font Size

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#377]
Please increase the font size by 25% for all menu items on the New Content Menu (new post, new poll, etc.)

**Comment by jterps08** [comment]
![screenshot_2016-11-13-17-46-59](https://cloud.githubusercontent.com/assets/7582457/20252681/4ec73ef4-a9f2-11e6-9664-5e563db872b1.png)

**Comment by eriklouis129** [comment]
fixed
![simulator screen shot nov 14 2016 10 31 57 am](https://cloud.githubusercontent.com/assets/20544710/20259489/978fd9e4-aa55-11e6-999f-ca7b16e08a64.png)

**Comment by jterps08** [comment]
awesome - marking ready for retest - can you reference the commit ID for reference please?

**Comment by eriklouis129** [comment]
fixed in "Erik" branch

**Comment by jterps08** [comment]
@eriklouis129 can you fix the last item "New Group Announcement" so that it can be visible?

**Comment by XamarinGuru** [comment]
fixed
![screen shot 2016-11-21 at 5 30 21 pm](https://cloud.githubusercontent.com/assets/22253123/20491012/4042cea6-b010-11e6-98c3-6393561c5b7a.png)

**Comment by eriklouis129** [comment]
check from eik-new branch

**Comment by jterps08** [comment]
https://github.com/PowerlineApp/powerline-mobile/commit/f7ac88073c86ea096d3b94b583ae112a279f6dfc
