### ISSUE TITLE
New Event - Pre-fill RSVP Options

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#378]
It would be great if the first two RSVP answer options were pre-filled with:
"Yes, I can make it"
"No, I can't make it" 

But still editable by the user.

**Comment by jterps08** [comment]
When clicking New Group Event, the form that appears should have the first two answer choice fields pre-filled with text above, editable by user. Not placeholder (gray) text that disappears when the user taps on the field, but ACTUAL text in the field.

**Comment by eriklouis129** [comment]
this is already combined with backend logic and UI.

so it is not enough by changing UI in order to implement this function.

maybe needed some changes logic, too.

**Comment by jterps08** [comment]
Thanks Erik - reassigning to Igor...

Igor - Please update the backend so that new event form has two pre-filled answer choices as per above. Very low priority.

**Comment by igaponov** [comment]
@eriklouis129 API has two endpoints: 
1. create a poll
2. add an option
Use the first one to create an event and then the second one to create two options.

**Comment by jterps08** [comment]
@eriklouis129 did you update based on @igaponov remark above? In the build that I have, it seems that this is placeholder text instead of actual field text.

**Comment by eriklouis129** [comment]
I know.
I tried to implement it using radio group.
but current logic already implemented with at least default two answers("Yes, I can do it", "No I can't do it") and extra answers.

so what I wanted was how I can fix it with backend api logic.

**Comment by jterps08** [comment]
I just need you to pre-fill the field text with actual text. I don't need it created on the backend, because I want the user to be able to change the answer choice text... I just want it filled in with actual text, not placeholder text.

**Comment by eriklouis129** [comment]
fixed
![screen shot 2016-11-21 at 6 06 08 pm](https://cloud.githubusercontent.com/assets/20544710/20492495/3ef1b1b6-b015-11e6-833d-00690ee1279f.png)

**Comment by jterps08** [comment]
bingo thanks
