### ISSUE TITLE
New Fundraiser Creation UI Changes

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#379]
1. Change "Is Crowdfunding" label to "Make this a crowdfunder?" 
2. When user turns on crowdfunding, alert pops up "If you reach or exceed your goal amount by the deadline, all of your supporters will be charged. If you do not reach that goal by the deadline, your supporters will not be charged."
3. Change "Custom Amount Answer" label to "Allow Choose Your Own Amount?"
4. Is it possible to remove the X next to the $0 amount option?

**Comment by eriklouis129** [comment]
any screenshot?
how to move the screen...

**Comment by jterps08** [comment]
When you have created new group, go to pencil icon to create new group content called "New Group Fundraiser"... A screen similar to below will appear:

![screenshot_2016-11-13-17-46-59](https://cloud.githubusercontent.com/assets/7582457/20252647/03a71188-a9f2-11e6-9116-bb4933338041.png)
![screenshot_2016-11-13-17-47-14](https://cloud.githubusercontent.com/assets/7582457/20252648/03a87668-a9f2-11e6-8ba4-5680c651b647.png)

**Comment by eriklouis129** [comment]
fixed
![simulator screen shot nov 14 2016 10 27 49 am](https://cloud.githubusercontent.com/assets/20544710/20259392/03428700-aa55-11e6-8bb8-88ccc1f31e80.png)
![simulator screen shot nov 14 2016 10 28 16 am](https://cloud.githubusercontent.com/assets/20544710/20259396/119f344c-aa55-11e6-8034-d1a7573028bd.png)
![simulator screen shot nov 14 2016 10 28 45 am](https://cloud.githubusercontent.com/assets/20544710/20259409/22dcaa6e-aa55-11e6-9bec-aaf27ededa32.png)

**Comment by jterps08** [comment]
awesome - marking ready for retest - can you reference the commit ID for reference please?

**Comment by eriklouis129** [comment]
fixed in "Erik" branch
