### ISSUE TITLE
Invite to Group for Post/Petition Authors

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#383]
If a post or petition is boosted, the author may invite supporters to a group. 

If boosted, the lightning bolt symbol appears in the Item Detail screen. 
Tapping the lightning bolt symbol opens up the Group Selector modal. It has a message "Invite this post's supporters to join a group. This can only be done once."
User selects group.

Related to https://github.com/PowerlineApp/powerline-server/pull/47

**Comment by petervojtek** [comment]
@jterps08 , the lightning icon is already used to manually boost post/user-petition.
is it ok to use following icon for the purpose of inviting to group?:

<img width="414" alt="screenshot 2016-11-21 13 19 42" src="https://cloud.githubusercontent.com/assets/225506/20482484/2f2090fe-afed-11e6-91bb-29d7ac61325d.png">

Which user can perform that action? any group manager, and group owner?
and which group should be in the list?

@igaponov , is there some specific API endpoint to "Invite this post's supporters to join a group. " 

I am aware of [this endpoint](https://api-dev.powerli.ne/api-doc#put--api-v2-groups-{id}-users), but that one requires me to provide the list the supporters in request.
 
And once it is called, how can I learn that it has been executed for a particular Post/UserPetition? (in comment above is written that such action can be done only once for a particual post/userPetition).

**Comment by jterps08** [comment]
Peter:
Icon is okay for now.
Only the post/petition author can tap the button. Only after the item has been boosted (manually or automatically it doesn't matter)
Only the user's current groups will appear. He does not need to be a manager or owner in these groups.

@igaponov There should be some sort of api endpoint for this that Habibillah worked on a while ago. https://github.com/PowerlineApp/powerline-server/pull/47 it may be incomplete, though...

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#get--api-micro-petitions-{id}-invite-{group_id}
@jterps08 it was done for micropetitions, now it's deprecated. Should I implement it for v2?

**Comment by jterps08** [comment]
Please. Thank you. Should work for user posts and user petitions only when the item has been boosted...

**Comment by igaponov** [comment]
@petervojtek 
Endpoint "Invite this post's supporters to join a group." is not good for rest api, it's better to use one endpoint to get all supporters and then submit their usernames with [this endpoint](https://api-dev.powerli.ne/api-doc#put--api-v2-groups-%7Bid%7D-users)

@jterps08 why is it possible to do only once?

**Comment by jterps08** [comment]
@igaponov Basically, I do not want the enduser to have the usernames of all of the supporters and I don't want to put this effort on the frontend... We do not show who supported the post on the frontend and this data shouldn't be leaving the backend. We need an endpoint that the frontend can call that says 1) if this user is the author of this post, and 2) this post has been boosted, then 3) invite all of the people who upvoted this post to 4) join X group... There could be thousands of people who upvoted the post that need to be invited to the group. So I want this all handled on the backend.

In terms of why we only do it **once per boosted post** -- for now, I don't want people to abuse this feature. Otherwise, it might dissuade people from upvoting on posts later because they get pestered with group invites.... The intent of this feature is exemplified below:

Joe is a member of Save the Whales and the Animal Lovers group... Joe's post about "Feeding the Whales" gets boosted in Animal Lovers group. Joe thinks to himself "Hmmm, I don't think we talk about feeding the whales ever in the Save the Whales group - they're really focused on saving the whales, not feeding them... I'm going to start up my own group"... So he goes and creates a group called "Feed the Whales"... He goes back to his original post and has to choose whether to invite all of the boosted-post's upvoters to Save the Whales or his new group "Feed the Whales" -- but he *must* choose. Otherwise, everytime he said something popular he would be able to invite everyone to each of his groups, which could get really annoying....

**Comment by igaponov** [comment]
@petervojtek `PUT /api/v2/groups/{id}/users` is now deprecated.
Use [`PUT /api/v2/groups/{id}/invites`](https://api-dev.powerli.ne/api-doc#put--api-v2-groups-{id}-invites) to invite users by usernames/post's upvotes/petition's signatures.

**Comment by petervojtek** [comment]
@igaponov , the `PUT /api/v2/groups/{id}/invites ` seems to work fine, however I miss some indicator which will tell me whether user already called this action or not, as written here:

> Invite this post's supporters to join a group. This can only be done once.

When user calls the `PUT /api/v2/groups/{id}/invites ` , in sonsequence can you please attach some attribute (e.g. `supportersWereInvited: boolean`) to post/userPetition detail to indicate the the invitation feature was already used by user so that I can hide the action button from UI (for that post/userPetition).

**Comment by igaponov** [comment]
@petervojtek `supportersWereInvited` attribute was added

**Comment by petervojtek** [comment]
ok, done
