### ISSUE TITLE
group management settings: manage required fields

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#384]
Define and manage the required fields that need to be filled out to join a group. Not sure how many the backend supports, but currently production allows 5. If we can allow up to 8 (with no backend changes) that would be great. 

Production reference: https://admin.powerli.ne/group/fields

Design note: In the future, we may want to allow the group manager to make this a string field or select from a drop-down list. Drop-down not in scope right now.

**Comment by petervojtek** [comment]
@jterps08 , there does not seem to be a limit on number on on-join-questions (I added there at least 9 pcs so far to basic user group).

**Comment by petervojtek** [comment]
ok, hopefully done. this is how it looks so far:

<img width="353" alt="screen shot 2016-10-27 at 13 48 52" src="https://cloud.githubusercontent.com/assets/225506/19766070/21269822-9c4c-11e6-91a4-5de756b1027f.png">

**Comment by jterps08** [comment]
Haha I like your mockup questions. That works.
