### ISSUE TITLE
Required Questionss

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#386]
1. When joining a group, activate text wrap on the displayed questions so that the user can view the entire question.
2. Replace trash-can icon and "remove" label with just the "X" button to maintain consistency.
3. Relabel to "Users are required to answer these questions in order to join the group"

**Comment by eric80** [comment]
@jterps08  any screenshot for this?

**Comment by jterps08** [comment]
![screenshot_2016-11-04-11-50-36 1](https://cloud.githubusercontent.com/assets/7582457/20013601/20d06436-a28a-11e6-93f7-31a6e834f37c.png)

It looks like we already have the word-wrap here, but it may be on the group-join screen that I was referring to... I'll try to test and find out.. Otherwise, #2 and #3 in list above are in screenshot here.

**Comment by eriklouis129** [comment]
how to move above screen?

**Comment by sirius2013** [comment]
very easy to fix

**Comment by jterps08** [comment]
Once you create your own group, go to My Groups, and select the group you created. This will open the Group Profile screen. As the group owner, you should see a Manage button. Click the Manage button to get to this screen.

**Comment by eriklouis129** [comment]
need your detail explain about "When joining a group, activate text wrap on the displayed questions so that the user can view the entire question."

**Comment by eriklouis129** [comment]
fixed
![simulator screen shot nov 14 2016 10 26 02 am](https://cloud.githubusercontent.com/assets/20544710/20259365/d838e16c-aa54-11e6-9414-71023508df42.png)

**Comment by jterps08** [comment]
great thanks, please provide commit ID for reference...

**Comment by eriklouis129** [comment]
fixed in "Erik" branch
