### ISSUE TITLE
Join group -- question fields not shown to newcomer

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#387]
I experienced the issue with owner of the group (created some question fields, left the group and joined again).. first check if this is special for the owner or it behaves the way for all newcomers).

**Comment by jterps08** [comment]
Owner creates group, automatically joined to group
Owner creates required questions for joining group
Owner leaves group.
System does X with ownership privileges -- @igaponov what happens to ownership privileges currently when owner leaves group? 
Old-Owner re-joins group, no longer owner. 
Old-Owner should see required questions as ALL group members need to answer these questions when joining a group, if questions are defined.

**Comment by igaponov** [comment]
@jterps08 like you said - the oldest manager (or the oldest member if there are no managers in the group) becomes an owner

**Comment by jterps08** [comment]
Awesome - just wanted to confirm. Thank you @igaponov

**Comment by petervojtek** [comment]
ok, fixed.
