### ISSUE TITLE
Unable to send any leader content

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#389]
Application hangs when an authorized group owner/manager tries to create leadership content. Content is never created. 
![screenshot_2016-10-28-17-50-57](https://cloud.githubusercontent.com/assets/7582457/19832115/513d6bc8-9de9-11e6-875d-3b6975dd7756.png)

![screenshot_2016-10-29-14-13-09](https://cloud.githubusercontent.com/assets/7582457/19832110/2d5bb6ce-9de9-11e6-8473-fa5f943ac938.png)

**Comment by petervojtek** [comment]
my apologies, that was  my stupid mistake in code. fixed.
