### ISSUE TITLE
Unable to upgrade subscription

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#390]
Should also ask for discount code to accept Stripe discount code as part of subscription submission process.

![screenshot_2016-10-29-14-06-14](https://cloud.githubusercontent.com/assets/7582457/19832121/7ccd9a88-9de9-11e6-8220-86ef904268ce.png)

**Comment by petervojtek** [comment]
@jterps08  this bug is duplicate of #357 -- and it is not working because I am waiting for @igaponov to answer this: https://github.com/PowerlineApp/powerline-mobile/issues/373#issuecomment-256571284
