### ISSUE TITLE
Relabel "Payment Setup"

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#392]
Relabel section title to "Fundraiser Setup"
Instructions in tab should say "In order to send fundraisers to your group, you must provide a bank account first."

Bank Account modal must ask for routing and account number twice to confirm correct information.
Bank Account modal SSN field can say "Last 4 digits of SSN/EIN"

![screenshot_2016-10-29-14-06-24](https://cloud.githubusercontent.com/assets/7582457/19832129/a6d36a10-9de9-11e6-8c92-1eba0479374b.png)

**Comment by eriklouis129** [comment]
fixed
![simulator screen shot nov 14 2016 10 35 49 am](https://cloud.githubusercontent.com/assets/20544710/20259615/20ca3d8a-aa56-11e6-8d9c-113835a88e2f.png)
![simulator screen shot nov 14 2016 10 36 09 am](https://cloud.githubusercontent.com/assets/20544710/20259620/28fbd270-aa56-11e6-9436-d0dd8d27b196.png)
![simulator screen shot nov 14 2016 10 36 26 am](https://cloud.githubusercontent.com/assets/20544710/20259626/334ff88c-aa56-11e6-832d-a8e3d1df2ac4.png)

**Comment by jterps08** [comment]
awesome - please reference commit ID for reference

**Comment by eriklouis129** [comment]
fixed in "Erik" branch
