### ISSUE TITLE
 Manage Group Members needs only to indicate name and role

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#395]
Manage Group Members needs only to indicate name and role. Currently shows username and e-mail addresses as well which are not necessary. 

Also, from a UI perspective, we can simplify buttons to icons X (remove), checkmark (approve), and some other manager toggle icon (manager/non-manager - default non-manager).

**Comment by petervojtek** [comment]
@jterps08 , I removed the "remove" and "approve" text labels and the unnecessary user details, but I doubt there exist icons  "promote to manager" and "downgrade to regular member" which will be intuitively understood without text labels.

If you can suggest some icons I will use them. best if you can use some of those: http://ionicons.com/

**Comment by jterps08** [comment]
Okay thanks Peter... I think the up-arrow and down-arrow is fine for now.
