### ISSUE TITLE
New Menu Shortcut: Create New Group

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#398]
Add an icon to the menu to jump directly to group creation screen.

**Comment by eriklouis129** [comment]
fixed
![simulator screen shot nov 14 2016 10 34 25 am](https://cloud.githubusercontent.com/assets/20544710/20259571/eea37592-aa55-11e6-9f5c-7802968c91b5.png)
![simulator screen shot nov 14 2016 10 34 39 am](https://cloud.githubusercontent.com/assets/20544710/20259574/f49bd412-aa55-11e6-8ffd-ce120c87e5e8.png)

**Comment by jterps08** [comment]
For "New Group" icon, can you use different icon that indicates 'new' or 'create'... In fact, "Create Group" might be a better label. Please reference commit ID. Thank you!

**Comment by eriklouis129** [comment]
fixed
![screen shot 2016-11-14 at 5 25 56 pm](https://cloud.githubusercontent.com/assets/20544710/20272825/6b02465c-aa8f-11e6-9d32-3973525b94ba.png)

**Comment by jterps08** [comment]
I still am not sure I like the look of that icon for Create Group... It doesn't stand out enough compared to My Groups. Can use just make the icon a single giant plus sign + instead? This is a pathway for a potential customer so I'll probably have to experiment with other icons in the future - but for this task for you under the contract, let's just change it to + icon and we can close this... Thanks for your patience.

**Comment by eriklouis129** [comment]
fixed
![screen shot 2016-11-14 at 7 21 50 pm](https://cloud.githubusercontent.com/assets/20544710/20277151/a79d6d48-aa9f-11e6-82c0-4b83bd5b68ef.png)

**Comment by jterps08** [comment]
perfect thanks!

**Comment by jterps08** [comment]
fixed in https://github.com/PowerlineApp/powerline-mobile/commit/ababd82825a444cd5505b943b8bb7046862ef6f8
