### ISSUE TITLE
UI: New Poll Creation

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#399]
The Group Selector Overlay should cover the entire screen so that the user cannot tap anything 'behind' the group selector.

![screenshot_2016-10-31-11-25-41](https://cloud.githubusercontent.com/assets/7582457/20007181/7e539268-a271-11e6-99fe-0c8a04636af0.png)

**Comment by eric80** [comment]
@jterps08 
can you add workflow to go this screen please?

**Comment by jterps08** [comment]
Hey @eric80 From the Home Screen, click on the New Content icon (Pen and Paper) in the upper right hand corner and select "New Group Poll" from the drop-down list...

The overlay needs to extend to the bottom of the screen so that the user can't tap on anything in the background (e.g. "add answer" button).

**Comment by eric80** [comment]
okay, got it.

**Comment by eriklouis129** [comment]
There is no "New Group Poll" in the drop-down list.

it contains only "New Post" and "New Petition"

**Comment by jterps08** [comment]
@eriklouis129 - We can add you to the Slack channel so we can discuss further. Please look for an invite via e-mail! :-)

**Comment by jterps08** [comment]
@eriklouis129 since this is the first issue to work on in the contract, please knwo that you will have to create a group first under your own account THEN try to create new content with the pencil icon on the main screen in the upper right hand corner. After you select New Group (anything) is when the issue appears. The gray overlay should cover the entire screen so that the user doesn't try to click on the "Add Answer" button etc.

**Comment by eriklouis129** [comment]
fixed
![simulator screen shot nov 14 2016 10 24 09 am](https://cloud.githubusercontent.com/assets/20544710/20259302/8437b8cc-aa54-11e6-843e-82ff40fd38dd.png)

**Comment by jterps08** [comment]
awesome - marking ready for retest - can you reference the commit ID for reference please?

**Comment by eriklouis129** [comment]
fixed in "Erik" branch
