### ISSUE TITLE
Humanize error responses from backend when submitting forms

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#403]
currently mostly in group management when submit fails and backend responds with error, I only display the error in raw form:

<img width="320" alt="screen shot 2016-11-02 at 08 37 13" src="https://cloud.githubusercontent.com/assets/225506/19920216/a3488c54-a0d7-11e6-824c-1ad1eced54e0.png">

**Comment by jterps08** [comment]
I will expand this definition specifically for Stripe errors

**Comment by igaponov** [comment]
All endpoints should return a response with the same structure: `{"code": xxx, "message": "Message ...", "errors": {...}}`
For 5xx codes alert with text like "Error has occurred, try later".
400 - show `message` to user or use `errors` object to show errors in a form.
404 - app uses api in wrong way or there is invalid data in db.

**Comment by jterps08** [comment]
This is good Igor - the intent of this issue was to ensure that `message` displayed to user is humanized and not technical jargon. We can address at a later time.

**Comment by igaponov** [comment]
@jterps08 now our API shows Strip's errors. From Stripe API: `message: A human-readable message providing more details about the error. For card errors, these messages can be shown to your users.`

**Comment by jterps08** [comment]
awesome
