### ISSUE TITLE
Group management - what is manager not allowed to do (compared to owner)

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#405]
@jterps08 , can you please summarize here what group manager is not allowed to do in Group Management screen (when compared to owner) ?

**Comment by jterps08** [comment]
Manager cannot give manager privileges to users. Owner can.
Manager cannot change group subscription. Owner can.
Manager cannot change group payment information (bank account or CC). Owner can.

I think that's it...

**Comment by petervojtek** [comment]
@jterps08:
- can manager remove other managers froup group?

**Comment by jterps08** [comment]
Good question @petervojtek ... I'm going to say "NO". 

A manager can remove any member from the group. 
Only an owner can remove manager privileges from a user.
Only an owner can remove a manage from the group.

**Comment by petervojtek** [comment]
ok, done
