### ISSUE TITLE
User joins group with fields required to fill in on join -- manager/owner cannot see the answers

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#408]
there is currently no place in GUI where manager can see the answers

**Comment by jterps08** [comment]
This actually raises the broader issue of reporting results for all items:

(In Scope)
- Membership Roster
- Poll Responses
- Petition Responses
- Fundraiser Responses
- Event Responses

Responses include names (if response not private), response/answer choice, comments, and required information fields.
Membership roster includes user profile information (only permissioned-information) plus required information fields. 

(Out of Scope)
User Post Responses - Ability for people (not just leaders) to review the responses to a user's post, anonymized, by general user profile information and linked electeds.

So... The question is how can we achieve the in-scope objectives above as easily as possible? XLS downloads for now?

**Comment by jterps08** [comment]
I'm actually going to create a new issue #410 to have that conversation regarding comments above...

The only place we have ever shown the Required Information responses in the past is in the Membership Roster...

However, for advanced reporting purposes, we may want to be able to say, "Of the 1000 people who answered this poll, how many were under the age of 35 and who filled out the required information field of favorite whale as "humpback whale"? etc...

**Comment by petervojtek** [comment]
if the information should be available in form of table-oriented data, then the XLS export is something which will be implemented on backend (and there will be only some "Export data" button in app).

Not sure how about the analytics queries like "how many responded yes and were from north carolina".. there should be gui to allow to build such query, but the query itself will be executed on backend.

**Comment by jterps08** [comment]
see #410 for the continuation of report discussion

**Comment by jterps08** [comment]
Closing this as we've addressed via Reports in 410. thanks peter
