### ISSUE TITLE
Registration: Address Entry - Google-assisted Fill-out

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#411]
When the user starts entering the street address, the Google address assist pop-up correctly appears. If the user taps an option in the pop-up, the form correct fills out.

If the user taps the wrong option by mistake and starts to fill out the Street Address again, all fields are not consistently replaced with new address in pop-up.

This issue seems to occur only when the user has 1) already selected an address the first time, and 2) tries to select the top choice in the popup the second time he fills out the Street address... The town field is not re-placed. 

It would be good to test the behavior of this feature because it really does help the user expedite the registration process..

**Comment by petervojtek** [comment]
@jterps08 , do you mean this form? ;

<img width="412" alt="screenshot 2016-11-21 09 04 03" src="https://cloud.githubusercontent.com/assets/225506/20474964/83fa1272-afc9-11e6-8b49-182e83b76b24.png">

>  The town field is not re-placed.

there is no field named Town. there is City, but from my experience it seems the address is replaced properly.

here is the address I fill in into the first field (Street Address): `2150 Market Street`

and then I have several options provided by google. when I pick one option, and later change it to another, following fields are replaced with new value: zipcode, city, state.

**Comment by jterps08** [comment]
@petervojtek exactly 

Town/City is the same thing. That's okay.

But when you pick one option and change it to another, *all* fields need to be replaced with new value.

**Comment by petervojtek** [comment]
> all fields need to be replaced 

@jterps08 , which are are all fields?
which other fields should be filled in apart from zipcode, city, state (which are filled in) ?

**Comment by jterps08** [comment]
@petervojtek the actual address that is suggested in the Google suggestion box

If the suggested address is 135 Washington Street Apt 1 Hoboken NJ 07030 and the user selects that, I would expect to see the entire form filled out with whatever available information was provided Street Address 1 Street Address 2 City State Country Zip Code... 

It doesn't make sense to select a different address and not refresh all the fields.

**Comment by petervojtek** [comment]
@jterps08 , this is how the register new user form looks like:

<img width="354" alt="screenshot 2016-11-23 11 39 02" src="https://cloud.githubusercontent.com/assets/225506/20558715/b5ea7750-b171-11e6-85d4-f3fecea17816.png">


following fields are updated when you pick some address provided by google address search:
street address, zipcode, city, state.

then there is field named `Apt/Suite` which is not filled in by the address autofill. 

can you please specify what exactly should I change in the existing behaviour of this form?

**Comment by jterps08** [comment]
@petervojtek -- I don't understand where you are confused. Please contact me on Slack if there are any additional questions on this issue. This is taking too long to resolve via GH.

1. Type in partial address in first field.
2. Google suggests a list of different addresses.
3. User selects first address.
4. All fields that can be filled out (street address zip code city state and country) are filled out with Google info.
5. User selected wrong address.
6. User goes back to first field, starts typing and selects different address.
7. All fields that can be filled out are filled out with Google info <-- This is where you wrote "and then I have several options provided by google. when I pick one option, and later change it to another, following fields are replaced with new value: **zipcode, city, state.**" <-- This needs to be _street address_, zip code, city, state, and _country_.... All fields need to be replaced with new values based on the selected address from the suggestion box (the second, third, or fourth etc. time they are selecting an address from the suggestion box)

It's very easy for the user to select the wrong suggested address from Google the first time. SO, when user changes their address using suggestion drop-down, we need to make sure that it actually changes all fields. It does not. That's the problem. As a user, I expect whatever address I select to fully replace all address-related fields (not e-mail obviously).

**Comment by petervojtek** [comment]
> street address, zip code, city, state, and country

yes, in the previous comment I did not entered all the fields properly, it is my mistake. I apologize.
So currently from my experiments with the register new user form, I can see that following fields are being replaced with new values when another suggested address is picked:
Street Address, zipcode, city, state, country.

> All fields need to be replaced with new values based on the selected address from the suggestion box

Street Address, zipcode, city, state, country are replaced when another suggested address is picked. 
the `Apt/suite` is not replaced, because it is not filled in by the autosuggest.

What should I change on this behaviour?

**Comment by jterps08** [comment]
This is the correct behavior - I guess I will have to close this issue and try to replicate the issue in the next build. Thanks.
