### ISSUE TITLE
Phantom Social Activity for New User

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#412]
I just created a new user who is not following anyone and has not joined any groups... And yet, the following information appears - not even for today, but for a few days ago according to the Social Activity Feed...

I assume this is a backend issue?

![screenshot_2016-11-04-09-22-38](https://cloud.githubusercontent.com/assets/7582457/20007166/69c067a4-a271-11e6-9547-0e7eb647ee49.png)
![screenshot_2016-11-04-09-21-28](https://cloud.githubusercontent.com/assets/7582457/20007165/69bfa51c-a271-11e6-9a52-184ba81f710d.png)

**Comment by jterps08** [comment]
@igaponov can you explain what was happening? I was a new user and I was receiving updates for people I wasn't following and groups I hadn't joined. Can you explain what happened?

**Comment by igaponov** [comment]
@jterps08  There were three type of activities, `follow-%entity%-commented`, that are pushed only for people who subscribed to entities, not for followers, so they don't have `following` attribute. But `GET /.../social-activities` uses `following` attribute to query rows. You've seen old activities without `following` attribute.
