### ISSUE TITLE
New Menu Shortcut: Manage Group

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#413]
Add an option "Manage Group" to the main menu that appears only if user is a leader of any group(s). 
Tapping the button displays the "Group Selector" modal with only options that the user can manage.
Tapping the appropriate group leads directly to the group management screen.

**Comment by petervojtek** [comment]
@jterps08 , on smaller screens (iphone4s below) the existing menu is already too large for the screen. adding there additional item will force user to screen down the menu (which is something we should avoid).

<img width="343" alt="screenshot 2016-11-28 09 57 29" src="https://cloud.githubusercontent.com/assets/225506/20661880/3cf295ce-b551-11e6-8907-b5e53aea6941.png">

**Comment by jterps08** [comment]
@petervojtek please do not work on P3/P4 items. I don't want you spending any time on P3/P4 items. I said this in Slack.

**Comment by jterps08** [comment]
Okay - good point... Let's do this instead @petervojtek 

On the My Groups Screen, let's list the groups the user is a manager/owner for first in one list (new)... followed by the rest of the groups the user is part of in alphabetical order (same as now)

We can label the section "Managed Groups"
