### ISSUE TITLE
create leader content -- allow user to choose whole group or only group section when publishing content

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#414]
based on #337

**Comment by petervojtek** [comment]
@igaponov , currently when creating&publishing new leader content (e.g. event), it is sent to all group members. How can I denote that I want to send the content only to a group section?

It seems there is not such parameter in [publish poll call](https://api-dev.powerli.ne/api-doc#patch--api-v2-polls-{id}).

**Comment by igaponov** [comment]
@petervojtek now if the group has sections a new content will be sent to section's users. There is no functionality to send it only to one group section. Do you need to add it?

**Comment by petervojtek** [comment]
lets see what will say @jterps08 , here is design which suggest that there should be a section picker when publishing a content:

<img width="398" alt="screen shot 2016-11-11 at 09 04 56" src="https://cloud.githubusercontent.com/assets/225506/20208364/009c42e8-a7ee-11e6-9585-06768d1cb8e9.png">

**Comment by jterps08** [comment]
The section picker allows you to send to either 1) all group members, or 2) a specific group section. It would be ideal if the leader could select one ore more group sections, but "All" or "one section only" is fine too. 

The default is always All.

**Comment by igaponov** [comment]
@petervojtek do you need it only for polls?

**Comment by jterps08** [comment]
All leader content @igaponov (not user posts or user petitions)

**Comment by igaponov** [comment]
@jterps08 that means all kind of polls and announcements, right?

**Comment by jterps08** [comment]
Yes please @igaponov - poll, leader petition, event, discussion/news, fundraiser/crowdfunder, announcement

**Comment by petervojtek** [comment]
ok, done.

the checkboxes are constrained by following rules:
- by default option All is checked, all other are unchecked.
- you can pick several sections
- if you choose a section, All is automatically unchecked 
- if you choose All, all other checkboxes are unchecked
- if you uncheck all checkboxes, All option is automatically checked

this is how it looks like:
<img width="399" alt="screenshot 2016-11-14 09 16 45" src="https://cloud.githubusercontent.com/assets/225506/20257635/26b76d40-aa4b-11e6-90ec-f0726834bf38.png">

**Comment by jterps08** [comment]
sweet thanks Peter
