### ISSUE TITLE
New Group Creation Forum - Unable to Submit

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#417]
Latest build erik+develop... unable to submit New Group form... Fill out form, hit send, shows spinner, stays on form. Should take me to new group profile screen.

**Comment by petervojtek** [comment]
@igaponov , when trying to create a group following response comes from server:

```
Request URL:https://api-dev.powerli.ne/api/v2/user/groups
Request Method:POST
Status Code:500 Internal Server Error

{"manager_first_name":"Peter10","manager_last_name":"Is Leader","manager_email":"peter10@test.com","manager_phone":"+1123","official_name":"G61","official_type":"Non-Profit (Not Campaign)","official_description":"G61","acronym":"G61"}

{"code":500,"message":"The endpoint you've tried to access does not exist. Check your URL.","errors":null}
```

**Comment by jterps08** [comment]
@igaponov is this resolved now due to Server-410 above or still open? I'd like to get the latest build as soon as possible. 

@petervojtek - develop+erik was working well for me with the exception of the issues that I found yesterday (namely, creating new group and my Reps listing screen)... Not sure how these broke and if they were due to Erik's work or igor or you... I have not tested sorting or notifications (let's pray that notifications are working exactly as expected) ... Please advise if we can close this and get a build with bugs completed.

**Comment by igaponov** [comment]
@jterps08 resolved

**Comment by jterps08** [comment]
Keeping it open with Ready for Retest, letting Peter verify to close

**Comment by petervojtek** [comment]
it works.
