### ISSUE TITLE
Confusing Subscription Flow

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#419]
Currently, user needs to go to Fundraiser Setup tab to Add Payment Card for Subscription Level... We should move Add Payment Card section from Fundraiser Setup to Subscription Level tab. If group does not have card setup, the screen

**Comment by petervojtek** [comment]
@jterps08 , it seems you did not finished the sentence:

>  If group does not have card setup, the screen

**Comment by jterps08** [comment]
sorry...

... If the group does not have a card setup, the screen should automatically show the CC entry screen when the user taps a subscription package other than Free.

**Comment by petervojtek** [comment]
ok, done. the CC details are at the end of the Subscription plan section.
when you pick a non-free plan and group has no CC, the add CC popup is displayed, and when the card is successfully added, the group will change its plan to the desired one.
