### ISSUE TITLE
Unable to Tap on "Invite Followers to Group"

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#420]
I try to tap on Invite Followers to Group from Group Profile screen... button stays visible, but does not result in pop-up as expected.

**Comment by petervojtek** [comment]
I cannot reproduce this bug. as Peter10 I can successfully click Invite button in top right corner in G60 group detail and the invititation request is sent successfully

**Comment by jterps08** [comment]
I cannot reproduce it either
