### ISSUE TITLE
Save Credit Card Fails

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#421]
From My Settings Screen, user goes to Add Card, enters information, hits Submit. Nothing happens. No error, no card added.

**Comment by petervojtek** [comment]
@jterps08 , I cannot reproduce the bug (at least as Peter12) -- I can successfully add a card with number `4012888888881881`.

**Comment by jterps08** [comment]
perhaps its because I have an "old" user that I'm trying to do this with... 

![screenshot_20161121-074927](https://cloud.githubusercontent.com/assets/7582457/20483275/2c872bce-afbf-11e6-856f-f03567a2a6d4.png)

**Comment by igaponov** [comment]
@jterps08 you need to go back to live mode or create a new customer

**Comment by jterps08** [comment]
Okay @igaponov can you explain why it's not creating new customer now or adding credit card to current customer in test environment? If you can't, that's okay... I just need to make sure this works in live mode for current users (and new users). I should always be able to add/remove a credit card for an existing user or a new user.

**Comment by igaponov** [comment]
@jterps08 there is a customer in our db for your user (so the system doesn't need to create a new one) created in Stripe's live mode, but now we use test mode and Stripe returns an error, because customers for live and test modes are different.

**Comment by jterps08** [comment]
ahhh that makes total sense. The app doesn't know that we switched to test mode, but the user was registered in live mode... got it. Thanks.
