### ISSUE TITLE
Expired Poll is showing up in Priority Zone

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#422]
Logged in as user 1.JesseChen. There is a poll "Something" in Build Test Three. I try to answer, but I can't because it's expired. Expired content should not be in the priority zone.

**Comment by igaponov** [comment]
@jterps08 this poll was expired yesterday, 17:21 UTC. You added your comment at 14:59 UTC, so it must be in prioritized zone. What did you do to answer it?

**Comment by jterps08** [comment]
I was unable to answer it. I could only add a comment. 

Or maybe I had answered it previously but it was still showing up in the priority zone.

**Comment by igaponov** [comment]
@jterps08 what do you mean "unable to answer"? Did you get an error? Or there is no a button to answer in app?

**Comment by jterps08** [comment]
no buttons to select an answer choice

**Comment by igaponov** [comment]
@petervojtek what is the condition to hide the button?

**Comment by petervojtek** [comment]
I confirm that expired poll was displaying "Answer" button in activity newsfeed (there was no condition to hide it in the source code).

I added the condition so that the "Answer" button is hidden when poll is expired.

**Comment by jterps08** [comment]
Ok, we can keep it closed but - to be clear - it was showing a red dot. It was in the priority zone. I would ask you to find it yourself, but it has now actually expired. It was showing a red dot before it was expired and either 1) after I had answered it or 2) I was unable to answer it -- not clear whether it was 1 or 2.

**Comment by petervojtek** [comment]
> It was showing a red dot before it was expired and either 1) after I had answered it or 2) I was unable to answer it -- not clear whether it was 1 or 2.

at the time I inspected it yesterday the `boosted` attribute (set by backend) was already set to `expired`.

**Comment by jterps08** [comment]
Okay will close, but hopefully it does not re-appear as an issue...
