### ISSUE TITLE
Missing Images in Newsfeed

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#424]
There are three ways that images can appear in the newsfeed:
1) Metadata Preview
2) Attached Video Thumbnail Preview
3) Attached Image

Somehow, this is all not functioning. We built this a long time ago (I believe bakbanga did most of the work on 2 and 3 but you may have done the work on #1)... https://github.com/PowerlineApp/powerline-mobile/commit/4daf0eb449b47ed15deb8cdca2b8a64fc77087f0 https://github.com/PowerlineApp/powerline-mobile/commit/03e0e7e5d390c3ef37c59f9b12e7d49c5136e500

#1 - when there is a URL inside an item, metadata is leveraged to display "meta data preview" as shown below. This would not be in production.
#2 - When a video URL is attached to leader content item, thumbnail/still is shown. User should be able to tap and play the video inside the newsfeed without opening up different app. This might be partially in production.
#3 - When a picture is attached to leader content item, thumbnail is shown. User should be able to tap on the image and have full-display of the image. Imgix should be leveraged. This might be partially in production.

 Partial View (picture attached to poll) - old screenshot
![screenshot_2015-06-30-08-58-40](https://cloud.githubusercontent.com/assets/7582457/20485028/d5939416-afc7-11e6-9ddd-193a792975c1.png)

Full View (picture attached to a poll, ignore the SAF bug) - old screenshot
![delayed ui switch to saf](https://cloud.githubusercontent.com/assets/7582457/20485102/1b54f92c-afc8-11e6-8094-ca05df381fae.png)

Unfortunately I do not have screenshots of attached videos or pictures, but we did have them working.

**Comment by petervojtek** [comment]
@jterps08, if I understand properly, the case "#1 - when there is a URL inside an item" has nothing to do with attachments (in the context of this issue). it is just an url inside e.g. post body text.
that is why I rather deal with it in separate issue #426

**Comment by petervojtek** [comment]
@igaponov, I am looking for a way to display "play youtube video" in activity newsfeed for an leader item.

When I attach a video URL to e.g. a leader discussion, then the activity for this discussion looks like this:

```
{"zone":"prioritized","id":1056,"title":"","description":"group discussion with video attachment","description_html":"group discussion with video attachment","sent_at":"2016-11-23T13:32:29.000Z","expire_at":"2016-11-25T13:32:29.000Z","responses_count":0,"owner":{"id":341,"type":"group","group_type":0,"official_name":"G60","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png"},"user":{"official_title":"Peter10 Is Leader","full_name":"Peter10 Is Leader","id":73,"type":"user","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"leader-news","id":485},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":"https://img.youtube.com/vi/yS-vW2CQX2g/0.jpg","updated_at":"2016-11-23T13:32:29+0000","poll":{"is_subscribed":true,"answers_count":null},"user_petition":null,"post":null}
```

there seems to be some `"image_src":"https://img.youtube.com/vi/yS-vW2CQX2g/0.jpg"`, but I would rather expect to leverage `metadata` attribute for that purpose [like here](https://github.com/PowerlineApp/powerline-mobile/issues/426#issuecomment-262513684) and I would expect there to be the youtube video URL. 

please correct me if I miss some point. I need the video from attachment to appear in the activity item payload to avoid any additional requests.

**Comment by jterps08** [comment]
@petervojtek - Regarding your comment:

> there seems to be some "image_src":"https://img.youtube.com/vi/yS-vW2CQX2g/0.jpg", but I would rather expect to leverage metadata attribute for that purpose like here and I would expect there to be the youtube video URL.

We do want the video to appear in the newsfeed and clickable as embedded youtube video directly in newsfeed. It's not simply a static thumbnail image. It should be ready to play within the newsfeed itself. This should be working this way in production...

**Comment by igaponov** [comment]
@petervojtek metadata comes from item's description. Image/video is item's educational context.

About newsfeed - it's getting more complex every time you guys want to add a new attribute to any item, query becomes slower and page speed reduces. If you want to add metadata to every item I have to add 20 sql queries for each request.

In this case we should start to think about creating of newsfeed asynchronously and return cached response.

**Comment by jterps08** [comment]
This is a good point @igaponov ... We need to think about this at scale... The frontend only loads 20 items at a time, but we want to be sensitive to how we design this so that we're not hurting our performance later OR so that we are not creating a situation where we are not being efficient with our limited resources at AWS. 

@austinpapp please weigh in here. 
@petervojtek and @igaponov SPECIFIC TO THE COMMENTS ABOVE: Let's do what we need to do to meet the requirements at this point. If an image is attached to an item, I need to see it in the newsfeed. If a video is attached to an item, I need to see it in the newsfeed and play it from within the newsfeed. If a URL is in a post or user petition, I need to see the metadata image/text/description in the newsfeed... Let's worry about performance tuning later, but let's try to design it with performance in mind now. 

IN GENERAL: There are certain design concepts that are not negotiable. Making things as easy as possible for the user are generally not negotiable... That said, I understand how these little features like upvoting a post or signing a post or following the author of a post etc can result in additional queries etc...  I need you guys to be thinking about the scalability and performance at the system. The average user will only be part of 10-15 groups MAX... Within each group, there could be a 0 to 200 or 300 posts per day... There could be thousands of groups on the platform. There might be millions of users on the platform (God willing one day)... Leveraging load balancing technology and AWS services, we can scale up/down as we need from a hardware standpoint, but the software should be written in such a way so that we're not *unnecessarily* relying on additional hardware computing power.

**Comment by petervojtek** [comment]
>  If you want to add metadata to every item I have to add 20 sql queries for each request.

@igaponov , even if you would need to use the N+1 SQL antipattern, it is definitely faster to fire 20 sql requests on backend that to call 20x1 http requests where every request triggers one sql call.

 if we make a HTTP request for every leader content item in activity newsfeed to check if it has attachments (and display them if yes):
 * we will use the so called [N+1 perfomance antipattern](https://secure.phabricator.com/book/phabcontrib/article/n_plus_one/).
* the screen will be almost unresponsive unless all the 20 http requests are handled, and when they will finally resolve, the items may start to move on the screen because the attachments will be rendered -- this is another [well known issue to avoid](https://css-tricks.com/content-jumping-avoid/).

-----

few more thoughs on the "I have to add 20 sql queries for each request"

If I understand properly, when I make `GET /activities`, you think of matching some `activity items` table with `attachments` table. I am not sure how the `attachments` table is designed, but I guess that one attachment = 1 line in table (maybe that is the reason you cannot use one JOIN?). this is unfortunate for the query, because it has to seek the whole table because it does not knows how many results can we get. But, there are two reasons why it actually does not has to be that bad:
* attachments are attached only to leader content items (and not to Post and User Petitition).
* I guess that 90% of leader content items will be without attachments

so at the end the `attachments` table may not be very large.

**Comment by jterps08** [comment]
I appreciate your analysis @petervojtek... 

@petervojtek and @igaponov - please let me know if you require additional information from me.

**Comment by igaponov** [comment]
@petervojtek added `activity.poll.educational_context` attribute

**Comment by petervojtek** [comment]
@igaponov , I attached a video to a poll, but I cannot see it in its activity newsfeed item `poll.educational_context`:

```
{"zone":"prioritized","id":1066,"title":"","description":"poll with attachment 1","description_html":"poll with attachment 1","sent_at":"2016-11-28T08:24:48.000Z","expire_at":"2016-11-30T08:24:48.000Z","responses_count":0,"owner":{"id":341,"type":"group","group_type":0,"official_name":"G60","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png"},"user":{"official_title":"Peter10 Is Leader","full_name":"Peter10 Is Leader","id":73,"type":"user","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"question","id":491},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":"https://img.youtube.com/vi/jhnKBKZvb_U/0.jpg","updated_at":"2016-11-28T08:24:48+0000","poll":{"is_subscribed":true,"answers_count":null},"user_petition":null,"post":null,"answers":[]}
```

it am sure I attached it, as visible here:

```
Request URL:https://api-dev.powerli.ne/api/v2/polls/491/educational-contexts
Request Method:GET
Status Code:200 OK

[{"id":76,"text":"https:\/\/www.youtube.com\/watch?v=jhnKBKZvb_U","type":"video","imageSrc":null}]
```

**Comment by petervojtek** [comment]
ok, now attachments are displayed in activity newsfeed in following manner:
* when there are multiple images attached, only first one is displayed (not sure if you want to display all of them if there are e.g. 3 images attached)
* when there are multiple video attached, only first one is displayed
* clicking the video starts playing it
* clicking photos leads to item detail

@jterps08 , originally you wrote, that:
> User should be able to tap on the image and have full-display of the image.

but the image is already displayed with almost full width in the activity newsfeed. I find it useless to implement some fullscreen image viewer - the image will be almost the same size as im newsfeed.
but if you really want it that way, I can implement it.

**Comment by jterps08** [comment]
Thanks @petervojtek good work... 

Re: full screen image viewer, this is primarily to address the issue of detailed images (think infographics) that may not be legible on the mobile device. The point of viewing in full screen would be to pinch and zoom as needed. I would be open to a "long-press to save to device" concept if you think that would be easier/more effective. We just need to give people a way to zoom in on those attachments...

**Comment by petervojtek** [comment]
@jterps08 , you are right, I have not realized that there may be infographics and people would like to zoom in.

**Comment by jterps08** [comment]
@petervojtek if you have no P1/P2 items, you can work on this

**Comment by petervojtek** [comment]
@jterps08 , fullscreen image viewer added. it works in activity newsfeed and item detail when the item has an image attachment.
* when you click an attachment image, it is displayed in fullscreen
* when you click the fullscreen image, it will disappear (close) the fullscreen mode
* when in fullscreen mode,  you can zoom in the image by [pinch-zoom gesture](https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/UIScrollView_pg/ZoomZoom/ZoomZoom.html). I tested it on android and iphone.

this is how it looks like in full screen. as you can see, the top bar is still visible in fullscreen mode. if needed, it is possible for the fullscreen image to occupy whole screen estate including the top bar, but that will be more time consuming.

<img width="326" alt="screenshot 2016-12-06 09 45 11" src="https://cloud.githubusercontent.com/assets/225506/20918938/c2e0d5c6-bb99-11e6-81f3-6ff401945ce2.png">

**Comment by jterps08** [comment]
@petervojtek can you confirm that the attached image is being handled with imgix both in the newsfeed and in full-screen viewer?

**Comment by petervojtek** [comment]
@jterps08 , this is URL of an image provided as attachment as backend:
http://devpowerline.s3-website-eu-west-1.amazonaws.com/educational/583d3b4d5a4f3.jpeg

if it is supposed to be served from another domain/in different size, it has to be addressed on backend.

**Comment by jterps08** [comment]
@igaponov as a matter of practice we need to always default to serving images with imgix please for performance reasons... Can you make the update where needed to ensure that this is being processed through imgix? Thanks.

**Comment by igaponov** [comment]
@petervojtek fixed
