### ISSUE TITLE
@mentions not working in post/petition body

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#431]
User tries to create post or user petition with @mention and failure occurs. 

@mentions work correctly in comments.

Screenshot TBD

**Comment by petervojtek** [comment]
@jterps08 , so far cannot reproduce the bug, I can create Post and User Petition with @mention in description text successfully.

**Comment by jterps08** [comment]
Yeah, I'm definitely getting an error whenever I try to create a post or a petition on Android with the @mention in the description text. I will post the screenshot this morning.

**Comment by jterps08** [comment]
So weird - now I can't replicate it either! Well, that works for me... closing! :-)
