### ISSUE TITLE
Priority Zone: Author's Boosted Posts

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#432]
A user authors a post or user petition.
Author is unable to upvote/downvote that post or sign that petition (correct).
Group leader manually boosts the post or user petition.
The post or user petition is moved into the priority zone (correct)
But the author's cannot mark his own post/user-petition as read/answered so it is stuck in priority zone (incorrect).

Author must be able to move his own post / petition out of the priority zone if it becomes boosted. 

Screenshot TBD

**Comment by petervojtek** [comment]
@igaponov , this needs to be first implemented on backend, i.e. when I notify backend that user-petition/post has been read, there should be following business logic:
`when markAsRead(item, person), if person == author && item.isBoostedForThatPerson, set item.isBoostedForThatPerson = false`

**Comment by jterps08** [comment]
![screenshot_20161130-092431](https://cloud.githubusercontent.com/assets/7582457/20756067/549266fc-b6df-11e6-8318-3556ce6797a7.png)

**Comment by igaponov** [comment]
@petervojtek I've added a clause to the db query on backend, you just need to test.

**Comment by petervojtek** [comment]
@igaponov , I am confused by the activity newsfeed behaviour.

I create a Post and here is its correspoding activity item:

```
{"zone":"non_prioritized","id":1094,"title":"","description":"Test 3","description_html":"Test 3","sent_at":"2016-12-01T08:34:01.000Z","expire_at":"2016-12-03T08:34:01.000Z","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Is Leader","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"user":{"official_title":"Peter10 Is Leader","full_name":"Peter10 Is Leader","id":73,"type":"user","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"post","id":422,"group_id":341},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-12-01T08:34:01+0000","poll":null,"user_petition":null,"post":{"is_subscribed":true},"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":0,"answers":[],"quorum":0}
```

Now I manually boost the Post and then there appears two activity items for it, and both feature the Post as boosted:
```
{"zone":"prioritized","id":1095,"title":"","description":"Test 3","description_html":"Test 3","sent_at":"2016-12-01T08:35:13.000Z","expire_at":"2016-12-03T08:34:01.000Z","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Is Leader","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"user":{"official_title":"Peter10 Is Leader","full_name":"Peter10 Is Leader","id":73,"type":"user","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"post","id":422,"group_id":341},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-12-01T08:35:13+0000","poll":null,"user_petition":null,"post":{"is_subscribed":true},"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":0,"answers":[],"quorum":0}

{"zone":"prioritized","id":1094,"title":"","description":"Test 3","description_html":"Test 3","sent_at":"2016-12-01T08:34:01.000Z","expire_at":"2016-12-03T08:34:01.000Z","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Is Leader","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"user":{"official_title":"Peter10 Is Leader","full_name":"Peter10 Is Leader","id":73,"type":"user","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"post","id":422,"group_id":341},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-12-01T08:34:01+0000","poll":null,"user_petition":null,"post":{"is_subscribed":true},"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":0,"answers":[],"quorum":0}
```

is this an intended behaviour?

**Comment by igaponov** [comment]
We had the same question in https://github.com/PowerlineApp/powerline-mobile/issues/165#issuecomment-239072614 but after discussion that issue was closed and I didn't fix it.

**Comment by jterps08** [comment]
We do not need two items. Is that an easy fix @igaponov ? I noticed that too. It's probably P3, but if it's quick I'd make it P2...

**Comment by igaponov** [comment]
@jterps08 its easy

**Comment by jterps08** [comment]
ok thanks @igaponov we only need one item. Can you get rid of the second one? Otherwise all behavior should be the same (e.g. priority zone, notifications, etc).

**Comment by petervojtek** [comment]
ok, seems to work now in such manner, that when author reads his own boosted Post/User Petition, it is no longer in priority zone.
