### ISSUE TITLE
Slow Manual E-mail Registration

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#434]
Currently, the user fills out the registration form and hits submit.
User is currently waiting 15s-30s before tour guide is shown. 

We either need to speed this process up or show the user something that displays progress. For example an animated list "We are linking you to: 
Your elected leaders at the local level.
Your elected leaders at the state level.
Your elected leaders at the national level.
Your local group.
Your state group.
Your federal group." Checkmarks or something...

**Comment by petervojtek** [comment]
done. 
the checkmarks are progressing by 1 checkmark per 2 seconds pace, but the last checkmark will turn `checked` only when backend replies that registration is finished. if the registration is actually finished faster than in 5x2 seconds, then it will proceed to guide screen as soon as server will notify us that registration is successfully finished.

<img width="322" alt="screenshot 2016-12-08 09 30 36" src="https://cloud.githubusercontent.com/assets/225506/21002988/175da58a-bd29-11e6-888d-54f8d097e3a5.png">
