### ISSUE TITLE
Question: Android Permissions Behavior

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#435]
On one device, I get the list of permissions as shown to approve each time I install.

On another device, I do not get the list of permissions as shown to approve each time I install. I am assuming that this later version of Android keeps track of permissioned apps even if I uninstall/reinstall? Just want to make sure we're getting the right permissions (no more, no less).

Screenshots TBD

**Comment by petervojtek** [comment]
@jterps08 , on later android versions (android 6.0+), the app asks for permissions only when an actions requiring the permissions is really about to be performed (e.g.  take a photo).

In contrast, older android (pre 6.0), asked you for all the permissions at one place when you installed the app.

here are more details:
https://developer.android.com/training/permissions/requesting.html

> I am assuming that this later version of Android keeps track of permissioned apps even if I uninstall/reinstall

I would say that works only on app update, not uninstall&install.

**Comment by jterps08** [comment]
got it thanks @petervojtek
