### ISSUE TITLE
activity newsfeed - video not displayed on iPhone

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#438]
there is empty space instead of video. happens only on iPhone, android and browser (chrome) work properly.

![unadjustednonraw_thumb_1f](https://cloud.githubusercontent.com/assets/225506/20876574/6f95c998-bac3-11e6-8195-a1f6f5eb258c.jpg)

**Comment by jterps08** [comment]
Can you make sure you test the iphone for attached images and URL metadata preview? I have been unable to run that test on iphones yet...

**Comment by petervojtek** [comment]
@jterps08  jere is url metadata preview image attachment on iphone:

![img_0030](https://cloud.githubusercontent.com/assets/225506/20957022/a9b4a8a2-bc4d-11e6-9c6a-5c2acbe71e0a.PNG)

![img_0031](https://cloud.githubusercontent.com/assets/225506/20957025/afbf8352-bc4d-11e6-85af-f2430eb481b8.PNG)

**Comment by petervojtek** [comment]
also happens on newer iphones

**Comment by petervojtek** [comment]
fixed, however the behaviour on android and iphone is bit different:
* on android, the player will start playing inside the embedded player area. there is a button which allows to switch the video to fullscreen.
* on iphone, when users taps the video, the youtube video will automatically start playing on fullscreen. it is not possible to play the video in non-fullscreen mode.

apart from that, there is this minor issue on iphone #443
