### ISSUE TITLE
Social Activity Feed - Showing Weird Items

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#444]
In the post below, Kirsten Chen is logged in. She commented on Jesse Chen's post, but the label is wrong. The label says "Kirsten Chen commented on **your** own post." It should say "Kirsten Chen commented on **Jesse Chen's** post"... Same with the vote activity. This isn't her post. 
![img950328](https://cloud.githubusercontent.com/assets/7582457/21184187/4ae85986-c1d9-11e6-8036-94a96c57dc96.png)

In the post below, Jesse Chen is logged in a couple minutes after Kirsten Chen has registered. The activities that show below show the request to join New York, USA, groups, but those are not his. Those should appear in Kirsten's feed, not in Jesse's feed. He's not joined to New York and USA groups. 
![screenshot_20161210-123809](https://cloud.githubusercontent.com/assets/7582457/21184188/4ae8fbe8-c1d9-11e6-96ef-82160008e284.png)

We need to make sure the Social Activity Feed is reporting the appropriate updates based on the user that is seeing them.

**Comment by igaponov** [comment]
@jterps08 we don't have an activity with text "Kirsten Chen commented on Jesse Chen's post". You just don't have to see this activity.

**Comment by jterps08** [comment]
That's fine. We don't need to show the user her own activity.... user Kirsten never should have seen "Kirsten Chen commented on your own post."

**Comment by jterps08** [comment]
So is this fixed from your perspective @igaponov ?

**Comment by igaponov** [comment]
@jterps08 must be fixed, I've checked this endpoint on the dev server for your user.
