### ISSUE TITLE
Membership List Avatars

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#445]
Avatars are not appearing when the user goes to the Group Profile screen and selects "membership list". Avatars should be displayed same way they are served in newsfeed (with imgix).

**Comment by jterps08** [comment]
If user avatar is presented, it should display through imgix. (backend may need to change in order to provide this, not sure)...  If user avatar is not available, then ng-letter icons should show like below... Currently no image is showing for Membership List screen

![screenshot_2016-09-08-08-35-37](https://cloud.githubusercontent.com/assets/7582457/21336586/68c3ff14-c634-11e6-8774-6d9b555e92d9.png)

**Comment by jterps08** [comment]
@igaponov can you double check that when backend is returning group membership list, that the group member avatars are being provided with appropriate imgix information (should serve up avatar similar to how they are served in newsfeed)? It may already be doing this and the problem is on the frontend... Not sure.

**Comment by jterps08** [comment]
This should be ready for you @bakbanga

**Comment by devotebest** [comment]
@jterps08 
`Avatars are not appearing when the user goes to the Group Profile screen and selects "membership list". `
do you have screenshot(no appearing avatar) of this issue?

**Comment by jterps08** [comment]
The issue seems to be resolved now. It looks like this was the backend fix that Igor implemented above. Apologies!
