### ISSUE TITLE
Group Permissions Changed Behavior

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#447]
Should open the profile screen from the quick action button... Currently only opens Social Activity Feed

**Comment by jterps08** [comment]
When the notification pops up, the user can tap the Open button. It should show the Group profile screen. It does not. 

![screenshot_2016-09-22-08-01-47](https://cloud.githubusercontent.com/assets/7582457/21336550/370663f4-c634-11e6-914d-1b82df1b4d7e.png)

![screenshot_20161219-214353](https://cloud.githubusercontent.com/assets/7582457/21336573/5968ab00-c634-11e6-8c4e-9c5cf533f4ac.png)

**Comment by devotebest** [comment]
@jterps08 
How could I send Push notification for testing?

**Comment by jterps08** [comment]
Unfortunately, we are going to have to wait until notifications is fixed first... However, the way this would normally be triggered is:

User A creates group
User A is group owner. User A is a group leader.
User B and C joins group. User B and C are group members.
User A goes to Group Profile screen via My groups. User A can see "manage group" button because he is a group leader. User A can change group permissions from Manage Group Screen by checking or unchecking different boxes (address, phone, etc.).
When User A makes these changes and saves them, this action will trigger notification alert to Users B and C.

**Comment by devotebest** [comment]
@jterps08 
I can't test with one device?
Is there any admin panel to send push notification?

**Comment by jterps08** [comment]
@devotebest I don't think you can test with one device. Unless you're logged into your emulator and using that under one account (User A) and you have a different account on your mobile/table device maybe? (User B and C)

**Comment by jterps08** [comment]
Tested on Android 6.01 successfully. Tried to test on Android 5.01 but was unable to login with Facebook to test. Logged in manually on 5.01 and it worked.
