### ISSUE TITLE
Missing ability to upload/change/remove group avatar

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#448]
When managing a group, the group leader needs the ability to upload/change/remove a group avatar. Currently all other fields are available to change, but not avatar... Process should be similar to how the user can update their own avatar.

**Comment by jterps08** [comment]
I can't tap the image to change/edit/remove...

![screenshot_20161219-212213](https://cloud.githubusercontent.com/assets/7582457/21336507/f442aff0-c633-11e6-8bcd-e732970536d1.png)

**Comment by jterps08** [comment]
@igaponov can you make sure there's an endpoint in place for adding/changing/removing group avatar?

**Comment by igaponov** [comment]
Use `POST  /api/v2/user/groups` to add, `PUT /api/v2/groups/{id}` to change and `DELETE  /api/v2/groups/{id}/avatar` to delete an avatar. Check API doc for more information.

**Comment by devotebest** [comment]
@jterps08 
Could I get app design about when click "avatar"?

**Comment by jterps08** [comment]
@devotebest Whatever you think is best... Either we can make it an additional field in the Profile Setup drawer or we can allow the user to tap the avatar and change it from there as if it were a similar process to the Edit My Profile screen where the user can change his own avatar. The key issue to address is the removal of the avatar must be replaced by the NG-Letter concept (currently implemented, it shows the first initial of the group name when no avatar exists). So group should be able to add/edit/remove their group avatar. Easiest and most conventional UX preferred.

**Comment by devotebest** [comment]
@jterps08 
I will use ionic Actionsheet to show "Upload/Remove/Cancel" button when click Avatar.
here is example. http://codepen.io/ionic/pen/jLylA
![image](https://cloud.githubusercontent.com/assets/10233895/22048567/c45e905a-dd68-11e6-879d-f90bb0080a94.png)

1. **Upload** will be same like Profile image update
2. **Remove** will remove avatar
3. **Cancel** will cancel action.

**Comment by jterps08** [comment]
Works for me. Thanks @devotebest

**Comment by devotebest** [comment]
@jterps08  
This is API from @igaponov 
**Use POST /api/v2/user/groups to add, PUT /api/v2/groups/{id} to change and DELETE /api/v2/groups/{id}/avatar to delete an avatar. Check API doc for more information.**
Is there any API to operate with Only Avatar?
Right now, After upload image for avatar, we should click "Save" button at **Profile Setup** section?
![image](https://cloud.githubusercontent.com/assets/10233895/22049250/25daf770-dd6d-11e6-9d3b-c0f6cc8cb9fe.png)

**Comment by igaponov** [comment]
@devotebest I didn't know anything about UI, so there is no separate endpoint to upload avatar. You can use `PUT /api/v2/groups/{id}`, send all current data + new avatar after upload, so no need to push "Save" button. But if you want I can add an endpoint for avatar.

**Comment by devotebest** [comment]
@igaponov 
yes, I need endpoint for avatar.

**Comment by igaponov** [comment]
`PUT  /api/v2/groups/{id}/avatar`

**Comment by devotebest** [comment]
![image](https://cloud.githubusercontent.com/assets/10233895/22091719/4b4e9270-de33-11e6-8957-96651dafabb2.png)
@igaponov 
I tried to update avatar as above request, but got below error.
`{"code":400,"message":"Validation Failed","errors":{"children":{"avatar":{"errors":["The mime type of the file is invalid (\"inode\/x-empty\"). Allowed mime types are \"image\/png\", \"image\/jpeg\", \"image\/jpg\"."]}}}}`

**Comment by jterps08** [comment]
Does this work now @devotebest ?

**Comment by devotebest** [comment]
@jterps08 
It doesn't work yet.
FYI @igaponov

**Comment by igaponov** [comment]
Blocked by #455

**Comment by igaponov** [comment]
Should be fixed now.

**Comment by jterps08** [comment]
@devotebest please investigate and let us know if it is ready to proceed

**Comment by devotebest** [comment]
@jterps08 will check this now.

**Comment by jterps08** [comment]
This is working... Can you add the little indicator to the upper right-hand corner of the group avatar so that users know that they can tap on it to update it? This is the way it looks for user profile. This would only appear for group owners/managers in the Manage Group screen... @devotebest 

Highlighted in red... 
![image](https://cloud.githubusercontent.com/assets/7582457/22255444/66b235ee-e225-11e6-9e58-85d7d3dabffe.png)
