### ISSUE TITLE
Restore "Posts remaining" counter

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#449]
When the user creates a new post or petition, he should be able to see how many more posts he is allowed that month in that particular group. We used to have this and it was removed. The user needs an idea of how many posts they have left in the group.

**Comment by jterps08** [comment]
Should be available for posts or petitions... This is how it used to look

![screenshot_2016-08-05-23-01-04 1](https://cloud.githubusercontent.com/assets/7582457/21336503/e215588c-c633-11e6-9dcd-b8b87dbf974f.png)

**Comment by devotebest** [comment]
@jterps08 
there is no field like **data.group.available**, so remained counter will no appeared.
https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/templates/posts/create.html#L24-L26

there is field **"group.petition_per_month"**, so I am about to show this field.
but I want to make sure with backend developer.

**Comment by jterps08** [comment]
@igaponov can you confirm that group.petition_per_month represents the number of posts that user has left for the month in that particular group/community?

**Comment by igaponov** [comment]
@jterps08 it represents the number of __posts__ / __user petitions__ that user has left for the month in that particular group/community.

**Comment by devotebest** [comment]
@igaponov 
so we can use this, right?

**Comment by jterps08** [comment]
Yes, that works fine @devotebest

**Comment by jterps08** [comment]
I can see the counter @devotebest but when I create a post in a group (e.g. United States), I would expect to see the number decrease. Instead, it still says 5... I would expect it to decrease with each post made... 

@igaponov can you confirm this is working as expected?

**Comment by igaponov** [comment]
This property shows a limit, not a remained count.

**Comment by jterps08** [comment]
Hmm... That's interesting. I wonder if this had been handled on the frontend before. What's the level of effort to change it to remaining count, @igaponov ?

**Comment by devotebest** [comment]
we need remained count. :)
@igaponov

**Comment by devotebest** [comment]
@igaponov
any good news with this please?

**Comment by igaponov** [comment]
Use `posts_remaining` and `petitions_remaining` attributes.

**Comment by devotebest** [comment]
@igaponov 
make sure those attributes are available, I can't see those attributes, can see instead of petition_per_month.
