### ISSUE TITLE
Missing Group Name Label on Item Detail Screen

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#450]
Above the description text, the item detail screen should display the group in which the item was posted. Currently there is no way to understand where the item was posted except for group avatar (which may or may not be provided).

**Comment by jterps08** [comment]
The first image doesnt show the group name, the second image shows only the group name Build Test Three... The field should be "Author FullName | Group Name"

![screenshot_20161130-093342](https://cloud.githubusercontent.com/assets/7582457/21336490/cb71cebc-c633-11e6-8286-901b1bc6c772.png)
![screenshot_2015-01-07-16-27-28 1](https://cloud.githubusercontent.com/assets/7582457/21336489/cb71ae46-c633-11e6-84ed-ec9b4baebf53.png)

**Comment by devotebest** [comment]
@jterps08 
how to get `payment request` screen?

**Comment by jterps08** [comment]
For clarity @devotebest this is the "Item Detail Screen" template... it's the same screen that's used for a post, user petition, leader poll, leader petition, leader discussion, leader fundraiser/crowdfunder, and leader event... The template already features the author name across all content, we just need to add the pipe and the group name to that same row as described above.

**Comment by devotebest** [comment]
@jterps08 
yes, I found out how to fix that on `first screen`.
but I am still trying to find out how to go `payment request` screen.

**Comment by jterps08** [comment]
payment request screen is the old name for a fundraiser or crowdfunder... I don't think we label it "payment request" any longer (the screenshot above is old and is only to illustrate the group name). 

To get there, you would need to create and publish a fundraiser for your group members. This would require that you setup a bank account for the group. I believe that our Stripe setup is still in TEST mode. In which case, if it is, you can enter the information provided in the Stripe API https://stripe.com/docs/testing for fake bank account information in order for the app to allow you to proceed with creating and publishing the fundraiser.

**Comment by jterps08** [comment]
@devotebest I can see the group name, which is great... however it is hyperlinking to the author's profile screen. Can you hyperlink it to the group profile screen instead?

**Comment by jterps08** [comment]
Thank you!
