### ISSUE TITLE
Unstarring a Favorite item from Favorites List removed wrong item (offset by 1)

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#451]
User saves an item to the Favorites from the newsfeed by tapping empty star. Item is saved to Favorites List. (Correct).
User unsaves an item from the Favorites from the newsfeed by tapping golden star. Item is removed from Favorites List (Correct).
User saves an item to the Favorites from the newsfeed. User visits Favorites screen. User taps golden star to remove Item 2 from the list. Item 1 is removed instead (Incorrect).

**Comment by jterps08** [comment]
![screenshot_20161216-161931](https://cloud.githubusercontent.com/assets/7582457/21336470/bd2b2b28-c633-11e6-96c1-6704fbbec359.png)

**Comment by jterps08** [comment]
@devotebest I haven't tested this fix on iOS. I see 5603c12 references android. I assume 87e146c was for iOS. Please confirm this is fixed on both platforms. I did test on Android, so I am closing.

**Comment by devotebest** [comment]
@jterps08 
 sure it worked fine on ios. :)
