### ISSUE TITLE
User Profile showing wrong content as user's posts

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#452]
This is not the newsfeed. This is the list of items that appears when someone is looking at a user's profile screen. Should show the posts by the viewed user that were made in the same groups that logged-in user is also in.

For example, if Jesse is logged in and looking at Austin's posts. And Austin and Jesse are in USA group and New Jersey group and Save the Whales group, but Austin is in Wanamassa group and Surfing group and Jesse is in Hoboken group and Skiing group, then...

Austin's user profile screen shows all of Austin's posts in USA, NJ, and Save the Whales to logged-in user Jesse, but not Wanamassa or Surfing groups.

If Mike is logged in and is in USA group and he looks at Austin's user profile screen, he will only see Austin's posts in USA group because Mike and Austin do not share any other groups together.

**Comment by jterps08** [comment]
I'll talk to you about this separately Igor.. 178 should come first.

**Comment by jterps08** [comment]
Please fix this as part of #468

**Comment by igaponov** [comment]
@rudjdev which endpoint is used to get posts for another user's profile?

**Comment by rudjdev** [comment]
@igaponov  /api/profile/info/[id] is used

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#get--api-v2-users-{id}-posts

**Comment by oleg201119** [comment]
@igaponov can you please change the structure  of response data from api - "/api/v2/users/[id]/posts" same as the response from "/api/v2/activities" ?

**Comment by jterps08** [comment]
Have we resolved this yet?

**Comment by jterps08** [comment]
Once the frontend commit is made by @oleg201119 , we can mark this as closed as I've confirmed in DEV
