### ISSUE TITLE
Push Notifications Error for iOS/Android

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#455]
When logging into the mobile app on both iOS and Android, the user is presented with "Failed to registed your device to push notifications. This may happen when you login on another device under your account. Please logout and login on this device."

Logging out and logging back in does not solve the problem. This occurs with both FB and E-mail Login.

**Comment by devotebest** [comment]
When register token on device, I got this error, so maybe need backend developer to understand what is this.
`{"data":{"code":500,"message":"The security token included in the request is invalid.","errors":null},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://api-dev.powerli.ne/api/endpoints/","data":{"type":"ios","token":"e8e1785c3849174ed291518f25bd3168a8d3cba05074bf796ab4475b05515a3a"},"headers":{"Token":"4ib2h6u6glc044408sckg4wcs0ww4k8wkskc4kwgk00ssskgg16"}},"statusText":"Internal Server Error"}`

**Comment by jterps08** [comment]
Thanks David... Please be sure to assign @igaponov as needed... Igor can you take a look?

**Comment by jterps08** [comment]
What's the latest on this? Did we get appropriate credentials from @austinpapp ?

**Comment by igaponov** [comment]
@jterps08 not yet

**Comment by igaponov** [comment]
@jterps08 I've changed credentials, should works now.

**Comment by jterps08** [comment]
I will re-test today. Kindly proceed with other items, @igaponov

**Comment by devotebest** [comment]
@igaponov 
I am still getting error.
`[{"message":"You are not authenticated","class":"Symfony\\Component\\HttpKernel\\Exception\\HttpException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/srv\/civix\/vendor\/friendsofsymfony\/rest-bundle\/FOS\/RestBundle\/EventListener\/AccessDeniedListener.php","line":77,"args":[]},{"namespace":"FOS\\RestBundle\\EventListener","short_class":"AccessDeniedListener","class":"FOS\\RestBundle\\EventListener\\AccessDeniedListener","type":"->","function":"onKernelException","file":null,"line":null,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"]]},{"namespace":"","short_class":"","class":"","type":"","function":"call_user_func","file":"\/srv\/civix\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Debug\/TraceableEventDispatcher.php","line":458,"args":[["array",[["object","FOS\\RestBundle\\EventListener\\AccessDeniedListener"],["string","onKernelException"]]],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"]]},{"namespace":"Symfony\\Component\\HttpKernel\\Debug","short_class":"TraceableEventDispatcher","class":"Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher","type":"->","function":"Symfony\\Component\\HttpKernel\\Debug\\{closure}","file":null,"line":null,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"]]},{"namespace":"","short_class":"","class":"","type":"","function":"call_user_func","file":"\/srv\/shm\/powerline\/cache\/dev\/classes.php","line":1662,"args":[["object","Closure"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"doDispatch","file":"\/srv\/shm\/powerline\/cache\/dev\/classes.php","line":1595,"args":[["array",[["object","Closure"],["object","Closure"],["object","Closure"]]],["string","kernel.exception"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"dispatch","file":"\/srv\/shm\/powerline\/cache\/dev\/classes.php","line":1759,"args":[["string","kernel.exception"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"ContainerAwareEventDispatcher","class":"Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher","type":"->","function":"dispatch","file":"\/srv\/civix\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Debug\/TraceableEventDispatcher.php","line":139,"args":[["string","kernel.exception"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"]]},{"namespace":"Symfony\\Component\\HttpKernel\\Debug","short_class":"TraceableEventDispatcher","class":"Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher","type":"->","function":"dispatch","file":"\/srv\/civix\/app\/bootstrap.php.cache","line":2918,"args":[["string","kernel.exception"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handleException","file":"\/srv\/civix\/app\/bootstrap.php.cache","line":2871,"args":[["object","Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException"],["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handle","file":"\/srv\/civix\/app\/bootstrap.php.cache","line":2995,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel\\DependencyInjection","short_class":"ContainerAwareHttpKernel","class":"Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel","type":"->","function":"handle","file":"\/srv\/civix\/app\/bootstrap.php.cache","line":2275,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","function":"handle","file":"\/srv\/civix\/web\/app.php","line":16,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]}]},{"message":"A Token was not found in the SecurityContext.","class":"Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/srv\/civix\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/Security\/Http\/Firewall\/AccessListener.php","line":53,"args":[]},{"namespace":"Symfony\\Component\\Security\\Http\\Firewall","short_class":"AccessListener","class":"Symfony\\Component\\Security\\Http\\Firewall\\AccessListener","type":"->","function":"handle","file":"\/srv\/shm\/powerline\/cache\/dev\/classes.php","line":2322,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Component\\Security\\Http","short_class":"Firewall","class":"Symfony\\Component\\Security\\Http\\Firewall","type":"->","function":"onKernelRequest","file":null,"line":null,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"","short_class":"","class":"","type":"","function":"call_user_func","file":"\/srv\/civix\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Debug\/TraceableEventDispatcher.php","line":458,"args":[["array",[["object","Symfony\\Component\\Security\\Http\\Firewall"],["string","onKernelRequest"]]],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Component\\HttpKernel\\Debug","short_class":"TraceableEventDispatcher","class":"Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher","type":"->","function":"Symfony\\Component\\HttpKernel\\Debug\\{closure}","file":null,"line":null,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"","short_class":"","class":"","type":"","function":"call_user_func","file":"\/srv\/shm\/powerline\/cache\/dev\/classes.php","line":1662,"args":[["object","Closure"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"doDispatch","file":"\/srv\/shm\/powerline\/cache\/dev\/classes.php","line":1595,"args":[["array",[["object","Closure"],["object","Closure"],["object","Closure"],["object","Closure"],["object","Closure"],["object","Closure"],["object","Closure"],["object","Closure"],["object","Closure"],["object","Closure"],["object","Closure"],["object","Closure"],["object","Closure"]]],["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"dispatch","file":"\/srv\/shm\/powerline\/cache\/dev\/classes.php","line":1759,"args":[["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"ContainerAwareEventDispatcher","class":"Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher","type":"->","function":"dispatch","file":"\/srv\/civix\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Debug\/TraceableEventDispatcher.php","line":139,"args":[["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Component\\HttpKernel\\Debug","short_class":"TraceableEventDispatcher","class":"Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher","type":"->","function":"dispatch","file":"\/srv\/civix\/app\/bootstrap.php.cache","line":2881,"args":[["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handleRaw","file":"\/srv\/civix\/app\/bootstrap.php.cache","line":2866,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handle","file":"\/srv\/civix\/app\/bootstrap.php.cache","line":2995,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel\\DependencyInjection","short_class":"ContainerAwareHttpKernel","class":"Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel","type":"->","function":"handle","file":"\/srv\/civix\/app\/bootstrap.php.cache","line":2275,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","function":"handle","file":"\/srv\/civix\/web\/app.php","line":16,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]}]}]`

FYI @jterps08

**Comment by devotebest** [comment]
@igaponov  @jterps08 
screenshot about API request
![image](https://cloud.githubusercontent.com/assets/10233895/22208395/b27a9196-e1bd-11e6-85d2-a63aba0dec03.png)

**Comment by jterps08** [comment]
I believe this is working, but will re-test this evening... When user logs into app, it has previously displayed the error message "Failed to registed your device to push notifications. This may happen when you login on another device under your account. Please logout and login on this device." -- This is no longer appearing! (Good).

The app however is showing confirmation messages that the token is registered or already registered, and we don't want the user to see these, so we need to make sure that success messages are suppressed from the user. 

I will re-test all push notifications this evening on Android. I do not have an iOS device to access for easy testing tonight as we used Peter's device to do iPhone testing before...

**Comment by jterps08** [comment]
Initial tests indicate push notifications are working again. Closing for now. Full retest later.
