### ISSUE TITLE
Strange E-mail Registration Experience

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#456]
Try to register a new user via e-mail. 

User provides Name, Username, and Password. Clicks Next (ok)
User starts to enter address into Street Address field. Google auto-suggests different addresses based on entered text (ok). 
User selects an address from one of the suggestions on the list (ok)
The app auto-fills all of the appropriate fields except City field (wrong). City field should be auto-filled based on the selected address as well. **<<This is @devotebest assignment>>**
User enters e-mail address and confirms he is older than 13 (ok). 
User clicks next. 
System begins to process registration and displays fake progress animation for user (ok).
Registration fails (wrong). User should be logged in immediately. 

If an attempt is made to re-register using same information, the system says an account already exists (ok). 
If user manually backs out of registration screens and manually enters the username and password he set during account creation, the app will allow him to log in! (ok?)
The user should see his town, state, and country groups but doesn't (wrong). He should be auto-linked to his town, state, and country groups (according to Google I think).
The user should see also be able to see his Representatives, but sees nothing (wrong). He should be auto-linked to his elected leaders according to Cicero. << @igaponov can you investigate >>

I am unable to test a new Facebook registration, but I would imagine that a similar problem would happen there, too.

**Comment by devotebest** [comment]
@jterps08 
Regarding "The app auto-fills all of the appropriate fields except City field (wrong). City field should be auto-filled based on the selected address as well."
I checked `city` field, it seems that field is also correct. 
what 'street address` did you try to test?

**Comment by devotebest** [comment]
@jterps08 
and I got register success again with my email address.
what was your test information of `registration`?

**Comment by jterps08** [comment]
1088 Bedford Ave (auto filled Brooklyn addrrss)

**Comment by jterps08** [comment]
I will have to try another address... Maybe it's because I had entered the address once, it didn't pull in the city, and then i manually entered "new york" instead of brooklyn, and it failed... I will test again.

**Comment by jterps08** [comment]
I tried a few other e-mail addresses 17 Flatbush Avenue (brooklyn) "Error occurred" message appears (and brooklyn was not auto-filled into field)... I tried 108 9th avenue (new york) "error occurred" message appears (and new york *was* auto-filled into field)... This was on the Galaxy S4. 

The original errors occurred on the Galaxy S7.

**Comment by jterps08** [comment]
Can I get an update on this?

**Comment by devotebest** [comment]
@jterps08 
I think I missed your last comment for this, Please mention me when write comment.
will check this again.

**Comment by igaponov** [comment]
Blocked by #455

**Comment by igaponov** [comment]
@jterps08 check now

**Comment by jterps08** [comment]
I will check again. Thanks @igaponov

**Comment by jterps08** [comment]
Confirmed closed.

**Comment by jterps08** [comment]
Email registration may complete on the backend, but we're still having an issue with a Brooklyn address. David, can you investigate? 620 Atlantic Avenue, Brooklyn NY... if you select that from the auto-suggestion popup, it fills in everything except brooklyn... if this is google's fault (and not ours), then there's nothing that we can do about it and this is closed.

**Comment by jterps08** [comment]
Confirmed closed.
