### ISSUE TITLE
Unable to View Items in "Question Template" Screen

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#46]
User cannot open any item when tapping on the item in the newsfeed (content does not load on next screen). When user taps item in the newsfeed, it should open the item in the 'question template' screen. This question template screen is currently not loading correctly. It should load posts, petitions, discussions, fundraisers, and events with answer choices (if required), attachments, etc and comments, etc.

**Comment by petervojtek** [comment]
already fixed.
