### ISSUE TITLE
Newsfeed Activities 

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#461]
Igor - I am logged in as 1.JesseChen and following user JTest1. 

1.JesseChen lives in Hoboken, NJ USA and JTest1 lives in Washington, DC, USA. 

A post that JTest1 created in DC (District of Colombia) is appearing in 1.JesseChen's newsfeed. This shouldn't be happening. 

The only content that should appear in a user's newsfeed is content from the groups that he is joined to (his town, state, and country groups + any other groups that he joins). 

Can you investigate please?

**Comment by igaponov** [comment]
@jterps08 user `JTest` doesn't have any post in DC group. Can you please tell me a post's title? It's better to add this information every time you create issue like this.

**Comment by jterps08** [comment]
Here's the screenshot. User ZXC lives in New York and is *not* following User 1.JesseChen. User 1.JesseChen lives in New Jersey. 

User 1.JesseChen posts to New Jersey group. User ZXC cannot see the post because he lives in New York (correct). User ZXC should only be notified of new posts/user-petitions if he is an approved follower of 1.JesseChen AND 1.JesseChen has posted in a group they both share (e.g USA, but not New Jersey because ZXC lives in New York)... ZXC can see 1.JesseChen's new posts/user-petitions IF they are posted to a group they are both in. ZXC cannot see 1.JesseChen's items if they are NOT in a group that they are both in. This is all working when ZXC is not following 1.JesseChen...

User ZXC follows User 1.JesseChen. User 1.JesseChen approves follow request. 

User 1.JesseChen creates a post in New Jersey group. ZXC is not notified with a push notification because he is in New York group (this is correct behavior). 

ZXC can see 1.JesseChen's posts in other groups in his feed (NOT correct). This only happens when the user is following the person. These posts/user-petitions that should not be visible to ZCX are the ones that have no group name in the screenshot below. I believe resolving this resolves #425.

![image](https://cloud.githubusercontent.com/assets/7582457/22651000/689f0d9e-ec4f-11e6-837d-863f89a8da82.png)

**Comment by igaponov** [comment]
@devotebest can you tell where app gets data for `All` tab?

**Comment by devotebest** [comment]
I think
https://api-dev.powerli.ne/api/v2/activities?page=1

**Comment by jterps08** [comment]
FYI The All tab pulls the feed in. The other tabs (town tab, group tabs, etc) apply a filter to the All tab.

**Comment by jterps08** [comment]
This is closed.
