### ISSUE TITLE
Notification Action Button: Upvote doesn't work

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#462]
User receives push notification. 
Action button "Upvote" is availble. User clicks "Upvote" 
App should automatically upvote that post. Does not. Please investigate callback is operating properly.

**Comment by jterps08** [comment]
I provided a link on Slack that outlines the correct behavior for the push notification messages with the Upvote / Downvote action buttons

**Comment by jterps08** [comment]
It appears this is a problem with *all* action buttons on Android 5.01... still investigating.

**Comment by devotebest** [comment]
@jterps08 
How could I send push notification?
Is there any admin panel to send push notification?

**Comment by jterps08** [comment]
There is no admin panel @devotebest. You have to actually take the actions that result in push notifications. If you have two devices, it is easy to do to this. If you only have one device, you'll have to work with me or someone else to do this. I sent you a link in Slack that outlines in detail the scenarios that result in each notification.

**Comment by austinpapp** [comment]
The other option is to send a json formatted message directly from AWS sns. Pending you know the proper format of the json obj. I'll see if I can find something asi haven't used that in awhile.

**Comment by jterps08** [comment]
@austinpapp I think this page has an example... https://github.com/PowerlineApp/powerline-mobile/wiki/Push-notification-payload
