### ISSUE TITLE
Comment Field Placeholder Text / Field Size

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#464]
When making a comment on the Item Detail Screen (all content types), the comment field should already be sized to support 2 or 3 lines (see below) so that the user can see the placeholder text below. As the user types more text, the comment field expands (current behavior, should continue). 

Regardless of the item, on the Item Detail screen there should also be rotating placeholder text in the Comment field:
a) "It's all about different perspectives. Be kind." 
b) "Don't attack people. Understand them." 
c) "Listen first. Then ask questions."
d) "Take a deep breath."

When the user creates a new comment, one of these phrases will appear as placeholder text until the user taps into the field.

![image](https://cloud.githubusercontent.com/assets/7582457/22303872/2ffa35fe-e303-11e6-8b48-05a6dd8d888c.png)

**Comment by devotebest** [comment]
@jterps08 
Placeholder text rotating means "those 4 text should be changed per second one by one"?

**Comment by jterps08** [comment]
It means that one of these four randomly appears in the comment field. It
doesn't change like an animation. It appears differently randomly each time.

**Comment by jterps08** [comment]
Can you confirm that this is in place? I do not see the placeholder text on the Item Detail screen for fundraiser, poll, discussion, event, leader-petition... I only see the placeholder texton the user posts and user petitions. Placeholder text needs to be on the item detail screen for all types of content.

**Comment by devotebest** [comment]
@jterps08 
yes, working for this now.

**Comment by jterps08** [comment]
@devotebest this should not be an animation. When I open the Item Detail screen, one of these phrases is displayed at random in the comment field. It should not change while I'm on the same screen. If I leave the screen and come back later, the placeholder text should rotate to a different phrase, etc. Please fix.

**Comment by devotebest** [comment]
@jterps08 
will do
