### ISSUE TITLE
Authors should not see their own posts/user-petitions in the priority zone

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#465]
If the user is a group leader/manager and he is the *author* of *leader* content, it should appear in his own priority zone. If any user creates a new post or user-petition, it should not appear in his own priority zone UNLESS it is boosted by the group leader/manager.

**Comment by jterps08** [comment]
I am unable to duplicate this issue right now but leaving it open.

**Comment by igaponov** [comment]
@jterps08 post or user petition should appear in priority zone ONLY if it's boosted.

**Comment by jterps08** [comment]
That's correct @igaponov
