### ISSUE TITLE
List Managed Groups First

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#467]
When the user views "My Groups", he should see the groups he manages listed first (alphabetically, one single section), followed by the rest of his groups as-is (alphabetical sections)

**Comment by jterps08** [comment]
@igaponov does this require any backend work? Or should the frontend be able to sort based on existing information it receives about the user's groups?

**Comment by igaponov** [comment]
@jterps08 yes, I should implement sorting on backend

**Comment by jterps08** [comment]
@igaponov just fyi, we display groups alphabetically currently for my groups on frontend... we would want to display alphabetically for managed groups and non-managed groups
