### ISSUE TITLE
User Profile Screen

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#468]
For public
It should show Tagline, Bio, and Country fields... and authored posts in shared public communities (User A follows User B. User A and B live in California and New Jersey, but both live in USA. User A can see User B's posts in USA group, but cannot see posts in New Jersey group).

For approved followers, it should show Tagline, Bio, **Issues, State,** and Country fields... and authored posts in shared public communities **and shared groups** with the user. 

Date of Birth should not be shown. City should not be shown.

**Comment by igaponov** [comment]
@jterps08 frontend issue

**Comment by oleg201119** [comment]
@igaponov , how to get tagline, bio, issues and state for a user ?

**Comment by igaponov** [comment]
@oleg201119 https://api-dev.powerli.ne/api-doc#get--api-v2-users-{id}
`interests` are exposed now

**Comment by devotebest** [comment]
why send mail? is there any way to no receive mail? very boring.

**Comment by jterps08** [comment]
@igaponov - will that endpoint only work if user A is an approved follower of User B (where logged-in User A is trying to see the profile of User B) ? Just keeping an eye on user privacy here...

**Comment by igaponov** [comment]
@jterps08 this endpoint works for every user, but shows more info for an approved follower

**Comment by jterps08** [comment]
Got it. Thanks @igaponov

**Comment by jterps08** [comment]
confirmed
