### ISSUE TITLE
Manual Boosting Icon not working for authorized user

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#469]
User 1.JesseChen is group owner or manager of buildtest1088
User abc is a group member of buildtest1088

User JTest1 can see the boosting "lightning" icon on user abc's post "Anything 2" (correct)
User Jtest1taps button and very long error message displays (incorrect). 

User Jtest1 should be able to boost abc post

**Comment by igaponov** [comment]
@jterps08 can you provide very long error message?

**Comment by jterps08** [comment]
E-mailed it... I'm not kidding when I say 'very long' :-)

**Comment by jterps08** [comment]
Thanks Igor

**Comment by jterps08** [comment]
@igaponov I tried again and this is the error I got. Logged in as user zxc and tried to boost an item in zxcgroup1 authored by user abc... 

As a group owner/manager (zxc), I should be able to manually boost any item in the group by any user (abc) including myself (zxc). Currently, as group owner/manager of zxcgroup1, I am only able to boost my own posts (zxc) but not other group members posts (abc)

![screenshot_20170210-145200](https://cloud.githubusercontent.com/assets/7582457/22842460/4d9c4ad2-efa3-11e6-9969-1709b6b62059.png)

**Comment by igaponov** [comment]
@jterps08 this post is already boosted

**Comment by jterps08** [comment]
Ok - Can we humanize the error response? 

I need to confirm this works on an actual post that has not yet been boosted... I could not boost an item that was not mine... I could only boost posts that were mine... As a group leader I should be able to boost items by other users, not just my own... If it's already been boosted, we should inform the user.

**Comment by igaponov** [comment]
I think if it's boosted we shouldn't see a button. `boosted` flag is exposed in API.

**Comment by jterps08** [comment]
ok @devotebest we need a rule for the manual boost button above

manual boost button appears only for group leaders (owners or managers) for the group in which the item was posted in AND manual boost button appears only if post is not boosted...

User ZXC is group leader for zxcgroup1
User ABC is a group member in zxcgroup1
User ABC is a group leader for someothergroup

User ABC makes a post in ZXCgroup1
User ABC cannot boost a post in ZXCGroup1 because ABC is not a group owner/manager
User ZXC can see the manual boost button for user ABC's post because he is a group owner/manager in zxcgroup1 AND the post has not been boosted yet.
The item is boosted.
User ZXC cannot see the manual boost button any longer on the abc post because it now boosted.

**Comment by sirius2013** [comment]
what is manual boost button? could you add any screenshot?
and we need to test this on staging server or dev server?
what is test account?

**Comment by MobileDevGold** [comment]
could I work for this?

**Comment by MobileDevGold** [comment]
I got this apk
https://drive.google.com/open?id=0BxZueVVvaQcBTDN6emw3d1V0VkE

**Comment by jterps08** [comment]
Thank you @MobileDevGold - We have someone assigned to this already. Would you like to work on other items?

**Comment by MobileDevGold** [comment]
@jterps08 
okay.sure

**Comment by jterps08** [comment]
Would you like to join our Slack channel to work together? If so send me an e-mail slack at powerli.ne

**Comment by MobileDevGold** [comment]
mobiweb310@mail.com

**Comment by jterps08** [comment]
I will reach out to you - thanks @MobileDevGold!

**Comment by igaponov** [comment]
Should work now on staging

**Comment by jterps08** [comment]
Was there a commit relating to this resolution @igaponov ?

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/commit/77b7da5bb4fcee803afa17637086bcb70ae0e7bd

**Comment by jterps08** [comment]
confirmed
