### ISSUE TITLE
Invite Followers to Group

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#472]
Isn't generating a push notification alert or invitation for the user's followers.

Some user creates new group BuildTest2017.
User JTest1 approved follow request from 1.JesseChen

User JTest1 has a post that has been boosted uatomatically by the system in BuildTest2017, so he now is able to see and tap on the "megaphone" icon to invite followers to group. He taps the icon. He selects the group "Save the Whales"
User JTest1 invites followers to join Save the Whales. 

User 1.JesseChen does not not receive group invite or push notification.

**Comment by igaponov** [comment]
@jterps08 1.JesseChen follower status is `pending`, JTest1 should approve his request before invitation.
