### ISSUE TITLE
Announcements that are read need to stay "read"

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#474]
The user sees a counter (1) on the Announcements tab. 
The user views the Announcement.
The user switches to the Newsfeed tab. The Announcements counter (1) goes to 0 (this is correct).
The user logs out and logs back in and the Announcements counter is back at 1 although there is no new content (wrong). 

The user thinks there's a new announcement but there is no new announcement.

**Comment by jterps08** [comment]
@igaponov is "announcement read" something tracked currently by backend or only in the frontend?

**Comment by igaponov** [comment]
@jterps08 only in the frontend

**Comment by jterps08** [comment]
What's the level of effort to track **announcements** that are read (like how we track priority zone items that are read)?

**Comment by igaponov** [comment]
@jterps08 couple of hours

**Comment by igaponov** [comment]
Use attribue `is_read` for logged in user (https://api-dev.powerli.ne/api-doc#get--api-v2-announcements)
Use https://api-dev.powerli.ne/api-doc#patch--api-v2-announcements to mark announcements as read.

**Comment by jterps08** [comment]
![image](https://cloud.githubusercontent.com/assets/7582457/24014176/50d74086-0a5a-11e7-948c-abc8d8d8689d.png)

**Comment by oleg201119** [comment]
The logged in user is Oleg. But can't see any announcement. How to add new announcement for testing ?

**Comment by jterps08** [comment]
Create a new group in DEV... Once you create the group, you will become the group owner by default and you will be able to create announcements for that group.

**Comment by oleg201119** [comment]
@igaponov , Can you check patch api (PATCH  /api/v2/announcements) ?
Logged in user - Oleg gets an announcement for SergeyGroup  and property - is_read is "false" once the patch api was called.

**Comment by igaponov** [comment]
@oleg201119 api doc is fixed: https://api-dev.powerli.ne/api-doc#patch--api-v2-announcements

**Comment by oleg201119** [comment]
@jterps08 let's assume there are 10 new announcements. And screen shows only 4 announcements. If user does not scroll the screen, the user can't see 6 announcements. In this case, how to change counter ?

**Comment by jterps08** [comment]
I think the counter only displays a number for pending group invites. I do not think it counts the announcements - it only displays the blue circle "indicator" if there are any unread announcements. 

For group invites: User has 3 group invites, counter displays 3. User clicks Join for one group invite, counter reduces to 2. User clicks Ignore for the other two group invites, and counter reduces to 0 (but counter never displays '0'... 

For announcements: User has 10 announcements, blue indicator displays without number (number only displays if there are group invites).  User opens tab. Blue indicator disappears (unless there are pending group invites). Even if user does not scroll down, the blue indicator disappears. 

We can make this more advanced in the future so that the "viewed" announcements are actually counted or sorted on the screen differently, but we don't have to now. Let me know if that makes any sense @oleg201119

**Comment by oleg201119** [comment]
@igaponov , I am trying to use patch api with payload parameters. For example, request payload is 
{announcements: [155, 154], read: true}
But response payload is empty array.
Is it right ?

**Comment by igaponov** [comment]
@oleg201119 it's not right, this is request made from your user (id=130):
``` 
$ http PATCH https://api-dev.powerli.ne/api/v2/announcements announcements:=[154,155] read=true "Token:$TOKEN"

HTTP/1.1 200 OK
Cache-Control: no-cache, private
Connection: keep-alive
Content-Type: application/json
Date: Wed, 22 Mar 2017 11:29:58 GMT
Server: nginx/1.4.6 (Ubuntu)
Transfer-Encoding: chunked

[
    {
        "content_parsed": "0321-01", 
        "group": {
            "avatar_file_path": "https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png", 
            "group_type_label": "common", 
            "id": 402, 
            "official_name": "8G", 
            "type": "group"
        }, 
        "id": 154, 
        "is_read": true, 
        "published_at": "Tue, 21 Mar 2017 18:16:07 +0000", 
        "share_picture": null, 
        "user": {
            "avatar_file_path": "https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png", 
            "group_type_label": "common", 
            "id": 402, 
            "official_name": "8G", 
            "type": "group"
        }
    }, 
    {
        "content_parsed": "0321-02", 
        "group": {
            "avatar_file_path": "https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png", 
            "group_type_label": "common", 
            "id": 402, 
            "official_name": "8G", 
            "type": "group"
        }, 
        "id": 155, 
        "is_read": true, 
        "published_at": "Tue, 21 Mar 2017 18:17:45 +0000", 
        "share_picture": null, 
        "user": {
            "avatar_file_path": "https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png", 
            "group_type_label": "common", 
            "id": 402, 
            "official_name": "8G", 
            "type": "group"
        }
    }
]
```

**Comment by oleg201119** [comment]
@igaponov How did you pass parameters (announcements and read) ?

**Comment by oleg201119** [comment]
@igaponov The api returns empty response...
Here is http request.
![screen shot 2017-03-23 at 4 51 28 am](https://cloud.githubusercontent.com/assets/20283731/24229892/a39554b4-0f84-11e7-9bae-a84a790a87df.png)

**Comment by igaponov** [comment]
@oleg201119 I see that app every time has a problem with headers. For all requests to api you should use 'Content-Type' = 'application/json', I think it's possible to configure $http service globally.

**Comment by jterps08** [comment]
How is this now @oleg201119 ?

**Comment by oleg201119** [comment]
'Content-Type'='application/json' => works. This issue (for announcements) was solved. Now it needs to check for group invitation.

**Comment by jterps08** [comment]
Just go to some group's profile screen and tap the "Invite" button in the upper right hand corner to invite followers.. You'll need to have some test accounts following you for this to work. This is a workaround to the e-mail issue you are experiencing...

**Comment by jterps08** [comment]
confirmed
