### ISSUE TITLE
All Leader Content should show Group Avatar in Newsfeed, not Author Avatar

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#475]
Currently system provides the Author avatar with the leader content. The system should provide the Group avatar with the leader content (polls/leader-petitions/discussions/fundraisers/events/announcements). 

User posts and user petitions (boosted and non-boosted) should continue to show author avatar.

Served with imgix as usual.

**Comment by jterps08** [comment]
@igaponov is this something you would change on the backend or is this something that we would have changed on the frontend?

**Comment by igaponov** [comment]
Use activity.group.avatar_file_path to get link.

**Comment by jterps08** [comment]
Thanks Igor. So we'll use that to get the link. @devotebest when it's time to do this, we'll need to make sure imgix parameters are applied as usual. 

Group avatar displayed for new polls, leader petitions, discussions, fundraisers, and events. User posts and user petitions will continue to show user avatars.

**Comment by jterps08** [comment]
![image](https://cloud.githubusercontent.com/assets/7582457/23375874/f539ae40-fcf7-11e6-9577-e41ff06664c5.png)

Image on the left is the main newsfeed.
Image all the way to the right is related to the feed that is shown in User Profile screen (#452)

**Comment by jterps08** [comment]
@oleg201119 this should be pretty straight forward based on explanation above, but let me know if you have any questions... If User A is a group owner/manager of Group X, and he creates a user post or user petition, then User A avatar is shown in the newsfeed. If User is a group owner/manager of Group X and he creates leader content (poll/leader-petition/discussion/fundraiser/event/announcement), then the Group X avatar is show in the newsfeed. It should simply be a matter of logic checking "If group content, show group avatar... if user content, show user avatar" Currently system always displays user avatar.

We want to make sure the images continue to be served using the standard imgix image compression technique that is being used in the newsfeed currently for user avatars.

**Comment by oleg201119** [comment]
@jterps08 I am trying to change avatar for a user and a group for testing. But can't change profile avatar. The activity feed screen and profile screen shows default "character avatar" only.
How to upload/change avatar picture ?

**Comment by jterps08** [comment]
Tap the edit button in upper right corner for user profile to activate
profile editing.

Tap the manage group button on the group profile screen to activate profile
editing and change group avatar.

**Comment by oleg201119** [comment]
I did, but avatar image is disappeared on profile edit screen once image is selected  from photo library.

**Comment by jterps08** [comment]
What's wrong? Please show a screenshot. If it's a frontend problem, we'd ask you to fix it anyway

**Comment by oleg201119** [comment]
![device-2017-03-22-191341](https://cloud.githubusercontent.com/assets/20283731/24211318/50288274-0f34-11e7-96f9-a7dd15f741bc.png)

**Comment by oleg201119** [comment]
If I click 'save' button on this screen, the app shows 'success', but feed page and profile page shows 'character avatar' again. Not 'image avatar'.

**Comment by jterps08** [comment]
@igaponov can you take a look at this? Is this an imgix serving issue? 

User updates personal profile avatar. Clicks Save. App indicates successful save, but user profile page and newsfeed remain unchanged.

**Comment by igaponov** [comment]
Probably an sql error with reports causes this problem, need to retest after a deploy to dev.

**Comment by jterps08** [comment]
@igaponov can you explain in more detail / deploy today?

**Comment by jterps08** [comment]
What is the status with this @oleg201119 ?

**Comment by oleg201119** [comment]
@jterps08 I can't upload image for group..

**Comment by jterps08** [comment]
That is definitely a bug that we will need @igaponov to look at (user and group avatar upload)... 

But @oleg201119 - You shouldn't need that fixed to fix this issue ... if there's no image, the ng-letter concept shows instead... if user Oleg posts a poll in group X, right now it shows the "O" avatar (ng-letter). after the code change, if user Oleg posts a poll, the "X" avatar will show in newsfeed (ng-letter) for group X...

We need to fix the upload problem separately.

**Comment by oleg201119** [comment]
@jterps08 this issue is fixed if there's no image. But I got a problem if there is image. The api returns 3 images for an activity. ( group image, user image and owner image). And group image and user image are default image, but owner image is the image I uploaded. So how to show image for avatar ?
@igaponov Can you check this problem ?

**Comment by jterps08** [comment]
I don't know what the difference is between user image and owner image... 

@igaponov this image upload issue doesn't seem to exist on PROD... are we sure these query optimizations and everything else you've been working on hasn't negatively impacted dev stability?

**Comment by jterps08** [comment]
confirmed
