### ISSUE TITLE
Newsfeed Group Titles in Item Container

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#48]
Each post in the newsfeed should show the group the post was made next to the user's name (e.g. Jesse Chen | United States of America). Currently the group is not showing in the container correctly. Other UI elements in the container may also not be showing correctly (comment counter)- it is unclear due to lack of newsfeed data.

**Comment by petervojtek** [comment]
fixed the group name here. will fix the comment counter in #127
