### ISSUE TITLE
Standard Image Size for Attachments in Newsfeed

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#480]
Powerline currently has a single parameter by which all images are processed for imgix - the width of the screen. This is insufficient and creates wildly different image sizes in the newsfeed. See the example below:

![image](https://cloud.githubusercontent.com/assets/7582457/22306652/fe66d46a-e30d-11e6-9c3f-7e6a5e2b1d01.png)

In the example below, note how there is a consistent image size for all images that appear in the newsfeed. 

![image](https://cloud.githubusercontent.com/assets/7582457/22306238/7c4ea6c0-e30c-11e6-8b93-6f2e0c5363f0.png)

We need to apply the same concept for Powerline - consistent image size for newsfeed attachments (pictures and video-preview thumbnails).  I believe this is a matter of making a few imgix query parameter adjustments here (but not sure) - https://github.com/PowerlineApp/powerline-mobile/blob/366126e4569970a6c450d63c19e814e507b73425/www/js/controllers/home.js#L332

If you have not worked with imgix image processing API before, please reference https://www.imgix.com/imgix-js

If this is not a change we make on the frontend and instead a change we make on the backend, please assign to Igor. 

https://docs.imgix.com/apis/url/size/fit (clip)
https://docs.imgix.com/apis/url/size/max-h
https://docs.imgix.com/apis/url/auto (format and compress)

**Comment by jterps08** [comment]
@devotebest I think this parameter query needs to be applied to the following places:

**Newsfeed**

- user avatar
- newsfeed attachments (pics/vids)
- group avatar

The newsfeed slows down substantially when multiple images are in the feed and that's because we don't have this imgix query parameter on the call.

**Comment by devotebest** [comment]
@jterps08 
could you attach screenshots to get more clear idea?

**Comment by jterps08** [comment]
![image](https://cloud.githubusercontent.com/assets/7582457/22440551/ffa44a90-e701-11e6-8244-d658f9fc6e52.png)

@devotebest The newsfeed are the top row of items. All this should be is appending the correct imgix query to wherever the image URL is loaded. You'll want to reference the comments above and the imgix documentation. 

Anytime we load an image anywhere in the app we want to make sure that it is being processed via imgix *with* the appropriate parameters in place to reduce file size for faster performance...

**Comment by devotebest** [comment]
@jterps08 
It means all images on the feed should be cropped as same height?

**Comment by jterps08** [comment]
I will touch base with you in slack @devotebest

**Comment by jterps08** [comment]
I believe this is closed. I will inspect the commit once available.

**Comment by jterps08** [comment]
@devotebest when the user enters a web address in a post, the system correctly previews the content based on the address provided. This usually works well for web sites, but if the user enters a youtube link (user zxc did in zxcgroup1), then the system will provide a preview of that youtube link in the newsfeed. That's okay... however the size of the youtube container is huge. We need to make this the same size constraints as above work...

**Comment by jterps08** [comment]
![image](https://cloud.githubusercontent.com/assets/7582457/23007060/afb43714-f3d3-11e6-8118-f6463e5f9468.png)

**Comment by jterps08** [comment]
For additional clarity: 

![image](https://cloud.githubusercontent.com/assets/7582457/23141623/ada5bd3e-f785-11e6-9353-b3910165ca2b.png)

**Comment by jterps08** [comment]
It seems that this issue was resolved but never delivered in build. Marking as closed.

**Comment by devotebest** [comment]
I was sure. that was done with this commit 
https://github.com/PowerlineApp/powerline-mobile/commit/3f7f9e9659b1a173d8c9ab228c2a50943cb78e22

Sent from my iPhone
