### ISSUE TITLE
Add Individual/Company Selector to Bank Account Setup

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#484]
1) @devotebest In order to fully comply with Stripe legal requirements, we need to give users choice between "Individual" or "Organization" on the Bank Account Setup Form. It should be placed above "Business Name" field. The label "Account Type: Business" should be replaced by this toggle button.
It is passed via API to the backend as `type` along with the DOB and other fields. Individual selection is sent as `Individual` `type` and Organization as `Company` `type`.

2) @devotebest If Organization is selected, the "Business Name" field and the "Tax ID" field appears.
If Individual is selected, the "Business Name" field disappears and the "Tax ID" field disappears. 
Note: The "Last 4 digits of SSN" stays regardless of which radio button is selected and should be labeled "Last 4 Digits of SSN".

2b) For @igaponov , please add API support for "legal_entity.business_tax_id" as `Tax_ID`

3) @devotebest Add the following label, including hyperlinks, above "Save & Submit button" and below "Confirm Account Number" field:
**By registering your account, you agree to our [Terms of Service](http://powerli.ne/legal) and the [Stripe Connected Account Agreement](https://stripe.com/connect-account/legal).**

**Comment by jterps08** [comment]
@devotebest tax ID field is ready

Thanks @igaponov for quick action here.

**Comment by devotebest** [comment]
@jterps08 
**The label "Account Type: Business" should be replaced by this toggle button.**
I am not sure about `toggle button` about above comment.

I think that should be **select button** like http://ionicframework.com/docs/components/#select

**Comment by devotebest** [comment]
![image](https://cloud.githubusercontent.com/assets/10233895/22419492/b87f1994-e718-11e6-8086-d67a4f90828d.png)
will make like this.

**Comment by jterps08** [comment]
That works fine. 

We should not have **two** DOB fields though :-)

**Comment by devotebest** [comment]
@jterps08 
okay, and what is position of **Tax ID**?

**Comment by jterps08** [comment]
You can put it right above the Last 4 Digits of SSN field

**Comment by jterps08** [comment]
This works, thank you!
