### ISSUE TITLE
@everyone notifier for group leaders

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#487]
Ability for a group leader (owner/manager) to utilize the @everyone mention to notify all group members from comment box. Unauthorized users (group members) will simply have the @everyone treated as text (no notification generated). 

From a frontend perspective, the auto-suggestion box should *not* suggest @everyone when the user types it even if the user is authorized. However, when an authorized user (group owner/manager) goes to submit a comment that contains @everyone, an alert is generated for the authorized comment author saying "You are about to notify X group members. Are you sure?" Send/Cancel. 

This should only apply to comments (on all content types), not body text of user posts/petitions (unless it is harder to separate to do only comments instead of comments/posts/petitions... in that case, we'll do whatever is easiest). 

The Notifications Reqts document is updated with details for backend work.

**Comment by igaponov** [comment]
Backend functionality is done.

**Comment by jterps08** [comment]
@devotebest do you want to work on this? If so, please ping me on Slack to discuss privately

**Comment by jterps08** [comment]
The frontend work for this issue is "When an authorized user (group owner/manager) goes to submit a comment that contains @everyone, an alert is generated for the authorized comment author saying "You are about to notify X group members. Are you sure?" Send/Cancel."

1. User A is an authorized group owner or group manager for Group X. User B is just a normal member of Group X. 
2. User A creates a comment on some item that was published in Group X and includes the "@everyone" mention in the body of his comment. User B does the same. 
3. (Logic is something like this: When User A submits his comment, the app checks to see if @everyone is in the body of comment. If so, the system checks to see if User A is a group owner or manager. If yes, the pop-up is displayed before the comment is submitted.)
4. User A gets the pop-up as defined above because User A is an authorized group owner/manager. User B does *not* get the pop-up because, even though he typed @everyone, he is not a group owner or manager ofr that group.
5. 

In both cases (for User A and User B), the auto-suggestion box for @mentions does not include @everyone in the results.

**Comment by oleg201119** [comment]
@igaponov , which api is used for this issue ?

**Comment by igaponov** [comment]
@oleg201119 
https://api-dev.powerli.ne/api-doc#post--api-v2-polls-{id}-comments
https://api-dev.powerli.ne/api-doc#post--api-v2-posts-{id}-comments
https://api-dev.powerli.ne/api-doc#post--api-v2-user-petitions-{id}-comments
