### ISSUE TITLE
Confirm Stripe  in Staging/Prod

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#489]
The hardest testing we have to execute besides notification testing is Stripe payment processing.

We need to completely test payments in Staging using the Test Mode Stripe key (and test bank account / credit card information provided by Stripe).

We are currently experiencing the following two errors in Dev. We can resolve them in Staging. 

1) Adding valid test credit card fails to process payment transaction correctly. 

2) Adding valid test credit card fails under old user because user was not created in Test Mode; user was created in Live mode (Resolved/Ignore this -- I think this is a non-issue).

When we deploy to Prod, we will test using the Live Mode Stripe key (and real bank account / credit card information)

**Comment by devotebest** [comment]
@jterps08 
do you have any screenshot about failed `valid test card info`?

**Comment by jterps08** [comment]
There is no issue yet. This is a placeholder.

**Comment by jterps08** [comment]
@igaponov 
User adds valid credit card number and makes payment - following error is displayed. 
![image](https://cloud.githubusercontent.com/assets/7582457/22714621/5ee56516-ed5b-11e6-92f0-45ae01135cc4.png)


Invalid Routing Number - Humanize the error response that is displayed to user.
Invalid Account Number - Humanize the error response that is displayed to user.

**Comment by jterps08** [comment]
@igaponov it may make sense to test this again in the TEST Stripe environment... I thought it was working fine in TEST, but we can try it there again?

**Comment by igaponov** [comment]
@jterps08 fixed. You've already answered to this payment request, so try another one.

**Comment by jterps08** [comment]
ok I will inspect - can you give me an idea of what happened? @igaponov

**Comment by jterps08** [comment]
@igaponov @devotebest It seems that everything works. I am still getting an error message, but there's no content. The donation is processed by Stripe and it seems like the server has processed everything. 

@igaponov is this something that the backend is returning? This is even happening if I select a $0 (no donation) option... 
![image](https://cloud.githubusercontent.com/assets/7582457/22813319/cce0fbf2-ef18-11e6-97fe-47ae82e46633.png)

**Comment by jterps08** [comment]
Also @igaponov, can you confirm that we are passing all of these fields to Stripe, please? (For group bank account setup)

![image](https://cloud.githubusercontent.com/assets/7582457/22813697/b090e590-ef1b-11e6-8723-cff5c536cf32.png)


It seems that, when I created the bank account in LIVE environment, the information was not passed. I should be able to see all of this information filled out because our form asks for it, but it doesn't seem like it's being passed... 

![image](https://cloud.githubusercontent.com/assets/7582457/22813799/7fee935a-ef1c-11e6-97dc-bc325711867c.png)


https://stripe.com/docs/connect/updating-accounts

**Comment by igaponov** [comment]
@jterps08 answer works, I tried for `zxc` user. Please provide your user name and poll with that error. 
You can use 0 as amount, so I assume it's not good behavior. Should we set some minimum amount?
There was old code sending `legal_entity` info, but I'm not sure if it works fine, I've just added `dob` fields. Type, first name and last name were already added in this code before. Didn't you test this in dev environment?

**Comment by jterps08** [comment]
@igaponov I actually did not test this in dev environment. I accidentally tested it in Staging because I wanted to check whether or not our crowdfunder had actually fired or waited as it was supposed to... For the record, the crowdfunder works (when there is deadline/goal-amount)...

To fully test this feature, I have to create a new group, add the bank account information, create a fundraiser, and have someone make a payment... I then have to look at Stripe and confirm that the bank account information all got provided to Stripe correctly. As of now, *it is not*.

**Comment by jterps08** [comment]
@igaponov This was my fault. I looked at the wrong record. Sorry for the confusion.

We still want to address the [] error that's being sent back...

**Comment by jterps08** [comment]
@igaponov the [] error no longer exists

**Comment by jterps08** [comment]
@igaponov I have to re-test with bad CC information and bad bank account information to confirm humanized error responses via https://github.com/PowerlineApp/powerline-mobile/issues/489#issuecomment-278164632 before I can close this

**Comment by jterps08** [comment]
I am moving humanizing Stripe errors to a new issue and closing this.
