### ISSUE TITLE
Edit/Delete Posts

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#49]
Edit/Delete buttons should appear on any post I authored. They should not appear on posts I did not author.

The UI is supposed to display an Edit (pencil) icon and a Delete (trashcan) icon on any post I have authored. This was previously implemented in PR #15

**Comment by petervojtek** [comment]
fixed.

to test it, login as `JTest1`

this Post by Jesse has the Edit and Delete buttons:
http://localhost:8100/#/petition/109?focus=add-comment

while this one by Json Hlp lacks the buttons:
http://localhost:8100/#/petition/108?focus=add-comment
