### ISSUE TITLE
Upvoting/Downvoting My Post Should not be allowed

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#50]
I should not be able to upvote/downvote posts that I authored/created myself (buttons should not appear). I should only see the upvote/downvote buttons on other user’s posts.

**Comment by petervojtek** [comment]
blocked by #63

**Comment by petervojtek** [comment]
I fixed it only in main activity feed (i.e. set proper visibility of the up and down double arrow buttons)
. 
<img width="543" alt="screen shot 2016-06-21 at 11 43 57" src="https://cloud.githubusercontent.com/assets/225506/16225405/9db351b0-37a6-11e6-9eb9-a1e5a04e8092.png">

not sure if there are also other places in app where user can upvote/downvote.
