### ISSUE TITLE
Remaining Imgix Implementation

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#509]
Item Detail Screen Avatars and Attachments
Group Profile Screen Avatar and Newsfeed (A) 
Group Profile Screen Membership List Avatars
User Profile Screen Avatar and Newsfeed (B)
Favorites Screen User Avatars and Newsfeed Attachment (C) 
Social Activities Feed (You Tab & Following Tab) User Avatars
My Influences Screen User Avatars
Manage Group Avatar
Edit Profile Avatar

format=auto, format=compress, q=75
Newsfeed attachments in items A, B, and C above should all follow same sizing as main newsfeed

**Comment by jterps08** [comment]
As discussed on Slack, here are the screenshots..

![image](https://cloud.githubusercontent.com/assets/7582457/22788864/3387915a-eeaf-11e6-8063-a329c6cc2b45.png)

**Comment by jterps08** [comment]
As discussed on Slack... @devotebest 

![image](https://cloud.githubusercontent.com/assets/7582457/22788960/89afcc1e-eeaf-11e6-94a7-07332b726825.png)

**Comment by devotebest** [comment]
@jterps08 
![image](https://cloud.githubusercontent.com/assets/10233895/22789415/d4af25e8-ef1d-11e6-9ea9-207e5364a2ef.png)

these icons are coming from ng-letter-avatar library, and image source is below.
src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHBvaW50ZXItZXZlbnRzPSJub25lIiB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoNjQsIDEwLCAyNyk7IHdpZHRoOiA1MHB4OyBoZWlnaHQ6IDUwcHg7Ij48dGV4dCB0ZXh0LWFuY2hvcj0ibWlkZGxlIiB5PSI1MCUiIHg9IjUwJSIgZHk9IjAuMzVlbSIgcG9pbnRlci1ldmVudHM9ImF1dG8iIGZpbGw9IiNmZmZmZmYiIGZvbnQtZmFtaWx5PSJIZWx2ZXRpY2FOZXVlLUxpZ2h0LEhlbHZldGljYSBOZXVlIExpZ2h0LEhlbHZldGljYSBOZXVlLEhlbHZldGljYSwgQXJpYWwsTHVjaWRhIEdyYW5kZSwgc2Fucy1zZXJpZiIgc3R5bGU9ImZvbnQtd2VpZ2h0OiA0MDA7IGZvbnQtc2l6ZTogMzBweDsiPjE8L3RleHQ+PC9zdmc+"

we should apply imgix filter?

**Comment by devotebest** [comment]
@jterps08 
I did everything except ng-letter-avatar icons.

**Comment by jterps08** [comment]
that's correct - the ng-letter avatars do not need to be igmix processed. Thanks @devotebest

**Comment by jterps08** [comment]
Closing this, need to confirm via code inspection that all screens were adjusted as indicated above @devotebest

**Comment by devotebest** [comment]
@jterps08 
okay, here it is.
https://github.com/PowerlineApp/powerline-mobile/pull/515/commits/0c70401b2c4b6c2938eceb401e8331c4ef29bc74
