### ISSUE TITLE
Followers Tab Should List Pending Requests

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#510]
Currently the "Followers" tab in the My Influences screen lists only the user's "approved" followers. The only place  to approve a follower's follow request is to go into the Social Activity Feed and approve it from there. This is confusing. The user should be able to see Follow Requests at the top of the Followers tab. The order of the tabs should be switched, too. Followers on the left (default view) and Following on the right.

**Comment by jterps08** [comment]
Will need Approve / Ignore buttons for the pending requests, which should be listed first.
![image](https://cloud.githubusercontent.com/assets/7582457/24015703/9832b604-0a5f-11e7-85ec-df771ce3c440.png)

**Comment by oleg201119** [comment]
@jterps08 Which image (or icon) is for Approve , and which is for Ignore ? I'd like to see design for this screen.

**Comment by oleg201119** [comment]
@igaponov How to get Follow requests for user ?

**Comment by igaponov** [comment]
@oleg201119 https://api-dev.powerli.ne/api-doc#section-Followers

**Comment by jterps08** [comment]
@oleg201119 you can just use simple "Approve" and "Ignore" labeled text buttons... Or a checkmark and an X if you don't have space. We're probably going to have redesign this anyway in our next release or two.

**Comment by igaponov** [comment]
@jterps08 followers endpoint now returns "pending" followers, but only if they requested in the last 6 months. Do we need to change this behavior? I'll change sort order.

**Comment by jterps08** [comment]
Let's move to requested in last 2 years for now. There's been some confusion for users who were on Powerline v1.0, I think. We'll change it back in a couple releases...

**Comment by jterps08** [comment]
confirmed
