### ISSUE TITLE
iOS Build Not Working in Staging

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#513]
Unable to test on 10.1.1 iOS
-Unable to login manually
-Unable to login with Facebook
-Unable to register with Facebook
-Unable to register with new account

**Comment by devotebest** [comment]
@jterps08  @igaponov 

I think there is problem with backend.

**Comment by jterps08** [comment]
There shouldn't be a problem with backend if it works on Android, which it does.

**Comment by jterps08** [comment]
Issue resolved. Staging environment doesn't have SSL certificate.
