### ISSUE TITLE
General Open Staging Issues

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#514]
RESOLVED 1. Push notification does not arrive for Follow Request, Group Invite, New Poll, etc. Push notifications are not working (@igaponov)
RESOLVED 2. User abcd registered and was only linked to New York State and United States of America. Not linked to Town group. Linkage to Elected leaders was successful. (@igapanov)
RESOLVED / UNABLE TO REPRODUCE 3. Newsfeed attachments not appearing for polls in newsfeed on Android 5 - User Zxc created a poll in a 'zxcgroup1'. The poll appears correctly in the newsfeed. The attached image does not in Android 5. The image appears correctly on Android 6. (@devotebest)

FOR DAVID 4. User Zxc authors a poll in 'zxcgroup1' - The report button does not appear for that user on the poll. The button appears on the leader petition screen but does not work. The button appears on the event screen and does not work. The button appears on the fundraiser screen and does not work (@devotebest) 

RESOLVED System very slow at searching for people to follow but I think that is due to t1.micro instance?

**Comment by devotebest** [comment]
@jterps08 
what is test account information(username and password)?

**Comment by devotebest** [comment]
![image](https://cloud.githubusercontent.com/assets/10233895/22884627/e02c3472-f230-11e6-9cd9-6e43547b0cc9.png)
I got this screen.
@jterps08 
could you add your screenshots please?

**Comment by jterps08** [comment]
Re: #3 above... @devotebest If you create a Discussion with an attachment, you will see the problem. The attachment appears in newsfeed correctly on Android 6 but does not load in Android 5. I will send screenshots when I have my Android 5 again, which won't be for a few hours as I left it at home. 

Re: #4, let me know if you have any questions...

**Comment by devotebest** [comment]
@jterps08 
there is NO discussion creation button with that account.
![image](https://cloud.githubusercontent.com/assets/10233895/22911940/98c19704-f29d-11e6-8036-d14d65fd3c91.png)

**Comment by devotebest** [comment]
@jterps08 
Yes, I will need explain with screenshot about item 4 also.

**Comment by devotebest** [comment]
@jterps08 
I tried on android 4.x, I can see attached images.

**Comment by jterps08** [comment]
Re: #3, I will try to replicate.

Re: #4 ... The missing reports button on the polls screen... This button should *only be visible to users who are group leaders (owner or manager) for the group in which the item was made... If ZXC is group manager in zxcgroup1 and ABC is only group member, then ZXC can see reports button on polls, petition, fundraiser, event BUT ABC *should not*.
![image](https://cloud.githubusercontent.com/assets/7582457/22915114/fd2e9896-f242-11e6-8f36-511166a56672.png)

**Comment by devotebest** [comment]
@jterps08 
@igaponov 
This API didn't return correct data for group to check owner or manager.

https://api-staging.powerli.ne/api/poll/question/199
![image](https://cloud.githubusercontent.com/assets/10233895/22922079/2c6190a2-f2d7-11e6-9810-6743b6f0cdd3.png)

**Comment by igaponov** [comment]
@devotebest https://api-staging.powerli.ne/api-doc#get--api-v2-groups-{id} `user_role` attribute

**Comment by jterps08** [comment]
Thanks @igaponov ... @devotebest the only item remaining in 514 is #4, this reports button thing....

**Comment by jterps08** [comment]
#4 is done.
