### ISSUE TITLE
Emoji handling in post and petition content

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#519]
Make sure that the system doesn't break when a user includes an emoji in the body of the item.

**Comment by igaponov** [comment]
@devotebest I need to get raw request with emoji to see how mobile client send it (what is in a body of response), because in db I can see only spaces.

**Comment by igaponov** [comment]
Need to change settings for AWS db: https://github.com/openimages/dataset/issues/4

**Comment by jterps08** [comment]
We need to make sure these changes are in sync with the frontend... The frontend seems to have lost a lot of functionality as a result of this change. I assume we can do a mass find-and-replace to change to utf8mb4 across the frontend codeset @igaponov

**Comment by jterps08** [comment]
I believe this is closed. I have tested posts, petition, comments, announcements, and polls... It seems to have worked!
