### ISSUE TITLE
Group Profile Membership List Not Appearing

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#52]
The membership list should appear when user taps on membership count in Group Profile page. Currently no list appears. 

The membership list screen should display all group members and allow the user to tap on any individual user listed to view their profile. The membership list screen should also display a Follow All Members button that displays a warning confirmation dialog box when the user taps it. Mockup below - this was previously implemented in PR #26 or #24 

![screenshot_2016-03-03-10-36-06](https://cloud.githubusercontent.com/assets/7582457/15658412/63ae9c4a-268a-11e6-85f5-0160b7708f5d.png)

**Comment by petervojtek** [comment]
blocked by #101 (partly it's duplicate)

**Comment by petervojtek** [comment]
was resolved in #101
