### ISSUE TITLE
Humanizing Stripe Errors

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#520]
https://github.com/PowerlineApp/powerline-mobile/issues/489

**Comment by igaponov** [comment]
Stripe errors now are returned as standard api errors: response with code 400 and a `message` attribute, that contains Stripe's error. From Stripe documentation: `A human-readable message providing more details about the error. For card errors, these messages can be shown to your users.`

**Comment by jterps08** [comment]
Awesome, let's close this
