### ISSUE TITLE
Regression Error: Report Button Icon Size

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#523]
The Report Button has blown up. Should be about the same size as the lightning icon... Not sure if this happened due to Imgix fix or why....

CORRECT
![screenshot_20170213-231540](https://cloud.githubusercontent.com/assets/7582457/23180531/b78bea0c-f83f-11e6-8df8-ce5753f4d061.png)

INCORRECT (CURRENT)
![image](https://cloud.githubusercontent.com/assets/7582457/23180356/272e49aa-f83f-11e6-9392-9fcea9ce8877.png)

**Comment by rudjdev** [comment]
fixed

**Comment by jterps08** [comment]
this is closed. thanks
