### ISSUE TITLE
PROD - Facebook Registration Screen Flow

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#526]
1. User A is not a registered Powerline user. 
2. User A opens the Powerline app.
3. User A taps the Register/Login with Facebook button.
4. App displays Facebook Login / Connect screen (correct).
5. User provides Facebook with appropriate permissions (correct).
6. App displays the User Profile screen for the user to complete remaining registration information (incorrect).
7. App *

should* display the "2nd screen" from the manual registration process.

**What the app is showing** - it shouldn't show this screen after FB authorization.
![image](https://cloud.githubusercontent.com/assets/7582457/23321425/7e7464ae-faad-11e6-97fc-b6ae629a6a4b.png)

What the app should be showing after FB authorization
![image](https://cloud.githubusercontent.com/assets/7582457/23321640/498087fe-faae-11e6-9abe-f0c70f27a58d.png)

If you close the app and re-open, it will show the correct screen when you hit the Login w Facebook button... but it should not be showing the incorrect screen at all.

**Comment by rudjdev** [comment]
fixed

**Comment by jterps08** [comment]
confirmed closed and working
