### ISSUE TITLE
Prod Mailgun

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#527]
Mailgun isn't working in Prod

**Comment by igaponov** [comment]
fixed

**Comment by jterps08** [comment]
I just created a new group ProdTest3 and I see no mailing list created in mailgun. I see a prodtest2 yesterday, but not sure why there are no members in the mailing list...

**Comment by jterps08** [comment]
any update on this @igaponov ?

**Comment by igaponov** [comment]
@jterps08 it's ready for retest

**Comment by jterps08** [comment]
confirmed!
