### ISSUE TITLE
Push Notification Registration at Completion of Registration

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#528]
When a new user completes new user registration (via manual e-mail address registration or via Facebook registration), we need to ensure the device has a token registered. Right now, the user must log out and log back in in order to register a token... User should not need to log out/in for push notifications to work.

**Comment by rudjdev** [comment]
fixed

**Comment by jterps08** [comment]
@rudjdev @igaponov push notifications are not working on iOS. Not sure if it's related to this or not. 

There also is an error at the end of registration now. Again, not sure if it's related to this.

**Comment by sirius2013** [comment]
I can fix this

**Comment by jterps08** [comment]
Confirmed on Android. Unable to test on iOS due to prod notifications cert issue.

**Comment by jterps08** [comment]
confirmed on ios
