### ISSUE TITLE
Manual User Registration not working on iOS

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#530]
Hangs on this screen

![image](https://cloud.githubusercontent.com/assets/7582457/23323487/c89aa0bc-fab6-11e6-8a40-502a43c95356.png)

**Comment by rudjdev** [comment]
I disabled SSL cert validation on client side and registration works

**Comment by jterps08** [comment]
Marking this as ready for retest. We will need to fix the SSL Cert issue on the prod server @igaponov @austinpapp  and once that's done we will need to enable SSL cert validation on the client side again and confirm it works before deploying to app stores.

**Comment by devotebest** [comment]
hi, should I work now?

**Comment by austinpapp** [comment]
SSL cert is good?

**Comment by jterps08** [comment]
I will re-open this if needed, but Igor confirmed the cert is good... The Report Dwonload button now works without any problems so I think that the cert is good.. I will test again today
