### ISSUE TITLE
Collect All Certs, Keys, Etc.

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#532]
API public and private keys (Mailgun, Stripe, Google)

Push Notifications Dev / Prod for Google and Apple

Deployment Keys for Apple and Google App Stores

Deployment Certs and Files for Backend Server

Other? Please add to list. I will hunt around and collect in a secure location.

**Comment by austinpapp** [comment]
@jterps08 let's keep this to mobile only. backend certs should be added to the server issues.
