### ISSUE TITLE
Unable to Save User Profile

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#533]
When user tries to edit user profile and changes a non-email field, and clicks save, the system gives an error because the e-mail address is already being used.

System should know that, when e-mail is not being changed, it should not go through the "already being used" error check.

I think this is only a problem on Facebook-connected accounts.

**Comment by igaponov** [comment]
@jterps08 release 2.1 or 2.0?

**Comment by jterps08** [comment]
Discovered in 2.0 but we don't have to fix it until 2.1
