### ISSUE TITLE
ionic 2 

### ISSUE THREAD

**Issue by leroygumede** [PowerlineApp/powerline-mobile#539]
I would love to push a few pull-requests, Any plans on moving to ionic 2 ? 
and how does one log into the app with dev config

**Comment by cquezpro** [comment]
sure, I am super with ionic 2.

**Comment by leroygumede** [comment]
@sirius2013 me too :) , would love to help but only with ionic 2 framework

**Comment by jterps08** [comment]
@leroygumede @sirius2013 thank you both for your interest in Powerline! We do plan on moving to Ionic 2, but we are prioritizing user-facing experience changes (milestones 2.1, 2.2, 2.3) before moving to Ionic 2. Do you have any idea on how long it would take to move this app to Ionic 2?

**Comment by leroygumede** [comment]
@jterps08 in realistic terms it should not take a while. All the backend services have been created and general look at feel has already been set.

**Comment by jterps08** [comment]
@leroygumede Thanks for this. Are you on Upwork? Can you provide a link to your profile, if so so that we can save you for future reference. I would like to upgrade to Ionic 2 eventually. Thanks.

**Comment by leroygumede** [comment]
Sure @jterps08 I would love to help, Please feel free to PM at [here](https://www.upwork.com/o/profiles/users/_~01c44be080320b0fbf/)
