### ISSUE TITLE
Staying Logged in After Registration & First Login

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#55]
I should be able to register with or without Facebook with no problem and stay logged in on the user’s device after the new user's first login. (The user should stay logged in after completing registration).

When I log out manually and log back in, the app should work with no problem. Otherwise, user should stay logged in if "stay logged in" option is true (default true).

**Comment by petervojtek** [comment]
I have to first fix #60 and #59 to reproduce this issue (registration workflow).

**Comment by petervojtek** [comment]
fixed. current behaviour is following:
after successful registration user is kept signed in (after app restart or browser reload).
on login, user is kept signed in only when keepSignedIn checkbox is turned on.

I tested it on register via email. register via facebook is currently broken due to #66
