### ISSUE TITLE
Edit/Delete Comments Buttons Not Appearing

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#56]
Not Able to Test (Comments not loading): Edit/Delete buttons should appear on any comment I authored. They should not appear on any comments I did not author.

Please see issues #10 for details. This was previously implemented in PR #15

**Comment by petervojtek** [comment]
I am unable to reproduce this bug, I guess bug #61 prevents me to see any posts and comments. Even when I create new message, I cannot see this new message in feed (and thus I am unable to add a comment to the message).

**Comment by petervojtek** [comment]
I experience following behaviour:
Edit and Delete buttons do appear properly (when I click the three blue dots on right side of a comment), and they are visible only when I am author of the comment.

However when I try to edit or delete my comment, following error is raised:

```
Edit comment:
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/micro-petitions/106/574. Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.

Delete comment:
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/micro-petitions/106/574. Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response.
```

@igaponov , can you guide me on how to alter the ajax calls to match the latest API?

**Comment by luckydevstar** [comment]
These are very easy issue. But I want to get approval from Jesse. Before that, I can't commit anything to that.

**Comment by jterps08** [comment]
Thank you Peter - you should work with Igor (@igapanov), not Ivan on this. Igor is our backend expert. He will work with you moving forward and answer questions regarding the backend.

**Comment by petervojtek** [comment]
@jterps08 , I apologize for wrong assignment. However you may see that @igapanov is actually not recognized by github annotator (and thus Igor is not notified when his name is mentioned) -- I guess that is because he is not added to this project?

**Comment by jterps08** [comment]
No need to apologize. I have tried to add @igapanov to the team. I did so about 5 minutes ago. He is not online right now, but I'm sure he will join when he is back. I also pinged him on the Slack.

**Comment by igaponov** [comment]
You need to use `PUT|DELETE /api/micro-petitions/{micro-petition-id}/comments/{comment-id}` endpoints.

**Comment by petervojtek** [comment]
hi @igaponov , I altered the URL as suggested, but the error remains:

```
edit comment:

XMLHttpRequest cannot load https://api-dev.powerli.ne/api/micro-petitions/106/comments/574. 
Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.
```

As far as I can see, there is no [API method](https://api-dev.powerli.ne/api-doc) in API documentation which features `micro-petitions` and `comments` in one url.

**Comment by igaponov** [comment]
Can not reproduce:

```
http PUT https://api-dev.powerli.ne/api/micro-petitions/106/comments/574 "Authorization: Bearer type=\"user\" token=\"$TOKEN\"" "Origin: https://powerli.ne"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: accept, origin, x-requested-with, token, content-type
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Mon, 20 Jun 2016 19:29:54 GMT
Server: nginx/1.4.6 (Ubuntu)
Set-Cookie: PHPSESSID=o3bgpjrevh8b7plhqmuegkgb21; path=/
Transfer-Encoding: chunked
X-Debug-Token: 9e3fec

{
    "author_picture": "http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/5630c377e06b3.jpeg", 
    "comment_body_html": "", 
    "created_at": "Mon, 20 Jun 2016 07:37:33 +0000", 
    "id": 574, 
    "parent_comment": 459, 
    "privacy": 0, 
    "rate_sum": 1, 
    "rates_count": 1, 
    "user": {
        "avatar_file_name": "http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/5630c377e06b3.jpeg", 
        "first_name": "Jesse", 
        "full_name": "Jesse Chen", 
        "id": 16, 
        "last_name": "Chen", 
        "type": "user", 
        "username": "jtest1"
    }
}
```

Can you show your raw request?

API method: `PUT /api/{typeEntity}/{entityId}/comments/{id}`

**Comment by petervojtek** [comment]
@igaponov , the issue is when I test it from browser (chrome 51), browser will not trigger the actual PUT request, because it is preceded by preflight OPTIONS request -- this OPTIONS request is successful (200 OK), but response header lacks `Access-Control-Allow-Methods`, as stated here:

```
XMLHttpRequest cannot load https://api-dev.powerli.ne/api/micro-petitions/106/comments/574. 
Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.
```

So the browser will halt the real PUT (and DELETE) request.

Surely there are browsers which do not perform this preflight OPTIONS check (or have different security model), or when tested from cmdline via curl or wget, the OPTIONS request is omitted and directly the PUT is performed, but this does not seem to be option for me from JS app.

I am not sure if we understand each other, from my point of view the correct solution is to set proper values to `Access-Control-Allow-Methods` on server side -- but maybe I am wrong, feel free to correct me :)

**Comment by igaponov** [comment]
I know about OPTIONS, this is my request:

```
http OPTIONS https://api-dev.powerli.ne/api/micro-petitions/106/comments/574 "Authorization: Bearer type=\"user\" token=\"$TOKEN\"" "Origin: https://powerli.ne"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: accept, origin, x-requested-with, token, content-type
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Tue, 21 Jun 2016 06:29:24 GMT
Server: nginx/1.4.6 (Ubuntu)
Transfer-Encoding: chunked
X-Debug-Token: f9eb57
```

Show me yours please

**Comment by petervojtek** [comment]
here is my request:

```
Request URL:https://api-dev.powerli.ne/api/micro-petitions/106/comments/503
Request Method:OPTIONS
Status Code:200 OK
Remote Address:52.5.45.80:443

request headers:
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Access-Control-Request-Headers:token
Access-Control-Request-Method:PUT
Connection:keep-alive
Host:api-dev.powerli.ne
Origin:http://localhost:8100
Referer:http://localhost:8100/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

response headers:
Access-Control-Allow-Headers:accept, origin, x-requested-with, token, content-type
Access-Control-Allow-Origin:*
Cache-Control:no-cache
Connection:keep-alive
Content-Type:application/json
Date:Tue, 21 Jun 2016 06:39:34 GMT
Server:nginx/1.4.6 (Ubuntu)
Transfer-Encoding:chunked
X-Debug-Token:402256
```

**Comment by igaponov** [comment]
Show PUT request

**Comment by petervojtek** [comment]
there is no PUT request, because the OPTIONS request response headers lacks the `Access-Control-Allow-Methods: PUT, DELETE`, and thus browser will not fire the PUT request.

**Comment by igaponov** [comment]
@petervojtek wait for merging https://github.com/PowerlineApp/powerline-server/pull/150
