### ISSUE TITLE
Ability to View Posts by Followed Users Only

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#566]
For the main newsfeed, I need to be able to easily see just those I follow somehow. We need to think of a situation where a feed has extremely high volume and the user only wants to see the people he follows.

**Comment by igaponov** [comment]
@jterps08 there are already two tabs in the mobile apps: You/Following. Is it not what you are looking for?

**Comment by jterps08** [comment]
@igaponov It's different than the Social Activity updates... 

Basically, we need a newsfeed that only returns posts by followed users in their town/state/country groups and shared groups... We can discuss on Slack

**Comment by jterps08** [comment]
see #558

**Comment by jterps08** [comment]
Closing this as a duplicate
