### ISSUE TITLE
Unstable UI Behavior

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#57]
The home screen UI is periodically unstable. The title bar element/row (menu button + title) disappears and group selector element/row disappears randomly as well. It is unclear why this happens. It seems the following events trigger this to occur.

Triggered events:
1. Tapping a filter button on group selector
2. Tapping Add Group button on group selector. 
3. Visiting Favorites List and returning to Home screen. 
4. Opening an item in newsfeed and returning to Home screen.
5. Others TBD and listed as discovered.

**Comment by petervojtek** [comment]
I experienced this behaviour as well, but since I f[ixed several bugs](https://github.com/PowerlineApp/powerline-mobile/issues/129#issuecomment-230492545) related to groups selector, this bug seems no longer present.
