### ISSUE TITLE
Correct UI Performance - GIF Gallery

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#58]
Test Plan Inventory: https://docs.google.com/spreadsheets/d/1XN_LdWTkLXAvTMh4YzNohKwvxrrXJH8Y9YigNd0KA4k/edit?usp=sharing

Easier to add the GIFs here than it is to add them to the Wiki...

Joining a group with passcode and required information
![joining a group with passcode and required information](https://cloud.githubusercontent.com/assets/7582457/15658483/ffd6ad06-268a-11e6-87bd-02f6ffd47bc1.gif)

Viewing My Representatives Information
![my representatives](https://cloud.githubusercontent.com/assets/7582457/15658482/ffd60b58-268a-11e6-817e-ebb0995f833e.gif)

Opening a Post and Mentioning a User
![opening a post and mentinoing a user 2](https://cloud.githubusercontent.com/assets/7582457/15658484/ffd87294-268a-11e6-9ddb-4600bef85ab9.gif)

Adding a Comment to a Post and Upvoting another user's comment
![adding a comment to a post and upvoting another user s comment](https://cloud.githubusercontent.com/assets/7582457/15658485/ffd90ccc-268a-11e6-96f5-5dad2684d52b.gif)

Upvoting another user's post
![upvoting a user s post](https://cloud.githubusercontent.com/assets/7582457/15658486/ffd90bd2-268a-11e6-9817-7a02f8377c4b.gif)

Following another user
![following another user](https://cloud.githubusercontent.com/assets/7582457/15658487/ffd91c8a-268a-11e6-859f-41265773858b.gif)

Creating a new post
![creating a new post](https://cloud.githubusercontent.com/assets/7582457/15658488/ffde2f0e-268a-11e6-9124-85b459ce2a16.gif)

**Comment by petervojtek** [comment]
this issue is to exhibit how the app is supposed to be used
