### ISSUE TITLE
Root comments

### ISSUE THREAD

**Issue by igaponov** [PowerlineApp/powerline-mobile#582]
Add a possibility to add a root comment (without a parent comment)

**Comment by igaponov** [comment]
Backend is ready

**Comment by jterps08** [comment]
Can we clarify the difference between root comment, parent comment, and child comment? Also is this v2.2 or is this critical for delivering Comment Counter in v2.1?

**Comment by igaponov** [comment]
@jterps08 root comment has no parent. It's critical for delivering Comment Counter in v2.1

**Comment by jterps08** [comment]
I see - we need to make adjustments to the app then? I didn't know this was going to delay 2.1 :-( Will connect in Slack

**Comment by jterps08** [comment]
This is a reference for @rudjdev 

![image](https://cloud.githubusercontent.com/assets/7582457/24957108/977a5326-1f58-11e7-8f5c-68c37a3f4d6e.png)

**Comment by jterps08** [comment]
Reopening per discussion on Slack. There is still a problem with viewing root comments on the Item Detail Screen and making new comments from the Item Detail Screen. @rudjdev @igaponov
