### ISSUE TITLE
UX Redesign Support: Group Profile Additions

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#585]
The ability for the system to support the creation/modification/deletion and display of the following to the general group profile:

- Up to five hyperlinks - with labels (e.g. Yahoo! - http://www.yahoo.com)... label, hyperlink - up to 5
- A group banner (an image this is distinct from the group avatar)... image
- Group Welcome Video... hyperlink - 1
- Group Rules... one large text/memo field, ideally with markdown support
- Group Tags... ability for a group to be associated to tags for searching purposes

**Comment by igaponov** [comment]
This issue is too big
@jterps08 maybe it'd be better to split it up in 5 separated issues?

**Comment by austinpapp** [comment]
Agree with @igaponov. Let's break this up and explicitly define the request

**Comment by jterps08** [comment]
Replaced by #595, #596, #597, and #507....
