### ISSUE TITLE
Register user via email in browser fails with Cannot read property 'datePicker' of undefined

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#59]
date of birth date picker is not working in browser (it works in android) and there is not other way to fill in the d.o.b.

**Comment by luckydevstar** [comment]
it is error of date picker cordova plugin. and Ionic application can't run any cordova plugin in browser.

**Comment by petervojtek** [comment]
I fixed it in such a manner that in browser it will fill in a fixed date (01/01/1970), just to be able finish registration successfully for further development purposed. On smartphone it works with the date picker as up to now, so that user can pick his own d.o.b.

I intentionally did not added some datepicker to browser as that will be more time consuming and I guess we will use browser only for development purposes.
