### ISSUE TITLE
Unable to login with Facebook

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#601]
We need to stabilize DEV: Right now, it does not seem FB registration is working correctly given the dev APK that we are working with. It is *possible* that the dev APK we have is not the same as PROD, but I'm not completely certain. I would like to be completely sure that when we deploy backend to PROD, FB Registration and FB login work correctly

Non-FB Registration - SUCCESS
FB Registration - **FAILED**
Email Login - SUCCESS
FB Login - SUCCESS
Group registration - SUCCESS
Content creation (all types) - SUCCESS
Commenting, @mentions, #hashtags - SUCCESS
Push notifications - SUCCESS
Elected leader information - SUCCESS 
Payments - SUCCESS
Influences - SUCCESS
Groups - SUCCESS

**Comment by igaponov** [comment]
@jterps08 should it be closed?
