### ISSUE TITLE
STAGING - Notification Registration Authentication Error

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#604]
I'm assuming this is related to the authentication change made to the API? We need the api to be backwards compatible as we're not making another Ionic release to the app store. User is kicked back out to Login screen after this error, but can log back in with no problem. user abc2

![image](https://user-images.githubusercontent.com/7582457/26906892-80dec214-4bbd-11e7-8275-fb07b0ae4939.png)

**Comment by igaponov** [comment]
User should be authorized to access this endpoint, it's frontend issue.

**Comment by jterps08** [comment]
Sigh. Okay. I don't know why this didn't happen in Dev before with the dev build. Maybe it did and I ignored it somehow? I'm not sure. We can't deploy this v2.1.1 release to PROD if it's going to break new user registration and device notification registration on the v2.1.0 Ionic app.

So, what this means is that v2.1.1 cannot go to PROD until RN app is ready to replace Ionic app in app stores (or if that looks like we'll miss our mid-July target, we might have to have the Ionic app updated). Do you agree @igaponov ? I need a little extra perspective on this. There is no urgency to deploying v2.1.1 to prod with v2.1 ionic app unchanged, right? The only real benefit would be at-everyone mention.

**Comment by igaponov** [comment]
@jterps08 nothing was changed for device registration, Ionic app should work with 2.1.1 version of backend. There is no sense to wait for RN app, because it needs some features from v2.1.2 (590, 596,597 for example)

**Comment by jterps08** [comment]
@igaponov I registered another user abc3 on STAGING and did *NOT* experience 604. Closing.
