### ISSUE TITLE
STAGING - Group letter avatar not appearing

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#606]
User avatars appearing correctly in newsfeed and in User Profile screen. 

Group Avatars NOT showing Letter Avatar in Newsfeed or Item Detail Screen or in Group Profile screen. See below:

![image](https://user-images.githubusercontent.com/7582457/26907064-97f074c4-4bbe-11e7-9217-9f6985880f5b.png)

![image](https://user-images.githubusercontent.com/7582457/26907066-9c3bda28-4bbe-11e7-85ce-75fd75d9e77b.png)

**Comment by igaponov** [comment]
@jterps08 avatars in a newsfeed are updated

**Comment by jterps08** [comment]
confirmed and closing
