### ISSUE TITLE
PROD/STAGING - Comments do not work on leader content

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#608]
This somehow slipped by me for v2.1.0... Comments only work on user posts and user petitions. This is probably related to that comments counter structure thing :-(. At this point, we can't make a new ionic release, so if there's nothing we can do from a backend perspective, we'll just need to make sure this is roundly addressed in the RN app. 

User is unable to add a comment to any leader content (poll, discussion, etc.)

**Comment by igaponov** [comment]
@jterps08 I've added a comment for your post "This is a test ghat no one should see" successfully. Had you seen any error when you tried to comment?

**Comment by jterps08** [comment]
I get no error at all in fact... I will try to record video and share on Slack
