### ISSUE TITLE
home page - HTTP GET api-dev.powerli.ne/api/activities - not found

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#61]
`GET https://api-dev.powerli.ne/api/activities/?offset=0&limit=20&sort=priority 404 (Not Found)`
due to this reason the group activity pane displays loading spinner indefinitely.

happens in dev env.

**Comment by luckydevstar** [comment]
You must referenced dev-api document.
You can remove "offset" and "limit" in api call url.

**Comment by petervojtek** [comment]
Privet @ohienko1991,

thanks for reply, I confirm that once _offset_ and _limit_ is removed from url the call is successfull and activites are displayed.

I did not commited any patch regarding this bug as I am not sure if you want to get rid of all the business logic around _offset_ and _limit_ [here](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/activity.js#L243).

**Comment by petervojtek** [comment]
I fixed it, but I rather do not removed all the business logic related to [offset and limit](https://github.com/PowerlineApp/powerline-mobile/commit/e4b52aba07efcd97f206e4767e2c59571d685728), thought it is not used. 

I am not sure if I should remove the `offset` and `limit` business logic completely from code or it will be maybe used later.

**Comment by jterps08** [comment]
We definitely want the newsfeed to support "infinite scrolling" which is why I think the offset and limit is in there... @austinpapp ?

**Comment by petervojtek** [comment]
btw there is some [/api/v2/activities](https://api-dev.powerli.ne/api-doc#get--api-v2-activities) call which has a `page` and `per_page` parameters..maybe that one was meant to be used..

**Comment by austinpapp** [comment]
we should use v2 where we can. api-doc should expose that. but as @jterps08 said, we had used those parameters for infinite scrolling.
