### ISSUE TITLE
icons for some groups as missing

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#62]
`http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/54330a0a8721a.jpeg 404 (Not Found)`

dev env.

<img width="675" alt="screen shot 2016-06-08 at 08 04 16" src="https://cloud.githubusercontent.com/assets/225506/15884297/c6054f26-2d4f-11e6-9725-5c919ca19393.png">

**Comment by petervojtek** [comment]
I am not sure if this is only an issue of old groups, or it can affect newly created groups as well - I do not think I have the ability to create a group with custom avatar image. Maybe @jterps08 can tell me when/how is it supposed to be possible to assign a group a custom avatar?

**Comment by jterps08** [comment]
We can create a group first and then edit the group profile to upload a custom avatar. 

For what it's worth, based on the screenshot you have below, there are two icons showing: 1) The placeholder icon (5-person gray/white icon) which should not appear anywhere (it should show NG-letter instead), and 2) The broken-image-link icon (cloud+mountain icon) which represents a bad image hyperlink / bad imgix processing.... 

In the screenshot above, it's item 2 that needs to be fixed. I don't know why these references have broken, but we can't load http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/54330a0a8721a.jpeg manually so I'm assuming that whatever the app is referencing on the backend is part of the problem.

Austin can you help identify an accurate avatar hyperlink for testing purposes from one of the groups in the screenshot above (Group2014 or BuildTestGroup etc)

**Comment by petervojtek** [comment]
1) ok, in the meanwhile I will fix groups to display ng-letter icons if group has no imgix avatar image.

**Comment by austinpapp** [comment]
im not sure exactly where this file name came from but its in the database and thus constructed in the fashion you see. however, s3 does not have that file available to it hence the broken image. 

we could create a 1 time script that goes through and checks if the file exists on s3 with what the data field has. if it does exist, we simple skip that one. if it doesn't exist on s3, we NULL the value in the field. this should prevent broken images and default to ng-letter.

**Comment by austinpapp** [comment]
all of the `avatar_file_name` references in the dev db do not actually exist in dev s3 bucket. i'm not that concerned about that. anyway, i nulled all of those values. however, i did update group 308 with a reference to an existing file. we can test there. basically, all groups should show up with ng-letters now.

**Comment by petervojtek** [comment]
I confirm that group 308 icon is working :)

<img width="777" alt="screen shot 2016-07-26 at 15 04 36" src="https://cloud.githubusercontent.com/assets/225506/17138809/59fa9868-5342-11e6-9c28-eee839d5b5c3.png">

**Comment by jterps08** [comment]
Finally! :100:
