### ISSUE TITLE
unable to add comment to post

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#63]
in dev env, In home screen in activity feed, I click Reply button under a post.
I am forwarded to this screen `http://localhost:8100/#/petition/undefined?focus=add-comment`.

When I insert text into the comment text field and press button, I receive following error:

```
ionic.bundle.min.js:139 TypeError: Cannot read property 'id' of undefined
    at n.$scope.reply (discussion.js:147)
    at fn (eval at compile (ionic.bundle.min.js:1), <anonymous>:4:206)
    at f (ionic.bundle.min.js:283)
    at n.$eval (ionic.bundle.min.js:165)
    at n.$apply (ionic.bundle.min.js:166)
    at HTMLFormElement.<anonymous> (ionic.bundle.min.js:283)
    at HTMLFormElement.dispatch (jquery.js:4435)
    at HTMLFormElement.r.handle (jquery.js:4121)
    at n (ionic.bundle.min.js:22)
    at t (ionic.bundle.min.js:22)
    at HTMLDocument.r (ionic.bundle.min.js:22)
```

I guess the problem is that some object ID is not set properly (`undefined`): `http://localhost:8100/#/petition/undefined?focus=add-comment`

also following error occur in js console at the same time:

```
GET https://api-dev.powerli.ne/api/micro-petitions/undefined/comments/ 404 (Not Found)
```

**Comment by petervojtek** [comment]
I fixed the bug, however following behaviour occurs:

no matter on which Post I click Reply, I always am redirected to this one particular petition:
`http://localhost:8100/#/petition/106?focus=add-comment`

@igaponov maybe you can to help me determine if I am doing something wrong here ? (or is it desired behaviour?)

I acquire the url ID 106 via `activity.entity.group_id`.
 formerly, `activity.entity.id` was used for the purpose, but currently backend API provides no value in `activity.entity.id` (that is why there was `undefined` in url)

**Comment by igaponov** [comment]
This redirect is on the frontend side. The url is wrong of course, id is undefined. Check object's id, that you use to create this url.

**Comment by petervojtek** [comment]
@igaponov , here are more details:

I created this Post:
<img width="397" alt="screen shot 2016-06-20 at 18 07 38" src="https://cloud.githubusercontent.com/assets/225506/16201543/2d8bbf74-3712-11e6-86c2-51afdae5fee9.png">

In activity feed the displayed information is correct, there is displayed proper `description` ("peter's test 1 on 2016/06/20") and proper Author ("jesse").

Then there are two IDs in the object: `id=347` and `entity.group_id=57`.

Now I go into detail of the Post. When I try to use `id=347` (GET `https://api-dev.powerli.ne/api/micro-petitions/347`), this throws `500 Internal Server Error`.

When I try to fetch data via `entity.group_id=57` (GET `https://api-dev.powerli.ne/api/micro-petitions/57`), I receive 200 OK, and following content:

```
{"id":57,"title":"","petition_body":"test123","group":{"id":55,"group_type":0,"avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/533ab314cf15e.jpeg","official_title":"Group2014"},"group_id":55,"is_outsiders_sign":false,"created_at":"Fri, 17 Jul 2015 06:19:07 +0000","expire_at":"Sat, 18 Jul 2015 06:19:07 +0000","user_expire_interval":1,"user":{"full_name":"Nik Hpl","id":33,"username":"nik","first_name":"Nik","last_name":"Hpl","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"publish_status":0,"type":"quorum","options":[{"id":1,"value":"Upvote","votes_count":0},{"id":2,"value":"Downvote","votes_count":0}],"cached_hash_tags":[],"metadata":{}}
```

As you can see, there is no mention of Jesse as an user (instead there is "Nik Hpl") nor my description `peter's test 1 on 2016/06/20`.

I am not sure what is actually the desired behaviour, originally the code was using `entity.id` when fetching Post details.

**Comment by igaponov** [comment]
This endpoint must be deprecated, wait for merging https://github.com/PowerlineApp/powerline-server/pull/149

**Comment by petervojtek** [comment]
the pull request seems to be merged, but I am not sure what am I supposed to receive from server -- the server behaviour seems to be the same (tested now).

**Comment by igaponov** [comment]
@petervojtek now you have to use another endpoint, check docs

**Comment by petervojtek** [comment]
currently the code is using following two API calls:
`GET https://api-dev.powerli.ne/api/activities?sort=priority`
to get feed of user activities

and
`GET https://api-dev.powerli.ne/api/micro-petitions/{ID}`
to get detail od a particual activity.

I would like to make sure:

Should I replace 
`GET https://api-dev.powerli.ne/api/activities`
with
`GET https://api-dev.powerli.ne/api/v2/activities`

?

And regarding activity item detail, I am not sure if I am supposed to replace
`GET https://api-dev.powerli.ne/api/micro-petitions/{ID}`
with some other API call. there does not seem to be any v2 call.

**Comment by igaponov** [comment]
1. `GET https://api-dev.powerli.ne/api/micro-petitions/{ID}` returns a micropetition, not an activity.
2. Yes, you should replace this endpoint
3. Wait for the next deploy, then check docs

**Comment by petervojtek** [comment]
since today the master-detail view is working properly (I made no additional code changes), thought only for posts created since today (micro-petitions and petitions). I consider this as fixed.

**Comment by jterps08** [comment]
Just an FYI here for @petervojtek ...

A post (micropetition) or a petition (petition) appears in the user's newsfeed (3person icon)... whereas a social activity appears appears in the user's social activity feed (2person icon)
