### ISSUE TITLE
Newly created Post/Petition is not immidiately displayed in Home page feed

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#69]
1. On Home page, I click top right corner (New Post)
2. I fill in the form and click create
3. I am redirected to #main page, but the new post is not visible in the the activity feed

when I refresh the whole #main page, the post appears.

@jterps08 , is this intended behaviour, or should the new post immidiately appear on step 3.?

**Comment by jterps08** [comment]
The post should appear immediately on Step 3 in the newsfeed. Ideally, every time the user opens the newsfeed, the user sees the most recent data.

For background information, back in November/December, we added the concept of local caching when we switched over from plain Cordova to Ionic. The idea was to increase performance and imrpove user experience to prevent long newsfeed loading time. Infinite scrolling (pagination) was part of this effort as well, but it wasn't until a few months later that we could make the backend change needed to support pagination.

We want the user's feed to be speedy, up-to-date, and intuitive..

**Comment by petervojtek** [comment]
I will fix this issue only after I fix #71

**Comment by jterps08** [comment]
Not sure if this is a dev server issue or not, but there is also a lag time between clicking the submit button on the New Post screen and the time that "toast" appears saying "Sent". The spinner appears during this time. If this is a backend issue, fine. If this is a frontend issue, it would be good for the user to experience a snappier reaction from the app after hitting the submit button.

**Comment by petervojtek** [comment]
@jterps08 , I cannot reproduce some significant lag time between clicking Submit and waiting for toast "Sent" to appear.. in my case there is almost no lag time (maybe 100-200ms).

**Comment by jterps08** [comment]
I will close this for now and re-open if it occurs again. May be my device.
