### ISSUE TITLE
Home screen - switching between groups is not filtering activity items properly

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#71]
1. I login as JTest1
2. on Home page, All tab is active, and I see the activity item feed (e.g. "Post made for Bucklin group.").
3. I click tab Bucklin and the feed is empty (I expected to see there at least the  "Post made for Bucklin group."
4. I click the All tab. I see no items in the feed (feed is empty) -- I expected here to see the same activity items as in step 2.

@jterps08 , can you please confirm what is the desired behaviour?

**Comment by jterps08** [comment]
You are correct. Switching between groups using the Group Selector on the Home screen should filter the feed.

The ALL feed shows all content in all of the groups that the user is part of, sorted according to priority and date. The user is automatically joined to town, state, country groups (e.g. Bucklin, Kansas, United States) but can create or join any other groups that he wants (e.g. Save the Whales). The All feed shows all of the content from these groups. Each icon on the "group selector" (e.g. Bucklin) should activate a filter in the feed to display only the items from that group.

**A note on sorting and counters**
The backend handles the prioritization of the posts (see powerline-server Issue 58 - https://github.com/PowerlineApp/powerline-server/issues/58)... The frontend should display the posts according to that provided sort order - @igaponov can clarify. 

There are also supposed to be "counters" that appear on the newfeed icon (2-person icon), the All Icon, and each of the Group tile icons. If zero, they are hidden. If 1 or greater, they represent the "Prioritized" content for that group (again, explained in the link above). 

For example: Let's say there's 2 polls in the USA group, 3 petitions in the Save the Whales group and, 1 boosted post in the Bucklin group, and 25 non-boosted posts in Kansas group. The counters would be as follows:
- Newsfeed icon / All icon - "6"
- Bucklin - "1"
- Kansas - (nothing)
- USA - "2"
- Save the Whales - "3"

The intent is to put content from leaders and boosted posts at the top of the feed (and in the count), followed by everything else. The group selectors are simply filters on the all feed in this respect.

**Comment by petervojtek** [comment]
@igaponov - can you please recommend me which API call should I use to replace this one:
`GET /api/poll/answers/`

Here is the [source code context](https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/activity.js#L298)

Also do I understand properly that Poll = Petition ?

**Comment by igaponov** [comment]
@petervojtek There is no new version of this endpoint now, I will create one.

Petition = Poll (Petition is a type of Poll).

**Comment by petervojtek** [comment]
ok, I move the task to #89, as this issue ("switching between groups is not filtering activity items properly") is actually resolved.
