### ISSUE TITLE
Cannot approve follower - no notification arrives

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#76]
1. login as JTest1
2. on Post created by Peter1, click Follow button
3. App says "Waiting for user to approve"
4. Login as Peter1
5. no message or activity feed arrived regarding the approval (not sure if it should be a message or social activity feed, but both of them are blank)

**Comment by jterps08** [comment]
This is hard to test alone. Ideally you need two separate devices to witness the live notification that is supposed to be generated when a new Follow request is created. 

When a user receives a follow request, two things happen:
1) A push notification alert is instantly sent to the followed user and displayed on the user's device if that user is logged into that device at the moment
2) A social activity is generated and displayed in the You tab of the Social Activity Feed (2person icon). It should result in the social activity counter (blue fill) turning to '1'.

A note on the SAF counter:
The newsfeed counter (3person icon, red-fill) continues to display until there are no more red/priority items in the newsfeed. The SAF counters (2person icon, blue-fill) displays with the number of updates, but resets to zero and disappears as soon as the user taps on the tab. The intent of this design is to encourage users to address all of their red-priority items in the newsfeed (similar to needing to address your 7 voicemails before the voicemail counter disappears). We may change this design in the future, but this is the way it is supposed to work currently. 

A note on the Announcements feed (mail icon):
There should be nothing in the Announcements feed (mail icon), which is for leader Announcements and group invitations.

Your notification problem may or may not be related to our switch to Event Listeners on the backend per PR #85 in the server repo.

**Comment by petervojtek** [comment]
I fixed the original bug as described in issue title. 
regarding to expected behaviour described by Jesse -- if I will find out that app behaves differently than Jesse described, I will create new bug regarding it.
