### ISSUE TITLE
Notification Action Buttons (Non-leader)

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#8]
Notification Action Buttons Scope - For each of these existing notifications, we want to add the following action buttons. Ignore is easy. Open is easy. The others are different and will require the callbacks: 1) Approve a received follow request, 2) Join/accept a received group invite, 3) Upvote a post [boosted or from a followed user], 4) Downvote a post [boosted or from a followed user].
- **NOTIFICATION EVENT**
- Button 1 Action
- Button 2 Action
  -*\* Social @Mention**
- Button 1: Open
- Button 2: Ignore
- **Social Follow Request**
- Button 1: Approve (also opens up Social Influences tab after)
- Button 2: Ignore
- **Social Post-created-by-Followed-User**
- Button 1: Upvote (also opens up item after, preferably uses Upvote double-arrow from newsfeed quick action bar)
- Button 2: Open
- **Automatic Boosted Post**
- Button 1: Upvote (also opens up item after, preferably uses Upvote double-arrow icon from newsfeed quick action bar)
- Button 2: Downvote (also opens up item after, preferably uses Downvote double-arrow icon from newsfeed quick action bar)
- **Manual Boosted Post**
- Button 1: Upvote (also opens up item after, preferably uses Upvote double-arrow icon from newsfeed quick action bar)
- Button 2: Downvote (also opens up item after, preferably uses Downvote double-arrow icon from newsfeed quick action bar)
- **Group Invite**
- Button 1: Join (also opens up group profile page)
- Button 2: Ignore
- **Group Permissions Changed**
- Button 1: Open
- Button 2: Ignore

This will likely require the latest version of the https://github.com/phonegap/phonegap-plugin-push plugin.

**Comment by jterps08** [comment]
Related: https://github.com/PowerlineApp/powerline-server/pull/140

**Comment by petervojtek** [comment]
Do I understand properly that this enhacement is related only to following two screen: social feed and messages? (or is it also somehow related to push notifications?)

<img width="764" alt="screen shot 2016-07-27 at 12 41 57" src="https://cloud.githubusercontent.com/assets/225506/17172849/98c98314-53f7-11e6-9d42-fcdf29df64f0.png">

**Comment by jterps08** [comment]
No, it is related to the OS push notification alerts. 

Our push notifications plugin: https://github.com/phonegap/phonegap-plugin-push 
has a concept called Notification Action Buttons: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons
which, as outlined here, we want to leverage for certain types of notifications: https://github.com/PowerlineApp/powerline-mobile/issues/8

The concept mockup looks something like this (iOS/Android OS notifications drawer): 

![02554d2a-44f1-11e5-8cd9-0aadd1e02b18](https://cloud.githubusercontent.com/assets/7582457/17188438/0e965942-540b-11e6-8808-9e63fb9bc8e9.png)

**Comment by petervojtek** [comment]
thanks for clarification @jterps08 .

So this issue is actually composed of three tasks:
1. Generate the push notification (on our backend I guess)
2. Deliver the push notification 
3. Display the push notification with proper action buttons.

I am not sure if step 1. and step 2. currently work at all -- how can I make sure the notifications are  working on backend side and are being delivered? Maybe @austinpapp knows the state of the art?

E.g., I did following:  as user A I started following user B, and as user B I was logged in in smartphone, but no notification arrived.

I use this notification plugin sender id:

```
<variable name="SENDER_ID" value="354736666363"/>
```

**Comment by jterps08** [comment]
Step 1 and step 2 should be completed. All push notification alerts are working in production environment and were last fully tested in February. We have been unable to test push notification alerts in dev environment because I don't have an interface to create leader content. 

This item should be about # 3, but we may end up having to confirm 1 and 2 work first. 

Bringing in @austinpapp to discuss how to proceed....

**Comment by petervojtek** [comment]
btw I live in development environment .. I have not tried to access production environment in order to avoid doing some damage..

**Comment by austinpapp** [comment]
the current situation is i have to write the logic to handle the leader questions because we do not have the endpoints to handle it right now...

**Comment by austinpapp** [comment]
as for the other push notification worthy content (micro-petitions, etc) i'm not sure of the best way to test the push notifications without a properly registered mobile device. i have to explore this one a bit more as we need to know what phone id number to use, make sure rabbitmq is working correctly, the consumer is picking up the content off the queue and dropping it on to the right aws sns queue(s). 

this one is not as trivial.

**Comment by jterps08** [comment]
For clarity:

> "... because we do not have the endpoints to handle it right now.."

Not true, we have the endpoints. Igor created them and I can see them in the API doc.

> "...i have to explore this one a bit more as we need to know what phone id number to use, make sure rabbitmq is working correctly, the consumer is picking up the content off the queue and dropping it on to the right aws sns queue(s)..."

Not only is this currently working in production correctly. It was working in February during the last test. I am unsure if any of this got screwed up when we transitioned to single sign-on and API v2. I have been unable to create leader content since API v2 was released. Thus, I am unable to test push notifications.  We need to be able to create leader content with a stub tester or with a quick & dirty frontend form in order to test push notifications since web app is not ready.

We cannot and will not release to the app stores with functioning push notifications.

**Comment by austinpapp** [comment]
it is true. if i create a leader petition, the current endpoint does not auto-publish that petition (not desired anyway) nor there is no endpoint to publish it. therefore, i have to replicate the logic to publish something which would include an entry in activities table and a message to our queue for push notifications.  

igor did work on the event listener to handle this work for the admin site only. we dont have an endpoint that utilizes this logic, yet. 

as for push notifications, i would highly consider prod and dev to be vastly different as far as functionality goes. we've done so much work on the backend that i can't guarantee the push notifications work as expected. so to say it works in prod and it _should_ work in dev is not accurate.

**Comment by petervojtek** [comment]
@austinpapp,

> as for the other push notification worthy content (micro-petitions, etc) i'm not sure of the best way to test the push notifications without a properly registered mobile device

it is not a problem for me to test push notifications on real mobile device (I just need the push notifications to be working in dev-api -- because I deploy powerline app build for dev-api to the mobile device for testing).

**Comment by jterps08** [comment]
I think we can close this as we are now managing issues separately. The item remains in history for requirements reference.
