### ISSUE TITLE
User groups are not displayed in list of her groups

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#81]
1. Login as `Peter1`
2. visit `http://localhost:8100/#/groups`
3. The page tells 'Looks you havent joined no groups'

but Peter1 is member of NY, New York and Usa groups.

**Comment by petervojtek** [comment]
@jterps08 , is it intentional that only groups of type COMMON are displayed in list of user groups (http://localhost:8100/#/groups) ?
I.e., groups of type COUNTRY, STATE and LOCAL are currently intentionally filtered out of the list.

**Comment by jterps08** [comment]
Hey Peter - That is correct - Local/State/Country groups are **not** supposed to be listed in Menu>My Groups list
