### ISSUE TITLE
refactor Activity Read business logic

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#85]
now it is spread all along the app, we want it to be in ActivityRead service, or abandon ActivityRead and move it to ActivityModel.

**Comment by jterps08** [comment]
It's worth discussing with @igaponov and @austinpapp to see what role the backend plays (or should play) in dealing with read activities.

**Comment by petervojtek** [comment]
done as a side effect of fixing #84 in 65409a4fd3c54b5159
