### ISSUE TITLE
Toggle notification (bell icon) on off not working at all

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#87]
and authors of their posts should have the bell enabled (=blue) by default.

**Comment by jterps08** [comment]
posts that the user did not author should have the bell disabled (grey) by default.

**Comment by petervojtek** [comment]
@igaponov , can you recommend me which API call should I use to subscribe an user to an activity (e.g. Post) so that the user will later receive notifications related to the activity?

I discovered [POST /api/users/self/subscriptions](https://api-dev.powerli.ne/api-doc#post--api-users-self-subscriptions), however the API doc is empty and thus I don't know what I am supposed to submit.

In the former mobile app souce code this feature is not implemented so that I cannot relate to any API call.

**Comment by jterps08** [comment]
Follow/Subscribe to a Post that you did not author - https://github.com/PowerlineApp/powerline-server/pull/60

Mute/Unmute the notifications from a post you did author  - https://github.com/PowerlineApp/powerline-server/pull/53

**Comment by igaponov** [comment]
@petervojtek 
submit 

``` json
{"id": "petition_id"}
```

**Comment by petervojtek** [comment]
@igaponov, and how do I unsubscribe?

**Comment by igaponov** [comment]
@petervojtek there is no way to unsubscribe now, wait for v2

**Comment by jterps08** [comment]
We need to have the ability for a user to unsubscribe, too. I'll create an issue.

**Comment by igaponov** [comment]
Move this functionality to v2 and add unsubscribe endpoint: https://github.com/PowerlineApp/powerline-server/pull/171

**Comment by austinpapp** [comment]
PowerlineApp/powerline-server#171 deployed

**Comment by petervojtek** [comment]
ok, it works.
