### ISSUE TITLE
newsfeed: groups of user A are still displayed when you logout as user A and login as user B

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#88]
1. login as Peter1 from NY
2. see groups NY, NY, USA
3. logout as Peter1
4. login as Peter7 (from San Diego)
5. List of groups is: NY, NY, USA.

**Comment by jterps08** [comment]
i assume this is a caching issue

**Comment by petervojtek** [comment]
still not working perfectly -- must press F5 (reload) to fully wipeout the cache -- need to fix it (to avoid pressing F5).
