### ISSUE TITLE
Adopt v2 API for Poll answers 

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#89]
first @igaponov will have to create the backend endpoint (replacement for `GET /api/poll/answers/`)

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/160

**Comment by petervojtek** [comment]
blocked by #142

**Comment by petervojtek** [comment]
will be probably  resolved in https://github.com/PowerlineApp/powerline-mobile/issues/193#issuecomment-243040994
