### ISSUE TITLE
Home screen: news feed: "More" groups button has wrong icon offset when button is active.

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#93]
<img width="761" alt="screen shot 2016-06-28 at 09 08 51" src="https://cloud.githubusercontent.com/assets/225506/16406708/08d96c36-3d10-11e6-9375-b18ad7591a3b.png">

**Comment by jterps08** [comment]
In the screenshot above, the app is also not displaying the town button... All, Town, State, Country... that only lists All, California (State), and US (Country) .Town is missing, which resulted in the More button being in the wrong position.

**Comment by petervojtek** [comment]
the screenshot above is from user `Peter7`, who is from San Diego. If I do understand properly Jesse's previous comment, this means that `GET https://api-dev.powerli.ne/api/v2/user/groups` should list `San Diego` along the list of groups. 

Here is the actual response body from `GET https://api-dev.powerli.ne/api/v2/user/groups`, which features only two groups in `payload` - US and CA. Maybe @igaponov can help us resolve why is `San Diego` group missing?

```
{"page":1,"items":20,"payload":[{"join_status":"active","id":1,"group_type":1,"username":"US","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"The United States of America","acronym":"US","joined":1,"created_at":"Mon, 10 Mar 2014 10:10:51 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5,"group":{"id":1,"group_type":1,"username":"US","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"The United States of America","acronym":"US","joined":1,"created_at":"Mon, 10 Mar 2014 10:10:51 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5}},{"join_status":"active","id":6,"group_type":2,"username":"CA","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"California","acronym":"CA","joined":1,"created_at":"Mon, 10 Mar 2014 10:10:51 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5,"group":{"id":6,"group_type":2,"username":"CA","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_group.png","official_title":"California","acronym":"CA","joined":1,"created_at":"Mon, 10 Mar 2014 10:10:51 +0000","membership_control":"public","fill_fields_required":false,"petition_per_month":5}}],"totalItems":2}
```

Here is profile for `Peter7` (GET `https://api-dev.powerli.ne/api/profile`):

```
{"full_name":"Peter7 Peter7","id":69,"username":"Peter7","first_name":"Peter7","last_name":"Peter7","email":"peter7@test.com","zip":"12345","avatar_file_name":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png","birth":"01\/01\/1977","address1":"San Die","address2":"33","city":"San Diego","state":"CA","country":"US","phone":"+1123","interests":[],"do_not_disturb":false,"is_notif_questions":true,"is_notif_discussions":true,"is_notif_messages":true,"is_notif_micro_following":true,"is_notif_micro_group":true,"is_notif_scheduled":false,"is_notif_own_post_changed":true,"is_registration_complete":true}
```

**Comment by jterps08** [comment]
We should be able to see Town, State, and Country... I don't need Town/State/Country listed in the "My Groups" main menu item. I do need it listed in the 'group selector' element in the newsfeed (and when creating a new post/petition)

**Comment by igaponov** [comment]
@petervojtek There is no `San Diego` group in db for this user. But I tried to register user with the same address and the user had all groups. So, try to register another user with the same city.

**Comment by petervojtek** [comment]
ok, I confirm that newly created user has also `San Diego` group. thanks @igaponov .

The original design bug (with wrong icon offset) remain even after having proper amount of groups, so that I will dive in to css later..

**Comment by petervojtek** [comment]
done.
