### ISSUE TITLE
Home page first visit -- occasionally throws Cannot read property 'confirm' of undefined

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#94]
```
ionic.bundle.min.js:139 TypeError: Cannot read property 'confirm' of undefined
    at n.$rootScope.confirm (app-init.js:140)
    at Object.checkRemind (session.js:160)
    at favorite.js:162
    at ionic.bundle.min.js:151
    at n.$eval (ionic.bundle.min.js:165)
    at n.$digest (ionic.bundle.min.js:163)
    at n.$apply (ionic.bundle.min.js:166)
    at l (ionic.bundle.min.js:118)
    at F (ionic.bundle.min.js:122)
    at XMLHttpRequest.K.onload (ionic.bundle.min.js:123)
```

**Comment by petervojtek** [comment]
root of this bug (which is present only in browser) is that the app is using native notification to ask "Your profile isn\'t finished! Fill it out now?" -- which is not working in browser (but works properly on android). 

The way I fixed it means that such notifications are displayed only on smartphones and not in browser (without throwing the error in browser). I would say that this is acceptable approach because we use browser only for dev purposes... otherwise I would have to spend more time replacing the native prompt notification with some more universal solution.

**Comment by jterps08** [comment]
Solutions that involve less time at this point are definitely better and appreciated!
