### ISSUE TITLE
Unable to switch to My Profile on Android 4.2

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#96]
in browser it works.

**Comment by petervojtek** [comment]
it's only issue of old android 4.2. on newer androids (5) it works.

@jterps08 , which is the minimal version of android we want to support?

**Comment by jterps08** [comment]
As long as it works on Android 5 or greater, I'm okay with this issue for now. I don't think it's worth us prioritizing at this point.

**Comment by petervojtek** [comment]
@jterps08 , do you really want to pay attention to android 4.2?
 I only hit that issue because I used one old smartphone I own, but many apps already dropped support for android 4.2 and the lowest android version they support is 4.3 or 4.4 (from my fresh experience: Xiaomi, banks in europe).

**Comment by austinpapp** [comment]
it's like ie6. at some point you just got to say enough is enough :) so imho, let's not worry about it.

**Comment by jterps08** [comment]
I don't mind non-compatibility with 4.2. Obviously, the more compatibility the better.

**Comment by petervojtek** [comment]
@jterps08 , I suggest to take android 4.4 as our bottom line: https://developer.android.com/about/dashboards/index.html
as you can see from the stats, androids 4.2 and 4.3 are getting out of mainstream.

I will test the app on android 4.4 and test if all works as expected, ok?

**Comment by jterps08** [comment]
sounds good
