### ISSUE TITLE
App Store Readiness

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#97]
Ensure app name is actually "Powerline" and not "PowerlineApp"
Ensure app permissions for new version are the same as the app permissions that are required in current/old version in the app store now so that existing users do not need to approve of any new permissions. (There should be no need for new permissions). 
Ensure Facebook hash has been added to Facebook Developers Console to allow for FB login.

**Comment by petervojtek** [comment]
@jterps08 , 
I altered app name, desc and contact.

What version number should we assign the upcoming release? The [current production app](https://play.google.com/store/apps/details?id=ne.powerli) is version 1.3. Given the large changes in the app, I would suggest 2.0.

To really test whether the permissions are the same same between the existing production release  1.3 (in app stores) and the upcoming release, I need to be able to create a production-like build from the latest mobile app sourc code-- to accomplish this, I need to know the passphrase for [release.keystore](https://bitbucket.org/powerlineapp/hybrid-cordova-3/src).

Regarding Friend Finder feature added in the latest code -- that one requires permission to access phone contacts ,but it seems such a permission is already granted in the [current production app v1.3](https://play.google.com/store/apps/details?id=ne.powerli):

> Permissions - Contacts - find accounts on the device

Regarding facebook login, it is being solved in #115.

**Comment by jterps08** [comment]
Good stuff, thanks Peter. 

Version 2.0 is fine with me given the framework changes (to Ionic) and the number of other changes to the v2 API, etc. 
Austin/I will send passphrase to you for release.keystore.
Good catch on the FriendFinder. I'm looking forward to testing this out. 

Thanks!
Jesse

**Comment by petervojtek** [comment]
@austinpapp , can you give me passphrase for `release.keystore` via slack  so that I can test/inspect the app in production env?

**Comment by jterps08** [comment]
@petervojtek @austinpapp we need to test this in staging before we go to production.

**Comment by petervojtek** [comment]
when asking for the passphrase I had no intention to push the production APK to google play store.. I only wanted to try it locally in smartphone to compare requires permissions (and in general check if there isn't something principally broken in production APK, as currently I work only with development APKs which are bit different).

I already received from Jesse the guidelines on how to build a production APK.

**Comment by jterps08** [comment]
Thanks for clarification @petervojtek - I want to make sure we test in staging environment... Right now we are working in Dev environment, but we do have a staging environment we can leverage (for apk/ipa to connect to backend staging), so that we can confirm server stability in staging environment before pushing to production server..

**Comment by austinpapp** [comment]
team - once we feel the backend is stable enough to be considered "ready", i'll push to staging. from there its bug only. enhancements will be addressed in another release.

**Comment by petervojtek** [comment]
@jterps08 , I confirm that the latest code (v2.0) does not adds any additional permission requirements (at least on android) compared to the current production version in app store (1.3). 

Actually, the version 2.0 currently requires less permissions than v1.3 -- the difference is in access to Calendar. I have not hit that use case in new app at all, I guess it will be related to Event activity (which I am unable to test yet, as I still wait for such content to by created in web app) and will require me to install some calendar-access plugin (which will bring the requirement).

**Comment by jterps08** [comment]
Thanks Peter - yes, access to the calendar will be required. We have a special behavior that when user receives Event from leader and responds to RSVP (Yes, No, etc.), that the answer is recorded and the user's device calendar is pre-populated with the event's details for easy saving to the user's actual calendar. We will need to keep that permission.
