### ISSUE TITLE
Quick Follow Icon Missing

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#99]
The Quick Action Bar should have display a "Follow/Followed" icon next to posts by other users so that people can be followed easily from the Newsfeed. This icon is missing.

**Comment by petervojtek** [comment]
@jterps08 , Just to make sure, you mean the person icon in the footer of each activity?

Can you please specify what is the desired behaviour? Here is my guess (from user A point of view):
- When user A is not following user B, for each activity by user B in newsfeed there should be an "person plus" icon in grey color. Clicling the icon will trigger "A wants to follow B".
- when user A is following B, for each activity by user B in newsfeed there should be a person icon (without the plus sign) in blue color. Not sure what should happen if A clicks the icon.
- Not sure what should be displayed when user A wants to follow B, but B has not yet confirmed it.

<img width="404" alt="screen shot 2016-07-13 at 14 47 48" src="https://cloud.githubusercontent.com/assets/225506/16803843/f9f744ea-4908-11e6-9904-ba6d3c32fc95.png">

**Comment by jterps08** [comment]
You are correct on all of your comments. 

Unfortunately, I don't think we have a way to differentiate between a current 'approved following' relationship vs a 'pending following' relationship. It would be ideal if 3 different icons were shown: 1) Follow this user, 2) Waiting for approval, 3) Approved and Following... We're going to have to update this later. If we have the capability to address this now, let's do that, but I don't think we do... :-(

**Comment by petervojtek** [comment]
ok, done.

current behaviour (newsfeed activity item author is A, current user is B):
- if B is not following A, icon is "grey person plus". Clicking it will launch follow action + toast.
- if B is approved-following A, icon is "blue person". clicking it will only display toast that "you are following this person".
- if B is waiting-for-approval A, icon is "grey person", clicking it will only display toast "waiting to approve".

the quick follow action should display below each activity item, thought currently I was able to test it only on micro-petitions.
